### ISSUE TITLE
Херсон - довідка про перебування на квартирному обліку

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/iBP#1]
опис та схеми бізнес-процесів для підготовки переведення в електронну форму послуги з видачі довідки про перебування на квартирному обліку. Послуга надається виконавчим комітетом Херсонської міської ради.

Детальніша інформація:

https://docs.google.com/document/d/1uy-hZTmaMuXla15YOzChiio_EOUF2SUocAXEbIHig7A/edit?usp=sharing

Заказчик :
Микола Шлапак
0669529735
mshlapak@kt-energy.com.ua

**Comment by GrekD** [comment]
беру в работу

**Comment by VadimGulich** [comment]
![image](https://cloud.githubusercontent.com/assets/12964120/9597933/445ae0e6-508f-11e5-8a55-50937538ccc6.png)

**Comment by VadimGulich** [comment]
Ожидаемый результат: Оригіналу

**Comment by VadimGulich** [comment]
При выборе статусу "Відмовити у видачі" , указав причину   не дает отработать заявку пока не укажешь дату и время получения.

![image](https://cloud.githubusercontent.com/assets/12964120/9598101/d7bd1894-5090-11e5-8d37-710045cf82c3.png)

Ожидаемый результат: при отказе не нужно заполнять поле даты получения оригинала.

**Comment by VadimGulich** [comment]
Выше указанные баги исправлены
--------------------------------------------------------------------
Ошибка в отображении печатной формы:
![image](https://cloud.githubusercontent.com/assets/12964120/9603419/4e809a0a-50b9-11e5-9006-6750003db51f.png)

В не заполненных полях отображается null
Ожидаемый результат: по аналогии с другими заявками  - если ничего не указано в поле то отображать его пустым
------------------------------------------------------
Вопрос: после успешной обработки заявки она не будет отображаться в "Оброблені" ?

**Comment by dmitrijzabrudskij** [comment]
Даша, в пустых полях ставь по умолчанию один пробел - тогда null'ов не будет

**Comment by GrekD** [comment]
Ожидаемый результат: по аналогии с другими заявками - если ничего не указано в поле то отображать его пустым
исправлено.

Дима, спасибо большое за подсказку

Вопрос: после успешной обработки заявки она не будет отображаться в "Оброблені" ?
у меня отображается в оброблених

**Comment by VadimGulich** [comment]
Одно поле осталось null
![image](https://cloud.githubusercontent.com/assets/12964120/9624010/3d27a648-5151-11e5-9d0c-d0228900b62f.png)

**Comment by GrekD** [comment]
Одно поле осталось null
исправлено - заказчик пожелал, чтоб это поле было обязательным для заполнения

**Comment by VadimGulich** [comment]
Исправлено, закрываю , БП работает корректно

**Comment by GrekD** [comment]
в Херсоне пока не делаем
