### ISSUE TITLE
Добавить на альфу процесс. Дніпропетровськ почта. Видача довідки про перебування на обліку (ПФ)

### ISSUE THREAD

**Issue by NikolayAngel** [e-government-ua/iBP#100]
Имя файла: dnepr_post_97.bpmn
Город: Днепропетровск
Группа: dnepr_post_97
Услуга: Дніпропетровськ почта. Видача довідки про перебування на обліку (ПФ)
Орган: пенсійний фонд, через почту

**Comment by kurbpa** [comment]
на альфе
