### ISSUE TITLE
Видача довідки про неотримання посвідчень батьків та дитини з багатодітної сім'ї у Генічеському районі 

### ISSUE THREAD

**Issue by Kylikpavel** [e-government-ua/iBP#1004]
Овчаренко Маргарита Вікторівна, начальник відділу з питань праці управління соціального захисту населення	Видача довідки про неотримання посвідчень батьків та дитини з багатодіної сім’ї

Пр.Миру, 43, м.Генічеськ, Генічеський район, Херсонська область, 75500	(05534) 3 52 44	03198184@mail.gov.ua

**Comment by GrekD** [comment]
одна и та же услуга с 
https://github.com/e-government-ua/iBP/issues/995
