### ISSUE TITLE
Надання відомостей з Державного земельного кадастру у формі витягу з Державного земельного кадастру про земельну ділянку у Генічеському районі

### ISSUE THREAD

**Issue by Kylikpavel** [e-government-ua/iBP#1006]
Терських Олена Олександрівна, головний спеціаліст сектору Державного земельного кадастру Відділу Держгеокадастру у Генічеському районі	Надання відомостей з Державного земельного кадастру у формі витягу з Державного земельного кадастру про земельну ділянку	Пр.Миру, 51, м.Генічеськ, Генічеський район, Херсонська область, 75500	(05534) 3 56 11	

genkut@ukr.net

**Comment by Akylish88** [comment]
https://delta.test.igov.org.ua/service/101/general
Редирект на всю страну
