### ISSUE TITLE
добавить на альфу в список услуг

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#102]
Имя файла: dnepr_post_98.bpmn
Город: Днепропетровск
Группа: dnepr_post_98
На локали:dnepr_post_98:1:299
Услуга: Призначення компенсації фізичним особам, які надають соціальні послуги особам, які не здатні до самообслуговування
Орган: Управління праці та соціального захисту населення

**Comment by kurbpa** [comment]
на альфе
