### ISSUE TITLE
Канів - Отримання дозволу на розміщення зовнішньої реклами - розкриття

### ISSUE THREAD

**Issue by Akylish88** [e-government-ua/iBP#1036]
kaniv_cnap@ukr.net
0989495629 Проняєва Олена

Группа cnap_cherk_kanivT

Логин и пароль: cherk_kanivT1

**Comment by smoktii-igov** [comment]
Віставлено в Дельте, отослано письмо на тестирование

**Comment by smoktii-igov** [comment]
Получено подтверждение, выставлено в РЕЛИЗ
