### ISSUE TITLE
добавить на альфу в список процессов

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#104]
1
Имя файла: dnepr_post_103.bpmn
Город: Днепропетровск
Группа: dnepr_post_98
На локали:dnepr_post_103:1:325
Услуга: Проведення безоплатного капітального ремонту власних житлових будинків і квартир осіб, що мають право на таку пільгу
Орган: Управління праці та соціального захисту населення

2
Имя файла: dnepr_post_107.bpmn
Город: Днепропетровск
Группа: dnepr_post_98
На локали:dnepr_post_107:1:251
Услуга: Призначення одноразової винагороди жінкам, яким присвоєно почесне звання України "Мати-героїня"
Орган: Управління праці та соціального захисту населення

3
Имя файла: dnepr_post_108.bpmn
Город: Днепропетровск
Группа: dnepr_post_98
На локали: dnepr_post_108:1:366
Услуга: Призначення державної соцальної допомоги у зв'язку з витратами, зумовленими похованням
Орган: Управління праці та соціального захисту населення

4
Имя файла: dnepr_post_109.bpmn
Город: Днепропетровск
Группа: dnepr_post_98
На локали: dnepr_post_109:1:286
Услуга: Призначення державної соцальної допомоги інвалідам з дитинства та дітям-інвалідам віком до 18 років
Орган: Управління праці та соціального захисту населення

5
Имя файла: dnepr_post_113.bpmn
Город: Днепропетровск
Группа: dnepr_post_98
На локали: dnepr_post_113:1:267
Услуга: Призначення одноразової матеріальної допомоги інвалідам та непрацюючим малозабезпеченим особам
Орган: Управління праці та соціального захисту населення

**Comment by kurbpa** [comment]
1. https://test.igov.org.ua/service/764/general/
2. https://test.igov.org.ua/service/765/general/
3. https://test.igov.org.ua/service/766/general/
4. https://test.igov.org.ua/service/767/general/
5. https://test.igov.org.ua/service/628/general/

**Comment by GrekD** [comment]
Паша, эти все процессы надо подвязать к Днепропетровску ))

**Comment by kurbpa** [comment]
@GrekD 
эти все процессы и так привязаны к городу Днепропетровску. Изначально
