### ISSUE TITLE
Добавить в конфиги

### ISSUE THREAD

**Issue by NizhnikAlex** [e-government-ua/iBP#105]
Услуга: "Декларація відповідності матеріально-технічної бази роботодавця вимогам законодавства з питань охорони праці та промислової безпеки"
Регион: Днепропетровск
ЦНАП
предоставляет: Територіальне управління Держгірпромнагляду у Дніпропетровській області
файл: dnepr_cnap_57u.bpmn
группа: dnepr_cnap_prav (заведено)

На альфе есть такой же процесс для ФОП. Этот для юр. лиц

**Comment by kurbpa** [comment]
https://test.igov.org.ua/service/758/general
