### ISSUE TITLE
Днепропетровск. Укрпошта. Призначення тимчасової державної допомоги дітям, батьки яких ухиляються відхиляються від сплати аліментів, не мають можливості утримувати дитину або місце проживання їх невідоме.

### ISSUE THREAD

**Issue by wantonness** [e-government-ua/iBP#111]
Разработка технологического процесса

**Comment by wantonness** [comment]
БП:
1.	Заявитель заполняет обязательные данные на портале. Прикрепляет сканы необходимых справок.  Получает подтверждение об отправке заявки по электропочте.
2.	Сотрудник Укрпочты проверяет документы. В случае неправильного заполнения отправляется письмо с отказом (необходимо написать комментарий о причине отказа).  
3.	В случае правильного заполнения – отправляется письмо с реквизитами для оплаты и кнопкой для оплаты в liqpay. Оплата должна бать призведена в течение 1 дня с момента подачи заявки. В случае неоплаты в течение 3 дней – отправляется письмо об отсутствии оплаты. 
4.	Если оплата была призведена, то сотрудник Укрпочты распечатывает и отправляет документы в управление соцзащиты (заявителю отправляется письмо о том, что его док-ты переданы в гос.орган) и ждет от них решения выдавать или не выдавать материальную помощь. После получения решения – укрпочта направляет письмо заявителю с комментарием положительное решение по его заявке или нет.

**Comment by Koffeek** [comment]
Реализовано напрямую через соцпомощь
