### ISSUE TITLE
Кузнецовск. Доработать процесс:Видача копій, витягів з розпоряджень міського голови, рішень, прийнятих міською радою та виконавчим комітетом.

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/iBP#116]
Процесс - kuznetsovsk_mvk_4

Необходимо:
1. убрать поля с паспортными данными гражданина
2. добавить поле для указания адреса проживания

**Comment by Koffeek** [comment]
Убираем паспортные данные и скан паспорта или только паспортные данные?

**Comment by Koffeek** [comment]
Процесс ушел в бой. Тесты проведены
