### ISSUE TITLE
Кузенцовск - Надання довідки про те, що посвідчення батьків та дитини з багатодітної сім'ї не видавалося

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/iBP#117]
Материалы - https://drive.google.com/folderview?id=0BydenhvN5xzeeHFsUWRNQUtkYVk&usp=sharing

Заказчик: Поремчук Євгеній Володимирович
 e.poremchuk@gmail.com

**Comment by GrekD** [comment]
на боевом
https://igov.org.ua/service/687/general

**Comment by GrekD** [comment]
Для Хмельницького

**Comment by GrekD** [comment]
@plyacik 
прошу протестувати
https://test.igov.org.ua/service/687/general

**Comment by GrekD** [comment]
@plyacik відкриваємо цю послугу чи ні?
