### ISSUE TITLE
Кузнецовск - поновлення договору оренди земельної ділянки

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/iBP#118]
Материалы - https://drive.google.com/folderview?id=0BydenhvN5xzeaFM1aWhvYXpOMTQ&usp=sharing

Заказчик: Поремчук Євгеній Володимирович
e.poremchuk@gmail.com

**Comment by Koffeek** [comment]
Из общения с региональным РМ и ЦНАПом. Добавилось
1. Заява пишення довільним чином на ім'я міського голови, обов'язково має бути вказано:  площа земельної ділянки, цільове призначення зем.ділянки, місце розташування зем.ділянки, на який термін поновити
2. При ненаданні послуги у вказаний законом термін від адміністратора заявник ніякі документи не отримує, він продовжує орендувати зем. ділянку, головне, щоб не було заборгованості по сплаті за оренду.
3. Адміністратор не відмовляє в наданні послуги, він може вказати на перелік документів, які не надані, або надані не належним чином оформлені. 
4. У випадку непродовження оренди відповідь відправити можна і електронним листом. Надсилається відповідь, що рішення ради не набрало необхідну кількість голосів серед депутатського корпусу, також додається витяг з протоколу сесії.
5. Цільове призначення земельної ділянки вказується у договорі, тому лишаємо поле для самостійного заповнення громадянином.
6. Площа земельної ділянки вказується у га, термін продовження оренди - у роках.
7. Відповідь адміністратор сканує і відправляє на ел.пошту заявнику. Але він може вказати, що хоче отримати результат і в електронному вигляді і в паперовому, тоді ще приходить в ЦНАП і забирає оригінал.

**Comment by Koffeek** [comment]
Прохождение процесса
1. Гражданин заполянет заявку
2. Гражданину приходит письмо о подтверждение заказа
3. Администратору ЦНАП приходит пиьсмо о новой заявке.
4. Администратор ЦНАП проверяет данные и по результатам.
 - отказывает в регистрации обращения
 - добавляет е-мейл специалиста землераспорядителя и передает заявку в работу ему
5. Гражданину приходит письмо, что его заявка передана в работу землераспорядителю или ему отказано в регистрации обращения.
6. Землераспорядителю приходит пиьсмо о новой заявке.
7. Землераспорядитель обрабатывает заявку по итогам выдает решение
 - данных заявки недостаточно для обработки
 - договор аренды продлен + прикрепляется копия решения сессии горсовета
 - договор аренды не продлен + прикрепляется копия решения сессии горсовета
8. Администратору ЦНАП приходит решение от Землераспорядителя по вопросу продления договора аренды и он пересылает решение гражданину.

**Comment by Koffeek** [comment]
Услуга на боевом
