### ISSUE TITLE
Днепропетровск. Укрпошта. Призначення компенсаційної виплати непрацюючій працездатній особі, яка доглядає за інвалідом І групи, а також за престарілим, який досяг 80-річного віку

### ISSUE THREAD

**Issue by wantonness** [e-government-ua/iBP#119]
Разработка технологического процесса

**Comment by wantonness** [comment]
БП:
1. Заявитель заполняет обязательные данные на портале. Прикрепляет сканы необходимых справок. Получает подтверждение об отправке заявки по электропочте.
2. Сотрудник Укрпочты проверяет документы. В случае неправильного заполнения отправляется письмо с отказом (необходимо написать комментарий о причине отказа).

3. В случае правильного заполнения – отправляется письмо с реквизитами для оплаты и кнопкой для оплаты в liqpay. Оплата должна быть произведена в течение 1 дня с момента подачи заявки. В случае неоплаты в течение 3 дней – отправляется письмо об отсутствии оплаты. 
4. Если оплата была произведена, то сотрудник Укрпочты распечатывает и отправляет документы в управление соцзащиты (заявителю отправляется письмо о том, что его док-ты переданы в гос.орган).

**Comment by GrekD** [comment]
такой процесс по соц.защите сделан
