### ISSUE TITLE
Кузнецовск - Надання  дозволу на проведення публічних богослужінь

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/iBP#12]
Алгоритм:
https://drive.google.com/file/d/0B1NO5RoNKst7Sy12SERLa2puRFNrcjlBYjVrNDNSSDVCaTlj/view?usp=sharing

Заява:
https://drive.google.com/file/d/0B1NO5RoNKst7aDRFMUhMcFAxSWZEeVFiUUtCNnVmV0dnWGU4/view?usp=sharing

Інформаційна карта послуги:
https://drive.google.com/file/d/0B1NO5RoNKst7YVBmZXMtRGE2a2psYlpwN0xENmU0MUlhZ21F/view?usp=sharing

**Comment by Koffeek** [comment]
на боевом
