### ISSUE TITLE
 Кузнецовск -  Звернення громадянина до міського голови

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/iBP#13]
Алгоритм:
https://drive.google.com/file/d/0B1NO5RoNKst7NXFIanhIR0hFY2x0U0lxbGFRbFA5T1Y3RERZ/view?usp=sharing

Заява:
https://drive.google.com/file/d/0B1NO5RoNKst7MlZlOUNQbUE2eFZLcGxQbS1UWlpmYm1BcjhR/view?usp=sharing

Прошу звернути особливу увагу на такі фактори:
1. Приписка про "Даю згоду на обробку персональних даних...";
2. Можливість пролонгації відповіді міського голови з 15 до 30 днів. (можливо автоматичне повідомлення користувачу про пролонгацію у разі відсутності закриття бізнес процесу за 15 днів від дати запуску бізнес-процесу користувачем);
3. Було б добре аби друкована форма була автентична шаблону який я додав до листа;
4. Вибір результату послуги: скан в електронному вигляді на порталі АБО "Заберу сам у ЦНАП"

**Comment by Koffeek** [comment]
На боевом
