### ISSUE TITLE
добавить процесс на альфу

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#132]
Имя файла: kuznetsovsk_vssm_117.bpmn
Город: Кузнецовск
Группа: Kuznetsovsk_vssm
На локали: kusnetsovsk_vssm_117:1:339
Услуга: Надання довідки про те, що посвідчення батьків та дитини з багатодітної сім'ї не видавалося
Орган: відділ у справах сім'ї та молоді

**Comment by kurbpa** [comment]
https://test.igov.org.ua/service/687/general

**Comment by GrekD** [comment]
kuznetsovsk_vssm_117.bpmn - это название процесса
а ИД процесса - kusnetsovsk_vssm_117
т.е. через букву s а не z (моя ошибка)
исправь, пожалуйста, в конфигах
правильно так:
kusnetsovsk_vssm_117

**Comment by kurbpa** [comment]
готово
