### ISSUE TITLE
Заменить процесс в конфиге

### ISSUE THREAD

**Issue by msvidran** [e-government-ua/iBP#134]
На портале: https://test.igov.org.ua/service/141/general заведен процесс dnepr_cnap_37 "Копії рішення міської ради про надання у постіне користування земельних ділянок державної або комунальної власності", а должен быть dnepr_cnap_38 "Копії рішення міської ради про передачу в оренду земельних ділянок державної або комунальної власності"     --  нужно поменять

**Comment by msvidran** [comment]
Имя файла: dnepr_cnap_38.bpmn
Город: Днепропетровск
Группы: dnepr_copyzemroz_rada_prav, dnepr_copyzemroz_rada_lev
Услуга:  Копії рішень міської ради про передачу в оренду земельних ділянок, що перебувають у державній або комунальній власності
Орган: Дніпропетровська міська рада

**Comment by kurbpa** [comment]
готово к выливке
https://test.igov.org.ua/service/141/general
https://test.igov.org.ua/service/140/general
