### ISSUE TITLE
Kiev_ДМС (Регистрация места проживания)_текст сообщения

### ISSUE THREAD

**Issue by OlgaKhomenko** [e-government-ua/iBP#138]
Шановний(-а),  #І.Б.#!
 

Ваш запит був успішно зареєстрований у нашій системі.

 

Для того, щоб закінчити процедуру подачі заяви та необхідних документів для отримання адміністративних послуг Державної міграційної служби Вам необхідно:

· Сплатити державне мито за реєстрацію місця проживання у розмірі 0,85 грн. і отримати квитанцію про сплату.

· Завітати до Центру надання адміністративних послуг #Назва району Києва#, що знаходиться за адресою: #Адреса ЦНАП# (є можливість попереднього запису на прийом).

Документи, які необхідно подати до Центру надання адміністративних послуг:
· паспортний документ;

· талон зняття з реєстрації (не подається в разі одночасного зняття з реєстрації місця проживання);

· свідоцтво про народження дитини (оригінал та копія);
· квитанція  про сплату державного мита;
· документи, що підтверджують право на проживання в житлі, перебування або взяття на облік у спеціалізованій соціальній установі, закладі соціального обслуговування та соціального захисту, проходження служби у військовій частині, адреса яких зазначається під час реєстрації (оригінал та копія);

· військовий квиток або посвідчення про приписку (для громадян, які підлягають взяттю на військовий облік або перебувають на військовому обліку, оригінал та копія):

· при проживанні батьків за різними адресами для реєстрації місця проживання дитини, яка не досягла 14 років, разом з одним з батьків надається письмова згода (у присутності адміністратора Центру) другого з батьків та довідка територіального підрозділу або адресно-довідкового підрозділу територіального органу ДМС України за місцем його проживання про те, що дитина не зареєстрована разом з ним*.

У разі подання заяви законним представником особи додатково подаються:

· документ, що посвідчує особу законного представника (оригінал та копія);

· документ, що підтверджує повноваження особи як законного представника, крім випадків, коли законними представниками є батьки (усиновлювачі) (оригінал та копія).

 * другий із батьків пред’являє адміністратору паспортний документ та подає його копію.
 

#Графік роботи ЦНАП#
З повагою,
Центр надання адміністративних послуг #Назва району Києва#,
Команда Порталу державних послуг iGov.org.ua.

**Comment by Koffeek** [comment]
Необхідні документи, які треба принести до відділення ДМС при реєстраціі місця проживання:
Документ, до якого вносяться відомості про місце проживання
Квитанцію про сплату державного мита або документ про звільнення від його сплати
Оригінали документів, що підтверджують:

    право на проживання в житлі (ордер, свідоцтво про право власності, договір найму (піднайму, оренди) або інші документи. У разі відсутності зазначених документів реєстрація здійснюється за згодою власника/співвласників житла, наймача та членів його сім’ї на реєстрацію місця проживання),
    перебування або взяття на облік у спеціалізованій соціальній установі, закладі соціального обслуговування та соціального захисту (довідка про прийняття на обслуговування в спеціалізованій соціальній установі, закладі соціального обслуговування та соціального захисту особи, копія посвідчення про взяття на облік бездомної особи),
    проходження служби у військовій частині (довідка про проходження служби у військовій частині, видана командиром військової частини),

адреса яких зазначається під час реєстрації;
військовий квиток або посвідчення про приписку (для громадян, які підлягають взяттю на військовий облік або перебувають на військовому обліку);
свідоцтво про народження або свідоцтво про належність до громадянства України, якщо реєструється місце проживання дитини, яка не досягла 16-річного віку;

Зверніть увагу: при проживанні батьків за різними адресами для реєстрації місця проживання дитини, яка не досягла 14 років, разом з одним з батьків надається письмова згода другого з батьків та довідка територіального підрозділу або адресно-довідкового підрозділу територіального органу ДМС України за місцем його проживання про те, що дитина не зареєстрована разом з ним. 

У разі подання заяви законним представником особи додатково подаються:

· документ, що посвідчує особу законного представника (оригінал та копія);

· документ, що підтверджує повноваження особи як законного представника, крім випадків, коли законними представниками є батьки (усиновлювачі) (оригінал та копія).

**Comment by kurbpa** [comment]
Готово. Протестировано.
на альфе. и бэте.
