### ISSUE TITLE
пока что временно в конфигах процессы сделать серыми

### ISSUE THREAD

**Issue by Koffeek** [e-government-ua/iBP#143]
подвяжем на них другие потом
    https://test.igov.org.ua/service/764/general/
    https://test.igov.org.ua/service/765/general/
    https://test.igov.org.ua/service/766/general/
    https://test.igov.org.ua/service/767/general/
    https://test.igov.org.ua/service/628/general/
dnepr_post_103.bpmn
dnepr_post_107.bpmn
dnepr_post_108.bpmn
dnepr_post_109.bpmn
dnepr_post_113.bpmn

**Comment by wantonness** [comment]
https://test.igov.org.ua/service/762/general  (dnepr_post_111)
https://test.igov.org.ua/service/759/general (dnepr_post_119)
https://test.igov.org.ua/service/768/general (dnepr_post_122)

**Comment by msvidran** [comment]
https://test.igov.org.ua/service/760/general (dnepr_post_99.bpmn)

**Comment by kurbpa** [comment]
готово
