### ISSUE TITLE
Дніпропетровськ - Соц. захист - Призначення допомоги на дітей-сиріт та дітей, позбавлених батьківського піклування та грошового забезпечення прийомним батькам

### ISSUE THREAD

**Issue by msvidran** [e-government-ua/iBP#147]
http://babushkinskarada.dp.ua/dopomoga-na-ditey-sirit-ta-ditey-pozbavlenih-batkivskogo-pikluvannya-budinki-simeynogo-tipu-priyomni

**Comment by GrekD** [comment]
Предложения:
1
Довідка з місця навчання про розмір стипендії:
якщо особа з числа дітей-сиріт та дітей, позбавлених батьківського піклування, віком від 18 до 23 років або до закінчення відповідних навчальних закладів навчається за денною формою у вищих навчальних закладах I-IV рівня акредитації та професійно-технічних навчальних закладах, подаються довідки про розмір стипендії та про те, що вона не перебуває на повному державному утриманні

По этому пункту сделать  дин.форму:
чи навчається дитина-сирота за денною формою у професійно-технічному або вищому навчальному закладі?
Если да - тогда можно это поле показать, только покороче и разбить на два:
name= довідка про розмір стипендії 
name= довідка про те, що дитина не перебуває на повному державному утриманні  

2.
Тут тоже можно подсократить название файла
было
Рішення районної, держадміністрації, виконавчого органу міської, районної у місті ради про влаштування дитини до дитячого будинку сімейного типу або прийомної сім'ї:
стало
Рішення про влаштування дитини до дитячого будинку сімейного типу або прийомної сім'ї:

3
Копія виписки із акта огляду медико-соціальної експертної комісії або медичного висновку лікарсько-консультативної комісії лікувально-профілактичного закладу про дитину-інваліда, виданих в установленому МОЗ порядку:
Тут тоже можно перед этим спросить в дин.форме:
Чи є дитина, на яку оформляється допомога, інвалідом?
Если да - показывать поле с этим файлом (причем рекваердовым), если нет – не показывать
