### ISSUE TITLE
добавить описание услуги

### ISSUE THREAD

**Issue by wantonness** [e-government-ua/iBP#167]
https://test.igov.org.ua/service/139/general - к этому процессу

https://drive.google.com/open?id=0BzuKb3PfDSiuU1Bxd1lVNExVNnM

**Comment by dmitrijzabrudskij** [comment]
расшарь описание

**Comment by wantonness** [comment]
готово

2015-09-24 13:08 GMT+03:00 dmitrijzabrudskij <notifications@github.com>:

**Comment by kurbpa** [comment]
добавил
