### ISSUE TITLE
Добавить на Альфу

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#169]
1
https://test.igov.org.ua/service/765/general
Имя файла: dnepr_soc_help_148
Город: Дніпропетровск
На локали:dnepr_soc_help_148:1:216
Услуга: Призначення одноразової винагороди жінкам, яким присвоєно почесне звання України "Мати-героїня"
Орган: Управління праці та соціального захисту населення

2
Имя файла: dnepr_soc_help_149
Город: Дніпропетровск
На локали:dnepr_soc_help_149:1:220
Услуга: Надання стипендії особам, яким виповнилось 100 і більше років
Орган: Управління праці та соціального захисту населення

3
https://test.igov.org.ua/service/767/general
Имя файла: dnepr_soc_help_150
Город: Дніпропетровск
На локали:dnepr_soc_help_150:1:224
Услуга: Призначення державної соцальної допомоги інвалідам з дитинства та дітям-інвалідам віком до 18 років
Орган: Управління праці та соціального захисту населення

**Comment by kurbpa** [comment]
1. https://test.igov.org.ua/service/765/general
2.  https://test.igov.org.ua/service/783/general
3. https://test.igov.org.ua/service/767/general
