### ISSUE TITLE
Добавить на альфу описания

### ISSUE THREAD

**Issue by NizhnikAlex** [e-government-ua/iBP#170]
1
https://test.igov.org.ua/service/736/general        
https://drive.google.com/file/d/0B90t3sr75wRQOVRBaEdEMElmZjQ/view?usp=sharing
2
https://test.igov.org.ua/service/719/general
https://drive.google.com/file/d/0B90t3sr75wRQakFEeHFSaGY2X2s/view?usp=sharing
3
https://test.igov.org.ua/service/773/general
https://docs.google.com/document/d/1oPSdF9xeQmSJIWOXl49uo-loa15GJe4OfCME-0UT3-I/edit?usp=sharing
4
https://test.igov.org.ua/service/771/general
https://docs.google.com/document/d/1Tp7KLYna2MIz3I8qLDXtqoPWtlXnut1uFZi1N1y8YUs/edit?usp=sharing
5
https://test.igov.org.ua/service/772/general
https://docs.google.com/document/d/1dXD7bZv63PIMosG6pZeeMs0o0pnvYOS8GzImarzauNw/edit?usp=sharing
6
https://test.igov.org.ua/service/770/general
https://docs.google.com/document/d/1HUjZesx0xC7YODluF5FjO8EWuOvGOKv0Rvdd9HU8Qtk/edit?usp=sharing

**Comment by msvidran** [comment]
№ 141 
https://drive.google.com/file/d/0B1uoWNhWT8YYT2V1eW00dExHSjg/view?usp=sharing

№ 153
https://drive.google.com/file/d/0B1uoWNhWT8YYN1pRWllXSTdfazQ/view?usp=sharing

**Comment by Koffeek** [comment]
1.
https://test.igov.org.ua/service/96/general
https://drive.google.com/file/d/0B68lQ-z45GpYNl8tMUxHVk80VUU/view?usp=sharing
2.
https://test.igov.org.ua/service/142/general
https://drive.google.com/file/d/0B68lQ-z45GpYQVp4bjBxaHhCVEk/view?usp=sharing

**Comment by GrekD** [comment]
1 викиди забруднюючих речовин (1 орган)
https://test.igov.org.ua/service/49/general
https://drive.google.com/open?id=0B6mOkUg9oq1zMUJoNnNqWm1SZWM

2. викиди забруднюючих речовин (2 орган)
https://test.igov.org.ua/service/49/general
https://drive.google.com/open?id=0B6mOkUg9oq1zMUJoNnNqWm1SZWM

3 лицензия
https://test.igov.org.ua/service/73/general
https://drive.google.com/open?id=0B6mOkUg9oq1zUlVNeGRIZ2p1X0U

4 тварини
https://test.igov.org.ua/service/746/general
https://drive.google.com/open?id=0B6mOkUg9oq1zVFctSGpkQV8wR0E

5 корма
https://test.igov.org.ua/service/745/general
https://drive.google.com/open?id=0B6mOkUg9oq1zRTJ4b0FYalhuc1U

6 постійне користування (земля)
https://test.igov.org.ua/service/140/general
https://drive.google.com/file/d/0B68lQ-z45GpYQVp4bjBxaHhCVEk/view?usp=sharing

7 риба
https://test.igov.org.ua/service/158/general
https://drive.google.com/open?id=0B6mOkUg9oq1zUDB5X1IxNzB6eU0

8 символіка
https://test.igov.org.ua/service/5/general
https://drive.google.com/open?id=0B6mOkUg9oq1zSTNoWmhmVUlQMHc

**Comment by kurbpa** [comment]
@NizhnikAlex 
@Koffeek 
@msvidran 
@GrekD 
Вылили на альфу.
