### ISSUE TITLE
Тернополь. Материальная помощь. Доработки динамических форм.

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/iBP#172]

**Comment by kelnerira** [comment]
поле "Прошу надати матеріальну допомогу:" вибір  - на дитину -інваліда - мають бути ті самі додаткові поля, що і при виборі "на мого підопічного

**Comment by kelnerira** [comment]
Чи можна щоб при виборі у полі "До якої категорії громадян Ви належите:" - "Законний представник" - у полі "Прошу надати матеріальну допомогу:" були тільки варіанти "На підопічного " і "на дитину-інваліда" ? А при виборі іншої категорії (пенсіонер, інвалід.....) - поле "Прошу надати матеріальну допомогу:" - автоматом заповнювалося "мені"

**Comment by kelnerira** [comment]
Файл для завантаження "Документ, що засвідчує повноваження законного представника:" - думаю варто залишити там, де був раніше - після файлів з копіями паспорта/св-ва про народження та ІПН підопічних. Бо,  як на мене, зручніше спочатку все заповнити, а потім додавати файли.

**Comment by kelnerira** [comment]
https://docs.google.com/spreadsheets/d/1nS30Vs8Y1Pf5mE84rOpNzwuGGTCmGa6_b0I7wZQyCpI/edit?usp=sharing тут посортувала документи у залежності від типу заявника та обставин

**Comment by Koffeek** [comment]
1. Зроблено
2. У розробці.
3. Зроблено.
4. Зроблено.
Завтра протестую і відправлю Вам на тест

**Comment by Koffeek** [comment]
Послуга готова для тестування. Маю до Вас одне питання: коли відмова у наданні послуги надходить після засідання коміссії, чи прикріпляється офіційний лист до е-мейла громадянинові?

**Comment by kelnerira** [comment]
Лист - відповідь після рішення комісії  прикріпляється не залежно від результату. 

Надіслано з iPhone

5 жовт. 2015 о 12:18 Koffeek <notifications@github.com> написав(ла):

**Comment by Koffeek** [comment]
@kelnerira послуга доопрацьована і готова для тестування. Окремо прошу приділити увагу текстам е-мейлів, оскільки їх було змінено.

**Comment by katyafursyk** [comment]
Послуга протестована, динамічні форми працюють. 

Відповідь заявнику про відмову у наданні послуги потрібно виправити.
На жаль, ми змушені відмовити вам у наданні послуги "надання одноразової матеріальної допомоги громадянам" було успішно розглянуте.
     НА
На жаль, ми змушені відмовити вам у наданні послуги "надання одноразової матеріальної допомоги громадянам".

**Comment by Koffeek** [comment]
@katyafursyk @kelnerira Виправлення зроблене. Виллється за півгодини. Якщо інших питань і зауважень немає, то будемо готувати оновлену версію у реліз.

**Comment by kelnerira** [comment]
Перед виставленням на бойовий - не забудьте показати Галині Романівні у ОДА! Катя, надіслала Вам телефон на e-mail

Надіслано з iPhone

6 жовт. 2015 о 08:18 Koffeek <notifications@github.com> написав(ла):

**Comment by katyafursyk** [comment]
@kelnerira  Покажемо, дякую!

**Comment by sofiadanylevych** [comment]
@Koffeek опис того, що відбулось + потрібні тоді ті заяви в pdf форматі, щоб працівник змогла собі окремо їх видрукувати. 
https://docs.google.com/document/d/1dph9ps_BAgH3gp6jW4CD7H5HhOk11Tz6yUduv8qzpxM/edit?usp=sharing

**Comment by Koffeek** [comment]
@sofiadanylevych Я тільки що продивився процес, який зараз виставлений на бойовий сервер. Там просто відсутня прінтформа як така, саме тому її неможливо розрукувати, до того ж архітектура процесу побудована на одному кроці обробки. Тому, по-перше, мені потрібен логін/пароль працівника, який обробляв заявку (тоді я зможу сформувати прінтформу і відправити її в pdf форматі). По-друге, чи перевірили сьгодні останню версію послуги (якщо так, то ми вночі виставимо її на бойовий замість існуючої)? Чекаю ваших відповідей.

**Comment by sofiadanylevych** [comment]
@Koffeek логін і пароль зараз відправлю поштою і останню версію послуги пройшли, все гаразд

**Comment by Koffeek** [comment]
@sofiadanylevych@kelnerira У процес додано прінтформи, продивіться, будь ласка. Буду чекати на Вашу відповідь.

**Comment by sofiadanylevych** [comment]
@Koffeek 
Щодо заявника, то при виборі "інші особливі обставити" потрібно добавити ще одне поля для того щоб додавати документ, поле повинно називатись "Копія документу, що підтверджує скрутний матеріальний стан"
![default](https://cloud.githubusercontent.com/assets/14632240/10338974/ac56ca4a-6d11-11e5-9e46-efd9891213e7.PNG)
Щодо заяви, то сказали забрати усі поля крім "дата подачі заяви", все решту не потрібно, поки що вирішили що так
![1](https://cloud.githubusercontent.com/assets/14632240/10339042/143130ce-6d12-11e5-923f-3a1eb3ad8fed.PNG)
Також просили по можливості, зменшити шрифт заяви, якось зменшити її, щоб вона поміщалась на 1 аркуш паперу при друці. Все решту підходить

**Comment by Koffeek** [comment]
@sofiadanylevych Софія, по прінтформам питання таке, якщо ми приберемо весь лістінг файлів, які повинні додавати громадяни, то вкладемося в один лист, також пропоную прибрати шапку, що заява затвердженна Мінсоцполітики, оскільки вона вже перероблена відносно оригіналу, це також скоротить об'єм заяви (проконсультуйтесь будь-ласка). Поле додам. Якщо вирішемо сьогодні. то вірогідно що вночі процес піде на бойовий.

**Comment by sofiadanylevych** [comment]
@Koffeek шапку в заяві можна забрати, те що "До заяви додаю" також можна забрати, сказали що ця заява в них і від руки може бути написана а затверджений зразок йде рекомендаційним а не обовязковим, оскільки був затверджений ще в 2012році то там немає переліку документів тих осіб які можуть подавати заяву зараз

**Comment by Koffeek** [comment]
@sofiadanylevych Прийнято. Десь за годину на тестовому можну буде перевірити.

**Comment by Koffeek** [comment]
На данном этапе доработки завершены и выставлены на боевой
