### ISSUE TITLE
Снятие флагов тест при добавлении процессов в бой

### ISSUE THREAD

**Issue by Koffeek** [e-government-ua/iBP#174]
Мои процессы:
dnepr_cnap_36
dnepr_cnap_39
kuznetsovsk_mvk_4

**Comment by msvidran** [comment]
Мои процессы:
dnepr_cnap_38
dnepr_cnap_72

**Comment by GrekD** [comment]
Uzhgorod_dmg_1
по ЦНАПУ к вечеру напишу, жду ответа от Капусты по почтам

**Comment by GrekD** [comment]
dnepr_cnap_37
dnepr_cnap_53
dnepr_cnap_54
dnepr_cnap_55
dnepr_cnap_56
dnepr_cnap_70

**Comment by kurbpa** [comment]
@Koffeek  - готово на альфе
@msvidran  -  готово на альфе
@GrekD  -  готово на альфе

**Comment by Koffeek** [comment]
ternopol_rcnap-9

**Comment by kurbpa** [comment]
@Koffeek - готово на альфе и бэте

**Comment by NizhnikAlex** [comment]
dnepr_cnap_59
dnepr_cnap_41
dnepr_minust_128
dnepr_minust_128

**Comment by GrekD** [comment]
Uzhgorod_dmg_1
dnepr_cnap_45

**Comment by Koffeek** [comment]
dnepr_cnap-44

**Comment by kurbpa** [comment]
@GrekD 
@Koffeek 
@NizhnikAlex 

на альфе

**Comment by NizhnikAlex** [comment]
Снова добавить
dnepr_cnap_59
dnepr_cnap_41
dnepr_minust_128
dnepr_minust_129
dnepr_minust_130
dnepr_minust_131

dnepr_minust_81 после добавления 128-131 (или одновременно) закрыть на боевом. Т.к. они будут дублировать друг друга

Uzhgorod_dmg_1
dnepr_cnap_45

dnepr_cnap-44

**Comment by kurbpa** [comment]
готово
