### ISSUE TITLE
Добавить процессы на альфу

### ISSUE THREAD

**Issue by msvidran** [e-government-ua/iBP#180]
1)
ID: dnepr_soc_help_179
Город: Дніпропетровськ
Услуга:  Надання пільг на придбання твердого палива і скрапленого газу.
Орган: Управління праці та соціального захисту населення

2)
ID: dnepr_soc_help_181
Город: Дніпропетровськ
Услуга: Призначення компенсації за послуги з центрального опалення житла, електропостачання та газопостачання.
Орган: Управління праці та соціального захисту населення

**Comment by kurbpa** [comment]
на альфе
