### ISSUE TITLE
Житомир - 23;Надання довідок незайнятому населенню про відсутність земельних ділянок для ведення ОСГ

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/iBP#183]
Существующий экземпляр процесса - zhitomir_mvk_2

Адаптировать для следующих органов Житомирской администрации - https://drive.google.com/file/d/0BydenhvN5xzeQUlULVZuVWR4YVZUVFBIV1pXUFB1ZE1RTjNn/view?usp=sharing

Зазкачик - Ванда Савинова (скайп - savinova.vanda)

**Comment by NizhnikAlex** [comment]
https://docs.google.com/spreadsheets/d/1i5jU-DBWIVxsx9u1yf_qa8wGNFYRF3el7UzOWZ1nKe0/edit?usp=sharing
