### ISSUE TITLE
Запорожье. Разрешение на Рекламу. Доработки

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/iBP#184]
Существующие  БП  разбиты на 2 в зависимости от  того кто опдает обращение.
- zaporoshye_mvk-1a.bpmn
- zaporoshye_mvk-1b_.bpmn

Необходимо привести их к одному процессу при помощи динамических форм + привести наполнение заявки в соответствии  с требуемым набором полей из файла (все поля, которые они хотели - это столбцы листа "база" - № справи, статус, дата надходження и т.д....) - https://drive.google.com/file/d/0BydenhvN5xzedkl0aV93YlJXM2c/view?usp=sharing

Заказчик - Максим Соловьев ( maksim maks.solovyov@gmail.com  / skype - maks.sol )

**Comment by GrekD** [comment]
тех.карты
https://drive.google.com/open?id=0B6mOkUg9oq1zY183cUR1dlJhVUstZTg2YTJjZnlVNzZleHRn
подання

переоформлення
https://drive.google.com/open?id=0B6mOkUg9oq1zV3NTWHQxZlZqN3RiTjl0T3o0U05lbXA0bV93

подовження
https://drive.google.com/open?id=0B6mOkUg9oq1zNGJ4YmFpendnZ1RXNXNrMmYzc1ZNM1JVenRr

анулювання
https://drive.google.com/open?id=0B6mOkUg9oq1zQUFfd1lQVjNoak4wZHpOcEthWVdHSFZGZ2RF

заява
https://drive.google.com/open?id=0B6mOkUg9oq1zaDEyZThWM1MxUTVJOGphMWN5c2tGZW5jYVM4

**Comment by GrekD** [comment]
для Запорожья пока неактуально
