### ISSUE TITLE
Славутський МВК - Видача витягу з технічної документації про нормативну грошову оцінку земельної ділянки

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/iBP#19]
https://drive.google.com/file/d/0BydenhvN5xzecV9Tc2hneE9TZDQ/view?usp=sharing 

Информационная карта - https://drive.google.com/file/d/0BydenhvN5xzeOUZSNmliRDFOM2c/view?usp=sharing 

(Копия процесса в г.Калуш)

**Comment by Koffeek** [comment]
Беру в работу

**Comment by Koffeek** [comment]
Описание работы: 1.Гражданин заполняет необходимые поля и прикрепляет документ. 2.Происходит загрузка документа и передача данных. 3.Чиновник просматривает данные и документы принятые гражданином. 4. Если чего-то не хватает, то отправляется письмо с указанием причины. 5. Если всё в порядке, то данные переходят дальше. 6. При поступлении вытяга к чиновнику он отправляет письмо, о его готовности к гражданину.

**Comment by NizhnikAlex** [comment]
1 в подписях писем заменить "Славутський МВК" на "Славутський міськвиконком" или "Виконавчий комітет Славутської міської ради"

**Comment by Koffeek** [comment]
Услуга заведена через Кадастровую карту на всю Украину
