### ISSUE TITLE
Смела - Надання витягу з технічної документації про нормативну грошову оцінку земельної ділянки

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/iBP#195]
Создать копию процесса для РДА Смелы.
"Надання витягу з технічної документації про нормативну грошову оцінку земельної ділянки" - https://igov.org.ua/service/10/general

Заказчик - Vadym Khivrenko (rezhisser@gmail.com)

**Comment by Koffeek** [comment]
https://drive.google.com/file/d/0B68lQ-z45GpYbWw0U0locnJtcEdpXy1iOXBhejRmMW5HeEFF/view?usp=sharing тех карта

**Comment by Koffeek** [comment]
Услуга запустилась на всю Украину редиректом на Кадастровую карту  http://www.map.land.gov.ua/kadastrova-karta
