### ISSUE TITLE
Днепропетровск. МВД - Отстрел оружия

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/iBP#199]
Принтформы заявлений - https://drive.google.com/folderview?id=0BydenhvN5xzeTDl3X3ZZLXNsTFU&usp=sharing 
Сценарий:
1. Гражданин выбирает услугу и проходит авторизацию
2. Заполняет на форме заявки необходимые поля. Нажимает  кнопку заказа услуги.
3. На своей емейл  гражданин должен получить:
* печатную форму заявления с заполненными полями
* кнопку и реквизиты для оплаты услуги
* информацию о графике работы субьекта предоставления услуги
* инструкции "что делать дальше"

**Comment by kurbpa** [comment]
График работы:
* пнд-птн  с 9:30 до 17:30. 
* Перерыв с 13:00 до 14:00

Адрес:
* г. Днепропетровск. ул.Строителей. тупик №1

При себе иметь:
* Разрешение на владение оружием либо временное разрешение
* оружие и 4 патрона для отрела ( для револьверов необходимо предоставить по 1 патрону на каждую камеру в барабане)
*  квитанцию об оплате

**Comment by GrekD** [comment]
https://igov.org.ua/service/343/general
на боевом
