### ISSUE TITLE
Смела РДА - Надання довідки з Державної статистичної звітності про наявність земель та розподіл їх за власниками земель, землекористувачами, угіддями (за даними форми 6-ЗЕМ)

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/iBP#20]
Бизнес-процесс - https://drive.google.com/file/d/0BwFj-1UKKvTiM1hOUl9WZDh4aXM/view?usp=sharing

Описание бизнес-процесса - https://docs.google.com/document/d/1HTtcagUeGBKLoQxNfjdOgUbz5YW3APCl6YD67jbS7N8/edit?usp=sharing

**Comment by NizhnikAlex** [comment]
Возьму на себя

**Comment by NizhnikAlex** [comment]
1. Пользователь вводит данные, в том числе 2 файла (один обязательный, второй нет)
2. Идет проверка введенных данных, принимается решение обрабатывать заявку или отказать при некорректности данных. Если отказ - письмо с отказом и причиной.
3. Изготовление заказанного документа
4. Еще одна проверка данных, так-же отказ или нет. Если отказ - письмо с причиной.
5. При положительном решении чиновник заливает скан заказанного документа, пользователь может его скачать из письма и (или) забрать в офисе.

**Comment by kurbpa** [comment]
https://test.igov.org.ua/service/102/general - ссылка на услугу на тестовом

**Comment by rezhisser** [comment]
Пользователь авторизован через bank_id
В форме заполнены все поля

При нажатии на кнопку "Замовити послугу" в кабинете Пользователя выдает:

ПОМИЛКАSYSTEM_ERR Exception while invoking TaskListener: Exception while invoking TaskListener: [REDEER] Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool

**Comment by rezhisser** [comment]
1. Нет перевода ошибок
2. Неплохо бы скролить форму к незаполненным полям при срабатывании контроля

**Comment by rezhisser** [comment]
В кабинене чиновника если выбрать "Опрацювати" и не прикрепить файл довідки, то операция виснет (раньше выдавало предупрежедние)
