### ISSUE TITLE
сделать мерчант для услуги по отстрелу оружия

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#203]
Одержувач платежу – НДЕКЦ при ГУМВС України в Дніпропетровській області
Рахунок одержувача – 31251201114278 в ГУДКСУ у Дніпропетровській області
МФО – 805012 ЄДРПОУ 25575055
Обов’язково вказувати вид платежу – *;04000043; 036032;1;* – відстрілювання 
вогнепальної зброї та огляд її технічного стану: нарізної і комбінованої мисливської та спортивної зброї 
Сума платежу – 84 грн 42 коп

**Comment by kurbpa** [comment]
public_key	i14273228627
