### ISSUE TITLE
Замечания от Шевченковской РДА

### ISSUE THREAD

**Issue by OlgaKhomenko** [e-government-ua/iBP#206]
1. Зробити атрибут "Номер справи" редагованим на всіх етапах, так як працівнику ЦНАП не завжди зручно створювати справу зразу. (сделать для всех процессов - приватизация, квартучет, регистрация и снятие  с регистрации)
2. Для користувачів програми https://demo.igov.org.ua/admin при надходженні електронних звернень необхідно встановити автоматичне повідомлення про їх надходження.
3. Так як не впроваджена єдина  електронна база реєстрації місця проживання мешканців району,  необхідно відмінити обов’язковість завантаження на етапі для ЦНАП  довідки по ф.3 для квартобліку  або  довідки з попередніх  місць реєстрації для відділу приватизації. Без завантаження файлів неможливо опрацювати справу та надати результат. (сделать необязательным загрузку файла - формы 3 для услуги квартучета и формы 2 для приватизации на шаге ЦНАП. Это связано с тем, что в некоторых РДА эту справку получает отдел, а не ЦНАП)
4. В закладку оброблені у співробітника квартвідділу  ШРДА потрапляє одна справа два рази! (при взятті в роботу працівником квартвідділу та обробці справи). (просят, чтоб учет был по заявке, а не задачам на закладке "Оброблені")
5. На останньому кроці виводити повідомлення  "Справу завершено", а не «форма відправлена».
6. Якщо справа знаходиться «В роботі», щоб була можливість на цьому етапі «відкласти розгляд» або «відхилити» або повернути в «необроблені».
7. Решить проблему с обновлением страницы портала. Сейчас нельзя увидеть созданную задачу на любом шаге процесса без постоянного обновления. Пользователь работает в ИЕ
8. Додати атрибут "Номер і дата результату" на другому кроці "Формування довідки в РДА" для працівників відділів квартобліку  та приватизації необхідно  вводити номер документа, замість сканування документу (Немає можливості прикріпити довідку, в зв’язку з відсутністю сканерів в відділах). 
9. На шаге "Формування довідки в РДА" сделать загрузку файла необязательным
10. Для працівників відділів квартобліку  та приватизації на крок  "Формування довідки в РДА" додати атрибут «Результат формування довідки в РДА», т.к. на цьому етапі (після розгляду документів можуть виникнути питання, тощо та  повинна бути можливість відмовити громадянину. Варианты значений атрибута «Результат формування довідки в РДА»: 
-Довідка надана
-у видачі довідки відмовлено
Следующая задача назначается по одной ветке, как и раньше: на ЦНАП. Разница только в тексте уведомлений гражданину. При отказе высылается сообщение гражданину, текст уведомления такой же - 1.для случая отказа 
11. Добавить атрибут на шаге "Формування довідки в РДА" в процессе по услуге приватизации и услуге квартотдела - "Коментар щодо відмови у наданні послуги"
12. Шаг "Надання довідки громадянину" для Шевченковской РДА по двум услугам - приватизация и квартучет назначать на учетку, которую сделали универсальную на всех сотрудников ЦНАП, т.к. на выдаче документов сидит любой из сотрудников.

**Comment by OlgaKhomenko** [comment]
Исправить сообщение гражданину: адрес Шевченковской РДА, а не Деснянской. Сейчас приходит следующее сообщение:
Шановний(-а), ДМИТРО ОЛЕКСАНДРОВИЧ.
Підготовка довідки про участь в приватизації житла державного житлового фонду, успішно завершена!
Оригінал документу Ви можете отримати в Центрі надання адміністративних послуг Деснянського району, що знаходиться за адресою: м.Київ, пр. Маяковського, 29
У випадку, якщо Ви перебуваєте на пільговій квартирній черзі, при собі необхідно мати оригінал документу, який підтверджує це (наприклад, Довідка з місця роботи).

З повагою,
Центр надання адміністративних послуг Шевченківського району м.Киів,
Команда Порталу державних послуг iGov.org.ua.

**Comment by kurbpa** [comment]
1. ok
2. ok. Уведомления можем сделать на те емейлы, которые были указаны при регистрации пользователей
3. ок
4. Раздел обороботанных в разработке. То о чем просят не совсем соответствует его идеологии
5. В работе есть задача , которая  позволит задавать текст на этой форму вручную при создании процесса. Сейчас текст везде стандартный.
6. в будущем будет. Запланирована доработка более глобальная, включающая это пожелание
7.Поставьте другой браузер. Хром или фаерфокс. Задачу однако на кроссбраузерность поставили.
8. телефоном сфотографировать они  справку не могут и прикрепить фото ? Этот тот же сканер? В наш век высоких технологий сканер утратил свой статус эксклюзивности. Если совсем люди ограничены в технологиях то можем сделать. Хотя крайне странно.
9. ок
10. ок
11. ок
12. так ведь я сразу общей учетной записи доступ дал. Проверьте.

**Comment by OlgaKhomenko** [comment]
Это уже можно тестировать?

**Comment by kurbpa** [comment]
1.на альфе
2.в работе
3.на альфе
9.на альфе
10.на альфе (если я правильно понял всё)
11.на альфе(если я правильно понял всё)
13.на альфе

**Comment by OlgaKhomenko** [comment]
14. -	з надання послуг «Видача довідки про перебування  на обліку громадян, які потребують поліпшення житлових умов», «Видача довідки про участь в приватизації житла державного житлового фонду» - при замовленні послуги на порталі необхідно прописати, що ці довідки надаються тільки в тому районі, де дійсно знаходиться об’єкт приватизації або людина стоїть на квартобліку.
15. -	«Реєстрація місця проживання», «Зняття з реєстрації місця проживання» - при замовленні послуги на порталі необхідно прописати, умови реєстрації мп або зняття з мп ,  може навіть зразу перелік необхідних документів і таке інше, також попередити, що заява заповнюється тільки державною мовою та необхідні дані для заповнення заяви повинні відповідати паспортним даним.

Це необхідно, щоб людина зразу розуміла чи варто їй замовляти ту чи іншу послугу, а не отримати відмову. Це зайва витрата нашого часу та громадянина.
16. Атрибут В роботі - «Реєстрація місця проживання», «Зняття з реєстрації місця проживання», якщо людина не звернулась в ЦНАП протягом 5- ти днів з моменту взяття в роботу адміністратором звернення, щоб автоматично це звернення  видалялось з системи. 
17. А також громадянину на його електрон.пошту разом з оповіщенням щодо звернення в ЦНАП необхідно попередити про ці 5 днів, надати перелік документів та умови надання послуг згідно наказу МВС №1077.
