### ISSUE TITLE
Тернополь ОДА "Защита бизнеса"

### ISSUE THREAD

**Issue by Koffeek** [e-government-ua/iBP#207]

**Comment by katyafursyk** [comment]
@Koffeek При замовленні послуги на тестовому порталі вибиває помилку. В чому причина?

**Comment by Koffeek** [comment]
@katyafursyk Я Ірині писав. У нас злетіли групи та користувачі на тестовому порталі за останні два тижні. Зараз відновлю по Ваших процесах і зможете замовити десь хвилин за 10

**Comment by Koffeek** [comment]
@katyafursyk проблема не у групах користувачів. Проводиться якесь тестування функціоналу, яким ми показуємо/ховаємо поля. Як поправлять - відпишусь.

**Comment by katyafursyk** [comment]
@Koffeek Добре, будемо чекати. Дякую.

**Comment by Koffeek** [comment]
@katyafursyk альфу поправили. можна тестувати

**Comment by Koffeek** [comment]
послуга протестована та виставлена на бойовий
