### ISSUE TITLE
Тернопільська РДА - Надання довідки з Державної статистичної звітності про наявність земель та розподіл їх за власниками земель, землекористувачами, угіддями (за даними форми 6-ЗЕМ)

### ISSUE THREAD

**Issue by NizhnikAlex** [e-government-ua/iBP#208]
Копия с https://github.com/e-government-ua/iBP/issues/20

**Comment by Koffeek** [comment]
https://docs.google.com/spreadsheets/d/1jhK0pLcVOu8WQLVLt6_u3sZS0HonzOwcH39JXC-IKqM/edit?ts=562f890e#gid=0

**Comment by katyafursyk** [comment]
Доброго дня
Внесіть будь ласка зміни по послузі на порталі чиновника 
https://docs.google.com/spreadsheets/d/1jhK0pLcVOu8WQLVLt6_u3sZS0HonzOwcH39JXC-IKqM/edit#gid=0
Крім того, треба зробити так, щоб на пошту земельникам приходили скан-копії документів заявника + копія його паспорту.

**Comment by Koffeek** [comment]
@katyafursyk
Зроблено. Можете тестувати.

**Comment by Koffeek** [comment]
послуга протестована та виставлена на бойовий
