### ISSUE TITLE
Тернополь ОДА "Запит на отримання публічної інформації"

### ISSUE THREAD

**Issue by Koffeek** [e-government-ua/iBP#209]
Копия процесса по Запорожской области id_BP=zaporoshye_oda_1

**Comment by kelnerira** [comment]
послуга вже працює на бойовому, видно помилково виставили)  Ви комусь давали логін/пароль до сторінки чиновника на бойовий? Якщо ні - скиньте мені в приват. Дякую!

**Comment by kelnerira** [comment]
За законом ідентифікація громадянина для замовлення цієї послуги не є обов`язковою. Питання: 1. чи можна крок ідентифікації  зробити за бажанням - хочеш, щоб особисті дані заповнилися автоматично і потім щоб мати доступ до відслідковування стану запиту - ідентифікуйся, ні - то ні. 
2. Поля, обов`язкові для заповнення - ПІП, e-mail. При виборі способу отримання результату листом - поштова адреса. Телефон - не обов`язкове поле.
3. Потрібно перевірити чи приходить у листі з інформацією про нову заявку посилання на вхід у власний кабінет чиновника. Контакти відповідальної особи скинула у приват.
4. Кажуть в ОДА, що поле з внутрішнім номером заявки їм не потрібне, чи можна лишити не обов`язковим для заповнення? Бо думаю, що помиляються, коли буде маса запитів від одної особи, тоді зрозуміють. Чи краще зараз забрати, а як попросять - додамо назад?

**Comment by Koffeek** [comment]
Доброго дня, Ірино. Стосовно Ваших правок:

1. Ідентифікація обов'язкова на даний момент.
2. Поправимо.
3. Посилання приходить, контактну інформацію отримав і вніс.
4. Зробимо.

Сьогодні підміню процес на бойовому. щоб повідомлення про нові зверення
надходили на пошту відповідальній особі, а не мені:) Також там будуть усі
правки. Про розгортання повідомлю додатково. Дякую.

3 листопада 2015 р. 11:45 kelnerira <notifications@github.com> написав:

> За законом ідентифікація громадянина для замовлення цієї послуги не є обовязковою.
> Питання: 1. чи можна крок ідентифікації зробити за бажанням - хочеш, щоб
> особисті дані заповнилися автоматично і потім щоб мати доступ до
> відслідковування стану запиту - ідентифікуйся, ні - то ні.
> 2. Поля, обовязкові для заповнення - ПІП, e-mail. При виборі способу
> отримання результату листом - поштова адреса. Телефон - не обовязкове
> поле.
> 3. Потрібно перевірити чи приходить у листі з інформацією про нову заявку
> посилання на вхід у власний кабінет чиновника. Контакти відповідальної
> особи скинула у приват.
> 4. Кажуть в ОДА, що поле з внутрішнім номером заявки їм не потрібне, чи
> можна лишити не обовязковим для заповнення? Бо думаю, що помиляються,
> коли буде маса запитів від одної особи, тоді зрозуміють. Чи краще зараз
> забрати, а як попросять - додамо назад?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/e-government-ua/iBP/issues/209#issuecomment-153300614>
> .
>



-- 
З повагою,
Жиган Роман
бізнес-аналітик порталу igov.org.ua

**Comment by kelnerira** [comment]
протестувала, без введення телефону замовлення послуги неможливе, бо видає : "Помилка в номері телефону."

**Comment by Koffeek** [comment]
послуга протестована та виставлена на бойовий
