### ISSUE TITLE
Замечания по соцуслугам

### ISSUE THREAD

**Issue by OlgaKhomenko** [e-government-ua/iBP#210]
1. по услугам "Допомога на дітей, які перебувають під опікою чи піклуванням", "Призначення допомоги на дітей-сиріт та дітей, позбавлених батьківського піклування та грошового забезпечення прийомним батькам"не приходит уведомление типа: 
Шановний(-а) ДМИТРО ОЛЕКСАНДРОВИЧ.

Ваше звернення щодо призначення допомоги на дітей одиноким матерям зареєстровано.

Вам необхідно принести оригінал Витягу з Державного реєстру актів цивільного стану громадян про державну реєстрацію народження дитини, або довідка про народження, або документ про народження, виданий компетентним органом іноземної держави, в якому відсутні відомості про батька, за умови його легалізації в установленому законодавством порядку.

Коментар спеціаліста:

Чекаємо Вас за адресою:
Київ, вул.Закревського, 87

Телефон для довідок: 
2. адрес необходимо исправить: Київ, вул.Закревського, 87-д
3. телефон для довідок (044) 530-42-22
4.В услугах "Призначення соціальної допомоги особам, які не мають права на пенсію, та інвалідам", "Призначення державної соціальної допомоги малозабезпеченим сім'ям", "Призначення тимчасової державної допомоги дітям, батьки яких ухиляються від сплати аліментів, не мають можливості утримувати дитину або місце проживання їх невідоме" не могу распечатать форму заявления, отображает сообщение: При завантаженні форми сталася помилка

**Comment by OlgaKhomenko** [comment]
5. в услугах "Призначення одноразової винагороди жінкам, яким присвоєно почесне звання України "Мати-героїня", "Призначення державної соцальної допомоги інвалідам з дитинства та дітям-інвалідам віком до 18 років", "Призначення надбавки на догляд за інвалідом з дитинства або дитиною-інвалідом", "Призначення допомоги при усиновленні дитини", "Призначення допомоги у зв'язку з вагітністю та пологами", "Призначення компенсаційної виплати непрацюючій прецездатній особі, яка доглядає за інвалідом І групи, а також за престарілим, який досяг 80-річного віку", "Щомісячна грошова допомога малозабезпеченій особі, яка проживає разом з інвалідом I чи II групи внаслідок психічного розладу, який за висновком лікарської комісії медичного закладу потребує постійного стороннього догляду, на догляд за ним", "Видача довідкок про отримання/неотримання усіх видів державних соціальних допомог." на форме гражданина нет соглашения на обработку персональных данных
6. в сообщение гражданина по услуге "Призначення допомоги інвалідам з дитинства та дітям-інвалідам", которое формируется после первого шага сотрудника управления, добавить информацию по управлению (Управління праці та соціального захисту населення Деснянської районної в м.Києві державної адміністрації, Київ, вул.Закревського, 87-д)

Ваше звернення щодо призначення допомоги інвалідам з дитинства та дітям-інвалідам передано на розгляд в управління праці та соціального захисту населення і буде опрацьовано протягом 10 робочих днів.

Ви отримаєте додаткове повідомлення за результатами розгляду звернення.
Телефон для довідок:

З повагою,
Управління праці та соціального захисту населення
Деснянської районної в м.Києві державної адміністрації
Команда Порталу державних послуг iGov 
7. на втором шаге у сотрудника управления по услугах "Призначення допомоги інвалідам з дитинства та дітям-інвалідам", "Призначення надбавки на догляд за інвалідом з дитинства або дитиною-інвалідом", "Призначення допомоги при усиновленні дитини", "Призначення допомоги у зв'язку з вагітністю та пологами", "Призначення компенсаційної виплати непрацюючій прецездатній особі, яка доглядає за інвалідом І групи, а також за престарілим, який досяг 80-річного віку", "Щомісячна грошова допомога малозабезпеченій особі, яка проживає разом з інвалідом I чи II групи внаслідок психічного розладу, який за висновком лікарської комісії медичного закладу потребує постійного стороннього догляду, на догляд за ним" нет информации, которая біла введена гражданином, только поле "Автор звернення"
8. нет сообщений, в которых описано какие оригиналы документов предоставить, куда прийти и что дальше делать. Везде отсылается сообщение с уведомлением о результате и вложен ответ в виде копии.
9. в сообщении гражданину по услуге "Призначення державної допомоги у зв'язку з вагітністю та пологами" исправить адрес на Київ, вул.Закревського, 87-д:

Шановний(-а) ДМИТРО ОЛЕКСАНДРОВИЧ.

Ваше звернення щодо призначення державної допомоги у зв'язку з вагітністю та пологами прийнято в роботу.
Вам призначено дату і час візиту для надання оригіналу довідки про вагітність - 21/10/2015.
Адреса: Київ, вул.Закревського, 87, кабінет 201
Після надання оригіналу документу, звернення буде передано на подальше опрацювання.
Телефон для довідок:

З повагою,
Управління праці та соціального захисту населення
Деснянської районної в м.Києві державної адміністрації
Команда Порталу державних послуг iGov 
10. исправить адрес управления в сообщению гражданину по услуге "Видача довідкок про отримання/неотримання усіх видів державних соціальних допомог" на Київ, вул.Закревського, 87-д. Сейчас приходит такое сообщение:
Шановний(-а) ДМИТРО ОЛЕКСАНДРОВИЧ.

Ви подавали звернення щодо отримання довідки:
призначення допомоги інвалідам з дитинства та дітям-інвалідам
Сканкопія довідки знаходиться у додатку до листа.
Ви можете отримати оригінал довідки в Управління праці та соціального захисту населення
Деснянської районної в м.Києві державної адміністрації за адресою:
Київ, вул.Закревського, 87
Телефон для довідок:

З повагою,
Управління праці та соціального захисту населення
Деснянської районної в м.Києві державної адміністрації
Команда Порталу державних послуг iGov

**Comment by GrekD** [comment]
7. на втором шаге у сотрудника управления нет информации, которая біла введена гражданином, только поле "Автор звернення"
на этом этапе все стартовые поля вобщем-то не нужны, т.к. они ни на что уже не влияют
на этапе сообщается уже принятое решение: схвалити-відмовити
Вы уверены что эти поля надо передавать сюда?

8. нет сообщений, в которых описано какие оригиналы документов предоставить, куда прийти и что дальше делать. Везде отсылается сообщение с уведомлением о результате и вложен ответ в виде копии.
Такие сообщения есть только для услуг где необходимо предоставлять оригиналы документов. Чтоб сгенерить такое сообщение для гражданина чиновник должен выбрать 2-й вариант на этапе "проверка документов". Вариант выбора: Дані надані не в повному обсязі - направити громадянину повідомлення
подробнее в инструкции
https://docs.google.com/document/d/1-ivNSSkYmKvqvCiBGtu6VYIXQ8VptWlXU-BQBAxcxk4/edit

замечания касательно адреса, телефонов, згоди исправлю и отпишусь

**Comment by msvidran** [comment]
1.	по услугам "Допомога на дітей, які перебувають під опікою чи піклуванням", "Призначення допомоги на дітей-сиріт та дітей, позбавлених батьківського піклування та грошового забезпечення прийомним батькам"не приходит уведомление…
Эта услуга отличается от «помощь одиноким матерям» дле нее, на первом этапе обработки, нужно выбрать один из трех решений: 
- Заповнені дані вірні, інформація направлена на розгляд, очікується рішення
- Дані заповнені невірно, відхилити звернення (обов'язково впишіть коментар нижче)
-Дані надані не в повному обсязі - направити громадянину повідомлення (обов'язково впишіть коментар нижче)
При первом решении не приходит ничего, просто ожидают решения и после его принятия (положительного или отрицательного) тогда только отправляется письмо.
При втором решении письмо отказа с комментариями при неправильном заполнении данных в полях.
При третьем решении специалист просит гражданина донести недостающие документы в срок 3 месяца, а пока заявка будет висеть в «необроблені», по истечению 3-х месяцев, если гражданин не донес недостающие документы, дело закрывается.

2,3,4 вопросы поправим

**Comment by OlgaKhomenko** [comment]
1. на втором шаге у сотрудника управления нет информации, которая біла введена гражданином, только поле "Автор звернення"
на этом этапе все стартовые поля вобщем-то не нужны, т.к. они ни на что уже не влияют
на этапе сообщается уже принятое решение: схвалити-відмовити
Вы уверены что эти поля надо передавать сюда?

нет, не уверена, копируем услуги Днепропетровска без анализа. Написала исходя из других услуг. Если вы уверены, что это так и должно быть, тогда без замечания.

2. нет сообщений, в которых описано какие оригиналы документов предоставить, куда прийти и что дальше делать. Везде отсылается сообщение с уведомлением о результате и вложен ответ в виде копии.
Такие сообщения есть только для услуг где необходимо предоставлять оригиналы документов. Чтоб сгенерить такое сообщение для гражданина чиновник должен выбрать 2-й вариант на этапе "проверка документов". Вариант выбора: Дані надані не в повному обсязі - направити громадянину повідомлення
подробнее в инструкции
https://docs.google.com/document/d/1-ivNSSkYmKvqvCiBGtu6VYIXQ8VptWlXU-BQBAxcxk4/edit

опять же, не могу спорить. Пока оставляем, как в Днепропетровске, после анализа этих услуг в Киеве, будем исправлять.

**Comment by GrekD** [comment]
все изменения внесены

**Comment by OlgaKhomenko** [comment]
в услуге "Призначення компенсаційної виплати непрацюючій прецездатній особі, яка доглядає за інвалідом І групи, а також за престарілим, який досяг 80-річного віку" нет згоды.

**Comment by GrekD** [comment]
спасибо, исправила

**Comment by GrekD** [comment]
услуги на боевом
