### ISSUE TITLE
Дніпропетровська обл. (Вільногірськ) - Реєстрація громадського об’єднання

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#213]

**Comment by GrekD** [comment]
Документация:
1. nikolaev_oda_1

2. http://e-services.dp.gov.ua/_layouts/Information/pgCardServices.aspx?ID=8322&TypeAg=0&Filter=%D0%A0%D0%B5%D1%94%D1%81%D1%82%D1%80%D0%B0%D1%86%D1%96%D1%8F%20%D0%B3%D1%80%D0%BE%D0%BC%D0%B0%D0%B4%D1%81%D1%8C%D0%BA%D0%BE%D0%B3%D0%BE%20%D0%BE%D0%B1%E2%80%99%D1%94%D0%B4%D0%BD%D0%B0%D0%BD%D0%BD%D1%8F

3. http://e-services.dp.gov.ua/_layouts/WordViewer.aspx?id=/Lists/PermitStages/Attachments/8322/%D0%86%D0%BD%D1%84%D0%BE%D1%80%D0%BC_%D0%BA%D0%B0%D1%80%D1%82%D0%BA%D0%B0.docx

**Comment by GrekD** [comment]
https://igov.org.ua/service/20/general
на боевом

**Comment by annastolbova** [comment]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [ ]  Першотравенськ
- [ ]  Синельникове
- [ ]  Криворізький р-н
- [ ]  Томаківський р-н
- [ ]  Юр’ївський р-н


закрити послугу на наступні міста/райони:

- [ ]  Вільногірськ
- [ ]  Дніпродзержинськ

**Comment by GrekD** [comment]
выполнено
