### ISSUE TITLE
Дніпропетровська обл. (Вільногірськ) - Прийняття повідомлення про утворення громадського об’єднання

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#214]

**Comment by GrekD** [comment]
1. http://e-services.dp.gov.ua/_layouts/Information/pgCardServices.aspx?ID=7600&TypeAg=0&Filter=%D0%9F%D1%80%D0%B8%D0%B9%D0%BD%D1%8F%D1%82%D1%82%D1%8F%20%D0%BF%D0%BE%D0%B2%D1%96%D0%B4%D0%BE%D0%BC%D0%BB%D0%B5%D0%BD%D0%BD%D1%8F%20%D0%BF%D1%80%D0%BE%20%D1%83%D1%82%D0%B2%D0%BE%D1%80%D0%B5%D0%BD%D0%BD%D1%8F%20%D0%B3%D1%80%D0%BE%D0%BC%D0%B0%D0%B4%D1%81%D1%8C%D0%BA%D0%BE%D0%B3%D0%BE%20%D0%BE%D0%B1%E2%80%99%D1%94%D0%B4%D0%BD%D0%B0%D0%BD%D0%BD%D1%8F

2. http://zakon2.rada.gov.ua/laws/show/z2100-12#n18

**Comment by GrekD** [comment]
https://igov.org.ua/service/1408/general
на боевом

**Comment by annastolbova** [comment]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [ ] Першотравенськ
- [ ]  Синельникове
- [ ] Криворізький р-н
- [ ] Томаківський р-н
- [ ] Юр’ївський р-н

закрити послугу на наступні міста/райони:

- [ ] Вільногірськ	
- [ ] Дніпродзержинськ

**Comment by GrekD** [comment]
выполнено
