### ISSUE TITLE
Дніпропетровська обл. (Вільногірськ) - Внесення до реєстру громадських об’єднань запису про рішення щодо саморозпуску або реорганізації громадського об’єднання, а також про припинення діяльності громадського об’єднання

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#219]

**Comment by GrekD** [comment]
1. карта
 http://e-services.dp.gov.ua/_layouts/Information/pgCardServices.aspx?ID=7604&TypeAg=0&Filter=%D0%92%D0%BD%D0%B5%D1%81%D0%B5%D0%BD%D0%BD%D1%8F%20%D0%B4%D0%BE%20%D1%80%D0%B5%D1%94%D1%81%D1%82%D1%80%D1%83%20%D0%B3%D1%80%D0%BE%D0%BC%D0%B0%D0%B4%D1%81%D1%8C%D0%BA%D0%B8%D1%85%20%D0%BE%D0%B1%E2%80%99%D1%94%D0%B4%D0%BD%D0%B0%D0%BD%D1%8C%20%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D1%83%20%D0%BF%D1%80%D0%BE%20%D1%80%D1%96%D1%88%D0%B5%D0%BD%D0%BD%D1%8F%20%D1%89%D0%BE%D0%B4%D0%BE%20%D1%81%D0%B0%D0%BC%D0%BE%D1%80%D0%BE%D0%B7%D0%BF%D1%83%D1%81%D0%BA%D1%83

2. заява
http://zakon2.rada.gov.ua/laws/show/z2100-12#n18

**Comment by GrekD** [comment]
[inf-kartka-vnes-vidom-pro-samorozpusk.docx](https://github.com/e-government-ua/iBP/files/29843/inf-kartka-vnes-vidom-pro-samorozpusk.docx)

**Comment by GrekD** [comment]
на боевом

**Comment by annastolbova** [comment]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [ ]  Першотравенськ
- [ ]  Синельникове
- [ ]  Криворізький р-н
- [ ]  Томаківський р-н
- [ ]  Юр’ївський р-н

закрити послугу на наступні міста/райони:

- [ ]  Вільногірськ
- [ ]  Дніпродзержинськ

**Comment by GrekD** [comment]
выполнено
