### ISSUE TITLE
Днепр обл. Видача довідки про: наявність та розмір земельної частки (паю), наявність у Державному земельному кадастрі відомостей про одержання у власність земельної ділянки у межах норм безоплатної приватизації за певним видом її цільового призначення (використання)

### ISSUE THREAD

**Issue by Koffeek** [e-government-ua/iBP#238]
переработка процесса issue 78 с дополнениями. 
Инфокарта http://e-services.dp.gov.ua/_layouts/WordViewer.aspx?id=/Lists/PermitStages/Attachments/8129/%D0%86%D0%9A_006.doc
Заява 
https://drive.google.com/file/d/0B68lQ-z45GpYMGUyZnhxdzJDcHM/view?usp=sharing

**Comment by NizhnikAlex** [comment]
Для большей гибкости разбита на две услуги 238 и 238a.
