### ISSUE TITLE
Ужгород - "Підготовка та завіряння копій рішень, витягів з них, підготовка ксерокопій матеріалів"

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/iBP#24]
Опис
https://drive.google.com/open?id=0B5RcylWxCQTwRnBvbDlTekMtanM

Зразок заяви: https://docs.google.com/document/d/15jhM1dVLig9OFZm2MPnj2Mzcct_a-08Lb8QhZGo0tZw/edit#

**Comment by NizhnikAlex** [comment]
1. Пользователь передает данные
2. Чиновник проверяет данные, готовит и заверяет документ.
3. Результат - или отказ (если запрашиваемый документ не найден, или письмо клиенту что он может забать заказанный документ по определенному адресу

**Comment by VadimGulich** [comment]
В дашбоарде  не отображаются поля номера телефона и адреса из-за этого(при печати формируется заявка не соответствующая описанию  (при заказе услуги указываются эти данные)
![image](https://cloud.githubusercontent.com/assets/12964120/9625209/e4030e7a-515c-11e5-94e5-fa2b7c6bbf6a.png)

Это согласовано ?

**Comment by NizhnikAlex** [comment]
Исправил, должна отображатся вся информация

**Comment by VadimGulich** [comment]
Исправлено, БП  работает корректно
