### ISSUE TITLE
Дніпропетровська обл. - Дозвіл (санітарний паспорт) на проведення робіт з джерелами іонізуючих випромінювань в установах України

### ISSUE THREAD

**Issue by msvidran** [e-government-ua/iBP#248]
Регламент: http://e-services.dp.gov.ua/_layouts/Information/PDFViewer.aspx?Patch=/Lists/PermitStages/Attachments/6360/%D0%A0%D0%B5%D0%B3%D0%BB%D0%B0%D0%BC%D0%B5%D0%BD%D1%82+%28%D1%96%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D1%96%D0%B9%D0%BD%D0%B0+%D0%BA%D0%B0%D1%80%D1%82%D0%BA%D0%B0%29.pdf
Заява: http://e-services.dp.gov.ua/_layouts/WordViewer.aspx?id=/Lists/PermitStages/Attachments/6360/%D0%97%D0%B0%D1%8F%D0%B2%D0%B0+%28%D0%97%D0%A3+%D0%9F%D1%80%D0%BE+%D0%B4%D0%BE%D0%B7%D0%B2%D1%96%D0%BB%D1%8C%D0%BD%D1%83+%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D1%83+%D1%83+%D1%81%D1%84%D0%B5%D1%80%D1%96+%D0%B3%D0%BE%D1%81%D0%BF%D0%BE%D0%B4%D0%B0%D1%80%D1%81%D1%8C%D0%BA%D0%BE%D1%97+%D0%B4%D1%96%D1%8F%D0%BB%D1%8C%D0%BD%D0%BE%D1%81%D1%82%D1%96%29.doc
реквізити для сплати: http://e-services.dp.gov.ua/_layouts/WordViewer.aspx?id=/Lists/PermitStages/Attachments/8891/%D0%A0%D0%B5%D0%BA%D0%B2%D1%96%D0%B7%D0%B8%D1%82%D0%B8+%D1%80%D0%B0%D1%85%D1%83%D0%BD%D0%BA%D1%96%D0%B2.doc

**Comment by annastolbova** [comment]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [ ]  Жовті Води
- [ ] Орджонікідзе
- [ ] Першотравенськ
- [ ] Васильківський р-н
- [ ] Магдалинівський р-н
- [ ] Синельниківський р-н

**Comment by zolotovatatyana** [comment]
https://drive.google.com/file/d/0B2wsXHZDmFW6aktER1FuNk50eDA/view?usp=sharing с 1 мая сэс не предоставляет услуги

**Comment by zolotovatatyana** [comment]
на боевом
