### ISSUE TITLE
Ужгород - Аварійний дозвіл на проведення земельних робіт.

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/iBP#25]
: https://drive.google.com/open?id=0B5RcylWxCQTwcTVVdkZjc2hwcHM

Перелік документів та зразок заяви: https://docs.google.com/dohttps://drive.google.com/open?id=0B5RcylWxCQTwcTVVdkZjc2hwcHMcument/d/14DRK5s4zwtAbJi3RoI_S__D-vEgdadk2WUMebiDTmiU/edit

**Comment by GrekD** [comment]
Паша, кто региональный
 РМ по этому процессу? Есть контакты какие-то?

**Comment by smit-pb** [comment]
Перелік документів та зразок заяви: https://docs.google.com/dohttps://drive.google.com/open?id=0B5RcylWxCQTwcTVVdkZjc2hwcHMcument/d/14DRK5s4zwtAbJi3RoI_S__D-vEgdadk2WUMebiDTmiU/edit
-----------------------------
Not Found
Error 404
документ удален ? или ссылка не корректная ?

**Comment by GrekD** [comment]
https://docs.google.com/document/d/1g_-FTsvAwuajn998QnsX_KqXb7s_gERV24PuchffKtg/edit
вот есть копия

описание процесса:
1. гражданин подает заявку с кучей бумажных приложений, получает уведомление что заявка зарегистрирована
2. чиновник проверяет приложения (копии бумажных документов), если все ок - берет в работу заявку, если нет - отклоняет с комментариями для гражданина
3. чиновник получает подписи других чиновников, если разрешение дают - то гражданин получает об этом уведомление и приглашение прийти забрать разрешение; если они не дают разрешение - то гражданин уведомляется об этом

**Comment by kurbpa** [comment]
@smit-pb 


https://docs.google.com/document/d/1g_-FTsvAwuajn998QnsX_KqXb7s_gERV24PuchffKtg/edit
вот есть копия

описание процесса:
1. гражданин подает заявку с кучей бумажных приложений, получает уведомление что заявка зарегистрирована
2. чиновник проверяет приложения (копии бумажных документов), если все ок - берет в работу заявку, если нет - отклоняет с комментариями для гражданина
3. чиновник получает подписи других чиновников, если разрешение дают - то гражданин получает об этом уведомление и приглашение прийти забрать разрешение; если они не дают разрешение - то гражданин уведомляется об этом

**Comment by GrekD** [comment]
на боевом
