### ISSUE TITLE
КМДА - Доработки услуги:Надання довідки про перебування на обліку громадян, які потребують відповідно до законодавства поліпшення житлових умов

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/iBP#26]
1.  Добавить возможность на форме гражданина прикрепить форму 3:
Копія довідки про місце реєстрації та склад сім’ї (форма 3)
Серыми буквами написать информацию под название атрибута: громадянам, які проживають у відомчих гуртожитках, приватних будинках, будинках житлово-будівельних кооперативів та ін. необхідно самостійно надати довідку по формі № 3

2. Доработать процесс ( убрать лишний шаг в ЦНАПе на старте процеса)

3. На шаге “Перевірка пакету документів в РДА” сделать Підставу для відмови в наданні послуги вариантами с возможностью выбора :
* Виявлення в поданих документах недостовірних відомостей.
* Подання заявником неповного пакета документів.
* Громадянин не перебуває на квартирному обліку

4.На шаге “Перевірка пакету документів в РДА” добавить текстовый блок “Коментар щодо відмови у наданні послуги”

5. В сообщение 6.1 про відмову вывести  “Коментар щодо відмови у наданні послуги”:

Шановний(-а), #І.Б.#!
На жаль, змушені відмовити Вам у наданні послуги: "Надання довідки про участь в приватизації житла державного житлового фонду".                    
Підстава: #значение атрибута “Підстава для відмови”#
Коментар щодо відмови у наданні послуги: #значение атрибута “Коментар щодо відмови у наданні послуги”#
З повагою,
Відділ обліку та розподілу житлової площі
#Назва району Києва#

**Comment by kurbpa** [comment]
Вылито на альфу

**Comment by OlgaKhomenko** [comment]
Не отображается форма3, которую прикрепил гражданин, на следующих шагах у чиновника.

**Comment by kurbpa** [comment]
вылито на боевой
