### ISSUE TITLE
Замечания субсидии _Киев

### ISSUE THREAD

**Issue by OlgaKhomenko** [e-government-ua/iBP#260]
1. Не работает поиск под пользователями v.dyachuk, desnsubsidy. Думаю, что проблема в длинном ФИО пользователя. Верстка съезжает и поле для ввода ФИО неактивное.
Протестировала на своем компе, под  v.dyachuk не работает, под desnsubsidy работает. Но у пользователя desnsubsidy на рабочем месте проблема есть.
2. На печатную форму заявы в левый верхний угол вывести номер заявки гражданина из системы. 
3. Сделать фильтр в "Обработанные" по результату, чтоб было понятно, по каким заявкам отказано.
4. Не работает фильтр "Фільтр за групою статусів"
5. Сделать подсказку к полю "Назва організації, що надає послугу, де Ви працюєте " - Вкажіть повну назву та адресу (область, район, місто).
6. Когда гражданин выбрал по коммунальным услугам "не користуюсь", чтоб в форме чиновника проставляло прочерки в полях, которые относятся к улуге, тогда сотруднику соцзащиты будет понятно, что гражданин не пользуется, а не просто забыл ввести данные.
7.  в заявлении данные по паспорту не влазят, если там много информации.
8.  нельзя распечатать документы, если не выбрано значение в поле "Стан". Должна быть возможность распечатать заполненный формы без выбора решения.

**Comment by OlgaKhomenko** [comment]
6. в заявлении данные по паспорту не влазят, если там много информации.
7. нельзя распечатать документы, если не выбрано значение в поле "Стан". Должна быть возможность распечатать заполненный формы без выбора решения.

**Comment by kurbpa** [comment]
@OlgaKhomenko 
1.  Проблема  более глобальная. Связана с версткой.
2. Проблематично. Необходима доработка на стороне бэк-энда
3. Прошу не  трогать пока этот раздел - он в разработке.
4. Функционал в разработке.
5. Можете сделать своими силами - я подскажу как.
6. Можете сделать своими силами - я подскажу как
7. Надосмотреть на конкретном примере
8. Проблема более глобальная. Решиться после внедрения динамических форм на стороне  чиновника.

**Comment by OlgaKhomenko** [comment]
9. Есть два периода,по которым начисляют субсидии. Поэтому кроме года пресмотреть возможность выбора периода "за последние три месяца". При выборе этого периода добавить обязательность прикрепить справку о доходах с места работы.
10. Не предусмотрена возможность выбора нескольких вариантов значение "Ваш вид доходу". Ведь пенсионер может получать пенсию и работать одновременно!
11. Поле "Реєстраційний номер облікової картки платника податків особи1 и т.д." ограничить  на определенное количество символов
12. Если гарячей водой не пользуются, то должна быть возможность указать колонка или др.вариант.
13. Также по гарячей воде разные расчеты в зависимости от того есть полотенцесушитель или нет. Поля для ввода такой информации тоже не предусмотрено на форме гражданина.

**Comment by dmitrijzabrudskij** [comment]
1. они все равно в таком случае просят принести оригиналы -  период сотрудники соцзащиты видят при обработке заявок. поэтому пока не делалось. и не вижу смысла делать пока не договоримся с ними о приеме сканированной формы
2. в днепропетровском процессе предусмотрена - через запятую
3. можно, сделаем валидатор
4. не нужно этого указывать - достаточно поставить "не користуюсь" - в соцзащиту от коммунального предприятия и так поступает эта информация
5. это не нужно - горячая вода либо есть, либо ее нет.

**Comment by OlgaKhomenko** [comment]
@dmitrijzabrudskij 
1. понятно
2. через запятую потом вводят и место доходов?
3.ок
4. не нам с вами решать, что необходимо сотрудникам. 
5. от наличия полотенцесушителя зависит стоимость. Это необходимо учитывать.

Интересуют еще замечания, которые указаны в запросе. Что по ним мне обещать сотрудникам?

**Comment by dmitrijzabrudskij** [comment]
2. да
4. это ответ от соцзащиты Днепропетровска
5. не зависит. точно так же выяснял у нашей соцзащиты
по остальным путам вам Паша отвечал. он писал ответ вместе со мной

**Comment by OlgaKhomenko** [comment]
@dmitrijzabrudskij 
Я понимаю, что он писал. 
Просьба внести изменения в процесс хотя бы по:
1. по п.1 уменьшить ФИО сотрудников, чтоб эта проблема была решена хоть таким образом, т.к. на данный момент поиск не работает и очень сложно найти заявку по распечатанной декларации, чтоб дать ответ гражданину.
2. сделать п. 5 и п.6, т.к. у нас сейчас нет такой возможности в связи с единым процессом по субсидиям.

Также просьба сделать уведомления на почту сотруднику по новым заявкам.

**Comment by OlgaKhomenko** [comment]
@dmitrijzabrudskij 
Если делается единый процесс для всей страны, тогда необходимо изучить детально организацию и особенности в каждом регионе. В данном случае, работа в Днепропетровске отличается от работы в Киеве, т.к. взаимодействие с комунальными предприятиями настроены другим образом.  У нас есть единый центр, который отвечает за  коммунальные платежи и они никак не связаны с сотрудниками, которые принимают документы по субсидиям.

**Comment by OlgaKhomenko** [comment]
@dmitrijzabrudskij 

по вопросу "в днепропетровском процессе предусмотрена - через запятую" просьба предусмотреть и для Киева

**Comment by dmitrijzabrudskij** [comment]
можем вернуть вам ваш процесс и будете его править. все равно пока запуск на всю страну откладывается. 

но рано или поздно его перекроет днепропетровский процесс. и унифицировать под особенности каждого уголка страны не получится - будут свои нюансы вносить через уточнение данных (появится или в эту, или во вторую по порядку версию)
