### ISSUE TITLE
Создать бизнес-процесс по эскалации

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/iBP#282]
Создать бизнес-процесс по эскалации в котором на старте ожидать параметры из услуги 
(название файла процесса должно начинаться со слова system_escalation): 

Переменные:
переменные процесса:
bankIdlastName
bankIdfirstName
bankIdmiddleName
phone
nID_Protected - взять из таски
processName - название процесса 
processID - ид процесса (уникальный идентификатор)
organ - название группы, которая отработала закрываемую таску
data - не обязательное поле.

2) После старта переходим в юзертаску, где отображаем все вышеперечисленные поля,
а также поля для ввода коментария волонтера. 
Пока что в качестве группы-исполнителя проставлять одну единственную группу, которую необходимо создать для отработки эскалации. 

3) После отработки волонтером таски переходим в сервис-таску, где будем сохранять данные, 
введенные волонтером, в базу данных. activiti:delegateExpression сервис-таски setEscalationFeedback (ее создаст разработчик).

**Comment by Koffeek** [comment]
@OlgaTurenko 
Группа заведена. Процесс лежит в wf-region/src/main/resources/bpmn/Maksim_test/system_escalation.bpmn

**Comment by bvv4ik** [comment]
@OlgaTurenko 
"Процесс лежит в wf-region/src/main/resources/bpmn/Maksim_test/system_escalation.bpmn"
так а почему не в deployment?

**Comment by Koffeek** [comment]
По старому процессу вопросов нет
