### ISSUE TITLE
Дніпропетровськ - Державна реєстрація земельної ділянки з видачею витягу з Державного земельного кадастру

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#286]

**Comment by GrekD** [comment]
на боевом№100

**Comment by annastolbova** [comment]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [ ] Жовті Води	
- [ ] Марганець	
- [ ] Нікополь	
- [ ] Новомосковськ	
- [ ] Орджонікідзе	
- [ ] Павлоград	
- [ ] Першотравенськ	
- [ ] Синельникове	
- [ ] Тернівка	
- [ ] Васильківський р-н	
- [ ] Верхньодніпровський р-н	
- [ ] Криворізький р-н	
- [ ] Криничанський р-н	
- [ ] Магдалинівський р-н	
- [ ] Межівський р-н	
- [ ] Нікопольський р-н	
- [ ] Новомосковський р-н	
- [ ] П’ятихатський р-н	
- [ ] Павлоградський р-н	
- [ ] Петропавлівський р-н	
- [ ] Покровський р-н	
- [ ] Синельниківський р-н	
- [ ] Солонянський р-н	
- [ ] Томаківський р-н	
- [ ] Широківський р-н	
- [ ] Юр’ївський р-н

**Comment by GrekD** [comment]
раскрыто на боевом
https://igov.org.ua/service/100/general
