### ISSUE TITLE
Тернополь ОДА - Получение одноразовой материальной помощи

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/iBP#3]
Описание
https://drive.google.com/file/d/0B-TXzbaEvbw9eVhDNzdPOS1JeHM/view?usp=sharing 

Заказчик: Ирина Кельнер

**Comment by kurbpa** [comment]
@Aleksey1590 
https://docs.google.com/spreadsheets/d/1ZsOXapBS_wl4Jdg2y7o_Z9YPx81aCJFxKkCAIP6m01U/edit?usp=sharing правки, які потрібно внести за результатом підсумкової зустрічі в ОДА, те, що червоним - маю перепитати у чиновників чи вони то хочуть 

(Ирина Кельнер)

**Comment by kelnerira** [comment]
https://docs.google.com/spreadsheets/d/1ZsOXapBS_wl4Jdg2y7o_Z9YPx81aCJFxKkCAIP6m01U/edit?usp=sharing 
Аркуш 2 актуальні правки. Кажуть у ОДА, що вже остаточні.

**Comment by Koffeek** [comment]
На боевом
