### ISSUE TITLE
Нужны наставники

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/iBP#303]
Привет ребята! Новички хотят помогать, но они не в курсе что и как.
1. Кто готов стать наставником
2. Где вы общаетесь, потому как в Слаке тишина
3. Есть ли разжеванные инструкции для новичков
4. Ваши предложения и пожелания

**Comment by kurbpa** [comment]
@VadymVolos   
1. Вопрос настолько  неоднозначный, что ответить однозначно тоже не могу при всё желании.
Помогать можно по разному.
Всё что касается бизнес-аналитики ( системной-аналитики ) это достаточно  сложно. Я  инвестировал очень много времени на  вроде бы мотивированных и заинтересованных новичков, которые в итоге перестают выходить на связь.

К сожалению тут высокий порог вхождения и понизить его не представляется возможным

Принятое решение - не инвестировать больше время на аналитиков, за действительно редкими исключениями, когда 100% гарантия, что человек не пошлет всё подальше на пол-пути.

2. С аналитиками проекта у меня связь сейчас либо очно либо по телефону. Остальные - скайп, емейл, ФБ, слак и т.д.

3. Инструкции с чего начать (не связано с б-анализом и  проектированием процессов)- https://docs.google.com/a/privatbank.ua/forms/d/1w-BR01CSicvhWSXb36CiRjHCwvp-vyPuTHBaWw1iW4U/viewform

4.Затрудняюсь ответить, может  коллеги меня дополнят.

**Comment by ezhikus** [comment]
Как на счёт сделать короткий обучающий ролик? Представим себе "свежего бизнес-аналитика". Я понимаю, что такое Гитхаб, активити, могу смотреть бизнес-процессы в админке, вижу bpnm-файлы в репозитории. И вот я нахожу услугу, к примеру, для Днепропетровска, которая (с минимальными изменениями) может быть запущена для Житомира. Я понимаю, что вот сюда надо добавить оповещение на email, а вот здесь - поле на форму. Но что делать дальше? Достаточно ли отредактировать bpnm-файл (ну и может шаблон печати для заявления) или ещё нужно где-то его прописывать\деплоить? Имею ли я право комитнуть его в репозиторий и проверить на тестовом сервере? Мне лично очень помог бы короткий видеоролик (или инструкция) в духе "вот услуга для Днепра, давайте сделаем такую же, только чуть-чуть другую для города N". 

Можно такое сделать? Я бы тогда смог для своего города сам все процессы рисовать, было бы круто.

**Comment by NizhnikAlex** [comment]
Суть в масштабировании, а не создании для каждого населенного пункта нового процесса.
Нюансов очень много на самом деле. "Голый" активити не так много позволяет сделать. Многие вещи уже допиливались (и допиливаются постоянно). Т.е. надо не просто смотреть ролик и переделывать бпмн, а быть в курсе общего развития проекта (технической части), это не реально описать или снять.
"Свежий бизнес-аналитик" должен около 2-3 недель все свое время уделить проекту, крайне желательно в коллективе, да и потом отслеживать новшества, участвовать в миттингах и т.д.

**Comment by ezhikus** [comment]
Суть, конечно, в масштабировании. Нам нужно иметь бизнес-аналитиков в каждом городе в идеале. Я вот пересмотрел с десяток уже реализованных услуг и понял, что у нас в городе они ВСЕ работают иначе. И если на ребят из Днепра повесить переделку всех услуг для всех городов - они просто загнутся. Я хочу сам иметь возможность изменить услугу для своего города. Если там, грубо говоря, надо в форму заявки добавить 2 поля и потом использовать их в репорте для печати плюс лишний email отослать - ну неужели для этого нужно глубоко понимать все детали проекта?

**Comment by Koffeek** [comment]
@ezhikus В принципе желательно понимать детали проекта, как минимум это поможет избежать многих шишек. Услуги желательно максимально унифицировать иначе получается непонятная свалка. Даже добавить 2-3 поля под конкретный город в конкретный процесс будет быстрее, чем отрисовывать его заново. Нужно оптимизировать услуги для городов, а не заводить отдельные процессы для каждого. В Украине сколько городов? А ещё + районы, села, поселки... Если для каждого выводить свой процесс хотя бы по услугам ЦНАПов (от 80 до 150 в одном) мы просто запутаемся в хаосе.

**Comment by kurbpa** [comment]
@ezhikus 
Мне искренне импонирует Ваш высокий уровень мотивации!!!  :+1:  поэтому попробую  ответить последовательно по пунктам:

1. **сделать короткий обучающий ролик** 
к сожалению не готов взяться за  подобное, т.к. кастомный функционал   уже настолько велик и включает такое большое количество нюансов, что здесь целую рубрику делать надо. По  созданию же простых процессов стандартными средствами активити -  достаточно много видео  в сети существуют. В т.ч. даже в нашей wiki на гитхабе. - https://www.youtube.com/watch?v=0PV_8Lew3vg

2. **Если надо в форму заявки добавить 2 поля и потом использовать их в репорте для печати плюс лишний email отослать - ну неужели для этого нужно глубоко понимать все детали проекта?**
Чтобы изменить ЗАПУЩЕННУЮ  для конкретного города  услугу,   конечно  всех нюансов знать не нужно. Но проект в целом знать надо, т.к. настройки Б-процессов уже очень давно вышли за  границы только одного единственного bpmn- файла. Я постарался описать часть изменений в файле ( дополняю его по возможности ) - https://docs.google.com/document/d/1LES8GhAvwqRKkwX2QUsRGksoI45vGbdiRCHJUzxjMXw/edit#heading=h.rfpv86iult87
Но с другой стороны мы максимально стараемся стандартизировать услуги ( на момент  запуска в том или ином регионе). Стандартизированные услуги для нового региона/населенного пункта раскрывать довольно несложно - вопрос конфигурационных файлов.

3. **Достаточно ли отредактировать bpnm-файл (ну и может шаблон печати для заявления) или ещё нужно где-то его прописывать\деплоить? Имею ли я право комитнуть его в репозиторий и проверить на тестовом сервере?**
Для проверок настоятельно рекомендую использовать локальные сборки, чтобы не уложить тестовый сервак. 
Получение прав на **push**  подразумевает, что Вы уже ознакомились с проектом и осознаете какие изменения делаете и к чему они приведут. Мы готовы выдвать  такие доступы коенчно. Просто не хочется раздавать их  по-дефолту налево и направо, чтобы не  утонуть в логах ошибок.(как уже показала практика - хватает и такого).

Помимо этого  логично, что  изменения процесса  оговорены предварительно с теми же региональными координаторами групп, которые в курсе тенденций  внедрения электронных услуг в  регионе/городе.

**Comment by ezhikus** [comment]
Я бы хотел уточнить по поводу "Стандартизации услуг", о которой Вы говорите. Я видел в некоторых файлах код типа " if (тернополь) - показать такое поле, else if (николаев) - показать эти два поля". Речь идёт о такой стандартизации? А чем это лучше отдельных файлов для каждого города?

@kurbpa я пытаюсь как-то найти способ запускать услуги в своём городе. Вот нашел я работающую услугу на igov, уговорил ЦНАП её запустить, они мне написали 10 отличий их процесса от нашего, я написал письмо Вам - ну и сижу жду. А так хотелось бы что-то делать, чтобы было быстрее. По активити видео я посмотрел, и код понемножку тоже читаю. Просто трудно без подсказок, вопросы "а откуда это берётся и куда девается" - на каждом шагу.

Спасибо за гугл-доку, буду читать, не видел её раньше.

**Comment by Koffeek** [comment]
@ezhikus " Я видел в некоторых файлах код типа " if (тернополь) - показать такое поле, else if (николаев) - показать эти два поля"" - это как раз пример, когда город упирается стандартизации. Есть примеры (и их большинство), когда услуга, обработанная по шаблону одного города раскрывается ещё на 5-7 без проблем. В случае несовпадений - ищем компромиссы. Если услуги отличаются в мелочах, то можем пойти на описаный в цитате костыль, т.к. он же может встретится ещё в 2-3 городах. Если идет глобальное несовпадение и желание госоргана менять процесс отсутствует, тогда приходится делать отдельный процесс для города. Чем больше пул процессов, тем сложнее их рефакторить при появлении новых облегчающих жизнь моментов. Коллеги подтвердят, что, например, шаблонизация емейлов или внедрение динамических форм в весь спектр процессов даже месяц назад занимала огромное количество времени, которое могло тратиться на разработку новых услуг.

**Comment by ezhikus** [comment]
@kurbpa - обалденная дока! Дала мне ответы на ряд вопросов, ещё раз спасибо.
@Koffeek - конечно, Вы правы. Меньше сущностей - легче поддержка. Но я как подумаю, что каждую подгонку услуги в городе под стандарт igov придётся, возможно, протягивать отдельным приказом мера...

**Comment by VadymVolos** [comment]
Привет ребята!
На фейсбуке сделали закрытую группу: "IGov.org.ua - група для навчання Аналітиків і Менеджерів" https://www.facebook.com/groups/1445694629067339/

Ирина Кельнер откликнулась помочь, я решил ее сделать Куратором.
Ірина Кельнер - куратор з навчальної роботи аналітиків і менеджерів.

Она там помогает ребятам, отвечает на вопросы, кто юзает фейсбук присоединяйтесь помогайте ей.
