### ISSUE TITLE
Расширить услугу  на Николаев. Видача дубліката оригіналу свідоцтва про реєстрацію громадського об’єднання та/або статуту

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/iBP#309]
Заказчик - Решетник Юрий.
Ссылка на услугу на портале - https://igov.org.ua/service/1412/general

**Comment by GrekD** [comment]
На тестовом открыла, уже почти месяц жду ответ от мин.юста. Как только достучимся до них - переоткрою ишью
