### ISSUE TITLE
Расширить услугу  на Николаев. Внесення до реєстру громадських об’єднань відомостей про відокремлений підрозділ громадського об’єднання

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/iBP#310]
Заказчик - Юрий Решетник.
Ссылка на услугу на портале - https://igov.org.ua/service/1413/general

**Comment by GrekD** [comment]
На тестовом открыла, уже почти месяц жду ответ от мин.юста. Как только достучимся до них - переоткрою ишью
