### ISSUE TITLE
Житомир - правки по услуге "Надання довідок незайнятому населенню про відсутність земельних ділянок для ведення ОСГ"

### ISSUE THREAD

**Issue by ezhikus** [e-government-ua/iBP#315]
После обсуждения с ЦНАП г.Житомир в услуге "Надання довідок незайнятому населенню про відсутність земельних ділянок для ведення ОСГ" требуется сделать следующие изменения:

1. В футере всех писем изменить надпись "Міська державна адміністрація м.Житомир" на "Житомирська міська рада"
2. Из принт-формы заявления на услугу убрать поле "Рішення про надання послуги", поскольку на момент, когда форму нужно печатать - решение ещё не принято. А когда будет принято - это уже будет другой документ.
3. На форму ввода данных при заказе услуги добавить обязательное текстовое поле "Адреса реєстрації заявника" (сразу после паспортных данных).
4. На принт-форме заявления добавить вывод поля "Адреса реєстрації заявника" - сразу после поля "Паспортні дані"

**Comment by ezhikus** [comment]
Пункт 1 - сделано в коммите  c99c322f2074d253458d4eb50ed16a3eef847cb1 

А как бы мне эту задачу заассайнить на себя? Нет прав.

**Comment by Koffeek** [comment]
@ezhikus п.3, п,4 Сделано, п,2 У Вас в процессе не принтформа, а стандартный перечень данных. Если необходимо можем сделать полноценное заявление, но тогда нужен его образец. Процесс оставлять одноходовым или делать двухходовым по примеру khmelnitskij_mvk_2?

**Comment by ezhikus** [comment]
@Koffeek 
Процесс одноходовый - нормально. По пункту 2 - вывод в текущем виде устраивает, но нужно убрать из списка печатаемых данных поле "Рішення про надання послуги". Если это можно сделать в текущем варианте, то это устроит. А если в стандратном виде печатаются все поля и это нельзя изменить - тогда надо делать заявление по образцу (см. в аттаче).

[1.docx](https://github.com/e-government-ua/iBP/files/75507/1.docx)

**Comment by Koffeek** [comment]
@ezhikus Заявление сделать проще и выглядеть оно будет лучше, чем набор полей. Я там ещё тексты писем немного стандартизирую и отпишусь, когда будет готово для проверки на альфе

**Comment by Koffeek** [comment]
@ezhikus Можно проверять https://test.igov.org.ua/service/23/general
Внесённые изменения:
1. Добавлена принтформа для госслужащего согласно образца.
2. Переписаны тексты всех емейлов гражданину (прошу отдельно проверить адрес ЦНАП и график работы).
3. Добавлено письмо чиновнику, о поступлении новой заявки (пока замкнуто на мою почту, перед выкладкой попрошу у Вас почту ЦНАПа).

**Comment by ezhikus** [comment]
@Koffeek 
1. Услуга на https://test.igov.org.ua/service/23/general работает как-то странно - я не вижу никаких полей, ничего не могу заполнить (см. скриншот). Есть кнопка, но она ничего не делает. Пробовал разные браузеры, везде одинаково.
![1](https://cloud.githubusercontent.com/assets/1929332/12089316/35f41a9e-b2ec-11e5-99a0-89f1358a4940.png)

2. Адрес ЦНАП: м. Житомир, вул. Михайлівська, 4

время работы: 
Понеділок, середа, п'ятниця: з 8.00 до 18.00
вівторок,четвер: з 9.00 до 20.00
субота: з 8.00 до 15.00

3. Почта начальника ЦНАП - edo412@ukr.net (Сюзанна Галецкая - уже есть в базе на боевом).

**Comment by Koffeek** [comment]
@ezhikus Услуга не работает, т.к. регион альфы лежит, в течении 5-10 минут прольется фикс, тогда можно будет пробовать. Изменения по адресам и графику сейчас внесу, т.к. у меня были другие данные

**Comment by ezhikus** [comment]
@Koffeek  Я поправил адрес и время работы. Услуга на альфе работает хорошо. Думаю, можно переносить на бету и на боевой. Ну, почту только Вашу заменить.

**Comment by Koffeek** [comment]
@ezhikus Перенес в папки бета и прод. В проде почту заменил. Если не срочно, то на боевой попадет с версией (примерно 15,01).

**Comment by ezhikus** [comment]
Не срочно, 15.01 - нормально. Спасибо.

**Comment by Koffeek** [comment]
Тогда закрываю.

**Comment by ezhikus** [comment]
Ещё несколько моментов по этой услуге:

5. Администратору ЦНАП приходит письмо с темой "Нове звернення на тему: Видача довідки з державної статистичної звітності про наявність земель та розподіл їх за власниками земель, землекористувачами, угіддями.". Надо чтоб было "Нове звернення на тему: Надання довідок незайнятому населенню про відсутність земельних ділянок для ведення ОСГ"

6. В шапке заявления на принформе слишком узкий верхний левый блок (там где "кому" и "от кого" - надо сантиметра на 3 шире

7. В поле "дата подання заяви"  на принтформе выводить значение [sDateCreate]

**Comment by ezhikus** [comment]
Жаль нет прав переоткрыть заявку. 

@Koffeek , Вы не могли бы глянуть комит https://github.com/e-government-ua/i/commit/1c6c5e724ee49cd6103c0ace9d7dcd46a1f04c09 и, если всё ок, залить на боевой?

**Comment by Koffeek** [comment]
@ezhikus По коммиту посмотрел, всё нормально. Ночью уйдет на боевой (будет проливка скорее всего, т.к. есть немного изменений по другим процессам).

**Comment by ezhikus** [comment]
Спасибо

**Comment by Koffeek** [comment]
@ezhikus изменения выставлены. Закрываю
