### ISSUE TITLE
м.Хмельницький. Взяття на облік громадян, які потребують поліпшення житлових умов

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/iBP#317]
Підключіть будь ласка послугу до тестового порталу https://test.region.igov.org.ua/
на логін - khmel_mvk_1 
послуга "Взяття на облік громадян, які потребують поліпшення житлових умов", ця послуга працює в м.Миколаїв

-- 
Заказчик -  Пляцик Юрій Анатолійович
e-mail: plyatsik@gmail.com

**Comment by Koffeek** [comment]
Сделал.
