### ISSUE TITLE
Новопсковская РДА (Луганская область) - раскрыть на них 6-зем

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#318]
Ответственный есть по ЦНАПу- это Алифёрова Лариса Николаевна (укр Аліферова) e-mail: cnapnovopskov@i.ua  - получено согласие

координатор групи по Новопскову - Виктор Малетин
пошта - v-maletin@mail.ru
телефон - 099 117 87 05
фейсбук - https://www.facebook.com/v.maletin

**Comment by NizhnikAlex** [comment]
раскрыто на тестовых
