### ISSUE TITLE
Житомир - Надання статусу багатодітної родини/внесення до банку даних

### ISSUE THREAD

**Issue by ezhikus** [e-government-ua/iBP#320]
Послуга надається управлінням у справах сім'ї, молоді та спорту Житомирської міськради. Є принципова згода на впровадження.

Крок 1
Громадянин подає наступні документи:
-заява (зразок - https://docs.google.com/document/d/1FPO9-WNxTEQgOUuvoacLstnx-D6XUXVRG0uYS-hBC5M/edit?usp=sharing) - має бути створена принт-форма для друку даної заяви!
-копії сторінок паспорта батька та матері (сторінки 1, 2 та прописка)
-копії свідоцтв про народження дітей
-копія свідоцтва про шлюб
-копія довідки про склад сім'ї
-копії ідентифікаційного коду батька та матері

Крок 2
Співробітник управління перевіряє документи і або вносить родину в базу даних багатодітних сімей, або відхиляє заяву з поясненням причин. В обох випадках заявнику шлеться лист електронною поштою з результатом обробки. 

Особистий візит громадянина не потрібен на жодному кроці.

**Comment by Koffeek** [comment]
@ezhikus Немного о правилах именования файлов и работе с конфигами бизнес-аналитиков. 
1. Файл именуется по типу [город]-[орган принимающий/обрабатывающий заявку]-[номер ишшью в репозитории iBP]. Исключение, файлы созданные до октября 2015 (т.е. пока не появился отдельный репозиторий).
2. При записи процесса в СервисДату для тестирования необходимо учитывать следующий момент: если услуга не готова в бой, то флаг bTest должен иметь значение true. Иначе при глобальных выливках можно выставить услугу случайно.
3. Очень желательно увдомлять хоть кого-то из бизнес-аналитиков о добавлении новых процессов. Это поможет избежать многих недоразумений.
Если будут вопросы - пишите.

**Comment by ezhikus** [comment]
@Koffeek 
1,2 - Ок, спасибо, не знал. Эти переименую, а новые буду создавать уже правильно.
3 - Я уведомлял Дарью, так как она указана разработчиком схожих услуг по многодетным семьям
4 - Я собирал, всё собралось. А что, что-то сломалось?

Услуги ещё не закончены, залиты на альфу с целью демонстрации в горсовете сегодня-завтра. Дальше, возможно, будут фиксы.

**Comment by Koffeek** [comment]
@ezhikus 
Переименовывать процессы нельзя. Уже пусть будут как есть.

**Comment by ezhikus** [comment]
@Koffeek 
Ок. Было бы, кстати, хорошо описать правила именования bpmn-файлов, принт-форм, маркеров - не нашел этой информации ни в "Наших стандартах", ни в документе от Павла (https://docs.google.com/document/d/1LES8GhAvwqRKkwX2QUsRGksoI45vGbdiRCHJUzxjMXw/edit#)

**Comment by Koffeek** [comment]
@ezhikus 
3. Даша, сказала, что уведомление было о разработке услуг, а не о добавлении их в конфиги.
Правила именования стандартизарованы относительно недавно и не расчитаны на внешнюю команду аналитиков. Такие моменты обычно проговаривались при обучении, которого в Вашем случае не было. Именования принтформ обычно идут от БП, именование маркеров произвольно.

**Comment by ezhikus** [comment]
@Koffeek 
А как же можно разрабатывать и проверять услуги, не добавляя их в конфиги? Да и о добавлении в конфиги мы тоже говорили, она мне рассказывала о файлах ServiceData и Service. Наверное, просто недопоняли друг друга. Бывает при обсуждении в удалённом режиме.

"Такие моменты обычно проговаривались при обучении, которого в Вашем случае не было." - Я был бы просто счастлив, если бы мне кто-то провёл обучение! Ну хотя бы немножко.

**Comment by Koffeek** [comment]
@ezhikus Можем попробовать сегодня после 21,30 в скайпе списаться/созвониться.

**Comment by ezhikus** [comment]
@Koffeek 
Сорри, не заметил комментарий. Давайте сегодня (вторник), в любое время с 19 до 24, когда Вам удобно.

**Comment by ezhikus** [comment]
Услуга готова и выложена на боевой
