### ISSUE TITLE
Тернопіль ОДА - Допрацювання послуги Отримання разової (індивідуальної) ліцензії на здійснення суб’єктами зовнішньоекономічної діяльності зовнішньоекономічних операцій

### ISSUE THREAD

**Issue by kelnerira** [e-government-ua/iBP#33]
https://test.igov.org.ua/service/160/general  
Допрацювати функціонал форми запиту та порталу чиновника, пропозиції тут https://docs.google.com/document/d/1-sIXKIVuYGnyxT8Kc-dZ_DhBBCxCMYErpdbzumE5U-E/edit?usp=sharing

На підставі цієї послуги Мінекономрозвитку розробляє постанову,  що визначатиме порядок подання документів та видачі ліцензій в електронному вигляді.

**Comment by kelnerira** [comment]
Завдання для нових бізнесаналітиків:
1. Пройтися по процесу з точки зору заявника і виконавців, перевірити які саме пункти пропозицій виконані.
2. Перевірити процес на предмет необхідності використання динамічних форм.
3. https://docs.google.com/document/d/1VlXkZlSp7tt0M8wvjyRqDEbR_G9yy5mUszPLMwU82Jw/edit?usp=sharing форма для друку РІЛ (ліцензії). Зробити друк після прийняття рішення про видачу ліцензії. 
4. Внести відповідні правки, якщо це технічно можливо.

Опис бізнеспроцесу тут (посилання на документи клікабельні)  https://drive.google.com/file/d/0B-TXzbaEvbw9ZlZlWHVNTmZjZzA/view?usp=sharing
Інформаційна картка https://drive.google.com/open?id=1AlfR-FHnaEcOeNbrcTi60u6Ux8Zcrv7TADq3cAaGEgA
Технологічна картка https://drive.google.com/open?id=0B-TXzbaEvbw9Z3pZZmNfOXZ4X3M
Перелік документів https://drive.google.com/open?id=1SbtP0meDVZlCfekEa2xZtU2ahJDV81YbJGtpn08dm8A
Опитувальник послуги https://drive.google.com/open?id=1-q__RQaqTCa4kvlAm4XnwXSwe2dFp0dT9ZJqThakBdo

**Comment by GrekD** [comment]
Роблю цю послугу для Дніпропетровська, можу взяти в роботу, але у зв'язку з пыдвищенним потоком підключення регіонів зараз, буде не так швидко як хотілося

**Comment by NParhomenko** [comment]
Прошлась по услуге "Отримання разової (індивідуальної) ліцензії на зовнішньоекономічну операцію", оформила заявку, отписалась https://docs.google.com/.../1-sIXKIVuYGnyxT8Kc-dZ.../edit...

**Comment by kelnerira** [comment]
@NParhomenko дайте електронку, надам Вам доступ для редагування

**Comment by NParhomenko** [comment]
pashatan@list.ru

**Comment by NParhomenko** [comment]
хотя ее ж можно удалить - я просто тестировала

**Comment by kelnerira** [comment]
Я про зауваження - Ви не маєте права редагувати файл. Маєте електронну пошту на gmail?

**Comment by NParhomenko** [comment]
нет

**Comment by Koffeek** [comment]
@NParhomenko Якщо бажаєте написати повідомлення конкретному користувачу, будь ласка, використовуйте символ @ перед його логіном Гітхабу

**Comment by sofiadanylevych** [comment]
протестовано та виставлено на бойовий
