### ISSUE TITLE
Дніпропетровськ - Дозвіл на розроблення технічної документації із землеустрою щодо встановлення (відновлення) меж земельної ділянки

### ISSUE THREAD

**Issue by msvidran** [e-government-ua/iBP#337]
карта - https://docs.google.com/spreadsheets/d/1xm3II_KD--FhyflbGtBjc28LkkRgLDW1K_TbBNHH-HE/edit?pref=2&pli=1#gid=1206807768

**Comment by annastolbova** [comment]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [ ] Дніпродзержинськ
- [ ] Жовті Води
- [ ] Новомосковськ
- [ ] Павлоград
- [ ] Першотравенськ
- [ ] Синельникове
- [ ] Тернівка
- [ ] Юр’ївський р-н

закрити послугу на наступні міста/райони:

- [ ] Дніпропетровськ

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

інфо-карти знахдяться на офіційному [сайті](http://e-services.dp.gov.ua/_layouts/Information/pgServices.aspx)

**Comment by Akylish88** [comment]
https://igov.org.ua/service/1392/general
