### ISSUE TITLE
Дніпропетровськ - Припинення права користування земельною ділянкою

### ISSUE THREAD

**Issue by msvidran** [e-government-ua/iBP#338]
https://docs.google.com/spreadsheets/d/1xm3II_KD--FhyflbGtBjc28LkkRgLDW1K_TbBNHH-HE/edit?pref=2&pli=1#gid=920523285

**Comment by smoktii-igov** [comment]
Взял в рефакторинг dndz_cnap_190.bpmn

**Comment by smoktii-igov** [comment]
Все в релизе 
Розірвання договору оренди земельної ділянки або припинення права постійного користування земельною ділянкою
1393, dndz_cnap_190
