### ISSUE TITLE
м.Тернопіль ЦНАП - Виготовлення викопіювання в масштабі 1:500, 1:2000 Управління містобудування, архітектури та кадастру

### ISSUE THREAD

**Issue by kelnerira** [e-government-ua/iBP#34]
https://drive.google.com/file/d/0B-TXzbaEvbw9aEY2UkVKMzdldFU/view?usp=sharing бізнеспроцес послуги.

**Comment by Koffeek** [comment]
Ірина, скажіть, будь ласка, чи існує якийсь список потреб для яких робляться викопіювання. Це потрібно для заяви і відповідно заповнення користувачем.

**Comment by kelnerira** [comment]
лишіть вікно, заявник буде самостійно вписувати. Чіткого переліку немає

31 серпня 2015 р. 15:05 Koffeek <notifications@github.com> написав:

**Comment by Koffeek** [comment]
Описание работы: 1.Гражданин заполняет необходимые поля и прикрепляет документ. 2.Происходит загрузка документа и передача данных. 3.Чиновник просматривает данные и документы принятые гражданином. 4. Если чего-то не хватает, то отправляется письмо с указанием причины. 5. Если всё в порядке, то данные переходят дальше. 6. При поступлении вытяга к чиновнику он отправляет письмо, о его готовности к гражданину. 7. При поступлении отказа - отправляется письмо о необходимости прийти и забрать документы и отказ.

**Comment by kelnerira** [comment]
https://docs.google.com/spreadsheets/d/1K92yOa2fjHrUF4CIQDUMDEXYFUVY_kOvCSEmTXtXCMM/edit?usp=sharing тут зауваження,

**Comment by Koffeek** [comment]
1.  Зроблено.
2.  Зроблено.
7.  Зроблено.
8.  Зроблено.
9.  Зроблено.
10. Зроблено (календар на даний момент не доступний у чинвоників).
11. Зроблено.
12. Зроблено.

**Comment by katyafursyk** [comment]
Доброго дня. Шрифт заяви громадянина потрібно змінити на Times New Roman 14

**Comment by katyafursyk** [comment]
@Koffeek Послуга протестована, готова до випуску на бойовий.
cnapzal3@ukr.net  - Електронна пошта для отримання повідомлень про надходження заяв на електронні послуги, єдина для всього залу.
Доступ до роботи з ЕП необхідно для:
1. Дудченко Ольга Олександрівна 0951565673
2. Кузик Лілія Андріїівна 0978291277
3. Біла Надія Богданівна 0966085624

**Comment by Koffeek** [comment]
@katyafursyk 
Доступи зроблено. Дайте електронку, щоб скинути логіни/паролі. Послугу спробуємо виставити вночі. Як зробимо - відпишусь окремо.

**Comment by katyafursyk** [comment]
@Kaffeek  
Скидайте сюди katyafursyk93@gmail.com

**Comment by Koffeek** [comment]
послуга протестована та виставлена на бойовий
