### ISSUE TITLE
Для послуги "Отримання разової (індивідуальної) ліцензії на здійснення суб’єктами зовнішньоекономічної діяльності зовнішньоекономічних операцій" в полях де необхідно обрати та завантажити файл при його завантаженні з'являється повідомлення про помилку

### ISSUE THREAD

**Issue by Sokhatsky** [e-government-ua/iBP#341]

**Comment by Sokhatsky** [comment]
Серйозність помилки: [S4]
Оточення: Windows 7 service pack 1, Mozilla Firefox версія 43.0.1
Детальний опис помилки: Помилка з'являється  при спробі завантажити файл в поля, які пропонують обрати та завантажити файл .
Кроки відтворення.
1. Зайти на сайт https://test.igov.org.ua/
2. Вибрати послугу "Отримання разової (індивідуальної) ліцензії на здійснення суб’єктами зовнішньоекономічної діяльності зовнішньоекономічних операцій"
3. Успішно пройти верифікацію та зайти в послугу
4. Завантажити файл в поле, які пропонують обрати та завантажити файл
5. Фактичний результат Помилка
Очікуваний результат: Файл успішно завантажений
![ibp 341](https://cloud.githubusercontent.com/assets/16464887/12354180/d956be5e-bb9c-11e5-8a8b-7b89595aaee6.png)

**Comment by GrekD** [comment]
@Sokhatsky это была общая проблема для всех процессов, сейчас уже ок.
конкретно этот процесс сейчас еще дорабатывается
