### ISSUE TITLE
Хмельницький - Припинення права користування (оренди) земельною ділянкою

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#346]
Доброго дня, прошу розробити нові послуги та підключити їх в тестовий портал
https://test.region.igov.org.ua на логін - khmel_mvk_1

контакти відповідальних з боку державного органу: Малінковська Олена Володимирівна, cnap32@rada.khmelnytsky.com, elenamalinkovskaya@yandex.ru, 0672831292

інфокарта:
https://docs.google.com/document/d/18P1LkWjKJLkht95cfNJNswXXg0D3oc8XWAIeEtcCC7c/edit

**Comment by smoktii-igov** [comment]
Подтверждено, выставлено в РЕЛИЗ  3.04.2016
