### ISSUE TITLE
Хмельницький - Видача дозвіл на порушення об’єктів благоустрою міста Хмельницького

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#348]
Доброго дня, прошу розробити нові послуги та підключити їх в тестовий портал
https://test.region.igov.org.ua на логін - khmel_mvk_1

контакти відповідальних з боку державного органу: Малінковська Олена Володимирівна, cnap32@rada.khmelnytsky.com, elenamalinkovskaya@yandex.ru, 0672831292

інфокарта
https://drive.google.com/file/d/0BzhmqPf0m3-EWEsxNXRxUVAzTzg/view

**Comment by GrekD** [comment]
@plyacik Юрій, надішлить, будь ласка, приклад заяви по цій послузі

**Comment by plyacik** [comment]
@GrekD Ось що мені надали адміністратори ЦНАП
[1-09-01-Z.docx](https://github.com/e-government-ua/iBP/files/234645/1-09-01-Z.docx)

**Comment by smoktii-igov** [comment]
Реализовано и віставлено в бету, отослані письма с приглашением протестировать 

Видача дозволу на порушення об’єктів благоустрою
Анулювання дозволу на порушення об’єкту благоустрою
Видача дублікату дозволу на порушення об’єктів благоустрою
Переоформлення дозволу на порушення об’єктів благоустрою

**Comment by plyacik** [comment]
@smoktii-igov Доброго дня, перших 2 відтестовано, можна запускати в боєвий
1.Видача дозволу на порушення об’єктів благоустрою
2.Анулювання дозволу на порушення об’єкту благоустрою

Дякую!

**Comment by smoktii-igov** [comment]
Выставлено в РЕЛИЗ

1.Видача дозволу на порушення об’єктів благоустрою
2.Анулювання дозволу на порушення об’єкту благоустрою

Уйдет с выставлением новой версии
