### ISSUE TITLE
м.Тернопіль ЦНАП - Розгляд відповідності намірів щодо місця розташування тимчасової споруди

### ISSUE THREAD

**Issue by kelnerira** [e-government-ua/iBP#35]
https://drive.google.com/file/d/0B-TXzbaEvbw9ekF6c1Y5d1lLbEU/view?usp=sharing опис бізнеспроцесу

**Comment by kelnerira** [comment]
сьогоднЯшню - граматична помилка, сьогоднішню 
Питання - а дата не може вказуватись автоматично?

**Comment by msvidran** [comment]
Питання - а дата не може вказуватись автоматично?
Ні - поки не можливо.

**Comment by kelnerira** [comment]
Для обробки послуги дайте доступ користувачу	Ольга Дудченко 	dudchenko_olga@ukr.net
логін/пароль  test_tern_misto1

**Comment by kelnerira** [comment]
портал чиновника, граматична помилка " Дата подачИ заяви" - має бути  "..  подачі.."

**Comment by msvidran** [comment]
Ольга Дудченко dudchenko_olga@ukr.net
логін/пароль test_tern_misto1
доступ дав

**Comment by kelnerira** [comment]
![image](https://cloud.githubusercontent.com/assets/13996952/10192615/43e236b0-6786-11e5-971e-0d31306906b4.png)
не працює, що сталося?

**Comment by kseniatern** [comment]
Доброго дня!
Внесіть будь ласка зміни до послуги:
https://docs.google.com/spreadsheets/d/1uEMrATMAQVpafMWMPffoPB6q3ak3KOARq1lNl7kARLo/edit?ts=560da5f8#gid=0

**Comment by kseniatern** [comment]
Доброго вечора!
Потрібно, щоб заява була у форматі Times New Roman 14, виправте будь ласка.

**Comment by kseniatern** [comment]
Потрібно внести зміну (повідомлення замовнику про рішення ):
Ваше звернення про розгляд 
відповідності намірів щодо місця 
розташування тимчасової споруди - 
відправлене в управління 
містобудування, архітектури та 
кадастру. 
Спеціалісти з органу
місцевого самоврядування повинні 
дати відповідь протягом 10 
робочих днів з дня реєстрації заяви.

**Comment by kseniatern** [comment]
https://docs.google.com/spreadsheets/d/1uEMrATMAQVpafMWMPffoPB6q3ak3KOARq1lNl7kARLo/edit#gid=0

**Comment by kseniatern** [comment]
Доброго вечора!
Внесіть зміни:
1. Виправте шрифт та розмір заяви, формат Times New Roman 14.
2. Шапку в заяві необхідно вирівняти по лівому краю (Начальнику управління містобудування, архітектури та кадастру...).
3. Працівник ЦНАПу повинен прописувати дату реєстрації сам чи можна автоматично вибирати з календаря?

**Comment by msvidran** [comment]
Добрий вечір!
1. Шрифт та розмір поправлений ще раніше, спобуйте роздрукувати на принтері або pdf-принтері.
2. Шапку виправлю.
3. Поки що прописувати руками, як стане можливо - я швидко зроблю правку в продакшені.

**Comment by kseniatern** [comment]
1. Сьогодні пробували, шрифт не відповідає.

**Comment by kseniatern** [comment]
Доброго вечора!
Перегляньте та виправте будь ласка ще раз, "шапочку" заяви не відформатовано по правому краю.

**Comment by Koffeek** [comment]
@kseniatern 
зроблено на тестовому. З версією сьогодні-завтра вийде на бойовий.

**Comment by kseniatern** [comment]
Доброго вечора!
На бойовому порталі послуга не працює, перегляньте, будь ласка, ще раз.
По-перше, прикріпило декілька однакових файлів (11 шт.).
По-друге, бере в роботу, але не опрацьовує. Пише "Зачекайте" і не грузить.
![image](https://cloud.githubusercontent.com/assets/14842029/11614227/c581555a-9c44-11e5-8d34-b217b9e2b5ef.png)

**Comment by msvidran** [comment]
Добрий вечір.
Тільки що пройшов всі кроки (зробив тестову заяву на бойовому) - все ок.

**Comment by kseniatern** [comment]
Доброго дня!
А у мене та у ЦНАПі знов на бойовому не працює.
Вже "Зачекайте..." 10 хв

![image](https://cloud.githubusercontent.com/assets/14842029/11626428/6936e25e-9ceb-11e5-865b-60a5d9b8e472.png)
