### ISSUE TITLE
Суми - видача витягів, копій рішень

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#352]
Видача витягу з протоколу пленарного засідання Сумської міської ради
Видачі витягів з протоколів засідань постійних комісій Сумської міської ради
Видача копій рішень (витягів з рішень) Сумської міської ради
Ответственный в ЦНАПе:
Роман Мороз.
0951085682
e-office@meria.sumy.ua
http://cnap.sumy.ua/taxonomy/term/22
контакт координатора: Михаил Горкуша <m.yu.gorkusha@gmail.com> 0504506075

**Comment by Koffeek** [comment]
Сумской ЦНАП прекратил сотрудничество с проектом
