### ISSUE TITLE
Богодухов (Харьковская обл.) - раскрыть "Звернення до міського голови"

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#354]
инфо от координатора:
Чуть больше недели назад мы проводили презентацию для Богодухова, там согласились на внедрение услуги "Звернення до голови" для трех голов.

Вот контакты исполнителей этих услуг для Богодухова:
ИВАХ Алина (Представник районної державної адміністрації)
093-962-27-29
a.ivakh@bogodukhivrda.gov.ua
       
МИЩЕНКО Ольга (Представник міської ради)
050-174-08-68

БАБЕНКО Оксана (Представник районної ради)
066-723-34-49
bog_rr@ukr.net

https://www.facebook.com/valery.stavitsky
координатор

**Comment by YmNIK13** [comment]
В БП rda_360 реализован продвинутий БП с юзертаском для гововы, чтоб он мог вписать свою резолюцию и назначить ответственного.
Для открытия такого функционала в атрибутах необходимо добавить флаг **bFlagRda360;hard**
