### ISSUE TITLE
Днепропетровск ЦНАП - Копії рішень міської ради  про продаж земельних ділянок державної та комунальної власності

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/iBP#36]
Тех.карта
https://drive.google.com/file/d/0BydenhvN5xzeWkY1d1ZBODdoZGtXbUZSc0I0aTlvZFJjTTFv/view?usp=sharing

Заявление:
https://docs.google.com/document/d/1PNPOPcYd4-FsK6XyoZ4mUteEgE1VbPZZd8ThluDjAbs/edit

**Comment by Koffeek** [comment]
Процесс ушел в бой. Тесты проведены
