### ISSUE TITLE
Хмельницький - Присвоєння та зміни поштових адрес об’єктам нерухомого майна (рефакторінг)

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#362]
- Необхідно додати вимогу про витребування наступних документів:  "Схема розміщення земельної ділянки","Засвідчена в установленому порядку копія документа, що підтверджує право власності на об'єкт нерухомого майна  (при наявності)."

1. Потрібно передбачити лише графу копія документа, що підтверджує право власності на об'єкт нерухомого майна та варіанти відповіді так/ні. Тобто це не залежить від того чи це новозбудований об'єкт чи ні.

https://mail.google.com/mail/u/0/#inbox/1524010cfc61077b?projector=1

**Comment by GrekD** [comment]
@plyacik 
Прошу направити на тест
https://test.igov.org.ua/service/1429/general

**Comment by plyacik** [comment]
https://github.com/GrekD
Послугу протестили, можна в боєвий

**Comment by GrekD** [comment]
https://igov.org.ua/service/1429/general
на боевом
