### ISSUE TITLE
Тернопіль - Висновок державної санітарно-епідеміологічної  експертизи діючих об’єктів у тому числі військового та оборонного призначення

### ISSUE THREAD

**Issue by msvidran** [e-government-ua/iBP#365]
Зразки заяв https://docs.google.com/document/d/1BjFZvEBKAwGKr93M7P_Kh0bsufN8MrUBFIkvOy6NC2o/edit?usp=sharing
https://docs.google.com/document/d/1Okn6xkyUPvHoNtFO_wEVf6l1NolJY2Cf5wb90bPMYxY/edit?usp=sharing
А також дані для створення кабінетів 
https://docs.google.com/spreadsheets/d/1HDzwSqT9iwjlIjeiAQhcKnFdPnB2KNk2t9YZ8daZVkY/edit?usp=sharing

**Comment by sofiadanylevych** [comment]
Появились цьогорічні реквізити для сплати 
https://drive.google.com/file/d/0B-erTirZzRs0RTFiUklfcU5SSy12SzVnR2MwT0Y1SzNKUEk4/view?usp=sharing

**Comment by sofiadanylevych** [comment]
Що саме треба зробити
https://docs.google.com/spreadsheets/d/1hJMIpS8oclJ0qC-j2-hISuHNT4zKcwGhD4aOipIJIsA/edit?usp=sharing
+ дані для створення кабінетів
https://docs.google.com/spreadsheets/d/1HDzwSqT9iwjlIjeiAQhcKnFdPnB2KNk2t9YZ8daZVkY/edit?usp=sharing

**Comment by sofiadanylevych** [comment]
**1. Залишити тільки 1 варіант "Видача висновку"**
**2. Забрати поля для громадянина**
Дані про контракт на постачання об'єкта в Україну:
*Заявник (власник):
*Країна реєстрації заявника:
*Реквізити заявника:
В заяві в ідеалі повинні бути прочерки на цих полях, якщо ні то принаймні пусті поля
**3. Копія квитанції**
За законом "Документ, що підтверджує внесення плати за комплексне вивчення документів та підготовку проекту висновку державної санітарно-епідеміологічної експертизи" це неправильно
повинно бути
"Документ, що підтверджує внесення плати за надання адміністративної послуги:"
Особливо зараз тому що ці кошти йдуть в місцеві бюджети
**4. Далі по документах що не потрібні**
- Документ власника, що декларує відповідність об'єкта експертизи визначеним в Україні вимогам щодо їх безпеки для здоров'я людини   -  в нас цього не треба
- Акт про обстеження підприємства (за наявності), висновки галузевих експертиз або фахівців та інші матеріали, що характеризують підприємство - це взагалі за законом скасували
**5.Далі ті які ще треба додати і вони обов'язкові**
- Копія документа, який підтверджує прийняття в експлуатацію закінченого будівництвом об’єкта (зареєстрованих декларації або сертифіката згідно вимог постанови КМ України від 13.04.2011р № 461 або акту державної приймальної комісії про прийняття в експлуатацію закінченого будівництвом (реконструкцією) об’єкта чи акта технічної комісії, засвідчена у встановленому порядку (для об’єктів, що вперше розпочали свою діяльність і стають на державний облік/нагляд), інвентарна справа, проект відповідності санітарним нормам і правилам наявних приміщень розроблений та затверджений ліцензованою архітектурно-проектною організацією з обов’язковим долученням копії інвентарної справи, паспорт прив’язки, тощо).
- Копія документа, що підтверджує право власності на приміщення або право користування ним (копію угоди оренди або свідоцтва права власності).
**6. Документи, які треба додати але опціональні, можуть бути у людини а можуть не бути**
- Документи щодо земельної ділянки: відведення / права власності / користування (за наявності).
- Асортиментний перелік продукції у двох примірниках (для закладів торгівлі, аптек, громадського харчування, об’єктів харчової промисловості).
**7. І на додачу **
якщо можна забрати скан-копію додавання скан-копію висновку, громадянин і так за оригіналом буде йти а в них сканера нема в кабінеті в санстанції.

**Comment by zolotovatatyana** [comment]
https://igov.org.ua/service/1398/general на боевом
