### ISSUE TITLE
Миргород - Дозвіл на виготовлення технічної документації із землеустрою щодо встановлення меж земельної ділянки  (земельний)

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#367]
Миргородский городской ЦНАП (руководитель: Коротина Оксана Владимировна, тел. 066-752-15-71 cnapkorotina@gmail.com):

координатор: Слемзин Александр, 0937528704 slemzin@gmail.com

**Comment by GrekD** [comment]
просят ускорить

**Comment by Akylish88** [comment]
https://delta.test.igov.org.ua/service/1392/general
отправил на тест

**Comment by Akylish88** [comment]
https://igov.org.ua/service/1392/general
на бойовому
