### ISSUE TITLE
Миргород - Дозвіл на розроблення проекту землеустрою щодо відведення земельної ділянки (самочинно збудоване нерухоме майно) (земельний)

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#368]
Миргородский городской ЦНАП (руководитель: Коротина Оксана Владимировна, тел. 066-752-15-71 cnapkorotina@gmail.com):

координатор: Слемзин Александр, 0937528704 slemzin@gmail.com

**Comment by GrekD** [comment]
просят ускорить запуск )

**Comment by Akylish88** [comment]
https://delta.test.igov.org.ua/service/27/general
отправил на тест

**Comment by Akylish88** [comment]
https://igov.org.ua/service/27/general
на бойовому
