### ISSUE TITLE
Миргород (раскрытие) -  Видача копій, витягів з розпоряджень міського голови, рішень, прийнятих міською радою та виконавчим комітетом

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#369]
Общий отдел Исполкома миргородского городского совета (руководитель:  П"ятниця Яна Олександрівна, 0667048686, lastothka3@ukr.net; головний спеціаліст загального відділу: Климко Людмила Пилипівна, 0952156816, klimko_l@ukr.net)

координатор: Слемзин Александр, 0937528704 slemzin@gmail.com

**Comment by Koffeek** [comment]
С уважением прошу активировать услугу - Видача копій, витягів з розпоряджень міського голови, рішень, прийнятих міською радою та виконавчим комітетом #369
Тестирование прошло нормально.
координатор групи - Олександр Слємзін
пошта - slemzin@gmail.com

**Comment by Koffeek** [comment]
Выставлено на боевой
