### ISSUE TITLE
Днепропетровск ЦНАП - Копії рішення міської ради про надання у постіне користування земельних ділянок  державної або комунальної власності

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/iBP#37]
Тех карта - https://drive.google.com/file/d/0BydenhvN5xzeSTJ6VEdlLWtWelYtR2lrSXplQ1dNdmRISnFV/view?usp=sharing

Заявление - https://docs.google.com/document/d/16ll4Wer7KnbCdUrdywbZrharMZs4w03mMapTIZ0tYRg/edit

**Comment by GrekD** [comment]
процесс на боевом
