### ISSUE TITLE
м. Ромни, Сумська обл. - ДМС раскрыть

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#370]
- Обмін паспорта громадянина в разі зміни (переміни) прізвища, імені або по батькові;
 - Обмін паспорта громадянина у разі непридатності для користування;
-  Вклеювання до паспорта громадянина фотокартки при досягненні 25- і 45-річного віку

**Comment by Koffeek** [comment]
Протестировано и выставлено на боевой
