### ISSUE TITLE
Маріуполь - Рішення міської ради про затвердження проекту землеустрою щодо відведення земельної  ділянки для передачі її у власність

### ISSUE THREAD

**Issue by msvidran** [e-government-ua/iBP#373]
https://drive.google.com/a/privatbank.ua/file/d/0B6hKo-clAKYgTkpxeHUzYXJKWWlta0k1SnhldkhpSjhMYm44/view?usp=sharing

координатор Мариуполь dmitriy.istomin82@gmail.com

**Comment by Akylish88** [comment]
Связался с Дмитрием из Мариуполя, сказал что пока эту услугу убираем, так как в самом процессе много проволочек.
