### ISSUE TITLE
Тернопіль, розкриття послуг для Міської Ради

### ISSUE THREAD

**Issue by kelnerira** [e-government-ua/iBP#379]
Звернення до міського голови
Запит на доступ до публічної інформації
Запис на прийом до міського голови
відповідальні, адреса, графік роботи, телефони тут: https://docs.google.com/document/d/1NHP5DRLH9oVNCCIxwu4KHnX4OIooHmypqO23WTrEDco/edit?usp=sharing 
Зразки заяв, форма запиту тут https://drive.google.com/folderview?id=0B-erTirZzRs0dUpGSXpLaWRpc1E&usp=sharing

**Comment by Koffeek** [comment]
@kelnerira Зверннення до міського голови вже можна тестувати. Логін/пароль для усіх тестових МВК послуг ternopil_mvk_1.

**Comment by sofiadanylevych** [comment]
@Koffeek можна до запиту на публічну інформацію додати заяву довільної форми?

**Comment by sofiadanylevych** [comment]
Done
