### ISSUE TITLE
Днепропетровск ЦНАП - Копії рішення міської ради про передачу в оренду земельних ділянок  державної або комунальної власності

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/iBP#38]
Тех.карта - https://drive.google.com/file/d/0BydenhvN5xzeaDMyNFNKaGNqbVIzNjlGWm5JRS1IT2UyQnpz/view?usp=sharing

Заявление - https://docs.google.com/document/d/16ll4Wer7KnbCdUrdywbZrharMZs4w03mMapTIZ0tYRg/edit

**Comment by msvidran** [comment]
Описание БП:
1. Гражданин заполняет необходимые поля и нажимает "Замовити послугу".
2. Чиновнику приходит письмо с уведомлением о новой заявке и ссылка что бы ее обработать.
3. Гражданину приходит письмо с уведомлением об успешной регистрации заявления. 
4. Чиновник просматривает данные и документы переданные гражданином.
5. Если чего-то не хватает или неправильные (неполные) данные - то отправляется письмо о невозможности регистрации заявления с указанием причины.
6. Если всё в порядке, то данные переходят в департамент корпоративных прав.
7. Заявка возвращается во вкладку "Необработаные"
8. Гражданину приходит письмо об отправке заявления в департамент корпоративных прав.
9. Поступлениие решения к чиновнику в зависимости от которого он прикрепляет копию решения и:
              а) Отпраляет письмо, об отсутствии документа (с коментарием и прикрепленном отказе департамента).
              б) Отправляет письмо (с прикрепленным файлом) о готовности копии и необходимости его забрать в ЦНАПе.
