### ISSUE TITLE
Тернопільська обл. Розкриття послуг ДМС, ЦНАП Чортківського р-ну 

### ISSUE THREAD

**Issue by kelnerira** [e-government-ua/iBP#380]
Реєстрація місця проживання особи (із опцією одночасного зняття з реєстрації з попереднього місця)
Зняття з реєстрації місця проживання
Реєстрація місця проживання дитини до чотирнадцяти років
Зняття з реєстрації місця проживання дитини до чотирнадцяти років
Обмін паспорта громадянина в разі зміни (переміни) прізвища, імені або по батькові
Вклеювання до паспорта громадянина фотокартки при досягненні 25- і 45-річного віку
Видача довідки про реєстрацію місця проживання/перебування особи
Видача довідки щодо реєстрації/зняття з реєстрації місця проживання фізичної особи
Видача паспорта громадянина України замість викраденого
Видача паспорта громадянина України замість утраченого
Обмін паспорта громадянина у разі непридатності для користування

Відповідальна  Нашкольна Інна Вікторівна    cnap_chortkiv@ukr.net, її тестовий логін/пароль  chortR_rai_cnap1 

https://drive.google.com/folderview?id=0B-TXzbaEvbw9a1BtdVdpY3RqeVE&usp=sharing актуальні документи

**Comment by Koffeek** [comment]
Виставлено на бойовий 29,02,2016
