### ISSUE TITLE
Житомирська область - звернення до голови ОДА

### ISSUE THREAD

**Issue by ezhikus** [e-government-ua/iBP#382]
Зробити дану послугу для Житомирської області аналогічно до того, як вона працює в Тернопільскій, Чернігівській областях.

Дані:
Кому заява (голова ОДА): Машковському С.О.
Адреса ОДА: м. Житомир, майдан С. П. Корольова, 1
Тел. відділу обробки заяв громадян: (0412) 47-51-49
Електронна пошта відділу обробки заяв громадян: zvern_ztoda@ukrpost.ua

Список працівників відділу обробки заяв ОДА (для створення акаунтів) буде доданий трохи пізніше  (коли ми його отримаємо).

**Comment by Koffeek** [comment]
@ezhikus Я смотрю Вы всё уже сделали сами. Что-то от нас нужно?

**Comment by ezhikus** [comment]
@Koffeek 
Сейчас нет. Завтра потестим с сотрудниками ОДА, возьмём их список для создания аккаунтов и нужно будет залить на боевой. Я напишу об этом отдельно.

**Comment by ezhikus** [comment]
@Koffeek 
Просьба завести на боевом сервере группу и юзера (см. https://github.com/e-government-ua/iBP/issues/326#issuecomment-185100046) и перенести процесс с альфы на боевой.

**Comment by Koffeek** [comment]
@ezhikus Принято. Выставим на выходных с версией.

**Comment by ezhikus** [comment]
@Koffeek 
Спасибо. И ещё, на всякий случай явно уточню - оповещение о новых заявках на боевом нужно слать на zvern_ztoda@ukrpost.ua

**Comment by ezhikus** [comment]
ОДА попросила добавить на принт-форму заявления поле "Бажана форма відповіді" - "Отримати поштою" или "Електронна версія"

**Comment by ezhikus** [comment]
Проверено - работает.
