### ISSUE TITLE
Новопсков - Видача дозволу на розроблення технічної документації із землеустрою щодо встановлення меж земельної ділянки в натурі (на місцевості)

### ISSUE THREAD

**Issue by msvidran** [e-government-ua/iBP#385]
https://drive.google.com/open?id=0B1uoWNhWT8YYdHFfVXZqeGppdHMyZmNBT3g3cDBoZDFtbHJR
https://drive.google.com/open?id=0B1uoWNhWT8YYYlNIZFhwSTdSUEpNYW9iVUJ3MXVZbmhnRWFj
https://drive.google.com/open?id=0B1uoWNhWT8YYSDJqdnBFT1g3ZDdzdW5JaTNGeFZ6eWNoZ0ZZ
https://drive.google.com/open?id=0B1uoWNhWT8YYdmcxTnVhWGUxaWpXOS1fdUJRdXV1MEU3MHE4
https:/drive.google.comopen?id=0B1uoWNhWT8YYVHVBalBBM1dyWmk3MGhPaWpJRzdKWEFMQWJV

**Comment by Akylish88** [comment]
Это есть на район на боевом
https://igov.org.ua/service/1392/general
По поводу города уточнить

**Comment by Akylish88** [comment]
На город пока не открываем
