### ISSUE TITLE
Калуш - розкриття ДМС

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#388]
1. Видача довідки про реєстрацію місця проживання/перебування особи
2. Видача паспорта громадянина України для виїзду за кордон для дитини
3. Видача/заміна паспорта громадянина для виїзду за кордон

Контактна особа:
Романишин Анастасія Ярославівна
тел. +380993171311
e-mail - nastinkaromanyshyn@gmail.com
skype - nastikaroman

**Comment by Koffeek** [comment]
Координатор не выходит на связь длительное время. Пока закрываю, позже сможем переоткрыть
