### ISSUE TITLE
Днепропетровск ЦНАП - Копії рішення міської ради про  надання дозволу на розроблення проекту відведення земельної ділянки

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/iBP#39]
Тех.карті - https://drive.google.com/file/d/0BydenhvN5xzeQ2lZdGRNYWJRUnk4VXUtTGlsUUpuVU92bElZ/view?usp=sharing

Заявление - https://docs.google.com/document/d/16ll4Wer7KnbCdUrdywbZrharMZs4w03mMapTIZ0tYRg/edit

**Comment by NikolayAngel** [comment]
Бизнес-процесс:
1. Клиент заполняет заявление по ссылке https://test.igov.org.ua/service/139/general 
2. Клиенту отправляется письмо на почту об успешной отправки заявки
3. Заявка попадает в работу чиновнику
4. Чиновник на основании документов:
   а) Отправляет клиенту отказ с указанием причины
   б) Отправляет клиенту копию письма с положительным ответом (с возможностью добавления файла)
5. Конец процесса

**Comment by smit-pb** [comment]
Требует доработки - 
1) 
![image](https://cloud.githubusercontent.com/assets/12965717/9629309/6f2a7f66-517a-11e5-9698-1282325c7ab2.png)
Вместо гиппер ссылки - отображается просто полный путь к файлу.

2) Есть возможность загрузить файлы любого формата и размера. 
3) При загрузке 2-го файла - название файла отображается с правой стороны а не снизу как в случае с первым файлом.
![image](https://cloud.githubusercontent.com/assets/12965717/9629366/c2f3ba54-517a-11e5-8dbf-3d3275eff38f.png)

**Comment by NikolayAngel** [comment]
1. Нет пока гиперссылок
2. Файлы так и должны загружаться
3. Зависит от размера названия
это НЕ баги бизнес-процесса

**Comment by smit-pb** [comment]
Требует доработки. 
Уведомление о позитивном решении - приходит без Названия.
![image](https://cloud.githubusercontent.com/assets/12965717/9633004/0ff5fb38-5193-11e5-8711-2299f4a936c2.png)

**Comment by NikolayAngel** [comment]
Уведомление о позитивном решении - приходит без Названия.
Исправил

**Comment by smit-pb** [comment]
Все работает - согласно Бизнес-процессу

**Comment by VadimGulich** [comment]
Не убирайте  лейбл "test" , пож-ста )

**Comment by wantonness** [comment]
Бизнес-процесс:
1. Гражданин заполняет заявку https://test.igov.org.ua/service/139/general. Ему на email отправляется письмо с уведомлением об успешной регистрации его заявки
2. Заявка попадает в ЦНАП, где чиновник ее обрабатывает, проверяет правильность заполнения полей, делает опись прикрепленных документов (если они есть, пока эта ф-ция не нужна и не работает), заполняет свое ФИО, как проверяющего, присвает заявке свой внутренний номер.
3. Если что-либо в заявке заполнено неверно, то заявителю отправляется e-mail с отказом и указанной причиной.
4. Если заявка правильная, то чиновник из ЦНАП отправляет ее в Департамент корпоративных прав, где ее рассматривают и принимают решение, выдавать копию или нет (ЦНАП в это время ожидает).
5. Если не выдавать, то заявителю отправляется письмо с отказом и причиной отказа.
6. Если выдавать, то заявителю отправляется письмо с графиком работы ЦНАП + чиновник должен прикрепить отсканированную копию решения к письму.

Конец.

**Comment by GrekD** [comment]
![2015-09-21_171822](https://cloud.githubusercontent.com/assets/10836093/9994589/a9f29460-6086-11e5-8979-ecc57afe8acd.jpg)
![2015-09-21_1718223](https://cloud.githubusercontent.com/assets/10836093/9994593/ad05ec06-6086-11e5-826b-326de0b8fc63.jpg)
![2015-09-21_1727425](https://cloud.githubusercontent.com/assets/10836093/9994596/afb46d92-6086-11e5-9b52-17a6af533663.jpg)

**Comment by wantonness** [comment]
все исправила

**Comment by Koffeek** [comment]
Процесс ушел в бой. Тесты проведены
