### ISSUE TITLE
Колонщина - Надання дозволу на знесення аварійних будівель 

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#393]
От заявителя нужны следуюющие документы - копия паспорта, копия кода, копия свидетельства о праве собственности на дом, 
заявление в свободной форме на имя головы сельрады пелешок Юлии Васильевны.

контактное лицо:
Татьяна Гончарова <tatiana0706@ukr.net>

**Comment by smoktii-igov** [comment]
Взято в работу

**Comment by smoktii-igov** [comment]
Протестировано и выставлено на боевой 29,02,2016
