### ISSUE TITLE
Колонщина - Надання згоди на виготовлення буд.паспорта на житловий/садовий будинок

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#394]
нужно от заявителя - Заява в свободной форме, копии паспорта, кода, документы подтверждающие собственность зем.участка. 
Указать площадь планируемого дома, выкопировку из ген.плана.

контактное лицо: Татьяна Гончарова <tatiana0706@ukr.net>

**Comment by Akylish88** [comment]
Я эту возьму

**Comment by Akylish88** [comment]
https://igov.org.ua/service/35/general реализовано на боевом.
