### ISSUE TITLE
Калуш - Надання статусу та видача (заміна) посвідчення «Ветеран праці» 

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#398]
Координатор - Vitaliy Maliborskiy <igov.kalush@gmail.com>
инфокарту искать в архиве:
https://drive.google.com/open?id=0B6mOkUg9oq1zeGpJOEw0MHcyMk0

**Comment by zolotovatatyana** [comment]
https://igov.org.ua/service/8/general на боевом
