### ISSUE TITLE
 Тернополь ОДА - Надання містобудівних умов та обмежень забудови земельної ділянки

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/iBP#4]
Описание

https://drive.google.com/file/d/0B-TXzbaEvbw9dWFIbnVBb0ZYblU/view?usp=sharing 

Заказчик: Ирина Кельнер

**Comment by NikolayAngel** [comment]
Взял в работу

**Comment by kelnerira** [comment]
Це не ОДА, а ЦНАП м.Тернопіль

**Comment by kelnerira** [comment]
помилки тут https://docs.google.com/spreadsheets/d/13XH-ViLjL9DqRrdlDEP8Eyt_fV7oS-6n3voXYvQYavg/edit?usp=sharing, надалі всі зауваження теж буду фіксувати тут

**Comment by kelnerira** [comment]
а тут скріни https://docs.google.com/document/d/1YpYnEf6FKCXMd00erClMx79G_aqLbEVhX8khp1CG7V4/edit?usp=sharing

**Comment by kelnerira** [comment]
По цій послузі - пауза, є 2 документи, які ми маємо подати у оригіналі. Один з них - витяг з реєстру, зараз ЦНАП у процесі навчання персоналу, другий - груба книжка, яку друкує архітектурне бюро. Виясняємо можливість отримання її у електронному вигляді з ЕЦП архітектора. 
 Варіант з завантаженням заяви і документів, які вимагаються у копії - не дуже добрий, бо є регламент - має ЦНАП передати документи в Управління архітектури не пізніше 3-х днів. 
Хіба можемо робити електронну чергу, але це не доцільно, бо вже електронна черга для всіх видів послуг ЦНАП розробляється на їх сайті.

**Comment by kelnerira** [comment]
розглядаємо варіант подачі копій усіх документів, крім останнього + електронна черга на подачу оригінала. Це потребує змін у порядку розгляду в ЦНАП - заявка не реєструється у внутрішній програмі, поки немає оригіналу.
