### ISSUE TITLE
КМДА. Регистрация места проживания. Доработки

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/iBP#40]
https://docs.google.com/document/d/1rtfFgGBxW-Ie8lnU3T_KoJ1lHQhNUjw53YCik3RhVv0/edit

**Comment by kurbpa** [comment]
Описание  самого процесса - https://docs.google.com/document/d/1OHs36pf6o9m9WdLdQ3mXRDF20nL8bo7tUOVGsfvpAVs/edit

**Comment by kurbpa** [comment]
https://docs.google.com/document/d/1hn4eEFFLPd-ljQi9-HO0xAdVynW8jbPGcnz7blZA8P4/edit#heading=h.gjdgxs - Справочник районных адмиинистраций города Киева.

**Comment by kurbpa** [comment]
Отказ на шаге 3 может быть:
Відсутність одного з документів,  необхідних для отримання адміністративної послуги.
В этом случае сообщение пользователю:

Шановний(-а), #І.Б.#!
На жаль, змушені відмовити Вам у наданні послуги: "Реєстрація місця проживання".
Підстава:
Відсутність одного з документів,  необхідних для отримання адміністративної послуги.

**Comment by Koffeek** [comment]
заменить процесс на альфе на kiev_dms-40.bpmn

**Comment by kurbpa** [comment]
готово на альфе

**Comment by Koffeek** [comment]
Процесс доработан. Приемка прошла.
