### ISSUE TITLE
Калуш - Надання статусу та видача (заміна)  посвідчення «Учасник війни» 

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#400]
Координатор - Vitaliy Maliborskiy igov.kalush@gmail.com
инфокарту искать в архиве:
https://drive.google.com/open?id=0B6mOkUg9oq1zeGpJOEw0MHcyMk0

**Comment by Akylish88** [comment]
Наталя 057173065

керівник відділу Людмила Миронівна 0994892253

**Comment by Akylish88** [comment]
https://test.igov.org.ua/service/36/general на боевом
