### ISSUE TITLE
Калуш -Надання статусу та видача (заміна)  посвідчення «Сім’я загиблого (померлого) ветерана війни» 

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#401]
Координатор - Vitaliy Maliborskiy igov.kalush@gmail.com
инфокарту искать в архиве:
https://drive.google.com/open?id=0B6mOkUg9oq1zeGpJOEw0MHcyMk0

**Comment by zolotovatatyana** [comment]
Ответсвенный чиновник - Дайнега Наталя Петрівна 0507173065

**Comment by zolotovatatyana** [comment]
https://igov.org.ua/service/30/general
