### ISSUE TITLE
Колонщина - Видача дозволу на проведення зборів, мітингів, маніфестацій і демонстрацій, спортивних видовищних та інших масових заходів

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#404]
П.п3 п.б ст..38 Закону України «Про місцеве самоврядування в Україні» 
Заява с указанием намерений в свободной форме на главу сельрады, документы физ.лица/организации,  
которая проводит массовые мероприятия. Идет на рассмотрение выконкома/сессии.

контактное лицо: Татьяна Гончарова tatiana0706@ukr.net

**Comment by smoktii-igov** [comment]
1. ЗАКОН УКРАЇНИ Про місцеве самоврядування в Україні http://zakon3.rada.gov.ua/laws/show/280/97-%D0%B2%D1%80/page
2. Лист Мін'юст України "Щодо правового регулювання проведення мирних заходів" від 26.11.2009 № 1823-0-1-09-18 http://zakon5.rada.gov.ua/laws/show/v823-323-09

**Comment by smoktii-igov** [comment]
Сповіщення органів виконавчої влади чи органів  місцевого 
самоврядування   про   проведення   зборів,  мітингів,  походів  і 
демонстрацій - масових мирних зібрань. 
Завчасне  сповіщення  відповідних  органів  про 
проведення тих чи інших масових зібрань - це строк від дня  такого 
сповіщення до дати проведення масового зібрання.

**Comment by smoktii-igov** [comment]
Услуга переименована на "Повідомлення про проведення зборів, мітингів, маніфестацій і демонстрацій, спортивних, видовищних та інших масових заходів #404"

В соответствии с Листом Мін'юст України "Щодо правового регулювання проведення мирних заходів" від 26.11.2009 № 1823-0-1-09-18 http://zakon5.rada.gov.ua/laws/show/v823-323-09
...Обмеження щодо реалізації права  зборів, мітингів і т.ін. може  встановлюватися
СУДОМ відповідно до закону...

**Comment by smoktii-igov** [comment]
Протестировано и выставлено на боевой 18,03,2016
