### ISSUE TITLE
Тернопіль - Видача довідки про те, що за місцем реєстрації батька або матері посвідчення батьків та дитини з багатодітної сім'ї не видавались (рефакторінг)

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#406]
) Це Видача довідки про те, що за місцем реєстрації батька або матері посвідчення батьків та дитини з багатодітної сім'ї не видавались
Там саме те що я вказувала в ішью  є тільки 1 коло обробки зразу з рішенням, нам потрібно 2 кола, перше коло це стягнути документи і роздрукувати довідку (https://docs.google.com/document/d/1LVVPOxP2M2jf1h3da948ZDGB7jRv5H6FVxxyjx8tyJE/edit?usp=sharing), а друге коло це вже коли з сектору матимуть цю довідку готову повідомлятимуть про це особу.
Цю довідку просто можуть брати і люди і з інших областей тому думаю поки що потрібно оригінал щоб предявити її в іншому місті.
І ще одне при заповленні послуги там пише "ЦНАП Тернопільського району" при виборі, логічніше просто "Тернопільський район" тому що саме за цю послугу я подивлюсь чи вона через цнап йтиме чи напряму оскільки є витікаючою.
І добавте будь ласка цю послугу у групу для тестування під паролем Children_Tern, хочемо поки що згрупувати послуги для сімї під одним паролем, щоб на майбутнє можна було всім службам у районах порозсилати їхні послуги потестувати.

**Comment by sofiadanylevych** [comment]
Closed
