### ISSUE TITLE
Бердичів (Житомирська область) - Довідка про перебування на квартирному обліку

### ISSUE THREAD

**Issue by ezhikus** [e-government-ua/iBP#409]
Разработать услугу согласно её описанию в приложенном файле. Все данные исполнителей, собиравших данные волонтёров - в нём же.
[Видача довідок про перебування( не перебування) на квартирному обліку.docx](https://github.com/e-government-ua/iBP/files/149951/default.docx)

**Comment by Koffeek** [comment]
@msvidran Не пугайся

**Comment by agerman-ua** [comment]
прошу обратить внимание на ишью №428. Тот-же процесс.

**Comment by julyprodan** [comment]
на боевом
