### ISSUE TITLE
ЦНАП - Дніпропетровськ Видача листа-довідки на перевезення (перезахоронення) загиблого в зоні АТО

### ISSUE THREAD

**Issue by dmitrijzabrudskij** [e-government-ua/iBP#41]
кто предоставляет: АО Головне управління Держсанепідслужби у Дніпропетровській області

заява: https://dl.dropboxusercontent.com/u/91233927/%D0%A6%D0%9D%D0%90%D0%9F/%D0%98%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B5%20%D0%BA%D0%B0%D1%80%D1%82%D0%BE%D1%87%D0%BA%D0%B8%20%D0%B8%20%D0%B1%D0%BB%D0%B0%D0%BD%D0%BA%D0%B8%20%D0%B7%D0%B0%D1%8F%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B9%20%D1%87.1/439/%D0%97%D0%B0%D1%8F%D0%B2%D0%B0%20%281%29.doc

інформаційна картка: https://dl.dropboxusercontent.com/u/91233927/%D0%A6%D0%9D%D0%90%D0%9F/%D0%98%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B5%20%D0%BA%D0%B0%D1%80%D1%82%D0%BE%D1%87%D0%BA%D0%B8%20%D0%B8%20%D0%B1%D0%BB%D0%B0%D0%BD%D0%BA%D0%B8%20%D0%B7%D0%B0%D1%8F%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B9%20%D1%87.1/439/%D0%86%D0%9D%D0%A4%D0%9E%D0%A0%D0%9C%D0%90%D0%A6%D0%86%D0%99%D0%9D%D0%90%20%D0%9A%D0%90%D0%A0%D0%A2%D0%9A%D0%90.pdf

**Comment by NizhnikAlex** [comment]
1. Гражданин заполняет заявление (печатная форма), к заявлению добавляется 6 файлов скан-копий. Выбирает как ему удобнее получить оригинал справки - почтой или в одном из двух ЦНАП
2. Чиновник проверяет правильность заполнения информации
3. При отрицательном ответе - заявитель получает письмо с отказом.
4. При положительном - чиновник прикрепляет к письму скан-копию справки и отправляет письмо. Вариант письма зависит от того, какой способ получения выбрал заявитель вначале.

**Comment by NizhnikAlex** [comment]
Запущено 29.09.2015
На альфе https://test.igov.org.ua/service/736/general
На бете https://test-version.igov.org.ua/service/736/general (пока не пролита)
На боевом https://igov.org.ua/service/736/general

1. Гражданин выбирает г. Днепропетрвск, идентифицируется при помощи БанкИД или ЭЦП (не проверялось).
2. Заполняет обязательные поля, прикрепляет 5 скан-копий обязательных документов и отправляет заявку.
3. Заявка попадает в ЦНАП, заявитель получает письма (приветствие и с номером), администраторы ЦНАП полуучают письмо о новой заявке.
4. Администраторы ознакамливаются с присланной информацией, сканами документов. Принимают решение передавать ли заявку дальше. Могут распечатать заполненную принт-форму заявления.
4а. Если присланных данных недостаточно, администратор выбирает соответствующий пунк выпадающего меню. По возможности - оставляет комментарий. Заявитель получает сообщение с отказом. Работа с заявлением окончена.
4б. Если данных хватает, администратор выбирает соответствующий пунк выпадающего меню, прикрепляет скан файла-описи принятых документов. Автоматом крепится копия заполненного заявления (в работе). Нажимает "обработать".
5. Заявитель получает письмо, заявление и присланные копии документов администратор передает в службу.
6. Администратор получает ответ от службы (лист-довідка или обоснованный отказ), снова берет заявку в работу. Прикрепляет этот ответ, нажимает "обработать".
7. Заявитель получает либо отказ, либо копию письма-справки. Также на почту приходит приглашение прийти за оригиналом решения в выбранный ЦНАП.
