### ISSUE TITLE
Бердичів (Житомирська область) - Довідка з державної статистичної звітності про наявність земель та розподіл їх за власниками земель, землекористувачами, угіддями.

### ISSUE THREAD

**Issue by ezhikus** [e-government-ua/iBP#410]
Разработать услугу согласно её описанию в приложенном файле. Все данные исполнителей, собиравших данные волонтёров - в нём же.
[Видача довідки з Державної статистичної звітності про наявність земель та розподіл їх за власниками земель, землекористувачами, угіддями..docx](https://github.com/e-government-ua/iBP/files/149953/default.docx)

**Comment by Koffeek** [comment]
@ezhikus Услуга уже разработана и работает во многих городах. Был ли показ существующей?

**Comment by NizhnikAlex** [comment]
Я даже добавлю. Услуга законодательно отменена с 1.01.2016. Правда, пока не разработан новый механизм, оказывается.

**Comment by Koffeek** [comment]
@julyprodan Просьба дать координатору для тестирования существующую услугу и по результатам вносить доработки и выставлять на боевой

**Comment by Akylish88** [comment]
https://test-delta.igov.org.ua/service/102/general
Розкрито на тестовому.
Надіслав на пошту mmaj@mail.ua

**Comment by Akylish88** [comment]
Пообщался с начальником ЦНАП, отправил ему на тест.
Подолян Михайло Степанович (ЦНАП) 0984155229
administrator_2@ukr.net

**Comment by Akylish88** [comment]
https://igov.org.ua/service/102/general/place/built-in/region/13/city/54
На боевом
