### ISSUE TITLE
Бердичів (Житомирська область) - Надання дозволу на відключення від мереж централізованого опалення і постачання гарячої води

### ISSUE THREAD

**Issue by ezhikus** [e-government-ua/iBP#412]
Разработать услугу согласно её описанию в приложенном файле. Все данные исполнителей, собиравших данные волонтёров - в нём же.
[Надання дозволу на відключення від мереж централізованого опалення і постачання гарячої води..docx](https://github.com/e-government-ua/iBP/files/149957/default.docx)

**Comment by aleksandralomova** [comment]
@ezhikus здравствуйте, нужна информация по созданию данной услуги. А именно: обработка заявления работником Управления жилищно-коммунального хозяйства (на промежуточном этапе процесса) тоже будет происходить через портал iGov на его страничке чиновника или же нет??

**Comment by julyprodan** [comment]
на боевом
