### ISSUE TITLE
Житомир - Довідка про несудимість

### ISSUE THREAD

**Issue by ezhikus** [e-government-ua/iBP#414]
На днях продемонстрировали в Житомирском МВД услугу по справке о несудимости в том виде, как она реализована сейчас в common_mvd-1_hand.bpmn. Им, в общем, понравилось. Но попросили внести ряд изменений именно для Житомира.

1. Заявитель должен иметь возможность отметить галочкой, хочет ли он, чтобы в справку о несудимости были внесены также его предыдущие фамилия\имя\отчество (возможно, несколько).
2. Хотят логический контроль заполнения "русских" и "украинских" полей анкеты. В "русские" не должно быть возможности вводить буквы "ї", "і", "є", в "украинские" - буквы "э", "ё", "ы", "ъ".
3. В полях, описывающих место рождения человека (страна, область, район, населённый пункт) нужно в подсказке написать, что не нужно писать слов "область", "район", "місто", "село", "смт", а просто названия.
4. Для полей, описывающих место рождения человека (страна, область, район, населённый пункт), нужно проверять наличие слов "область", "район", "місто", "село", "смт" и выдавать ошибку.
5. Для адреса проживания сделать всё, описанное в пунктах 3-4 для места рождения человека.
6. Дать возможность выбрать название документа, который человек предоставляет, из следующего списка: "Паспорт громадянина України", "Закордонний паспорт", "Свідоцтво про народження", "Свідоцтво про проживання осіб без громадянства", "Свідоцтво осіб без громадянства".
7. Добавить в заявление три чекбокса, которые пользователь должен явно отметить: "Підтверджую правильність заповнення всіх реквізитів запиту", "Мене попереджено про відмову у видачі довідки в разі зазначення недостовірних даних" и "Відповідно до Закону України "Про захист персональних даних" від 01.06.2010 №2297-VI даю згоду на обробку моїх персональних даних".
8. Сделать принтформу согласно примера: http://www.zt.npu.gov.ua/uk/publish/article/81167 (начиная от слова "Запит" и дальше)
9. Сделать возможность отправки принтформы на заданную электронную почту (в домене npu.gov.ua) на первом шаге рассмотрения заявления, на втором шаге уже непосредственно дать возможность решать, будет ли предоставлена справка или нет. Это связано с тем, что на компьютерах с Интернетом у них нет баз данных, а на компьютерах с базами данных нет Интернета. Будут пересылать заявления себе на почту, потом обрабатывать.

**Comment by ezhikus** [comment]
@kurbpa я сам все эти нюансы сделаю, скажите только - стоит ли их делать в common_mvd-1_hand.bpmn, или сделать отдельную копию для Житомира и заниматься там?

**Comment by kurbpa** [comment]
@ezhikus 
Владимир, я бы не заморачивался на реализацию вообще. 
За исключением принтформы (да и в принтформе у меня нет полной уверенности уже). Поясню.
Текущая версия ( как она есть)  подготовлена для запуска на автоматическую отработку в ПК Рубин, что позволит существенно ускорить отработку заявки (мы тестировали тайминг отработки - у меня результат был получен за неполные 2 суток).
Сам процесс  ручной отработки это только общее временное решение перед внедрением автоматической отработки.

п.7 - категорически против подобных контролов откровенно говоря т.к. это гигантский информационный мусор. (к тому же и явления чекбоксов у нас нет).

**Comment by ezhikus** [comment]
@kurbpa я всё понимаю и полностью согласен. Но расскажите как-то (здесь или по почте) как это всё будет работать вместе с Рубином. Не зная этого я не могу ничего объяснить в МВД, не могу ответить на вопросы. Они просят "сделайте так", а я ничего не могу предложить взамен.

**Comment by kurbpa** [comment]
@ezhikus ничего пока не делайте вообще. У нас всё поменялось. 
Не будут сотрудники даже дашборд видеть. Напрямую всё прогружается в их комплексы. 
Для них ничего не меняется, а для граждан услуга будет доступна  по всей стране.

**Comment by ezhikus** [comment]
Ок
