### ISSUE TITLE
Вільногірськ - Рішення міської ради про надання дозволу на розробку технічної документації із землеустрою щодо поділу (об’єднання) земельних ділянок

### ISSUE THREAD

**Issue by msvidran** [e-government-ua/iBP#417]
https://drive.google.com/open?id=0B6hKo-clAKYgb3BGRFJRbEhPdDhaVDRsQk1yTHhTbWVRS2F3

https://drive.google.com/open?id=0B6hKo-clAKYgUmRjbk1SMzVtZ29TaXJmNExpRnF3NG41UW04

**Comment by Akylish88** [comment]
https://igov.org.ua/service/1392/general
Ця послуга вже є трохи з іншою назвою.
