### ISSUE TITLE
Житомир - Видача копій, витягів з розпоряджень міського голови, рішень, прийнятих міською радою та виконавчим комітетом

### ISSUE THREAD

**Issue by ezhikus** [e-government-ua/iBP#422]
Ранее запущенная услуга для Житомира "Видача копій, витягів з розпоряджень міського голови, рішень, прийнятих міською радою та виконавчим комітетом" должна быть изменена, поскольку в Житомире она предоставляется совсем не так, как описано в процессе cnap_293.bpmn 

Услуга предоставляется не через ЦНАП, а напрямую через горсовет. Кроме того, услуга предоставляется двумя отделами: для физлиц это отдел по работе с обращениями граждан (каб.127), для юрлиц это отдел деловодства, контроля и хозяйственного обеспечения (каб.107). 

Таким образом, первым пунктом в заявлении для Житомира должен быть комбо-бокс с выбором того, хотим ли мы подать заявление как физ.лицо или как юр.лицо. Если как физ - форма остаётся та же, что и сейчас, уведомления о новой заявке надо слать на zvern@zt-rada.gov.ua, список сотрудников отдела по работе с обращениями граждан для создания аккаунтов будет предоставлен позже.

Если заявление подаётся от юрлица - в форме должны появиться новые поля: наименование юрлица, место регистрации, ЕДРПОУ. Они также должны быть в принтформе. Уведомления о новой заявке надо слать на mvk@zt.rada.gov.ua, список сотрудников отдела деловодства, контроля и хозяйственного обеспечения будет предоставлен позже.

!!! Не берите эту задачу, пожалуйста, я занимаюсь ею сам. А ещё лучше дайте мне права асайнить на себя задачи, чтобы я не писал каждый раз этот текст !!!

**Comment by Koffeek** [comment]
@ezhikus Вы планируете разрабатывать новый процесс или редактировать старый?

**Comment by ezhikus** [comment]
@Koffeek старый рассчитан на работу через ЦНАП. У нас ЦНАП это заявление не принимает и не обрабатывает. В виду различий и в процессе обработки (2 отдела) и в форме заявления (от юрлица) мне кажется нужно делать новый. Я прав?

**Comment by Koffeek** [comment]
@ezhikus Старый расчитан на орган. Что будет записано в ОрганДжойне, то и будет: ЦНАП значит ЦНАП, МВК значит МВК, точно так же как и с обращениями к городскому голове. Я бы корректировал существующий. Различия не столь существенны. Выбор почты можно корректировать скриптом, добавку полей маркером. Лишнюю форму заявки просто добавить и всё. Но просьба, если будет корректировка делать сегодня вечером или завтра. Там его давно подрефакторить надо.

**Comment by ezhikus** [comment]
@Koffeek ok, скрипт, маркер - всё звучит реально. Тогда займусь завтра.

**Comment by ezhikus** [comment]
Вторая часть (о юрлицах) не актуальна для данной услуги - на igov, оказывается, для этих случаев есть отдельные услуги:

https://igov.org.ua/service/139/general
https://igov.org.ua/service/140/general
https://igov.org.ua/service/141/general
https://igov.org.ua/service/142/general

нужно, значит, подключать для Житомира их, а не ломать процесс cnap_293.bpmn

**Comment by ezhikus** [comment]
Так, теперь в этом процессе мы можем выбирать для каждого города, кем обрабатывается обращение - ЦНАПом или горсоветом. На данный момент горсоветом - только в Житомире.

**Comment by ezhikus** [comment]
Изменения проверены на альфе и смержены в cnap_293.bpmn в папках beta и prod.

@Koffeek создайте, пожалуйста, пользователей группы mvk_zt_ztT согласно заявке #326 и залейте, пожалуйста, обновлённую версию cnap_293.bpmn на боевой сервер при следующей заливке.

**Comment by ezhikus** [comment]
Пока отбой. На очередном раунде тестирования в горсовете нам сказали, что надо сделать принт-форму (стандартная шапка - кому, от кого, "Заява", "прошу видати копію ...", дата, подпись). Займусь.

**Comment by ezhikus** [comment]
Ок, пофикшено.

@Koffeek создайте, пожалуйста, пользователей группы cnap_zvern_zt_ztT согласно заявке #326 и залейте, пожалуйста, обновлённую версию cnap_293.bpmn на боевой сервер при следующей заливке.

**Comment by Koffeek** [comment]
Протестировано и выставлено на боевой
