### ISSUE TITLE
Новопсков Луганської обл. Про приватизацію житлового приміщення.

### ISSUE THREAD

**Issue by malietin** [e-government-ua/iBP#423]
Заказчик - Малетин Виктор  Новопсков Луганская обл.
Skype - cluboz2   почта v-maletin@mail.ru,   tel. 099 117 87 05,   093 563 58 66

Услуга "Про приватизацію житлового приміщення"

![img061](https://cloud.githubusercontent.com/assets/17567307/13430183/a80a0596-dfcc-11e5-8e37-7d9f09677383.jpg)
![img062](https://cloud.githubusercontent.com/assets/17567307/13430188/b0475358-dfcc-11e5-9b05-7c3d79f3d86e.jpg)
![img063](https://cloud.githubusercontent.com/assets/17567307/13430193/b46b2270-dfcc-11e5-8c92-faf757a5c5c2.jpg)
![img064](https://cloud.githubusercontent.com/assets/17567307/13430197/b705da20-dfcc-11e5-911a-065b30bedc13.jpg)
![img065](https://cloud.githubusercontent.com/assets/17567307/13430198/b917dffc-dfcc-11e5-8644-7fd32924f047.jpg)

**Comment by zolotovatatyana** [comment]
От Малетина: Селищна рада, не назначила (или не захотела назначать) ответственних за услуги и я перешёл работать с другой организацией! По- этому все услуги селищной ради, зависли на этапе тестирования - нескем тестировать!
