### ISSUE TITLE
Маріуполь - Надання відомостей з Державного земельного кадастру у формі витягу з Державного земельного кадастру про земельну ділянку

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#426]
Проверить эту услугу на портале - если уже есть - сверить инфокарты
Если инфокарты совпадают - раскрыть услугу на Мариуполь
Если не совпадают - разобраться какие изменения необходимо внести, обсудить с Ныжныком Александром

контактное лицо: Истомин Дмитрий dmitriy.istomin82@gmail.com
Тел. (067) 523 77 97

инфокарты находятся по ссылке 
https://drive.google.com/open?id=0B6mOkUg9oq1zc2dwekJJeGdRclU
номер инфокарты в архиве для этого процесса: 60

дополнительная информация от заказчика:
1. необхідна розбивка на юридичні/фізичні особи;
2. потрібна розбивка на різні типи (оренда, держакт та ін.);
3. необхідний обмінний файл (диск) чи інша форма інформації, для відправки через Інтернет;
4. оплата держмита через банківську установу.

**Comment by NizhnikAlex** [comment]
Реализовано на кадастровой карте для всей Украины
