### ISSUE TITLE
Маріуполь - Надання відомостей з Державного земельного кадастру у формі довідки, що містить узагальнену інформацію про землі (території)

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#427]
Проверить эту услугу на портале - если уже есть - сверить инфокарты
Если инфокарты совпадают - раскрыть услугу на Мариуполь
Если не совпадают - разобраться какие изменения необходимо внести, обсудить с Ныжныком Александром

контактное лицо: Истомин Дмитрий dmitriy.istomin82@gmail.com
Тел. (067) 523 77 97

инфокарты находятся по ссылке 
https://drive.google.com/open?id=0B6mOkUg9oq1zc2dwekJJeGdRclU
номер инфокарты в архиве для этого процесса: 63

дополнительная информация от заказчика:
1.наявність електронного підпису заявника;
2. необхідна розбивка на юридичні/фізичні особи;
3. необхідний обмінний файл (диск) чи інша форма інформації, для відправки через Інтернет;
4. наявність правоустанавлюючих  документів
5. Довідка 6-ЗЕМ в електронному вигляді тільки у випадку оформлення технічної документації.

**Comment by NizhnikAlex** [comment]
Ошибочно дали услугу. Отбой от координатора
