### ISSUE TITLE
Маріуполь - Надання довідки про перебування на квартирному обліку при міськвиконкомі за місцем проживання та в житлово-будівельному кооперативі

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#428]
Проверить эту услугу на портале - если уже есть - сверить инфокарты
Если инфокарты совпадают - раскрыть услугу на Мариуполь
Если не совпадают - разобраться какие изменения необходимо внести, обсудить с бизнес-аналитиком, ответственным за услугу

контактное лицо: Истомин Дмитрий dmitriy.istomin82@gmail.com
Тел. (067) 523 77 97

инфокарты находятся по ссылке 
https://drive.google.com/open?id=0B6mOkUg9oq1zc2dwekJJeGdRclU
номер инфокарты в архиве для этого процесса: 67

дополнительная информация от заказчика:
1. необхідна розбивка на юридичні/фізичні особи;

**Comment by agerman-ua** [comment]
объединены ишью 409 и 428 как одинаковый процесс

**Comment by julyprodan** [comment]
готова, ожидаю подписание меморандума
