### ISSUE TITLE
Тернопільська обл., розкриття послуг ДМС для м. Тернопіль

### ISSUE THREAD

**Issue by kelnerira** [e-government-ua/iBP#429]
1.Розкрити для "Тернопільський міський відділ міграційної служби",  м.Тернопіль, вул.Є.Коновальця,6. тел. +38 (0352) 28-78-08, 26-11-65
 наступні послуги:
- Видача/заміна паспорта громадянина для виїзду за кордон
- Видача паспорта громадянина для виїзду за кордон для дитини
- Обмін паспорта громадянина в разі зміни (переміни) прізвища, імені або по батькові
- Оформлення та видача паспорта громадянина по досягненні 16-річного віку
- Вклеювання до паспорта громадянина фотокартки при досягненні 25- і 45-річного віку
- Видача паспорта громадянина України замість викраденого
- Видача паспорта громадянина України замість утраченого
- Обмін паспорта громадянина у разі непридатності для користування

2. Створити тестовий кабінет для користувача Гриців Світлана Михайлівна svystunsvitl@gmail.com 

3. Для послуг -"Видача/заміна паспорта громадянина для виїзду за кордон", "Видача паспорта громадянина для виїзду за кордон для дитини" додати поле "терміновість" у заявці та доробити друк прінтформ при обробці та паралельне надсилання їх для самостійного друку заявником (для пришвидшення процесу прийому документів у ДМС)
 Деталізація змін тут: https://docs.google.com/spreadsheets/d/1fTqWyUpDVe5CrRINoqpFgAVitLParjuPys2ks73s-HQ/edit?usp=sharing
прінтформи тут: https://drive.google.com/folderview?id=0B-TXzbaEvbw9SW1vSms5WXpWU2c&usp=sharing

**Comment by Koffeek** [comment]
@kelnerira поле терміновість додавати не будемо. Можемо зробити окремою послугою, просто у загальній черзі. В Дніпрі відмовились від такої послуги допоки не буде налаштований повністю процес, бо ми ж даємо запис в чергу, а від цього терміну потрібно додавати 10 днів. При цьому людина може подумати, що з моменту запису повинно пройти 10 днів, пропоную запустити на тест звичайні послуги, а коли налаштуємо процес додавати терміновість. По заявах буду розбиратись, можливо будемо давати лише посилання на бланк з прикладом для заповнення.

**Comment by Koffeek** [comment]
@kelnerira Окреме питання по графіку роботи для електронної черги і які послуги треба об'єднувати у одну чергу (усі в одну, чи реєстрація окремо, закордонні паспорти окремо інші паспортні послуги - окремо)

**Comment by kelnerira** [comment]
@Koffeek терміновість можна не додавати, якщо ми надсилаємо заяви без друку прінтформ, вона не потрібна. 
Для кожної послуги робимо свою чергу, бо у них окрема людина на кожен вид послуг, у т.ч. окремо робимо закордонний дитячий і дорослий. При потребі регулюватимуть вільними годинами для онлайн заявників різних типів послуг.
Реєстраційні послуги не робимо, бо з квітня їх буде надавати ЦНАП, запустимо одразу там.
Графік роботи напишу окремо, бо це нове відділення,  ще не мають на 100% погодженого.

**Comment by Koffeek** [comment]
@kelnerira Я вірно розумію, що у них стоять три окремих апарати, один для Видача/заміна паспорта громадянина для виїзду за кордон, другий для Видача паспорта громадянина для виїзду за кордон для дитини, а третій для Оформлення та видача паспорта громадянина по досягненні 16-річного віку (ID-картки)? Бо інакше це можуть бути просто різні кабінети, але черга мусить бути одна.

**Comment by kelnerira** [comment]
Так, правильно

**Comment by kelnerira** [comment]
@Koffeek  Графік роботи 
Вівторок, четвер:    з 9.00   до 18.00 год.
Середа, п’ятниця: з 10.00 до 19.00 год.
Субота:                 з 9.00   до 16.45 год.
Обідня перерва:    з 13.00 до 13.45 год.

**Comment by Koffeek** [comment]
Видача/заміна паспорта громадянина для виїзду за кордон на боевом
Видача паспорта громадянина для виїзду за кордон для дитини готово к выливке

**Comment by sofiadanylevych** [comment]
Done
