### ISSUE TITLE
Ірпінь - видача довідок для центра зайнятості, що особа не являється членом селянського господарства 

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#431]
контактна особа:
Карєв Костянтин - управляющий делами мерии iispolcom@gmail.com +38 066 519 36 13	Белоконь Виктор cigetsoftware@gmail.com +380 (66) 156-89-18

**Comment by zolotovatatyana** [comment]
За якоюсь інструкцією, вони зараз видають лише при написанні заяви власне заявником, тому нажаль зараз можна реалізувати чи через ЕЦП чи відтермінувати цю послугу(.
