### ISSUE TITLE
Ірпінь - Видача архівних копій рішень

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#432]
контактна особа:
Карєв Костянтин - управляющий делами мерии iispolcom@gmail.com +38 066 519 36 12	Белоконь Виктор cigetsoftware@gmail.com +380 (66) 156-89-17

**Comment by Koffeek** [comment]
Я вроде дорабатывал процесс, но перепроверь, пожалуйста

**Comment by smoktii-igov** [comment]
​Отослано на тестирование (Бета) ​​послуга ​​"Видача копій, витягів з розпоряджень міського (селищного) голови, рішень, прийнятих міською (селищною) радою та виконавчим комітетом"

**Comment by smoktii-igov** [comment]
Выствлено в боевой

**Comment by smoktii-igov** [comment]
В РЕЛИЗе
