### ISSUE TITLE
Макаров - Видача довідки про перебування на квартирному обліку

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#435]
контактна особа:
Татьяна Гончарова - tatiana0706@ukr.net

**Comment by Akylish88** [comment]
0631403294
0983732394

**Comment by Akylish88** [comment]
Есть похожий процесс, жду инфокартку

**Comment by Akylish88** [comment]
https://drive.google.com/drive/folders/0BzgswhzWV6-7T21nWi1RX2ZPQ28

**Comment by Akylish88** [comment]
https://igov.org.ua/service/686/general
Давно на боевом
