### ISSUE TITLE
ЦНАП - Дніпропетровськ Надання дозволу релігійним організаціям на проведення релігійних заходів, які проводяться поза межами культових споруд

### ISSUE THREAD

**Issue by dmitrijzabrudskij** [e-government-ua/iBP#44]
кто предоставляет: АО Управління внутрішньої політики Дніпропетровської міської ради

заява: https://dl.dropboxusercontent.com/u/91233927/%D0%A6%D0%9D%D0%90%D0%9F/%D0%98%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B5%20%D0%BA%D0%B0%D1%80%D1%82%D0%BE%D1%87%D0%BA%D0%B8%20%D0%B8%20%D0%B1%D0%BB%D0%B0%D0%BD%D0%BA%D0%B8%20%D0%B7%D0%B0%D1%8F%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B9%20%D1%87.1/503/%D0%97%D0%90%D0%AF%D0%92%D0%90_%28%D1%80%D0%B5%D0%BBi%D0%B3.%D0%B7%D0%B0%D1%85%D0%BE%D0%B4_%D0%A3%D0%92%D0%9F_%D0%94%D0%9C%D0%A0%29%20%284%29.doc

інформаційна картка: https://dl.dropboxusercontent.com/u/91233927/%D0%A6%D0%9D%D0%90%D0%9F/%D0%98%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B5%20%D0%BA%D0%B0%D1%80%D1%82%D0%BE%D1%87%D0%BA%D0%B8%20%D0%B8%20%D0%B1%D0%BB%D0%B0%D0%BD%D0%BA%D0%B8%20%D0%B7%D0%B0%D1%8F%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B9%20%D1%87.1/503/%D0%86%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D1%96%D0%B9%D0%BD%D0%B0%20%D0%BA%D0%B0%D1%80%D1%82%D0%BA%D0%B0%20%2856%29.doc

**Comment by Koffeek** [comment]
Описание работы: 1.Гражданин заполняет необходимые поля и прикрепляет документ. 2.Происходит загрузка документа и передача данных. 3.Гражданину приходит письмо с уведомлением об успешной регистрации заявления. 4.Чиновник просматривает данные и документы переданные гражданином. 5.Если чего-то не хватает, то отправляется письмо о невозможности оказать услугу с указанием причины. 6. Если всё в порядке, то данные переходят дальше. 7. Поступлениие решения к чиновнику в зависимости от которого он: 
    8а. Отпраляет письмо, о невозможности оказать услугу. 
    8б. Отправляет письмо о готовности дозвола и необходимости его забрать в ЦНАП Правый берег 
   8в. Отправляет письмо о готовности дозвола и необходимости его забрать в ЦНАП Левый берег

**Comment by Koffeek** [comment]
Описание работы: 
1.Гражданин заполняет необходимые поля, прикрепляет документ и выбирает ЦНАП, где ему удобнее будет забрать решение. 
2.Происходит загрузка документа и передача данных. 
3.Гражданину приходит письмо с уведомлением об успешной регистрации заявления. 4.Чиновник просматривает данные и документы переданные гражданином. 
5.Если чего-то не хватает, то отправляется письмо о невозможности регистрации заявления с указанием причины. 
6. Если всё в порядке, то данные переходят дальше. 
7. Поступлениие решения к чиновнику в зависимости от которого он прикрепляет копию решения и:
8а. Отпраляет письмо, об отказе в проведении мероприятия и необходимости его забрать в ЦНАП Правый берег.
8б. Отправляет письмо о готовности дозвола и необходимости его забрать в ЦНАП Правый берег
8в. Отправляет письмо о готовности дозвола и необходимости его забрать в ЦНАП Левый берег
8г. Отправляет письмо об отказе в проведении мероприятия и необходимости его забрать в ЦНАП Левый берег

**Comment by GrekD** [comment]
1. в принтформе поле "мета" может наползать на другие линии если там будет внесено много текста
![2015-09-21_150647](https://cloud.githubusercontent.com/assets/10836093/9991541/84ba87e2-6073-11e5-8e91-9ed5fa2ade14.jpg)
2. обязательно ли все поля передавать во вторую юзертаску? 
3 3.в письме кое-где видны теги
![2015-09-21_1506473](https://cloud.githubusercontent.com/assets/10836093/9991551/937b2232-6073-11e5-8147-d798ed2ca525.jpg)

**Comment by Koffeek** [comment]
1. Поправлено
2. ИМХО да.
3. Поправлено.

**Comment by Koffeek** [comment]
Процесс ушел в бой. Тесты проведены.
