### ISSUE TITLE
Корсунь-Шевченківська РДА - Надання висновку на відповідність ДБН з питань забудови

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#445]
Інформація про контактну особу по роботі з порталом iGov у відділі містобудування, архітектури, житлово-комунального господарства та будівництва Корсунь-Шевченківської районної державної адміністрації
Головний спеціаліст відділу містобудування,архітектури, житлово-комунального господарства та будівництва районної державної адміністрації
Яковенко Анатолій Володимирович	096-3400003	korsun-arhitektura-igov@ukr.net
[ЗАТВЕРДЖЕНО 4 забудова для IGov.docx](https://github.com/e-government-ua/iBP/files/281897/4.IGov.docx)
[ЗАТВЕРДЖЕНО в_дпов_дн_сть ДБН для IGov.docx](https://github.com/e-government-ua/iBP/files/281896/_._._.IGov.docx)

**Comment by annastolbova** [comment]
координатор на данный момент услугу в работу просил не брать

**Comment by Akylish88** [comment]
Новий

**Comment by Akylish88** [comment]
https://test-delta.igov.org.ua/service/1511/general
Готово для тестирования

**Comment by Akylish88** [comment]
https://igov.org.ua/service/1511/general
На бойовому. Нова. Інфо та ескалації є.
