### ISSUE TITLE
ЦНАП - Дніпропетровськ Переоформлення, видача копії або дубліката ліцензії на надання освітніх послуг у сфері загальної середньої, дошкільної, позашкільної освіти

### ISSUE THREAD

**Issue by dmitrijzabrudskij** [e-government-ua/iBP#45]
кто предоставляет: АО Департамент освіти і науки Дніпропетровської облдержадміністрації

заява: https://dl.dropboxusercontent.com/u/91233927/%D0%A6%D0%9D%D0%90%D0%9F/%D0%98%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B5%20%D0%BA%D0%B0%D1%80%D1%82%D0%BE%D1%87%D0%BA%D0%B8%20%D0%B8%20%D0%B1%D0%BB%D0%B0%D0%BD%D0%BA%D0%B8%20%D0%B7%D0%B0%D1%8F%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B9%20%D1%87.1/523/%D0%97%D0%B0%D1%8F%D0%B2%D0%B0%20%282%29.doc

інформаційна картка: https://dl.dropboxusercontent.com/u/91233927/%D0%A6%D0%9D%D0%90%D0%9F/%D0%98%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B5%20%D0%BA%D0%B0%D1%80%D1%82%D0%BE%D1%87%D0%BA%D0%B8%20%D0%B8%20%D0%B1%D0%BB%D0%B0%D0%BD%D0%BA%D0%B8%20%D0%B7%D0%B0%D1%8F%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B9%20%D1%87.1/523/%D0%86%D0%9D%D0%A4%D0%9E%D0%A0%D0%9C%D0%90%D0%A6%D0%86%D0%99%D0%9D%D0%90%20%D0%9A%D0%90%D0%A0%D0%A2%D0%9A%D0%90%20%2857%29.doc

**Comment by GrekD** [comment]
Имя файла: Dnepr_cnap_45.bpmn
Город: Днепропетровск
Группа: Dnepr_cnap_45
На локали: Dnepr_cnap_45:1:259
Услуга: Переоформлення, видача копії або дубліката ліцензії на надання освітніх послуг у сфері загальної середньої, дошкільної, позашкільної освіти
Орган: Департамент освіти і науки Дніпропетровської ОДА

1. гражданин подает заявку, прикрепляет заяву, сканкопию оригинала лицензии, чек об оплате услуги (необязательно)
2  в письме направляется кнопка для он-лайн оплаты (для случая если он не прикрепил чек)
3. гос.орган рассматривает пакет документов - либо выдает лицензию либо нет
4. гражданин получает уведомление о решении

**Comment by Koffeek** [comment]
1. Стартивнт: Валидатор на номер телефона учреждения. s4(3), Валидатор на номер ИНН учреждения. s4(3) Разбить верхний лейбл на 2 части, тогда будет читабельнее и удобнее s5
2. Юзерстаск1: Наименования полей на Юзерстаске (сделать без оберіть...). s5
3. Принтформа: Орг-прав форма, идент код закладу, Банк реквизиты без подчеркивания. s5
4. Принтформа: полное ПИБ рук-ля в подписи уходит на след строку. s4
5. Е-мейл отказа: добавить ЦНАП в подписи, а то непонятно кто отказал. s4(3)
6. Е-мейл с описом: добавить ЦНАП в подписи s4(3). Вынести регситрационный номер ЦНАП в отдельную строку и написать, что номер от ЦНАПа (а то у гражданина будет диссонанс). s5
7. Е-мейл отказа по услуге: добавить ЦНАП в подписи, добавить где и когда можно забрать відмову, какие для этого нужны документы. s4(3)
8. Е-мейл подтверждения по услуге: добавить ЦНАП в подписи s4(3). Распечатанную заяву (или копию) гражданин никак не получал и потому принести не сможет. s2

**Comment by GrekD** [comment]
на боевом
