### ISSUE TITLE
Новопсков Луганская обл. Надання громадянину / громадянці України земельної ділянки безоплатно у власність ( в т.ч. приватизація земельних ділянок, що знаходиться у користуванні)

### ISSUE THREAD

**Issue by malietin** [e-government-ua/iBP#450]
Заказчик - Малетин Виктор
Skype - cluboz2   почта v-maletin@mail.ru,   tel. 099 117 87 05,   093 563 58 66
![img068](https://cloud.githubusercontent.com/assets/17567307/13466561/1a64364e-e0a3-11e5-81a5-382e182c82bb.jpg)
![img069](https://cloud.githubusercontent.com/assets/17567307/13466562/1cff16a8-e0a3-11e5-8fc2-70c37ed6bb05.jpg)

**Comment by Akylish88** [comment]
Надається напряму селищною радою. Рада поки не погодилась на співпрацю з Igov.
