### ISSUE TITLE
Новопсков Луганська обл. Видача дозволу на розроблення технічної документації із землеустрою щодо встановлення меж земельної ділянки в натурі (на місцевості)

### ISSUE THREAD

**Issue by malietin** [e-government-ua/iBP#451]
Заказчик - Малетин Виктор
Skype - cluboz2   почта v-maletin@mail.ru,   tel. 099 117 87 05,   093 563 58 66
Нужен новый процесс для РДА, через ЦНАП
![img070](https://cloud.githubusercontent.com/assets/17567307/13491702/871f4082-e13c-11e5-9256-48bf756b0e90.jpg)
![img071](https://cloud.githubusercontent.com/assets/17567307/13491705/890e6fc6-e13c-11e5-8b4b-c0bdb7fb97e7.jpg)
![img072](https://cloud.githubusercontent.com/assets/17567307/13491712/8d127d92-e13c-11e5-9500-93711bddfeba.jpg)
![img073](https://cloud.githubusercontent.com/assets/17567307/13491714/8f491e68-e13c-11e5-83e1-387f58efd7cf.jpg)
![img074](https://cloud.githubusercontent.com/assets/17567307/13491716/921af346-e13c-11e5-9c11-f1ffe6bf40a6.jpg)

**Comment by Akylish88** [comment]
https://igov.org.ua/service/1392/general
На боевом. Но без очереди. Как только будет версия от програмистов(когда не знаю, обещали уже давно) добавлю очередь.
