### ISSUE TITLE
Новопсков Луганська обл. Видача дозволу (ордеру) на видалення зелених насаджень.

### ISSUE THREAD

**Issue by malietin** [e-government-ua/iBP#452]
Заказчик - Малетин Виктор
Skype - cluboz2   почта v-maletin@mail.ru,   tel. 099 117 87 05,   093 563 58 66
Нужен новый процесс, для бесплатной услуги, для поссовета минуя ЦНАП.
![img075](https://cloud.githubusercontent.com/assets/17567307/13492128/f18ebc3e-e13e-11e5-837f-1af715cd486b.jpg)
![img076](https://cloud.githubusercontent.com/assets/17567307/13492129/f3123f36-e13e-11e5-83bb-09c2ac1b57d3.jpg)
![img077](https://cloud.githubusercontent.com/assets/17567307/13492131/f524dfa4-e13e-11e5-8f16-21b8a212bd90.jpg)

**Comment by Akylish88** [comment]
Надається напряму селищною радою. Рада поки не погодилась на співпрацю з Igov.
