### ISSUE TITLE
Новопсков Луганська обл. Видача дозволу на розроблення проекту землеустрою щодо відведення земельної ділянки.

### ISSUE THREAD

**Issue by malietin** [e-government-ua/iBP#453]
Заказчик - Малетин Виктор
Skype - cluboz2    почта v-maletin@mail.ru,   tel. 099 117 87 05,   093 563 58 66
![img078](https://cloud.githubusercontent.com/assets/17567307/13492493/0ca1460c-e141-11e5-865f-5db70a6b2a19.jpg)
![img079](https://cloud.githubusercontent.com/assets/17567307/13492494/0ecdfe3e-e141-11e5-83b5-b2dd11ea0d72.jpg)
![img080](https://cloud.githubusercontent.com/assets/17567307/13492498/11ac4d2c-e141-11e5-8ec8-87962baae311.jpg)

**Comment by Akylish88** [comment]
Все услуги по Новопскову что не через ЦНАП приостановлены, инфа от координатора. Пробуксовка в селищной раде.

**Comment by Akylish88** [comment]
Надається напряму селищною радою. Рада поки не погодилась на співпрацю з Igov.
