### ISSUE TITLE
Новопсков Луганська обл. Про надання в оренду майна комунальної власності.

### ISSUE THREAD

**Issue by malietin** [e-government-ua/iBP#454]
Заказчик - Малетин Виктор
Skype - cluboz2   почта v-maletin@mail.ru,   tel. 099 117 87 05,   093 563 58 66
![img081](https://cloud.githubusercontent.com/assets/17567307/13492743/85a05e5c-e142-11e5-9e5b-178bc0c524dc.jpg)
![img082](https://cloud.githubusercontent.com/assets/17567307/13492744/8794d968-e142-11e5-8591-38b6f06f9112.jpg)
![img083](https://cloud.githubusercontent.com/assets/17567307/13492745/8a88592e-e142-11e5-9fca-3a558b3f1b70.jpg)

**Comment by Akylish88** [comment]
Стадія теста

**Comment by Akylish88** [comment]
Все услуги по Новопскову что не через ЦНАП приостановлены, инфа от координатора. Пробуксовка в селищной раде.

**Comment by Akylish88** [comment]
Надається напряму селищною радою. Рада поки не погодилась на співпрацю з Igov.
