### ISSUE TITLE
Новопсков Луганська обл. Надання рішення про продаж земельної ділянки комунальної власності.

### ISSUE THREAD

**Issue by malietin** [e-government-ua/iBP#455]
Заказчик - Малетин Виктор
Skype - cluboz2   почта v-maletin@mail.ru,   tel. 099 117 87 05,   093 563 58 66
![img084](https://cloud.githubusercontent.com/assets/17567307/13493042/391cb240-e144-11e5-95c8-0082163cc910.jpg)
![img085](https://cloud.githubusercontent.com/assets/17567307/13493044/3ae97c48-e144-11e5-89b3-835a6a53895b.jpg)
![img086](https://cloud.githubusercontent.com/assets/17567307/13493046/3cdbeb26-e144-11e5-9213-4bf3b9fcdacf.jpg)

**Comment by Akylish88** [comment]
Надається напряму селищною радою. Рада поки не погодилась на співпрацю з Igov.
