### ISSUE TITLE
Новопсков Луганська обл.Погодження на будівництво споруд, об’єктів дорожнього сервісу, автозаправних станцій, прокладення інженерних мереж та виконання інших робіт у межах смуги відведення автомобільних доріг.

### ISSUE THREAD

**Issue by malietin** [e-government-ua/iBP#458]
Заказчик - Малетин Виктор
Skype - cluboz2 почта v-maletin@mail.ru, tel. 099 117 87 05, 093 563 58 66

![img099](https://cloud.githubusercontent.com/assets/17567307/13597898/a7ea8570-e523-11e5-8ab7-75ff8a7530a9.jpg)
![img100](https://cloud.githubusercontent.com/assets/17567307/13597904/aae44f18-e523-11e5-9fc1-352be39678dd.jpg)
![img101](https://cloud.githubusercontent.com/assets/17567307/13597908/ad2aec8c-e523-11e5-8920-0b9ac4c31137.jpg)
![img102](https://cloud.githubusercontent.com/assets/17567307/13597911/af2903ac-e523-11e5-9f62-077bba20a38d.jpg)
![img103](https://cloud.githubusercontent.com/assets/17567307/13597916/b1b721f8-e523-11e5-9316-4d9e67570d12.jpg)

**Comment by Akylish88** [comment]
ЦНАП делаем

**Comment by Akylish88** [comment]
Координатор сказал что услугу не делать.
