### ISSUE TITLE
Хмельницький - Дозвіл (санітарний паспорт) на право експлуатації рентгенівського кабінету (зберігання та експлуатації пересувних і переносних (палатних) рентгенівських апаратів) лікувально-профілактичних закладів

### ISSUE THREAD

**Issue by plyacik** [e-government-ua/iBP#459]
підключити в боєвий портал, посадовець - Малінковська Олена Володимирівна - cnap32@rada.khmelnytsky.com - +380672831292
Хмельницький - ЦНАП

**Comment by zolotovatatyana** [comment]
раскрытие dnepr_cnap_244

**Comment by plyacik** [comment]
[https://drive.google.com/drive/u/0/folders/0BzhmqPf0m3-ET2hTSnYzbmxERmM](url)

**Comment by zolotovatatyana** [comment]
17/03 релиз
