### ISSUE TITLE
Хмельницький - Дозвіл (санітарний паспорт) на проведення робіт з джерелами іонізуючих випромінювань в установах

### ISSUE THREAD

**Issue by plyacik** [e-government-ua/iBP#460]
підключити в боєвий портал, посадовець - Малінковська Олена Володимирівна - cnap32@rada.khmelnytsky.com - +380672831292
Хмельницький - ЦНАП

**Comment by zolotovatatyana** [comment]
раскрытие dnepr_cnap_248

**Comment by zolotovatatyana** [comment]
17/03 релиз
