### ISSUE TITLE
Хмельницький - Надання довідки з Державної статистичної звітності про наявність земель та розподіл їх за власниками земель, землекористувачами, угіддями (за даними форми 6-ЗЕМ)

### ISSUE THREAD

**Issue by plyacik** [e-government-ua/iBP#461]
підключити в боєвий портал, посадовець - Малінковська Олена Володимирівна - cnap32@rada.khmelnytsky.com - +380672831292
Хмельницький - ЦНАП

**Comment by NizhnikAlex** [comment]
Подготовлено. Раскроется в версию
