### ISSUE TITLE
Хмельницький - Надання довідок незайнятому населенню про відсутність земельних ділянок для ведення ОСГ

### ISSUE THREAD

**Issue by plyacik** [e-government-ua/iBP#464]
підключити в боєвий портал, посадовець - Малінковська Олена Володимирівна - cnap32@rada.khmelnytsky.com - +380672831292
Хмельницький - ЦНАП

**Comment by plyacik** [comment]
@julyprodan @Koffeek @GrekD 
1. Можливо додати можливість скачувати копію паспорта в кабінеті держлужбовця?
2. Та можливість надсилати громадянину скан копію довідки, тобто якщо громадянин хоче отримати відповідь в електронному вигляді?

**Comment by julyprodan** [comment]
добрый день! сделаю

**Comment by julyprodan** [comment]
@plyacik 
https://test.igov.org.ua/service/23/general
Протестируйте, пожалйста

**Comment by plyacik** [comment]
@julyprodan можете подключить в боевой на 2 мейла, протестировали, все ок
Посадовець:
1. Малінковська Олена Володимирівна cnap32@rada.khmelnytsky.com 380672831292
2. Онищук Наталя Володимирівна cnap35@rada.khmelnytsky.com

**Comment by julyprodan** [comment]
перевела на боевые флаги, при ближайшем обновлении будет доступна гражданину

**Comment by julyprodan** [comment]
на боевом
