### ISSUE TITLE
Дніпропетровська область - Надання містобудівних умов і обмежень забудови земельної ділянки

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#466]
Розкрити/створити послугу на наступні міста Дніпроптеровської області:

- [ ] Вільногірськ
- [ ] Дніпродзержинськ
- [x] Дніпропетровськ
- [ ] Жовті Води
- [ ] Марганець
- [ ] Нікополь
- [ ] Новомосковськ
- [ ] Орджонікідзе
- [ ] Павлоград
- [ ] Першотравенськ
- [ ] Синельникове
- [ ] Тернівка
- [ ] Апостолівський р-н
- [ ] Васильківський р-н
- [ ] Верхньодніпровський р-н
- [ ] Дніпропетровський р-н
- [ ] Криворізький р-н
- [ ] Криничанський р-н
- [ ] Магдалинівський р-н
- [ ] Межівський р-н
- [ ] Нікопольський р-н
- [ ] Новомосковський р-н
- [ ] П’ятихатський р-н
- [ ] Павлоградський р-н
- [ ] Петриківський р-н
- [ ] Петропавлівський р-н
- [ ] Покровський р-н
- [ ] Синельниківський р-н
- [ ] Солонянський р-н
- [ ] Софіївський р-н
- [ ] Томаківський р-н
- [ ] Царичанський р-н
- [ ] Широківський р-н
- [ ] Юр’ївський р-н

Процес створювати чи рефакторити з використанням SubjectOrganJoinAttribute (атрибути будуть заведені централізовано на всі райони - окремо їх створювати не потрібно) та використанням уніфікованних змінних:
sNameOrgan
sWorkTime
sPhoneOrgan
sAddress
sMailClerk
sArea
nArea
sShapka
nID_Department_visitDay

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0):

**Comment by annastolbova** [comment]
закрити на наступні міста/райони:

- [ ] Верхньодніпровський р-н
- [ ] Покровський р-н
- [ ] Томаківський р-н
- [ ] Царичанський р-н

**Comment by julyprodan** [comment]
на Томаківський р-н район открыто не было
