### ISSUE TITLE
Дніпропетровська область - Видача будівельного паспорту забудови земельної ділянки

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#467]
Розкрити/створити послугу на наступні міста Дніпроптеровської області:
- [ ] Дніпродзержинськ
- [x]  Дніпропетровськ
- [ ]  Жовті Води
- [ ]  Марганець
- [ ]  Нікополь
- [ ]  Новомосковськ
- [ ]  Павлоград
- [ ]  Першотравенськ
- [ ]  Синельникове
- [ ]  Тернівка
- [ ]  Апостолівський р-н
- [ ]  Васильківський р-н
- [ ]  Верхньодніпровський р-н
- [ ]  Дніпропетровський р-н
- [ ]  Криворізький р-н
- [ ]  Криничанський р-н
- [ ]  Магдалинівський р-н
- [ ]  Межівський р-н
- [ ]  Нікопольський р-н
- [ ]  Новомосковський р-н
- [ ]  П’ятихатський р-н
- [ ]  Павлоградський р-н
- [ ]  Петриківський р-н
- [ ]  Петропавлівський р-н
- [ ]  Покровський р-н
- [ ]  Синельниківський р-н
- [ ]  Солонянський р-н
- [ ]  Софіївський р-н
- [ ]  Томаківський р-н
- [ ]  Царичанський р-н
- [ ]  Широківський р-н
- [ ]  Юр’ївський р-н

Процес створювати чи рефакторити з використанням SubjectOrganJoinAttribute (атрибути будуть заведені централізовано на всі райони - окремо їх створювати не потрібно) та використанням уніфікованних змінних:
sNameOrgan
sWorkTime
sPhoneOrgan
sAddress
sMailClerk
sArea
nArea
sShapka
nID_Department_visitDay

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

**Comment by annastolbova** [comment]
закрити на наступні міста/райони:

- [ ] Орджонікідзе
- [ ] П’ятихатський р-н
- [ ] Покровський р-н
- [ ] Царичанський р-н

**Comment by julyprodan** [comment]
закрыто
