### ISSUE TITLE
Дніпропетровська область - Видача паспорту прив’язки тимчасової споруди або продовження терміну його дії

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#468]
Розкрити/створити послугу на наступні міста Дніпроптеровської області:
- [x] Вільногірськ
- [x] Дніпродзержинськ
- [x] Дніпропетровськ
- [x] Жовті Води
- [x] Кривий Ріг
- [x] Марганець
- [x] Нікополь
- [x] Новомосковськ
- [x] Орджонікідзе
- [x] Павлоград
- [x] Першотравенськ
- [x] Синельникове
- [x] Тернівка
- [x] Апостолівський р-н
- [x] Васильківський р-н
- [ ] Верхньодніпровський р-н
- [x] Дніпропетровський р-н
- [x] Криворізький р-н
- [ ] Криничанський р-н
- [x] Магдалинівський р-н
- [x] Межівський р-н
- [x] Нікопольський р-н
- [x] Новомосковський р-н
- [x] П’ятихатський р-н
- [x] Павлоградський р-н
- [x] Петриківський р-н
- [x] Петропавлівський р-н
- [x] Покровський р-н
- [x] Синельниківський р-н
- [x] Солонянський р-н
- [x] Софіївський р-н
- [x] Томаківський р-н
- [ ] Царичанський р-н
- [ ] Широківський р-н
- [x] Юр’ївський р-н

Процес створювати чи рефакторити з використанням SubjectOrganJoinAttribute (атрибути будуть заведені централізовано на всі райони - окремо їх створювати не потрібно) та використанням уніфікованних змінних:
sNameOrgan
sWorkTime
sPhoneOrgan
sAddress
sMailClerk
sArea
nArea
sShapka
nID_Department_visitDay

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

**Comment by YmNIK13** [comment]
Отказались:

- Царичанський р-н 
- Широківський р-н
- Криничанський р-н
- Верхньодніпровський р-н

**Comment by annastolbova** [comment]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [ ] Новомосковськ
- [ ] Орджонікідзе
- [ ] Тернівка
- [ ] Криворізький р-н
- [ ] Магдалинівський р-н
- [ ] Новомосковський р-н
- [ ] П’ятихатський р-н

Закрити на наступні міста/регіони:

- [ ] Верхньодніпровський р-н
