### ISSUE TITLE
Дніпропетровська область - Присвоєння/підтвердження/зміна поштової адреси об’єктам нерухомого майна та земельним ділянкам наданим під будівництво

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#470]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [x] Вільногірськ
- [x] Дніпродзержинськ
- [x] Дніпропетровськ
- [x] Жовті Води
- [x] Марганець
- [x] Нікополь
- [x] Новомосковськ
- [x] Павлоград
- [x] Першотравенськ
- [x] Синельникове
- [x] Апостолівський р-н
- [x] Криничанський р-н
- [x] Межівський р-н
- [x] Томаківський р-н

Процес створювати чи рефакторити з використанням SubjectOrganJoinAttribute (атрибути будуть заведені централізовано на всі райони - окремо їх створювати не потрібно) та використанням уніфікованних змінних:
sNameOrgan
sWorkTime
sPhoneOrgan
sAddress
sMailClerk
sArea
nArea
sShapka
nID_Department_visitDay

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

**Comment by GrekD** [comment]
на боевом

**Comment by annastolbova** [comment]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [ ] Орджонікідзе
- [ ] Тернівка
- [ ] Юр’ївський р-н


Закрити на наступні міста/регіони:

- [ ] Томаківський р-н
- [ ] Межівський р-н
- [ ] Криничанський р-н
- [ ] Марганець

**Comment by GrekD** [comment]
на тестовом раскрыла

**Comment by GrekD** [comment]
на боевом
