### ISSUE TITLE
Дніпропетровська область - Погодження проекту землеустрою (технічної документації) щодо відведення земельної ділянки

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#471]
Розкрити/створити послугу на наступні міста Дніпропетровської області:
- [x] Нікополь
- [x] Новомосковськ
- [x] Орджонікідзе
- [x] Павлоград
- [ ] Першотравенськ
- [x] Синельникове
- [ ] Тернівка
- [ ] Апостолівський р-н
- [ ] Васильківський р-н
- [ ] Верхньодніпровський р-н
- [ ] Дніпропетровський р-н
- [x] Криворізький р-н
- [ ] Криничанський р-н
- [ ] Магдалинівський р-н
- [ ] Межівський р-н
- [ ] Нікопольський р-н
- [ ] Новомосковський р-н
- [ ] П’ятихатський р-н
- [ ] Павлоградський р-н
- [x] Петриківський р-н
- [ ] Петропавлівський р-н
- [ ] Покровський р-н
- [ ] Синельниківський р-н
- [x] Солонянський р-н
- [ ] Софіївський р-н
- [ ] Томаківський р-н
- [ ] Царичанський р-н
- [ ] Широківський р-н
- [ ] Юр’ївський р-н
Процес створювати чи рефакторити з використанням SubjectOrganJoinAttribute (атрибути будуть заведені централізовано на всі райони - окремо їх створювати не потрібно) та використанням уніфікованних змінних:
sNameOrgan
sWorkTime
sPhoneOrgan
sAddress
sMailClerk
sArea
nArea
sShapka
nID_Department_visitDay

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

**Comment by Akylish88** [comment]
https://igov.org.ua/service/1419/general на боевом

**Comment by annastolbova** [comment]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [ ] Вільногірськ	
- [ ] Дніпродзержинськ
- [ ] Жовті Води
- [ ] Марганець
- [ ] Новомосковськ
- [ ] Орджонікідзе
- [ ] Першотравенськ
- [ ] Тернівка
- [ ] Криворізький р-н
- [ ] Магдалинівський р-н
- [ ] П’ятихатський р-н


**Скрыть на боевом услугу для следующих городов:**

- [ ] Межівський р-н
- [ ] Нікопольський р-н
- [ ] Петропавлівський р-н
- [ ] Солонянський р-н
- [ ] Томаківський р-н
- [ ] Широківський р-н

**Comment by Akylish88** [comment]
заведено и удалено, пока на альфе.
