### ISSUE TITLE
Дніпропетровська область - Видача листа-довідки на перевезення (перезахоронення) трупу, у тому числі в он-лайн сервісі

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#473]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [x] Дніпропетровськ
- [x] Вольногорск
- [x] Марганець
- [x] Нікополь
- [x] Орджонікідзе
- [x] Павлоград
- [x] Нікопольський р-н
- [x] Павлоградський р-н
- [x] Юр’ївський р-н

Процес створювати чи рефакторити з використанням SubjectOrganJoinAttribute (атрибути будуть заведені централізовано на всі райони - окремо їх створювати не потрібно) та використанням уніфікованних змінних:
sNameOrgan
sWorkTime
sPhoneOrgan
sAddress
sMailClerk
sArea
nArea
sShapka
nID_Department_visitDay

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

**Comment by msvidran** [comment]
1. заява http://e-services.dp.gov.ua/_layouts/WordViewer.aspx?id=/Lists/List/Attachments/6210/%D0%97%D0%B0%D1%8F%D0%B2%D0%B0+%28%D0%BD%D0%B0+%D0%B2%D0%B8%D1%81%D0%BD%D0%BE%D0%B2%D0%BE%D0%BA+%D1%89%D0%BE%D0%B4%D0%BE+%D0%BC%D0%BE%D0%B6%D0%BB%D0%B8%D0%B2%D0%BE%D1%81%D1%82%D1%96++%D0%BF%D0%B5%D1%80%D0%B5%D0%BF%D0%BE%D1%85%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F+%29.docx

**Comment by msvidran** [comment]
https://igov.org.ua/service/736/general
