### ISSUE TITLE
Першотравневий район (Донецкая область) - Звернення до голови РДА (розкриття)

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#476]
Ссилка на iGov
https://igov.org.ua/service/11/general
ПІБ Відповідальної особи - Никольченко Ирина Николаевна
e-mail: nikolchenkoirina4@gmail.com
№ моб: 0987996975
Сайт Першотравневого району: http://www.meotida.com.ua/

**Comment by Koffeek** [comment]
Протестировано и выставлено на боевой 28,03,2016
