### ISSUE TITLE
Хмельницький: "Дозвіл на розміщення зовнішньої реклами"

### ISSUE THREAD

**Issue by smoktii-igov** [e-government-ua/iBP#477]
заява пишеться на ім`я:  Керівника робочого органу
Начальника управління архітектури та містобудування – головному архітектору міста.

**Comment by smoktii-igov** [comment]
В связи с тем, что у разных оргструктур могут быть разные объекты кому писать заявление, то необходимо использовать атрибут. При этом атрибута sShapka может быть недостаточно, так как сейчас Shapka заполняется не так как надо для услуги 15 Дозвіл на розміщення зовнішньої реклами. Предложение ввести атрибут sShapka_15
Прошу подтверждения введения нового атрибута. 
@GrekD , @Koffeek

**Comment by GrekD** [comment]
@smoktii-igov  все работает )

**Comment by YmNIK13** [comment]
@smoktii-igov Можно просто по ходу редактировать атрибут sShapka, чтоб туда входи вся информация :) как вариант.

**Comment by smoktii-igov** [comment]
Вариант с редактированием плох, так как гражданин может не знать точно кому адресуется заявление. Это определяет местные органы. По переменной-атрибуту итоговый вариант sShapka_dozvil_na_reklamu_184

**Comment by YmNIK13** [comment]
А гражданину то зачем это знать, мы ведь его забиваем/редактируем в атрибутах 
SubjectOrganJoinAttribute.csv

Или я что-то не то понял?

**Comment by smoktii-igov** [comment]
Или редактировать на юзер-таске? Но мне этот вариант не очень нравится...
На чем лучше остановится , @Koffeek? 
@YmNIK13 sShapka уже заполнена другими данными. Нужна отдельная переменная

**Comment by smoktii-igov** [comment]
Получено подтверждение от координатора, выставлено в РЕЛИЗ
