### ISSUE TITLE
Чернігів - Надання довідки про перебування на обліку громадян, які потребують відповідно до законодавства поліпшення житлових умов

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#478]
Послуги надає “Управління квартирного обліку та приватизації житлового фонду Чернігівської міської ради"

Контактні дані держслужбовця
Булах Тетяна Анатоліївна  ukopgf_cmr@meta.ua
0462 675-421
Аккаунт вже створено 
Логін та пароль - BulahTA.

Потрібно активувати послуги для міста Чернігів

**Comment by julyprodan** [comment]
на боевом
