### ISSUE TITLE
Чернігів - Видача довідки про встановлення режиму роботи об’єкта

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#480]
Відповідальна особа : Піскун Марина Андріївна;
Електронна адреса : mega-uspp@ukr.net
0462 67-28-83

Послуги надає “Управління споживчого ринку та підприємництва Чернігівської міської ради"

**Comment by smoktii-igov** [comment]
Видача довідки про встановлення режиму роботи об’єкта
dndz_cnap_193
Взял в обработку и рефакторинг

**Comment by smoktii-igov** [comment]
На примере Днепродзержинска по сути услуга "Видача довідки про встановлення режиму роботи об’єкта" является "Погодження режиму роботи об’єктів торгівлі та сфери послуг". Раскрою и попробую согласовать внедрение

**Comment by smoktii-igov** [comment]
Чернигов
Инфокарта https://drive.google.com/drive/folders/0By7kquTZG1v3bTZxWld2ZFZWUmc
Інформаційний лист-заява https://drive.google.com/drive/folders/0By7kquTZG1v3bTZxWld2ZFZWUmc

**Comment by smoktii-igov** [comment]
dnepr_cnap_529_mode_worktime_chernigov

**Comment by smoktii-igov** [comment]
Выставлено в РЕЛИЗ
