### ISSUE TITLE
Чернігів -  Звернення громадян до Управління житлового господарства міської ради

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#481]
Відповідальна особа : 
	
	Булавко Людмила Вікторівна
	gkxmr@ukr.net
	0634882160

Послуги надає “Управління житлово-комунального господарства Чернігівської міської ради”

**Comment by vdubyna** [comment]
Потрібно прибрати з форми наступні поля:
1. Район Вашого проживання
2. Зверніть увагу

**Comment by msvidran** [comment]
@vdubyna 
А всі теми зверення підійшли?

**Comment by vdubyna** [comment]
Так, по темам норм

**Comment by msvidran** [comment]
https://igov.org.ua/service/1450/general
