### ISSUE TITLE
Миргород - Видача копій, витягів з розпоряджень міського голови, рішень, прийнятих міською радою та виконавчим комітетом

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#482]
С уважением прошу активировать услугу - Видача копій, витягів з розпоряджень міського голови, рішень, прийнятих міською радою та виконавчим комітетом #369
Тестирование прошло нормально.
координатор групи - Олександр Слємзін
пошта - slemzin@gmail.com

**Comment by smoktii-igov** [comment]
Уже давно в РЕЛИЗе
