### ISSUE TITLE
Дніпропетровська область - Передача земельної ділянки у власність, постійне користування або оренду, що перебуває у державній або комунальній власності

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#483]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [ ] Дніпродзержинськ
- [ ] Нікополь
- [ ] Орджонікідзе
- [ ] Першотравенськ
- [ ] Синельниківський р-н
- [ ] Широківський р-н

Процес створювати чи рефакторити з використанням SubjectOrganJoinAttribute (атрибути будуть заведені централізовано на всі райони - окремо їх створювати не потрібно) та використанням уніфікованних змінних:
sNameOrgan
sWorkTime
sPhoneOrgan
sAddress
sMailClerk
sArea
nArea
sShapka
nID_Department_visitDay

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

**Comment by Koffeek** [comment]
Уже есть 3 отдельных услуги для Кузнецовска (kuznetsovsk_mvk-319or, kuznetsovsk_mvk-319v, kuznetsovsk_mvk-319pk) там особенность в том, что кроме ЦНАПа есть отдельный кабинет для землераспорядителя, который может отказать без подачи проекта на сессию.

**Comment by agerman-ua** [comment]
[Днепродзержинск-в користування.docx](https://github.com/e-government-ua/iBP/files/209937/-.docx)
[Днепродзержинск-в_оренду.docx](https://github.com/e-government-ua/iBP/files/209934/-._.docx)
[Днепродзержинск-у власність.docx](https://github.com/e-government-ua/iBP/files/209938/-.docx)

[Ордж-заява про  надання зд в пост.корист.,власність,оренду-7.docx](https://github.com/e-government-ua/iBP/files/209939/-.-7.docx)
[Ордж-Рішення щодо передачі у власність, користування, в оренду з.docx](https://github.com/e-government-ua/iBP/files/209940/-.docx)

Т.к. в наличии варианты с тремя/одной услугами по данному ишью решено реализовывать тремя услугами (легче искать человеку, разные ситуации).

**Comment by agerman-ua** [comment]
Объединили данный ишью с #504

**Comment by Akylish88** [comment]
https://igov.org.ua/service/126/general
https://igov.org.ua/service/127/general
https://igov.org.ua/service/128/general
на боевом

**Comment by annastolbova** [comment]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [ ] Вільногірськ
- [ ] Жовті Води
- [ ] Павлоград
- [ ] Тернівка
- [ ] Криворізький р-н

Закрити на наступні міста/регіони:

- [ ] Синельниківський р-н
- [ ] Широківський р-н

**Comment by Akylish88** [comment]
расскрыл и закрыл
