### ISSUE TITLE
Дніпропетровська область - Рішення про продаж земельних ділянок державної та комунальної власності

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#484]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [ ] Дніпродзержинськ
- [ ] Марганець
- [ ] Нікополь
- [ ] Новомосковськ
- [ ] Орджонікідзе
- [ ] Першотравенськ
- [ ] Синельникове
- [ ] Синельниківський р-н

Процес створювати чи рефакторити з використанням SubjectOrganJoinAttribute (атрибути будуть заведені централізовано на всі райони - окремо їх створювати не потрібно) та використанням уніфікованних змінних:
sNameOrgan
sWorkTime
sPhoneOrgan
sAddress
sMailClerk
sArea
nArea
sShapka
nID_Department_visitDay

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

**Comment by Akylish88** [comment]
https://igov.org.ua/service/1472/general Новий на бойовому.

**Comment by annastolbova** [comment]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [ ] Жовті Води
- [ ] Павлоград
- [ ] Криворізький р-н

Закрити на наступні міста/регіони:

- [ ] Синельниківський р-н

**Comment by Akylish88** [comment]
Расскрыл и закрыл.
