### ISSUE TITLE
Дніпропетровська область - Висновок державної санітарно-епідеміологічної експертизи діючих об’єктів

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#485]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [x] Дніпродзержинськ
- [x] Дніпропетровськ
- [x] Нікополь
- [x] Орджонікідзе
- [x] Нікопольський р-н
- [x] Петропавлівський р-н

Процес створювати чи рефакторити з використанням SubjectOrganJoinAttribute (атрибути будуть заведені централізовано на всі райони - окремо їх створювати не потрібно) та використанням уніфікованних змінних:
sNameOrgan
sWorkTime
sPhoneOrgan
sAddress
sMailClerk
sArea
nArea
sShapka
nID_Department_visitDay

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

**Comment by zolotovatatyana** [comment]
https://igov.org.ua/service/1398/general на боевом

**Comment by annastolbova** [comment]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [ ] Жовті Води
- [ ] Марганець
- [ ] Новомосковськ
- [ ] Павлоград
- [ ] Першотравенськ
- [ ] Васильківський р-н
- [ ] Верхньодніпровський р-н
- [ ] Криворізький р-н
- [ ] Криничанський р-н
- [ ] Межівський р-н
- [ ] Новомосковський р-н
- [ ] Павлоградський р-н
- [ ] Покровський р-н
- [ ] Синельниківський р-н
- [ ] Солонянський р-н
- [ ] Томаківський р-н
- [ ] Широківський р-н
- [ ] Юр’ївський р-н

**Comment by zolotovatatyana** [comment]
на боевом
