### ISSUE TITLE
Дніпропетровська область - Дозвіл (санітарний паспорт) на право експлуатації рентгенівського кабінету (зберігання та експлуатації пересувних і переносних (палатних) рентгенівських апаратів) лікувально-профілактичних закладів

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#486]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [x] Дніпродзержинськ
- [x] Павлоград
- [x] Синельникове
- [x] Павлоградський р-н
- [x] Синельниківський р-н
- [x] Юр’ївський р-н

Процес створювати чи рефакторити з використанням SubjectOrganJoinAttribute (атрибути будуть заведені централізовано на всі райони - окремо їх створювати не потрібно) та використанням уніфікованних змінних:
sNameOrgan
sWorkTime
sPhoneOrgan
sAddress
sMailClerk
sArea
nArea
sShapka
nID_Department_visitDay

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

**Comment by zolotovatatyana** [comment]
https://igov.org.ua/service/156/general на боевом

**Comment by annastolbova** [comment]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [ ]  Жовті Води
- [ ]  Марганець
- [ ]  Новомосковськ
- [ ]  Орджонікідзе
- [ ]  Нікополь
- [ ]  Першотравенськ
- [ ]  Васильківський р-н
- [ ]  Магдалинівський р-н
- [ ]  Межівський р-н
- [ ]  Нікопольський р-н
- [ ]  Петропавлівський р-н
- [ ]  Солонянський р-н
- [ ]  Царичанський р-н

Закрити на наступні міста/регіони:

- [ ]  Павлоградський р-н

**Comment by zolotovatatyana** [comment]
на боевом
