### ISSUE TITLE
Дніпропетровська область - Поновлення договору оренди земельної ділянки

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#487]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [ ] Новомосковськ
- [ ] Орджонікідзе
- [ ] Синельникове
- [ ] Петриківський р-н
- [ ] Широківський р-н

Процес створювати чи рефакторити з використанням SubjectOrganJoinAttribute (атрибути будуть заведені централізовано на всі райони - окремо їх створювати не потрібно) та використанням уніфікованних змінних:
sNameOrgan
sWorkTime
sPhoneOrgan
sAddress
sMailClerk
sArea
nArea
sShapka
nID_Department_visitDay

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

**Comment by Koffeek** [comment]
Есть подобные услуги уже для Кузнецовска и кажется Днепродзержинска.

**Comment by Akylish88** [comment]
https://github.com/e-government-ua/iBP/issues/500 Совмещено.

**Comment by Akylish88** [comment]
Реализовано https://igov.org.ua/service/790/general
