### ISSUE TITLE
Дніпропетровська область - Взяття на облік громадян, які потребують поліпшення житлових умов

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#488]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [x] Марганець
- [x] Нікополь
- [x] Павлоград
- [x] Першотравенськ

Процес створювати чи рефакторити з використанням SubjectOrganJoinAttribute (атрибути будуть заведені централізовано на всі райони - окремо їх створювати не потрібно) та використанням уніфікованних змінних:
sNameOrgan
sWorkTime
sPhoneOrgan
sAddress
sMailClerk
sArea
nArea
sShapka
nID_Department_visitDay

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

**Comment by agerman-ua** [comment]
Из Никополя прислали бланк заявления. 
Отличается от имеющегося на портале. Нужно проанализировать и либо изменить либо прокоммуницировать чтобы приняли имеющееся.
[22. ЗАЯВА на постановку на кварт.облік.docx](https://github.com/e-government-ua/iBP/files/193196/22.docx)
Контакт в шапке ишью.

**Comment by YmNIK13** [comment]
Проведен рефакторинг ранее БП под разделение справок от каждого отдельного члена семьи. 
Добавлена единая принтформа 
для Никополя ([строки](https://docs.google.com/document/d/1tOs-Zt2tKcGtSghrzQCs9KIKOzj_qgrlrJ-FQhtv--U/edit?usp=sharing)) и для Хмельницкого ([табличка](https://docs.google.com/document/d/19K0RWMAHB1IZ6CSe2J6Ioihf80SGTvEl71UWJD4M4lA/edit?usp=sharing))

Принтформа единая, переключается флагом **sFalgNikolaevOda2** из атрибутов, по умолчанию стоит значение **normal**, для переключение на табличную добавляем флаг **sFalgNikolaevOda2 ** со значением **hard**

**Comment by YmNIK13** [comment]
Відкрито на бойовому
https://igov.org.ua/service/17/general

тостові заявки опрацьовані
