### ISSUE TITLE
Дніпропетровська область - Видача дозволу на переобладнання і перепланування жилого будинку (жилого приміщення)

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#489]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [x] Вільногірськ
- [x] Жовті Води
- [x] Марганець
- [x] Першотравенськ

Процес створювати чи рефакторити з використанням SubjectOrganJoinAttribute (атрибути будуть заведені централізовано на всі райони - окремо їх створювати не потрібно) та використанням уніфікованних змінних:
sNameOrgan
sWorkTime
sPhoneOrgan
sAddress
sMailClerk
sArea
nArea
sShapka
nID_Department_visitDay

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

**Comment by agerman-ua** [comment]
Выложено на альфу. готово к бете.
