### ISSUE TITLE
Дніпропетровська область - Внесення змін до договору оренди землі

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#490]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [ ] Кривий Ріг
- [ ] Нікополь
- [ ] Орджонікідзе
- [ ] Межівський р-н

Процес створювати чи рефакторити з використанням SubjectOrganJoinAttribute (атрибути будуть заведені централізовано на всі райони - окремо їх створювати не потрібно) та використанням уніфікованних змінних:
sNameOrgan
sWorkTime
sPhoneOrgan
sAddress
sMailClerk
sArea
nArea
sShapka
nID_Department_visitDay

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

**Comment by Akylish88** [comment]
https://igov.org.ua/service/1481/general новий процесс на бойовому
