### ISSUE TITLE
Дніпропетровська область - Декларація відповідності матеріально-технічної бази суб’єкта господарювання вимогам законодавства

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#491]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [x] Дніпродзержинськ
- [x] Нікополь
- [x] Орджонікідзе
- [x] Межівський р-н

Процес створювати чи рефакторити з використанням SubjectOrganJoinAttribute (атрибути будуть заведені централізовано на всі райони - окремо їх створювати не потрібно) та використанням уніфікованних змінних:
sNameOrgan
sWorkTime
sPhoneOrgan
sAddress
sMailClerk
sArea
nArea
sShapka
nID_Department_visitDay

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

**Comment by zolotovatatyana** [comment]
https://igov.org.ua/service/719/general на боевом с 15/04
