### ISSUE TITLE
Хмельницький - Обстеження умов проживання громадян/Обстеження умов проживання дитини - нова послуга

### ISSUE THREAD

**Issue by plyacik** [e-government-ua/iBP#494]
оцифрувати нову послугу, одна Інф карта на 2 послуги
Координатор Эльза Витишина [https://www.facebook.com/elya.vityshyna?fref=ts](https://www.facebook.com/elya.vityshyna?fref=ts)	380673803243 zlataelya@gmail.com
Посадовець:
1. Малінковська Олена Володимирівна cnap32@rada.khmelnytsky.com 380672831292
2. Онищук Наталя Володимирівна cnap35@rada.khmelnytsky.com
[Обстеження умов проживання громадян.docx](https://github.com/e-government-ua/iBP/files/173721/default.docx)

**Comment by GrekD** [comment]
@plyacik  прошу протестувати
https://test.igov.org.ua/service/231/general

**Comment by plyacik** [comment]
@GrekD Протестували, підключайте в боєвий

**Comment by GrekD** [comment]
https://igov.org.ua/service/231/general
на бойовому
