### ISSUE TITLE
Хмельницький - Надання фізичній особі повної цивільної дієздатності - нова

### ISSUE THREAD

**Issue by plyacik** [e-government-ua/iBP#495]
оцифрувати нову послугу
Координатор Эльза Витишина https://www.facebook.com/elya.vityshyna?fref=ts 380673803243 zlataelya@gmail.com
Посадовець:
1. Малінковська Олена Володимирівна cnap32@rada.khmelnytsky.com 380672831292
2. Онищук Наталя Володимирівна cnap35@rada.khmelnytsky.com

[Надання фізичній особі повної цивільної дієздатності.docx](https://github.com/e-government-ua/iBP/files/173748/default.docx)

**Comment by GrekD** [comment]
@plyacik прошу протестувати
https://test.igov.org.ua/service/230/general

**Comment by plyacik** [comment]
@GrekD можна запускати в боєвий портал

**Comment by GrekD** [comment]
https://igov.org.ua/service/230/general
на боевом
