### ISSUE TITLE
Полтава - розкрити три послуги для ОДА

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#496]
- [x] Записатись на прийом до посадовця	Ночовний Олег Володимирович	zvg@adm-pl.gov.ua
- [x] Запит на отримання публічної інформації	Синягівська Ольга Василівна	zpi@adm-pl.gov.ua
- [x] Звернення до голови ОДА(або звернення до ОДА) НочовнийОлег Володимирович	zvg@adm-pl.gov.ua

координатор групи - Юлія Городчаніна 
пошта - Yuliya.bobur@gmail.com
телефон - (068) 159-84-43
фейсбук - https://www.facebook.com/yuliya.bobir

**Comment by Koffeek** [comment]
Запит на отримання публічної інформації, Звернення до голови ОДА уже на боевом, по Записатись на прийом до посадовця нужны небольшие правки (тема обращения, результат встречи) и можно будет выставить

**Comment by julyprodan** [comment]
на боевом
