### ISSUE TITLE
Дніпропетровська область - Продовження (поновлення) договору оренди земельної ділянки

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#500]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [ ] Дніпродзержинськ
- [ ] Марганець
- [ ] Нікополь
- [ ] Петриківський р-н

Процес створювати чи рефакторити з використанням SubjectOrganJoinAttribute (атрибути будуть заведені централізовано на всі райони - окремо їх створювати не потрібно) та використанням уніфікованних змінних:
sNameOrgan
sWorkTime
sPhoneOrgan
sAddress
sMailClerk
sArea
nArea
sShapka
nID_Department_visitDay

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

**Comment by Akylish88** [comment]
Идентична №487

**Comment by Akylish88** [comment]
https://github.com/e-government-ua/iBP/issues/487 реализовано https://igov.org.ua/service/790/general
