### ISSUE TITLE
Затвердження технічної документації із землеустрою щодо встановлення (відновлення) меж земельної ділянки (на місцевості) у власність для ведення товарного сільськогосподарського виробництва

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#502]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [ ] Кривий Ріг
- [ ] Криворізький р-н
- [ ] Солонянський р-н

Процес створювати чи рефакторити з використанням SubjectOrganJoinAttribute (атрибути будуть заведені централізовано на всі райони - окремо їх створювати не потрібно) та використанням уніфікованних змінних:
sNameOrgan
sWorkTime
sPhoneOrgan
sAddress
sMailClerk
sArea
nArea
sShapka
nID_Department_visitDay

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

**Comment by Akylish88** [comment]
Кривий ріг нема зв'язку. Криворізький і Солонянський р-н повідомили що такої послуги не надають.
