### ISSUE TITLE
Дніпропетровська область - Надання згоди на перенесення поховання

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#503]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [x] Жовті Води
- [x] Орджонікідзе
- [x] Синельникове

Процес створювати чи рефакторити з використанням SubjectOrganJoinAttribute (атрибути будуть заведені централізовано на всі райони - окремо їх створювати не потрібно) та використанням уніфікованних змінних:
sNameOrgan
sWorkTime
sPhoneOrgan
sAddress
sMailClerk
sArea
nArea
sShapka
nID_Department_visitDay

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

**Comment by msvidran** [comment]
**ЦНАП м. Жовті Води**
[Заява] (http://e-services.dp.gov.ua/_layouts/WordViewer.aspx?id=/Lists/List/Attachments/6219/%D0%97%D1%80%D0%B0%D0%B7%D0%BE%D0%BA+%D0%B7%D0%B0%D1%8F%D0%B2%D0%B8+%D0%BD%D0%B0+%D0%BF%D0%B5%D1%80%D0%B5%D0%BD%D0%B5%D1%81%D0%B5%D0%BD%D0%BD%D1%8F+%D0%BF%D0%BE%D1%85%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F.doc)
[Інфо-карта] (http://e-services.dp.gov.ua/_layouts/WordViewer.aspx?id=/Lists/List/Attachments/6219/%D0%86%D0%9A%D0%90%D0%9F+%D0%BD%D0%B0%D0%B4+%D0%BF%D0%BE%D0%B3%D0%BE%D0%B4%D0%B6+%D0%BD%D0%B0+%D0%BF%D0%B5%D1%80%D0%B5%D0%BF%D0%BE%D1%85%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F.doc)

**Comment by msvidran** [comment]
в бою https://igov.org.ua/service/1456/general
