### ISSUE TITLE
Дніпропетровська область - Переведення житлового приміщення у нежитлове

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#505]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [x] Вільногірськ
- [x] Дніпродзержинськ
- [x] Марганець

Процес створювати чи рефакторити з використанням SubjectOrganJoinAttribute (атрибути будуть заведені централізовано на всі райони - окремо їх створювати не потрібно) та використанням уніфікованних змінних:
sNameOrgan
sWorkTime
sPhoneOrgan
sAddress
sMailClerk
sArea
nArea
sShapka
nID_Department_visitDay

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

**Comment by GrekD** [comment]
на боевом

**Comment by annastolbova** [comment]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [ ] Першотравенськ
- [ ] Тернівка
- [ ] Юр’ївський р-н

**Comment by GrekD** [comment]
на тестовом розкрила

**Comment by GrekD** [comment]
на боевом
