### ISSUE TITLE
Дніпропетровська область - Погодження питань щодо спеціального використання природних ресурсів місцевого значення, клопотань про надання надр у користування з метою геологічного вивчення, розробки родовищ корисних копалин місцевого значення

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#506]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [ ] Дніпродзержинськ - існує два варіанта цієї послуги для цього населеного пункту
- [ ] Жовті Води

Процес створювати чи рефакторити з використанням SubjectOrganJoinAttribute (атрибути будуть заведені централізовано на всі райони - окремо їх створювати не потрібно) та використанням уніфікованних змінних:
sNameOrgan
sWorkTime
sPhoneOrgan
sAddress
sMailClerk
sArea
nArea
sShapka
nID_Department_visitDay

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

**Comment by Akylish88** [comment]
Ця послуга вже не надається.
