### ISSUE TITLE
Дніпропетровська область - Видача довідки про перебування на квартирному обліку або іншого документа, що підтверджує необхідність поліпшення житлових умов

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#510]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [ ] Марганець
- [ ] Першотравенськ

Процес створювати чи рефакторити з використанням SubjectOrganJoinAttribute (атрибути будуть заведені централізовано на всі райони - окремо їх створювати не потрібно) та використанням уніфікованних змінних:
sNameOrgan
sWorkTime
sPhoneOrgan
sAddress
sMailClerk
sArea
nArea
sShapka
nID_Department_visitDay

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

**Comment by julyprodan** [comment]
услуга для Першотравенска и Марганца - на бою
