### ISSUE TITLE
Дніпропетровська область - Експлуатаційний дозвіл для потужностей (об’єктів): з переробки неїстівних продуктів тваринного походження; з виробництва, змішування та приготування кормових добавок, преміксів і кормів

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#512]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [x] Дніпродзержинськ
- [x] Нікопольський р-н

Процес створювати чи рефакторити з використанням SubjectOrganJoinAttribute (атрибути будуть заведені централізовано на всі райони - окремо їх створювати не потрібно) та використанням уніфікованних змінних:
sNameOrgan
sWorkTime
sPhoneOrgan
sAddress
sMailClerk
sArea
nArea
sShapka
nID_Department_visitDay

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

**Comment by zolotovatatyana** [comment]
@Akylish88  тестировать с ДнДз

**Comment by zolotovatatyana** [comment]
https://igov.org.ua/service/151/general

**Comment by annastolbova** [comment]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [ ] Жовті Води
- [ ]  Марганець
- [ ]  Новомосковськ
- [ ]  Орджонікідзе
- [ ]  Павлоград
- [ ]  Першотравенськ
- [ ] Васильківський р-н
- [ ]  Верхньодніпровський р-н
- [ ] Криворізький р-н
- [ ] Магдалинівський р-н
- [ ]  Межівський р-н
- [ ]  Новомосковський р-н
- [ ]  Павлоградський р-н
- [ ] Петропавлівський р-н
- [ ] Синельниківський р-н
- [ ]  Солонянський р-н
- [ ] Царичанський р-н
- [ ]  Широківський р-н
- [ ]  Юр’ївський р-н

**Comment by zolotovatatyana** [comment]
на боевом
