### ISSUE TITLE
Дніпропетровська область - Експлуатаційний дозвіл операторам потужностей (об’єктів), що здійснюють виробництво харчових продуктів, підконтрольних ветеринарній службі, та для агропродовольчих ринків

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#513]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [x] Дніпродзержинськ
- [x] Нікопольський р-н

Процес створювати чи рефакторити з використанням SubjectOrganJoinAttribute (атрибути будуть заведені централізовано на всі райони - окремо їх створювати не потрібно) та використанням уніфікованних змінних:
sNameOrgan
sWorkTime
sPhoneOrgan
sAddress
sMailClerk
sArea
nArea
sShapka
nID_Department_visitDay

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

**Comment by zolotovatatyana** [comment]
@Akylish88  тестировать с ДнДз

**Comment by zolotovatatyana** [comment]
https://igov.org.ua/service/152/general

**Comment by annastolbova** [comment]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [ ] Дніпропетровськ
- [ ] Жовті Води
- [ ] Марганець
- [ ] Нікополь
- [ ] Новомосковськ
- [ ] Павлоград
- [ ] Першотравенськ
- [ ] Тернівка
- [ ] Васильківський р-н
- [ ] Верхньодніпровський р-н
- [ ] Криворізький р-н
- [ ] Криничанський р-н
- [ ] Межівський р-н
- [ ] Новомосковський р-н
- [ ] Павлоградський р-н
- [ ] Петропавлівський р-н
- [ ] Синельниківський р-н
- [ ] Солонянський р-н
- [ ] Томаківський р-н
- [ ] Царичанський р-н
- [ ] Широківський р-н
- [ ] Юр’ївський р-н

**Comment by zolotovatatyana** [comment]
от: Наталія Ковбаса tsar.alternatyva@gmail.com На даний час проходить реорганізація ветеринарної служби, яка закінчиться в травні 2016. (27/04 15:32)

**Comment by zolotovatatyana** [comment]
на боевом
