### ISSUE TITLE
Дніпропетровська область - Затвердження проекту землеустрою щодо визначення розмірів та встановлення меж водоохоронної зони та прибережної захисної смуги водотоку

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#515]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [ ] Кривий Ріг
- [ ] Криворізький р-н

Процес створювати чи рефакторити з використанням SubjectOrganJoinAttribute (атрибути будуть заведені централізовано на всі райони - окремо їх створювати не потрібно) та використанням уніфікованних змінних:
sNameOrgan
sWorkTime
sPhoneOrgan
sAddress
sMailClerk
sArea
nArea
sShapka
nID_Department_visitDay

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

**Comment by Akylish88** [comment]
https://igov.org.ua/service/1479/instruction на боевом. Но мной упущено "як це працюэ" будет добавлено при следующей заливке. На альфу добавил.
