### ISSUE TITLE
Дніпропетровська область - Затвердження технічної документації із землеустрою щодо складання документа, що посвідчує право користування зем. ділянкою, та надання в користування (оренду) зем. ділянки, межі якої встановлено в натурі (на місцевості) без зміни її цільового призначення

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#516]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [ ] Орджонікідзе
- [ ] Синельникове

Процес створювати чи рефакторити з використанням SubjectOrganJoinAttribute (атрибути будуть заведені централізовано на всі райони - окремо їх створювати не потрібно) та використанням уніфікованних змінних:
sNameOrgan
sWorkTime
sPhoneOrgan
sAddress
sMailClerk
sArea
nArea
sShapka
nID_Department_visitDay

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

**Comment by msvidran** [comment]
**Синелькове**
[Заява](https://drive.google.com/a/privatbank.ua/file/d/0B6hKo-clAKYgY3lLSDA4U2ZVWHRjT2NXM2FJVmFNNGhvX0o4/view?usp=sharing)
[Інфо-карта_1](https://drive.google.com/a/privatbank.ua/file/d/0B6hKo-clAKYgbFdfMXQ5MTZINFBhT08xZlFQUU5DekpKTzBr/view?usp=sharing)
[Інфо-карта_2](https://drive.google.com/a/privatbank.ua/file/d/0B6hKo-clAKYgVmNsWWVXbkt4ZEVTaWNuaGxNaVFZYnNJOHpV/view?usp=sharing)
[Інфо-карта_3](https://drive.google.com/a/privatbank.ua/file/d/0B6hKo-clAKYgY3lLSDA4U2ZVWHRjT2NXM2FJVmFNNGhvX0o4/view?usp=sharing)

**Comment by Akylish88** [comment]
Это передача в оренду юр лицу или в пользование физлицу.

**Comment by Akylish88** [comment]
Совмещено с ишью № 504 
Разбито на 2 услуги № 127, 128
