### ISSUE TITLE
Дніпропетровська область - Надання дозволу на експлуатацію об’єкту поводження з небезпечними відходами

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#517]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [ ] Орджонікідзе
- [ ] Нікопольський р-н

Процес створювати чи рефакторити з використанням SubjectOrganJoinAttribute (атрибути будуть заведені централізовано на всі райони - окремо їх створювати не потрібно) та використанням уніфікованних змінних:
sNameOrgan
sWorkTime
sPhoneOrgan
sAddress
sMailClerk
sArea
nArea
sShapka
nID_Department_visitDay

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

**Comment by annastolbova** [comment]
Нікопольский район не надає цю послугу

---------- Переслане повідомлення ----------
Від: Наталя Гордієнко <cnap_nikrda@ukr.net>
Дата: 4 квітня 2016 р. о 17:50
Тема: Re: запит на інфо-карти
Кому: Anna Stolbova <insanniyou@gmail.com>

НІ, ми цю послугу не надаємо через ЦНАП

**Comment by annastolbova** [comment]
---------- Переслане повідомлення ----------
Від: <clochkovskaya.inna@ukr.net>
Дата: 5 квітня 2016 р. о 08:00
Тема: Орджонікідзе
Кому: Anna Stolbova <insanniyou@gmail.com>

Така послуга не надається

**Comment by julyprodan** [comment]
Така послуга не надається
