### ISSUE TITLE
Дніпропетровська область - Надання дозволу на розроблення технічної документації із землеустрою щодо встановлення (оновлення) меж земельної ділянки в натурі (на місцевості) у власність для ведення товарного сільськогосподарського виробництва

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#518]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [ ] Кривий Ріг
- [ ] Криворізький р-н

Процес створювати чи рефакторити з використанням SubjectOrganJoinAttribute (атрибути будуть заведені централізовано на всі райони - окремо їх створювати не потрібно) та використанням уніфікованних змінних:
sNameOrgan
sWorkTime
sPhoneOrgan
sAddress
sMailClerk
sArea
nArea
sShapka
nID_Department_visitDay

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

**Comment by Akylish88** [comment]
http://e-services.dp.gov.ua/_Layouts/Information/pgCardServices.aspx?ID=7042&TypeAg=0&Territory=513%200&IsV=1

**Comment by Akylish88** [comment]
https://igov.org.ua/service/1392/general на боевом
