### ISSUE TITLE
Дніпропетровська область - Надання дозволу релігійним організаціям на проведення релігійних заходів, які проводяться поза межами культових споруд

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#519]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [x] Дніпродзержинськ
- [x] Дніпропетровськ

Процес створювати чи рефакторити з використанням SubjectOrganJoinAttribute (атрибути будуть заведені централізовано на всі райони - окремо їх створювати не потрібно) та використанням уніфікованних змінних:
sNameOrgan
sWorkTime
sPhoneOrgan
sAddress
sMailClerk
sArea
nArea
sShapka
nID_Department_visitDay

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

**Comment by Koffeek** [comment]
На боевом уже несколько месяцев. При необходимости можно рефакторить.

**Comment by Akylish88** [comment]
https://test.igov.org.ua/service/96/general Уже есть

**Comment by annastolbova** [comment]
внезапно еще надо открыть на

- [ ] Тернівка

**Comment by Akylish88** [comment]
ВНЕЗАПНО, раскрыл и рефакторил.

**Comment by Akylish88** [comment]
https://test.igov.org.ua/service/96/general
