### ISSUE TITLE
Дніпропетровська область - Рішення міської ради про надання дозволу на розробку технічної документації із землеустрою щодо встановлення (відновлення) меж земельної ділянки

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#523]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [ ] Вільногірськ
- [ ] Нікополь

Процес створювати чи рефакторити з використанням SubjectOrganJoinAttribute (атрибути будуть заведені централізовано на всі райони - окремо їх створювати не потрібно) та використанням уніфікованних змінних:
sNameOrgan
sWorkTime
sPhoneOrgan
sAddress
sMailClerk
sArea
nArea
sShapka
nID_Department_visitDay

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

**Comment by Akylish88** [comment]
Расскрыто https://igov.org.ua/service/1392/general
