### ISSUE TITLE
Дніпропетровська область - Рішення про внесення змін до рішення міської ради

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#524]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [ ] Марганець
- [ ] Нікополь

Процес створювати чи рефакторити з використанням SubjectOrganJoinAttribute (атрибути будуть заведені централізовано на всі райони - окремо їх створювати не потрібно) та використанням уніфікованних змінних:
sNameOrgan
sWorkTime
sPhoneOrgan
sAddress
sMailClerk
sArea
nArea
sShapka
nID_Department_visitDay

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

**Comment by smoktii-igov** [comment]
Марганець: В переліку послуг, що надаються через ЦНАП м.Марганця вищезазначені послуги не надаються, в звязку з чим інформаційні картки на дані послуги відсутні! (ответ 6.04.2016)

 Нікополь: https://github.com/e-government-ua/iBP/issues/527

**Comment by smoktii-igov** [comment]
Выставлено в релиз после подтверждения 22-04-2016
