### ISSUE TITLE
Дніпропетровська область - Рішення про надання дозволу на розробку проекту землеустрою щодо відведення земельної ділянки

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#526]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [ ] Вільногірськ
- [ ] Нікополь

Процес створювати чи рефакторити з використанням SubjectOrganJoinAttribute (атрибути будуть заведені централізовано на всі райони - окремо їх створювати не потрібно) та використанням уніфікованних змінних:
sNameOrgan
sWorkTime
sPhoneOrgan
sAddress
sMailClerk
sArea
nArea
sShapka
nID_Department_visitDay

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

**Comment by annastolbova** [comment]
@Akylish88 
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [ ] Дніпродзержинськ
- [ ] Жовті Води
- [ ] Новомосковськ
- [ ] Орджонікідзе
- [ ] Павлоград
- [ ] Першотравенськ
- [ ] Синельникове
- [ ] Тернівка
- [ ] Криворізький р-н
- [ ] Межівський р-н
- [ ] Павлоградський р-н
- [ ] Юр’ївський р-н

**Comment by Akylish88** [comment]
На Дніпродзержинськ, Орджонікідзе, Павлоград, Криворізький р-н уже расскрыто

**Comment by Akylish88** [comment]
Расскрыто. Пока на альфе.
