### ISSUE TITLE
Дніпропетровська область - Рішення про розірвання договору оренди земельної ділянки або припинення права користування земельною ділянкою

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#528]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [ ] Марганець
- [x] Синельникове

Процес створювати чи рефакторити з використанням SubjectOrganJoinAttribute (атрибути будуть заведені централізовано на всі райони - окремо їх створювати не потрібно) та використанням уніфікованних змінних:
sNameOrgan
sWorkTime
sPhoneOrgan
sAddress
sMailClerk
sArea
nArea
sShapka
nID_Department_visitDay

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

**Comment by smoktii-igov** [comment]
Дубль
https://github.com/e-government-ua/iBP/issues/508
