### ISSUE TITLE
Дніпропетровська область - Рішення щодо узгодження режиму роботи об’єктів торгівлі та сфери послуг

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#529]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [x] Марганець
- [x] Першотравенськ

Процес створювати чи рефакторити з використанням SubjectOrganJoinAttribute (атрибути будуть заведені централізовано на всі райони - окремо їх створювати не потрібно) та використанням уніфікованних змінних:
sNameOrgan
sWorkTime
sPhoneOrgan
sAddress
sMailClerk
sArea
nArea
sShapka
nID_Department_visitDay

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

**Comment by smoktii-igov** [comment]
Погодження режиму роботи об’єктів сфери торгівлі, ресторанного господарства та сфери обслуговування населення незалежно від форм власності
https://test.igov.org.ua/service/667/general

ternopol_mvk_rezhym_roboty
nikolaev_oda_6
netishin_cnap_292
kuznetsovsk_mvk_5
Ивано-Франковск http://www.cnap.if.ua/posl/2887

Попробую обобщить...

**Comment by smoktii-igov** [comment]
Остановился на названии "Погодження режиму роботи об’єктів торгівлі та сфери послуг"

**Comment by smoktii-igov** [comment]
@Koffeek Считаю целесообразным заменить все вышеперечисленные процессы одним (за исключением внешних форвардов). Тем более, что в них используются старые подходы и несовершенная структура (майлтаски и т.д.). Однако это займет больше времени, чем простой рефакторинг одного БП (в том числе согласование с уже включенными оргструктурами). Прошу подтвердить, что в этих работах есть смысл и этим надо заняться

**Comment by Koffeek** [comment]
@msvidran Помоги, человеку, как автор большинства процессов.

**Comment by smoktii-igov** [comment]
Выставлено в РЕЛИЗ 06-05-2016
