### ISSUE TITLE
Дніпропетровська область - Розірвання договору оренди земельної ділянки або припинення права постійного користування земельною ділянкою

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#530]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [x] Дніпродзержинськ
- [x] Орджонікідзе

Процес створювати чи рефакторити з використанням SubjectOrganJoinAttribute (атрибути будуть заведені централізовано на всі райони - окремо їх створювати не потрібно) та використанням уніфікованних змінних:
sNameOrgan
sWorkTime
sPhoneOrgan
sAddress
sMailClerk
sArea
nArea
sShapka
nID_Department_visitDay

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

**Comment by smoktii-igov** [comment]
Орджонікідзе никак не протестирует. 
повторно отослано письмо для тестирования 17.04.2016, 
Отослано письмо 31-03-2016

**Comment by smoktii-igov** [comment]
Выставлено в РЕЛИЗ 06-05-2016
