### ISSUE TITLE
Дніпропетровська область - Спеціальний дозвіл на складування, розміщення, зберігання або транспортування промислових та побутових відходів, які є джерелами забруднення атмосферного повітря забруднюючими речовинами та речовинами з неприємним запахом або іншого шкідливого впливу

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#531]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [ ] Дніпродзержинськ - існує два варіанта цієї послуги для цього населеного пункту

Процес створювати чи рефакторити з використанням SubjectOrganJoinAttribute (атрибути будуть заведені централізовано на всі райони - окремо їх створювати не потрібно) та використанням уніфікованних змінних:
sNameOrgan
sWorkTime
sPhoneOrgan
sAddress
sMailClerk
sArea
nArea
sShapka
nID_Department_visitDay

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

**Comment by julyprodan** [comment]
не предоставляется
