### ISSUE TITLE
Хмельницький - Дозвіл на всі види досліджень та експериментальні роботи з мікроорганізмами ІІІ-IV групи патогенності (небезпеки) або матеріалом підозрілим на їх вміст (в т.ч. приватним лабораторіям) - розкриття

### ISSUE THREAD

**Issue by plyacik** [e-government-ua/iBP#538]
Підключити послуги в боєвий портал
Координатор Эльза Витишина https://www.facebook.com/elya.vityshyna?fref=ts 380673803243 zlataelya@gmail.com
Посадовець:
1. Малінковська Олена Володимирівна cnap32@rada.khmelnytsky.com 380672831292
2. Онищук Наталя Володимирівна cnap35@rada.khmelnytsky.com

**Comment by zolotovatatyana** [comment]
https://igov.org.ua/service/134/general на боевом
