### ISSUE TITLE
Хмельницький - Дозвіл на проведення діагностичних, експериментальних, випробувальних, вимірювальних робіт на підприємствах, в установах та організаціях, діяльність яких пов`язана з використанням джерел неіонізуючого випромінювання - Розкриття

### ISSUE THREAD

**Issue by plyacik** [e-government-ua/iBP#539]
Підключити послуги в боєвий портал
Координатор Эльза Витишина https://www.facebook.com/elya.vityshyna?fref=ts 380673803243 zlataelya@gmail.com
Посадовець:
1. Малінковська Олена Володимирівна cnap32@rada.khmelnytsky.com 380672831292
2. Онищук Наталя Володимирівна cnap35@rada.khmelnytsky.com

**Comment by zolotovatatyana** [comment]
https://igov.org.ua/service/135/general на боевом
