### ISSUE TITLE
Завести группы и пользователей для Днепропетровской области

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#540]
внести информацию в [файл](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

**Comment by agerman-ua** [comment]
Заведены все на тестовый (test.region.igov.org.ua/wf).

**Comment by agerman-ua** [comment]
Следующий шаг - заведение на боевой.

**Comment by agerman-ua** [comment]
Заявка-список для заведения на боевой
**Регион - группа - пользователь**
- [ ] Апостоловський район - cnap_apostol - apostol - apostol
- [ ] Васильківський район - cnap_vasil - vasil
- [ ] Верхньодніпровський район - cnap_verhdnepr - verhdnepr
- [ ] Вільногірськ - cnap_vilnogirskT - VilnogirskT
- [ ] Дніпропетровський район - cnap_dnepr - dnepr
- [ ] Жовті Води - cnap_zhvodT - zhvodT
- [ ] Кривий Ріг - cnap_krivorogT - krivorogT
- [ ] Криворізьський район - cnap_krivorog - krivorog
- [ ] Криничанський район - cnap_krinic - krinic
- [ ] Магдалинівський район - cnap_magdal - magdal
- [ ] Марганець - cnap_marganT - marganT
- [ ] Межівський район - cnap_meziv - meziv
- [ ] Нікополь - cnap_nikopolT - NikopolT
- [ ] Нікопольський район - cnap_nikopol - nikopol
- [ ] Новомосковськ - cnap_novomoskT - novomoskT
- [ ] Новомосковський район - cnap_novomosk - novomosk
- [ ] Орджонікідзе - cnap_ordzonikT - ordzonikT
- [ ] П’ятихатський район - cnap_piatihat - piatihat
- [ ] Павлоград - cnap_pavlogradT - pavlogradT
- [ ] Павлоградський район - cnap_pavlograd - pavlograd
- [ ] Першотравенськ - cnap_persotravT - persotravT
- [ ] Петриківській район - cnap_petrik - petrik
- [ ] Петропавівський район - cnap_petropavl - petropavl
- [ ] Покровський район - cnap_pokrov - pokrov
- [ ] Синельниківський район - cnap_sineln - sineln
- [ ] Синельниково - cnap_sinelnT - sinelnT
- [ ] Солонянський район - cnap_solon - solon
- [ ] Софіївський район - cnap_sofiiv - sofiiv
- [ ] Тернівка - cnap_ternT - ternT
- [ ] Томаківський район - cnap_tomak - tomak
- [ ] Царичанський район - cnap_carich -carich
- [ ] Широківський район - cnap_shirok - shirok
- [ ] Юр’ївський район - cnap_jurivsk - jurivsk

[файл с подробными данными](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit)
