### ISSUE TITLE
Хмельницький - Висновок державної санітарно-епідеміологічної експертизи щодо продукції, напівфабрикатів, речовин, матеріалів та небезпечних факторів, використання, передача або збут яких може завдати шкоду здоров’ю людей (крім харчових продуктів) - рефакторинг

### ISSUE THREAD

**Issue by plyacik** [e-government-ua/iBP#542]
нужно добавить поле 
Документи з країни-постачальника (виробника), що засвідчують безпечність об'єкта експертизи

Координатор Эльза Витишина https://www.facebook.com/elya.vityshyna?fref=ts 380673803243 zlataelya@gmail.com
Посадовець:
1. Малінковська Олена Володимирівна cnap32@rada.khmelnytsky.com 380672831292
2. Онищук Наталя Володимирівна cnap35@rada.khmelnytsky.com

[26.pdf](https://github.com/e-government-ua/iBP/files/177940/26.pdf)

**Comment by zolotovatatyana** [comment]
https://igov.org.ua/service/1407/general на боевом
