### ISSUE TITLE
Хмельницький - Висновок державної санітарно-епідеміологічної експертизи щодо ввезення, реалізації та використання сировини, продукції (вироби, обладнання, технологічні лінії тощо) іноземного виробн. за умови відсутності даних щодо їх безпечності для здоров’я населення (крім харчових продуктів) - рефакторинг

### ISSUE THREAD

**Issue by plyacik** [e-government-ua/iBP#543]
нужно добавить поле:
Методи контролю небезпечних факторів в обєктах експертизи

Координатор Эльза Витишина https://www.facebook.com/elya.vityshyna?fref=ts 380673803243 zlataelya@gmail.com
Посадовець:
1. Малінковська Олена Володимирівна cnap32@rada.khmelnytsky.com 380672831292
2. Онищук Наталя Володимирівна cnap35@rada.khmelnytsky.com
[24.pdf](https://github.com/e-government-ua/iBP/files/177942/24.pdf)

**Comment by zolotovatatyana** [comment]
https://igov.org.ua/service/1406/general на боевом
