### ISSUE TITLE
Хмельницький - Зняття одноповерхових приватизованих житлових будинків та квартир з балансу житлово-експлуатаційних контор - Нова

### ISSUE THREAD

**Issue by plyacik** [e-government-ua/iBP#544]
Розробити нову послугу
Координатор Эльза Витишина https://www.facebook.com/elya.vityshyna?fref=ts 380673803243 zlataelya@gmail.com
Посадовець:
1. Малінковська Олена Володимирівна cnap32@rada.khmelnytsky.com 380672831292
2. Онищук Наталя Володимирівна cnap35@rada.khmelnytsky.com
[РПо-19-04.docx](https://github.com/e-government-ua/iBP/files/177966/-19-04.docx)

**Comment by Akylish88** [comment]
https://test-delta.igov.org.ua/service/1501/general
Доступно для тестування. Це портал новий тестовий портал Дельта.
Вводіть при тестуванні свій телефон. Ходять СМС.

**Comment by Akylish88** [comment]
https://igov.org.ua/service/1501/general
На бойовому. В перспективі, вдосконалення щоб ЦНАп передавав в Управління ЖКГ документи в електронці.
