### ISSUE TITLE
Хмельницький - Проведення обстеження стану житлового фонду з метою встановлення його відповідності санітарним та технічним вимогам - нова

### ISSUE THREAD

**Issue by plyacik** [e-government-ua/iBP#545]
Розробити нову послугу
Координатор Эльза Витишина https://www.facebook.com/elya.vityshyna?fref=ts 380673803243 zlataelya@gmail.com
Посадовець:
1. Малінковська Олена Володимирівна cnap32@rada.khmelnytsky.com 380672831292
2. Онищук Наталя Володимирівна cnap35@rada.khmelnytsky.com
[РПо-19-05.docx](https://github.com/e-government-ua/iBP/files/177969/-19-05.docx)

**Comment by Akylish88** [comment]
https://igov.org.ua/service/1496/general
На бойовому. В перспективі, вдосконалення щоб ЦНАп передавав в Управління ЖКГ документи в електронці.
