### ISSUE TITLE
Хмельницький - Видача технічних умов на будівництво та реконструкцію зливової каналізації - нова

### ISSUE THREAD

**Issue by plyacik** [e-government-ua/iBP#546]
Розробити нову послугу
Координатор Эльза Витишина https://www.facebook.com/elya.vityshyna?fref=ts 380673803243 zlataelya@gmail.com
Посадовець:
1. Малінковська Олена Володимирівна cnap32@rada.khmelnytsky.com 380672831292
2. Онищук Наталя Володимирівна cnap35@rada.khmelnytsky.com
[РПо-19-06.docx](https://github.com/e-government-ua/iBP/files/177971/-19-06.docx)

**Comment by Akylish88** [comment]
https://igov.org.ua/service/1477/general на боевом
