### ISSUE TITLE
Хмельницький - Погодження на розміщення цирку - нова

### ISSUE THREAD

**Issue by plyacik** [e-government-ua/iBP#547]
Розробити нову послугу
Координатор Эльза Витишина https://www.facebook.com/elya.vityshyna?fref=ts 380673803243 zlataelya@gmail.com
Посадовець:
1. Малінковська Олена Володимирівна cnap32@rada.khmelnytsky.com 380672831292
2. Онищук Наталя Володимирівна cnap35@rada.khmelnytsky.com
[12-2-IK.pdf](https://github.com/e-government-ua/iBP/files/178041/12-2-IK.pdf)
[12-2-Z.docx](https://github.com/e-government-ua/iBP/files/178042/12-2-Z.docx)

**Comment by Akylish88** [comment]
Не перспективно. Пока в приоритете услуги заказываемые массово.
