### ISSUE TITLE
Хмельницький - Погодження на розміщення обєктів пересувної та дрібної стаціонарної мережі з надання послуг у сфері відпочинку та розваг - нова

### ISSUE THREAD

**Issue by plyacik** [e-government-ua/iBP#548]
Розробити нову послугу
Координатор Эльза Витишина https://www.facebook.com/elya.vityshyna?fref=ts 380673803243 zlataelya@gmail.com
Посадовець:
1. Малінковська Олена Володимирівна cnap32@rada.khmelnytsky.com 380672831292
2. Онищук Наталя Володимирівна cnap35@rada.khmelnytsky.com
[12-1-IK.pdf](https://github.com/e-government-ua/iBP/files/178045/12-1-IK.pdf)
[12-1-Z.docx](https://github.com/e-government-ua/iBP/files/178046/12-1-Z.docx)

**Comment by Akylish88** [comment]
https://test-delta.igov.org.ua/service/1502/general
Доступно для тестування. Це портал новий тестовий портал Дельта.
Вводіть при тестуванні свій телефон. Ходять СМС.

**Comment by Akylish88** [comment]
https://igov.org.ua/service/1502/general
На бойовому
