### ISSUE TITLE
Новопсков Луганська обл.Видача рішення про  передачу в оренду земельних ділянок   державної  власності

### ISSUE THREAD

**Issue by malietin** [e-government-ua/iBP#552]
Замовник - Малєтін Віктор
Skype - cluboz2 , v-maletin@mail.ru, т. 099 117 87 05, 093 563 58 66
для ЦНАП
![img185](https://cloud.githubusercontent.com/assets/17567307/13903949/3b3ff1f2-ee98-11e5-887d-5bceae569fa5.jpg)
![img186](https://cloud.githubusercontent.com/assets/17567307/13903952/3b4083e2-ee98-11e5-803e-c0a927a5702b.jpg)
![img187](https://cloud.githubusercontent.com/assets/17567307/13903950/3b4027a8-ee98-11e5-921f-6d5e51336ad1.jpg)
![img188](https://cloud.githubusercontent.com/assets/17567307/13903954/3b439500-ee98-11e5-8522-5c19a445e52c.jpg)
![img189](https://cloud.githubusercontent.com/assets/17567307/13903953/3b40cdde-ee98-11e5-825c-7e707883f539.jpg)
![img190](https://cloud.githubusercontent.com/assets/17567307/13903951/3b405188-ee98-11e5-8b2b-c730f80cb26f.jpg)
![img191](https://cloud.githubusercontent.com/assets/17567307/13903955/3b5951a6-ee98-11e5-9684-b798b1fc9563.jpg)
![img192](https://cloud.githubusercontent.com/assets/17567307/13903956/3b5968c6-ee98-11e5-992a-4ed6717191f2.jpg)

**Comment by Akylish88** [comment]
https://test-delta.igov.org.ua/service/127/general
https://test-delta.igov.org.ua/service/128/general
Раскрыл 2 эти услуги. Отправил на тест

**Comment by Akylish88** [comment]
Делаем только одну
https://test-delta.igov.org.ua/service/127/general

**Comment by Akylish88** [comment]
На боевом
https://igov.org.ua/service/127/general
