### ISSUE TITLE
Новопсков Луганська обл.Видача сертифіката на право на земельну частку (пай) 

### ISSUE THREAD

**Issue by malietin** [e-government-ua/iBP#556]
Замовник - Малєтін Віктор
Skype - cluboz2 , v-maletin@mail.ru, т. 099 117 87 05, 093 563 58 66
для ЦНАП
![img209](https://cloud.githubusercontent.com/assets/17567307/13904237/70990366-eea2-11e5-967a-7ff9bec1f1ab.jpg)
![img210](https://cloud.githubusercontent.com/assets/17567307/13904238/709b1c82-eea2-11e5-931a-ab4f6d73cf8b.jpg)
![img211](https://cloud.githubusercontent.com/assets/17567307/13904239/709bd2b2-eea2-11e5-9348-913ab70f5fa9.jpg)
![img212](https://cloud.githubusercontent.com/assets/17567307/13904240/70a15250-eea2-11e5-80ec-06a4f94f5dc0.jpg)
![img213](https://cloud.githubusercontent.com/assets/17567307/13904241/70a24156-eea2-11e5-852c-99f3c8e7905d.jpg)

**Comment by Akylish88** [comment]
Сертификаті вероятно не відаются уже. Изучаю закон.

**Comment by Akylish88** [comment]
https://igov.org.ua/service/1505/general
На бойовому
