### ISSUE TITLE
Новопсков Луганська обл.Видача дубліката сертифіката на право на земельну частку (пай) взамін втраченого

### ISSUE THREAD

**Issue by malietin** [e-government-ua/iBP#557]
Замовник - Малєтін Віктор
Skype - cluboz2 , v-maletin@mail.ru, т. 099 117 87 05, 093 563 58 66
для ЦНАП
![img214](https://cloud.githubusercontent.com/assets/17567307/13904287/cce1272e-eea3-11e5-8d2e-4cb75655d324.jpg)
![img215](https://cloud.githubusercontent.com/assets/17567307/13904289/cce78862-eea3-11e5-89c0-6dacc4559f7f.jpg)
![img216](https://cloud.githubusercontent.com/assets/17567307/13904288/cce75162-eea3-11e5-9836-2adea3859ebf.jpg)
![img217](https://cloud.githubusercontent.com/assets/17567307/13904290/cce7ab80-eea3-11e5-9e77-e98a02ffdcb1.jpg)
![img218](https://cloud.githubusercontent.com/assets/17567307/13904291/cceafe84-eea3-11e5-9e8e-13d7d1bcfe4c.jpg)

**Comment by Akylish88** [comment]
Сертификаті вероятно не відаются уже. Изучаю закон.

**Comment by Akylish88** [comment]
На боевом
https://igov.org.ua/service/1505/general
