### ISSUE TITLE
Звернення до голови Комсомольської районної ради у м. Херсоні

### ISSUE THREAD

**Issue by Kylikpavel** [e-government-ua/iBP#562]
Стерлюс Ірина Олександрівна – головний спеціаліст-координатор відділу призначення державних допомог,
Кулакова Любов Віліївна – головний спеціаліст-інформатор відділу призначення державних допомог
вул. Суворова, 29, м. Херсон, Херсонська область, 73000
(0552) 22-96-81
komsomol2007@ukr.net

Координатор Павел Кулик kylikpavel@ukr.net

**Comment by julyprodan** [comment]
@Kylikpavel  добрий день! Чи вдалоося Вам протестувати?

**Comment by Kylikpavel** [comment]
Добрый день, я не получал пароль и логин для тестування !!!)))

**Comment by julyprodan** [comment]
на kylikpavel@ukr.net відправляла 10.05.2016 у 16:50.

**Comment by julyprodan** [comment]
@Kylikpavel продублировать или Вы нашли?

**Comment by Kylikpavel** [comment]
Я просил изменить название Комсомольский на Корабельный )))

**Comment by julyprodan** [comment]
@Kylikpavel  https://test.igov.org.ua/service/479/general 
пароли/пользователи прежние

**Comment by julyprodan** [comment]
Павел, Вы смотрели ?

**Comment by Kylikpavel** [comment]
Доброе утро, смотрел. Можем запускать! Прошу меня простить не успеваю(((

**Comment by julyprodan** [comment]
на боевом
