### ISSUE TITLE
ЦНАП - Дніпропетровськ Декларація відповідності матеріально-технічної бази роботодавця вимогам законодавства з питань охорони праці та промислової безпеки

### ISSUE THREAD

**Issue by dmitrijzabrudskij** [e-government-ua/iBP#57]
кто предоставляет: Територіальне управління Держгірпромнагляду у Дніпропетровській області

декларація: https://dl.dropboxusercontent.com/u/91233927/%D0%A6%D0%9D%D0%90%D0%9F/%D0%98%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B5%20%D0%BA%D0%B0%D1%80%D1%82%D0%BE%D1%87%D0%BA%D0%B8%20%D0%B8%20%D0%B1%D0%BB%D0%B0%D0%BD%D0%BA%D0%B8%20%D0%B7%D0%B0%D1%8F%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F%20%D1%87.3/175/%D0%94%D0%95%D0%9A%D0%9B%D0%90%D0%A0%D0%90%D0%A6%D0%86%D0%AF%20%28%D0%B1%D0%BB%D0%B0%D0%BD%D0%BA%29.doc

перелік робіт:  https://dl.dropboxusercontent.com/u/91233927/%D0%A6%D0%9D%D0%90%D0%9F/%D0%98%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B5%20%D0%BA%D0%B0%D1%80%D1%82%D0%BE%D1%87%D0%BA%D0%B8%20%D0%B8%20%D0%B1%D0%BB%D0%B0%D0%BD%D0%BA%D0%B8%20%D0%B7%D0%B0%D1%8F%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F%20%D1%87.3/175/%D0%9F%D0%B5%D1%80%D0%B5%D0%BB%D1%96%D0%BA%20%D0%B2%D0%B8%D0%B4%D1%96%D0%B2%20%D1%80%D0%BE%D0%B1%D1%96%D1%82%20%D0%BF%D1%96%D0%B4%D0%B2%D0%B8%D1%89%D0%B5%D0%BD%D0%BE%D1%97%20%D0%BD%D0%B5%D0%B1%D0%B5%D0%B7%D0%BF%D0%B5%D0%BA%D0%B8.doc

перелік машин: https://dl.dropboxusercontent.com/u/91233927/%D0%A6%D0%9D%D0%90%D0%9F/%D0%98%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B5%20%D0%BA%D0%B0%D1%80%D1%82%D0%BE%D1%87%D0%BA%D0%B8%20%D0%B8%20%D0%B1%D0%BB%D0%B0%D0%BD%D0%BA%D0%B8%20%D0%B7%D0%B0%D1%8F%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F%20%D1%87.3/175/%D0%9F%D0%B5%D1%80%D0%B5%D0%BB%D1%96%D0%BA%20%D0%BC%D0%B0%D1%88%D0%B8%D0%BD%2C%20%D0%BC%D0%B5%D1%85%D0%B0%D0%BD%D1%96%D0%B7%D0%BC%D1%96%D0%B2%2C%20%D1%83%D1%81%D1%82%D0%B0%D1%82%D0%BA%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F%20%D0%BF%D1%96%D0%B4%D0%B2%D0%B8%D1%89%D0%B5%D0%BD%D0%BE%D1%97%20%D0%BD%D0%B5%D0%B1%D0%B5%D0%B7%D0%BF%D0%B5%D0%BA%D0%B8.doc

інформаційна картка: https://dl.dropboxusercontent.com/u/91233927/%D0%A6%D0%9D%D0%90%D0%9F/%D0%98%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B5%20%D0%BA%D0%B0%D1%80%D1%82%D0%BE%D1%87%D0%BA%D0%B8%20%D0%B8%20%D0%B1%D0%BB%D0%B0%D0%BD%D0%BA%D0%B8%20%D0%B7%D0%B0%D1%8F%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F%20%D1%87.3/175/%D0%A0%D0%B5%D0%B3%D0%BB%D0%B0%D0%BC%D0%B5%D0%BD%D1%82%20%28%D1%96%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D1%96%D0%B9%D0%BD%D0%B0%20%D0%BA%D0%B0%D1%80%D1%82%D0%BA%D0%B0%29%20%2821%29.pdf

**Comment by NizhnikAlex** [comment]
Как работает:
1. ссылка на Альфе https://test.igov.org.ua/service/115/general

**Comment by NizhnikAlex** [comment]
Произошел глобальный рефакторинг БП. На данный момент услуга не предоставляется.
