### ISSUE TITLE
 Звернення до голови Дніпровської районної ради у м.Херсоні

### ISSUE THREAD

**Issue by Kylikpavel** [e-government-ua/iBP#575]
Гузь Оксана Інтигамівна, головний спеціаліст з інформаційно-аналітичного забезпечення	 Звернення до голови районної ради	вул. Перекопська,166, каб.300,
м. Херсон, Херсонська область, 73000	(0552) 35-43-45
(0552) 51-98-69	drik@ukr.net

Координатор Павел Кулик kylikpavel@ukr.net

**Comment by julyprodan** [comment]
на боевом
