### ISSUE TITLE
Комінтернівська РДА - розкриття земельних послуг (на 1.04.2016)

### ISSUE THREAD

**Issue by Kylikpavel** [e-government-ua/iBP#589]
по запуску уведомить координатора
Координатор проекта iGov в Одессе
+38 050 49 59 799 (там же Viber, Telegram, WhatsApp)
+38 063 23 67 527
i@royur.com
skype: iroyur 
facebook.com/iroyur

- [ ] Надання відомостей з Державного земельного кадастру у формі витягу з Державного земельного кадастру про обмеження у використанні земель
- [ ] Надання відомостей з Державного земельного кадастру у формі викопіювань з кадастрової карти (плану) та іншої картографічної документації Державного земельного кадастру
- [ ] Надання відомостей з Державного земельного кадастру у формі довідки, що містить узагальнену інформацію про землі (території)

ДАННЫЕ ПО ЦНАПУ
Адреса : Одеська область , Комінтернівський район смт Комінтернівське вул.Центральна , 69 
e-mail : admin_kom@ukr.net 
Контактний телефон : 04855-9-84-48 , 04855-9-17-82  (для всех услуг)
Viber :+380982813035
facebook: www.facebook.com/Центр-Надання-Адміністративних-Послуг-Комінтернівського-Району-502120189942386/?ref=aymt_homepage_panel
Сайт: http://komintern-rda.odessa.gov.ua/info/admnstrativn-poslugi/

Графік роботи : Понеділок , Вівторок , Середа , Четверг , Пятниця 
с 8-00 до 17-00 перерва на обід с 13-00 до 14-00 
Суббота с 09-00 до 15-00

Руководитель ЦНАПА:  Лобан Антон Анатолійович  (моб. +380674820735)
он же и администратор по нескольким услугам

**Comment by Akylish88** [comment]
https://test.igov.org.ua/service/47/general
https://test.igov.org.ua/service/48/general
https://test.igov.org.ua/service/45/general

Раскрыто 3 услуги.
