### ISSUE TITLE
ЦНАП - Дніпропетровськ Декларація відповідності матеріально-технічної бази суб’єкта господарювання вимогам законодавства

### ISSUE THREAD

**Issue by dmitrijzabrudskij** [e-government-ua/iBP#59]
кто предоставляет: Головне управління Держсанепідслужби у Дніпропетровській області

декларація: https://dl.dropboxusercontent.com/u/91233927/%D0%A6%D0%9D%D0%90%D0%9F/%D0%98%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B5%20%D0%BA%D0%B0%D1%80%D1%82%D0%BE%D1%87%D0%BA%D0%B8%20%D0%B8%20%D0%B1%D0%BB%D0%B0%D0%BD%D0%BA%D0%B8%20%D0%B7%D0%B0%D1%8F%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F%20%D1%87.3/178/%D0%94%D0%B5%D0%BA%D0%BB%D0%B0%D1%80%D0%B0%D1%86%D1%96%D1%8F%20%D0%B2%D1%96%D0%B4%D0%BF%D0%BE%D0%B2%D1%96%D0%B4%D0%BD%D0%BE%D1%81%D1%82%D1%96%20%D0%BC%D0%B0%D1%82%D0%B5%D1%80%D1%96%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE-%D1%82%D0%B5%D1%85%D0%BD%D1%96%D1%87%D0%BD%D0%BE%D1%97%20%D0%B1%D0%B0%D0%B7%D0%B8%20%28%D0%A1%D0%95%D0%A1%29%20%282%29.doc

перелік дій 1: https://dl.dropboxusercontent.com/u/91233927/%D0%A6%D0%9D%D0%90%D0%9F/%D0%98%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B5%20%D0%BA%D0%B0%D1%80%D1%82%D0%BE%D1%87%D0%BA%D0%B8%20%D0%B8%20%D0%B1%D0%BB%D0%B0%D0%BD%D0%BA%D0%B8%20%D0%B7%D0%B0%D1%8F%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F%20%D1%87.3/178/%D0%9F%D0%B5%D1%80%D0%B5%D0%BB%D1%96%D0%BA%20%D0%BF%D0%B5%D0%B2%D0%BD%D0%B8%D1%85%20%D0%B4%D1%96%D0%B9%2C%20%D1%8F%D0%BA%D1%96%20%D0%BD%D0%B5%20%D0%BC%D0%BE%D0%B6%D1%83%D1%82%D1%8C%20%D0%BF%D1%80%D0%BE%D0%B2%D0%B0%D0%B4%D0%B8%D1%82%D0%B8%D1%81%D1%8F%20%D0%BD%D0%B0%20%D0%BF%D1%96%D0%B4%D1%81%D1%82%D0%B0%D0%B2%D1%96%20%D0%94%D0%B5%D0%BA%D0%BB%D0%B0%D1%80%D0%B0%D1%86%D1%96%D1%97%20%281%29.doc

перелік дій 2: https://dl.dropboxusercontent.com/u/91233927/%D0%A6%D0%9D%D0%90%D0%9F/%D0%98%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B5%20%D0%BA%D0%B0%D1%80%D1%82%D0%BE%D1%87%D0%BA%D0%B8%20%D0%B8%20%D0%B1%D0%BB%D0%B0%D0%BD%D0%BA%D0%B8%20%D0%B7%D0%B0%D1%8F%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F%20%D1%87.3/178/%D0%9F%D0%B5%D1%80%D0%B5%D0%BB%D1%96%D0%BA%20%D0%BF%D0%B5%D0%B2%D0%BD%D0%B8%D1%85%20%D0%B4%D1%96%D0%B9%2C%20%D1%8F%D0%BA%D1%96%20%D0%BD%D0%B5%20%D0%BC%D0%BE%D0%B6%D1%83%D1%82%D1%8C%20%D0%BF%D1%80%D0%BE%D0%B2%D0%B0%D0%B4%D0%B8%D1%82%D0%B8%D1%81%D1%8F%20%D0%BD%D0%B0%20%D0%BF%D1%96%D0%B4%D1%81%D1%82%D0%B0%D0%B2%D1%96%20%D0%94%D0%B5%D0%BA%D0%BB%D0%B0%D1%80%D0%B0%D1%86%D1%96%D1%97%20%282%29.doc

інформмаційна картка: https://dl.dropboxusercontent.com/u/91233927/%D0%A6%D0%9D%D0%90%D0%9F/%D0%98%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B5%20%D0%BA%D0%B0%D1%80%D1%82%D0%BE%D1%87%D0%BA%D0%B8%20%D0%B8%20%D0%B1%D0%BB%D0%B0%D0%BD%D0%BA%D0%B8%20%D0%B7%D0%B0%D1%8F%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F%20%D1%87.3/178/%D0%A0%D0%B5%D0%B3%D0%BB%D0%B0%D0%BC%D0%B5%D0%BD%D1%82%20%28%D1%96%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D1%96%D0%B9%D0%BD%D0%B0%20%D0%BA%D0%B0%D1%80%D1%82%D0%BA%D0%B0%29%20%2823%29.pdf

**Comment by NizhnikAlex** [comment]
Не актуально. Субъект не оказывает услугу

**Comment by NizhnikAlex** [comment]
Запущено 29.09.2015
На альфе https://test.igov.org.ua/service/719/general
На бете https://test-version.igov.org.ua/service/719/general (пока не пролита)
На боевом https://igov.org.ua/service/719/general

1. Гражданин выбирает г. Днепропетрвск, идентифицируется при помощи БанкИД или ЭЦП (не проверялось).
2. Заполняет обязательные поля/
3. Заявка попадает в ЦНАП, заявитель получает письма (приветствие и с номером), администраторы ЦНАП получают письмо о новой заявке.
4. Администраторы ознакамливаются с присланной информацией. Принимают решение передавать ли декларацию дальше. Могут распечатать заполненную принт-форму декларации.
4а. Если присланных данных недостаточно, администратор выбирает соответствующий пунк выпадающего меню. По возможности - оставляет комментарий. Заявитель получает сообщение с отказом. Работа с декларацией окончена.
4б. Если данных хватает, администратор выбирает соответствующий пунк выпадающего меню, прикрепляет скан файла-описи принятых документов. Автоматом крепится копия заполненной декларации (в работе). Нажимает "обработать".
5. Заявитель получает письмо, администратор передает декларациюв службу.
6. Администратор получает ответ от службы о регистрации декларации или обоснованном отказе, снова берет заявку в работу. Прикрепляет этот ответ, нажимает "обработать".
7. Заявитель получает либо отказ, либо копию зарегистрированной декларации. Также на почту приходит приглашение прийти за оригиналом решения в выбранный ЦНАП.
