### ISSUE TITLE
ЧЕРНИГОВ: Несогласование атрибутов

### ISSUE THREAD

**Issue by smoktii-igov** [e-government-ua/iBP#591]
Обнаружил, что для 
Place.csv: 22;Чернігів;3;7410100000;
SubjectOrganJoin.csv: 1435;225;ЦНАП м. Чернігів;ЦОАУ г. Чернигов;chern_chernT;chern_chernT;;;NULL;NULL;7410100000

в SubjectOrganJoinAttribute.csv  

задана информация о горсовете, хотя атрибуты ЦНАПа. Потенциально опасная проблема!  
1409;1435;sShapka409;Управління квартирного обліку та<br>приватизації житлового фонду<br>Чернігівської міської ради
1410;1435;sPlase409;виконкомі Чернігівської міської ради

По идее необходимо переносить атрибуты на 
SubjectOrganJoin.csv: 1188;212;Відділ звернень Чернігівської міської ради;Отдел обращений Черниговского горсовета;mvk_chernT;mvk_chernT; ; ;NULL;NULL;7410100000

**Comment by julyprodan** [comment]
решено
