### ISSUE TITLE
Видача ліцензії на право роздрібної торгівлі алкогольними  напоями

### ISSUE THREAD

**Issue by Akylish88** [e-government-ua/iBP#592]
Налоговая Николаева

vladrakipov@rambler.ru
Влад Ракипов
063 945 23 40

**Comment by plyacik** [comment]
@Akylish88  Можливо цю послугу підключити в тест для Хмельницького
на пароль khmel_mvk_1  ???

**Comment by plyacik** [comment]
@Akylish88 В Хмельницькому погодились підключати послугу в боєвий
Координатор по Фіскальній - Ольга Паньковська - +380677140487 - pankovskaya@mail.ru - https://www.facebook.com/profile.php?id=100011112245135&fref=ts

Від держслужбовців - Уманець Олександр Володимирович
elzvit2225@ukr.net - (067) 370-22-27
тел. робочий -  (0382) 70-17-03
ДПІ у місті Хмельницькому, головного управління ДФС у Хмельницькій області
Понедельник-Четверг 9-00 - 18-15, Пятница 9-00 - 17-00, Суббота 9-00 - 16-00 (работает только ЦОП - центр обслуговування платників). Обед с 13 до 14.

**Comment by plyacik** [comment]
@Akylish88 доброго дня, Координатор по Фіскальній - Ольга Паньковська - +380677140487 - pankovskaya@mail.ru - https://www.facebook.com/profile.php?id=100011112245135&fref=ts
повідомила що для цієї послуги портібні були реквізити, надсилаю Вам:
р/р 33216825700002 отримувач: УК у м.Хмельницькому, код ЕДРПОУ 38045529 МФО 815013
Реквізити дійсні тільки для м.Хмельницького
Дякую!

**Comment by plyacik** [comment]
так точніше:
Плата за ліцензію на роздрібну торгівлю алкогольними та тютюновими виробами: 
Р/р 33216825700002
Одержувач: УК у м.Хмельницькому /м. Хмельницький/22011100
Ідентифікаційний код 38045529  
Банк одержувача: ГУДКСУ у Хмельницькій області м.Хмельницький 
МФО 815013 

В призначенні платежу: 
* ; 101 ; код платника ;  Плата за ліцензію на роздрібну торгівлю алкогольними та тютюновими виробами

22011100 - це код платежу

**Comment by Akylish88** [comment]
https://test-delta.igov.org.ua/service/1030/general
Реквизиты добавил на тестовый. В релиз уйдут в начале следующей недели.
