### ISSUE TITLE
Нетішин Хмельницька обл - Надання дозволу на відведення земельної ділянки в оренду

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#598]
Опрацьовувати їх буде та ж людина - начальник ЦНАПу Кушта Галина

Галина Кушта - начальник ЦНАП (їхня робоча пошта) 
cnap_netishyn@ukr.net 
neteshin_user1 - логин и пароль 
 
Олена Матросова (менеджер від iGov) 
olena.boichuk@gmail.com 
neteshin_user2 - логин и пароль 
 
Руслан Рудомський (менеджер від iGov) 
nebajduzhyj@gmail.com 
neteshin_user3 - логин и пароль

**Comment by Akylish88** [comment]
https://igov.org.ua/service/127/general
готово
