### ISSUE TITLE
Хмельницький - Надання одноразової матеріальної допомоги громадянам - Рефакторінг

### ISSUE THREAD

**Issue by plyacik** [e-government-ua/iBP#605]
При замовленні послуги при виборі установи що надає послугу відображає "ДПСНЗ Хмельницької ОДА", потрібно щоб відображало "УПСЗН Хмельницької Міськ.Ради"

Від волонтерів Пляцик Юрій https://www.facebook.com/yura.plyacik +380977299676
plyacik@gmail.com

Посадовець:
1. Веремчук Олег Борисович - verem225@gmail.com - 8(096)4672016
2. Кримовська Оксана Леонтівна - oksana_krm@ukr.net

**Comment by plyacik** [comment]
Дані по управлінню
Управління праці та соціального захисту населення Хмельницької міської ради
Поштова адреса:   29013, м.Хмельницький, вул.Проскурівського підпілля, 32
Приймальня (0382)79-59-59 Факс:  65-41-70
Електронна пошта: soczah_km@hm.ukrtel.net
офіційний сайт: www.soczahist.km.ua

**Comment by Koffeek** [comment]
@plyacik Изначально был разговор о том, что услуга открывается для ОДА, потому так и писали. Данные исправлены, услуга переоткрыта на город. Если надо чтобы была также область, напишите. пожалуйста.

**Comment by plyacik** [comment]
@Koffeek ой ой, вибачте, не розумію чому Управління Соц Захисту протестували цю послугу і скинули на мене звіт, я справді не звернув увагу що це послуга саме ОДА, я звірився з сайтом Управлінням Соц Захисту, вони не надають цю послугу, вибачте, просто держслужбовці скинули звіт що протестували цю послугу і потрібно доробити і я вже написав сюди, цю послугу надає ОДА, управління соц захисту не надає, вибачте

**Comment by Koffeek** [comment]
@plyacik Дивіться, ми можемо відкрити послугу і на місто і на область. Наразі я повертаю послугу на область, так як вона вже працювала. Якщо буде потрібно зробити те саме для міста - напишіть мені.
