### ISSUE TITLE
Хмельницьий - Призначення тимчасової державної допомоги дітям, батьки яких ухиляються від сплати аліментів, не мають можливості утримувати дитину або місце проживання їх невідоме - Розкриття

### ISSUE THREAD

**Issue by plyacik** [e-government-ua/iBP#609]
Підключити послуги в боєвий портал
Від волонтерів Пляцик Юрій https://www.facebook.com/yura.plyacik +380977299676
plyacik@gmail.com

Посадовець:
1. Веремчук Олег Борисович - verem225@gmail.com - 8(096)4672016
2. Кримовська Оксана Леонтівна - oksana_krm@ukr.net

**Comment by plyacik** [comment]
Дані по управлінню
Управління праці та соціального захисту населення Хмельницької міської ради
Поштова адреса:   29013, м.Хмельницький, вул.Проскурівського підпілля, 32
Приймальня (0382)79-59-59 Факс:  65-41-70
Електронна пошта: soczah_km@hm.ukrtel.net
офіційний сайт: www.soczahist.km.ua

**Comment by GrekD** [comment]
готово
