### ISSUE TITLE
Охтирський район Сумської області - Записатись на прийом до посадовця

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#612]
Призначена контактна особа
Шандиба Валентина Іванівна
телефон: (05446) 4-10-08
бажано на 050-039-77-31
ohtrda@gmail.com

Відповідальний за впровадження по Охтирському району (він і призначав відповідальних), начальник відділу з питань співробітництва та інвестицій Охтирської районної ради
Марченко Руслан, 066-3636148, ruslanmarchenko83@gmail.com

**Comment by julyprodan** [comment]
на боевом
