### ISSUE TITLE
Охтирський район Сумської області - Запит на отримання публічної інформації

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#613]
Призначена контактна особа
Шевченко Людмила Олексіївна
0662070515
телефон: (05446) 4-10-08

org_oht-rda@ukr.net

Відповідальний за впровадження по Охтирському району (він і призначав відповідальних), начальник відділу з питань співробітництва та інвестицій Охтирської районної ради
Марченко Руслан, 066-3636148, ruslanmarchenko83@gmail.com

**Comment by julyprodan** [comment]
на боевом
