### ISSUE TITLE
Охтирський район Сумської області - Отримання субсидії на оплату житлово-комунальних послуг  

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#614]
Призначена контактна особа
Калініченко Наталія Миколаївна
+38 095 8003931
телефон: (05446) 2-52-89
	
info11@upszn-sumy.gov.ua

Відповідальний за впровадження по Охтирському району (він і призначав відповідальних), начальник відділу з питань співробітництва та інвестицій Охтирської районної ради
Марченко Руслан, 066-3636148, ruslanmarchenko83@gmail.com

**Comment by zolotovatatyana** [comment]
раскрыто. проследить на появлением Охтырского района после релиза.

**Comment by zolotovatatyana** [comment]
Калініченко Наталія Миколаївна usznoht@gmail.com

**Comment by zolotovatatyana** [comment]
https://igov.org.ua/service/654/general на боевом с 15/04
