### ISSUE TITLE
Ужгород. Надання дозволу на влаштування автономного опалення.

### ISSUE THREAD

**Issue by UngvarIGov** [e-government-ua/iBP#618]
![17](https://cloud.githubusercontent.com/assets/18119838/14170887/a3b39a7e-f738-11e5-8ba5-0de0ef55f2b3.png)

Координатор Микола Лук'янчук
м. Ужгород
тел.: 050-939-95-78
e-mail -  9399578@gmail.com

[1нформ_картка_на дозвіл на ао.pdf](https://github.com/e-government-ua/iBP/files/197281/1._._.pdf)
[Заява_на_автономне опалення.pdf](https://github.com/e-government-ua/iBP/files/197282/_._.pdf)
[технолог1чна_картка_надання дозволу на ао.pdf](https://github.com/e-government-ua/iBP/files/197283/1._._.pdf)

**Comment by Akylish88** [comment]
https://test-delta.igov.org.ua/service/79/general
Готово для теста

**Comment by Akylish88** [comment]
https://igov.org.ua/service/1516/general
на бойовому, також чекаю пошту виконкому.
