### ISSUE TITLE
Дніпропетровська область - Запис на особистий прийом до керівника органу державної виконавчої служби

### ISSUE THREAD

**Issue by agerman-ua** [e-government-ua/iBP#619]
[Послуга 1 Запис на прийом.docx](https://github.com/e-government-ua/iBP/files/198056/1.docx)
[Графіки прийому громадян.xlsx](https://github.com/e-government-ua/iBP/files/198057/default.xlsx)

**Comment by dmitrijzabrudskij** [comment]
готовим услугу к релизу:
1. услуга раскрыта на всю днепропетровскую область
2. добавить в селект на форме все районы по области
3. завести под них очереди
4. добавить информацию о районе в имейл, который отправляем
5. убрать из имейла фразу о том, что "ответ придет в течение 1-3 дней" - записаться он может в любом случае
6. добавить в имейл кнопку отмены визита
7. в дашборде чиновника убрать селект со статусом и поле для комментария - они не нужны. (дашборд нужен для того, чтобы они могли подготовиться к визиту человека по его вопросу, который он пишет на старте)

**Comment by dmitrijzabrudskij** [comment]
данные районов для справочника: https://docs.google.com/spreadsheets/d/1byLeswt-KW60uSYKQkQVNv6aMr5kIo4vqD1RyLdQQ78/edit#gid=412697546

почта для отправки эскалации: info@dp.dvs.gov.ua

для этой и других услуг нужно выделить отдельную категорию "Виконавче провадження" (до того момента как мы перейдем к жизненным ситуациям)

**Comment by zolotovatatyana** [comment]
https://igov.org.ua/service/107/general
