### ISSUE TITLE
Киев МРЭО -  Копирование процессов для новых МРЭО

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/iBP#62]
https://test.igov.org.ua/service/159/general

Реализовать добавление копий процессов для новых МРЭО.
https://docs.google.com/document/d/1qsn4wFaLrwTPeKeyBJyATbQm0_AYHQK0ZoOLnZDjgGE/edit

**Comment by kurbpa** [comment]
Описание процесса.
1. Гражданн подает  заявление.

2. Гражданин получает на емейл уведомление, что его заявка зарегистрирована

3. Получает на емейл уведомление, что у него на обработке есть новая  заявка

4. Чиновник берет заявку  в работу. Проверяет наличие обременений.
* если нет обременений - чиновник прикрепляет  файл для оплаты гос.сбора за услугу. И гражданин получает его на емейл + адрес, где находится МРЭО
* если есть обременения, но машина не подлежит аресту - чиновник указывает в поле комменатариев причину отказа в предоставлении услуги. Гражданин получает информацию на емейл.
*  если  машна подлежит аресту, гражданин получает емейл с  указанием адреса МРЭО для  прохождения тех осмотра

5. Гражданин  приезжает на  тех.осмотр. Гослужащий берет заявку в работу и отмечает  повторно результат проверки на обременения (они могут  за день даже измениться) и отмечает результат тех.осмотра. Заявка уходит на проверку документов

6. Если ТО успешен, чиновник берет заявку в работу и ставит итог проверки оригиналов документов. Если всё ОК, заявка уходит на этап печати гос.номеров.

7. ЧИновник печатает гос.номера и фиксирует номер в заявке. 

Конец процесса.

**Comment by VadimGulich** [comment]
![image](https://cloud.githubusercontent.com/assets/12964120/9605052/068a2332-50c4-11e5-9844-c99e40f47131.png)

нет полей после входа через ИД Банк

**Comment by VadimGulich** [comment]
Нет возможности выбрать время (постоянно пустое поле на любую дату)
![image](https://cloud.githubusercontent.com/assets/12964120/9605616/75f3aa60-50c7-11e5-9a3e-fd1bcd059442.png)

**Comment by VadimGulich** [comment]
Верхние баги исправлены
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Ошибка в печатной форме, поле "Бажана дата тех.огляду авто" отображается не по феншую =): 
![image](https://cloud.githubusercontent.com/assets/12964120/9624180/e4018f5a-5152-11e5-8b8f-d0cffc8f79b8.png)

**Comment by VadimGulich** [comment]
Такая же дата приходит и на почту:

**Comment by dmitrijzabrudskij** [comment]
Паше: используй для этой даты переменную date_of_visit - туда автоматом тянется дата/время из тикета и отображается намного красивее, без закорлючек кода. можешь посмотреть как это сделано у меня в процессе dnepr_dms_passport

**Comment by kurbpa** [comment]
@VadimGulich  поправил отображание даты/времени визита в письмах.

**Comment by VadimGulich** [comment]
Исправлено ,БП работает корректно можно на боевой
