### ISSUE TITLE
Дніпропетровська область - Отримання інформації про хід виконавчого провадження

### ISSUE THREAD

**Issue by agerman-ua** [e-government-ua/iBP#620]
[Послуга 2 Інформація про хід ВП.docx](https://github.com/e-government-ua/iBP/files/198058/2.docx)

**Comment by agerman-ua** [comment]
https://trade.informjust.ua/vpdoc/getdoc.aspx
редирект сюда.

**Comment by dmitrijzabrudskij** [comment]
готовим услугу к релизу:
1. сделать услугу общенациональной

**Comment by zolotovatatyana** [comment]
https://igov.org.ua/service/76/general
