### ISSUE TITLE
Дніпропетровська область - Видача довідки про неотримання аліментів-розмір аліментів

### ISSUE THREAD

**Issue by agerman-ua** [e-government-ua/iBP#621]
[Послуга 3 Отримання довідки про аліменти.docx](https://github.com/e-government-ua/iBP/files/198059/3.docx)
[ЗАЯВКА ПРО ВИДАЧУ ДОВІДКИ ПРО РОЗМІР АЛІМЕНТІВ.docx](https://github.com/e-government-ua/iBP/files/198062/default.docx)
[ЗАЯВКА ПО ДОВІДКЕ ПО АЛІМЕНТАМ.docx](https://github.com/e-government-ua/iBP/files/198063/default.docx)

**Comment by dmitrijzabrudskij** [comment]
готовим услугу к релизу:
1. раскрыть на всю днепропетровскую область
2. добавить все районы в селект на форме (они будут такими же, как для процесса с записью на прием. группы тоже те же)
3. при выборе опции "про размер алиментов" нужно переделать блок с детьми:
- задавать вопрос о количестве детей (от 1 до 4)
- в зависимости от этого енума выводить правильное количество полей
4. добавить в имейл информацию о том, что в ответе прислана справка с наложенной эцп, которую они могут использовать для подачи заявки в соцзащиту (соцзащита, в свою очередь, будет такие справки принимать в работу). но в то же время они могут явиться за справкой лично
5. добавить в имейл информацию о районах (она есть в процессе по записи на прием)
6. написать инструкцию по работе чиновнику и "как это работает" для гражданина

**Comment by zolotovatatyana** [comment]
https://igov.org.ua/service/97/general
