### ISSUE TITLE
Дніпропетровська область - Отримання відомостей про платіжні реквізити

### ISSUE THREAD

**Issue by agerman-ua** [e-government-ua/iBP#622]
[Послуга 4 Платіжні реквізити.docx](https://github.com/e-government-ua/iBP/files/198066/4.docx)
[Платіжні реквізити.xlsx](https://github.com/e-government-ua/iBP/files/198067/default.xlsx)

**Comment by agerman-ua** [comment]
https://docs.google.com/document/d/1foIBzeJJ_VICWpPzyNrPzwLwIcpoKO74MBuSd-hmNbs/edit
Здесь по каждому органу ссылка на следующий файл
https://docs.google.com/document/d/1HlKflKS4JdvScHIFGSiooZh4hW9JR_VV0K_MdK7F4pY/edit?usp=sharing

**Comment by dmitrijzabrudskij** [comment]
таки нужно это сделать процессом: 
1. человек авторизируется
2. выбирает район 
3. ему на имейл уходит письмо с реквизитами для оплаты

**Comment by zolotovatatyana** [comment]
https://igov.org.ua/service/77/general
