### ISSUE TITLE
Дніпропетровська область - Зразки документів для звернення до органів державної виконавчої служби

### ISSUE THREAD

**Issue by agerman-ua** [e-government-ua/iBP#623]
[Послуга 5 Зразки документів.docx](https://github.com/e-government-ua/iBP/files/198069/5.docx)
[Типові форми заяв до послуги 5.docx](https://github.com/e-government-ua/iBP/files/198070/5.docx)

**Comment by dmitrijzabrudskij** [comment]
делаем услугу общенациональной и она готова к релизу

**Comment by zolotovatatyana** [comment]
https://igov.org.ua/service/78/general
