### ISSUE TITLE
Киевская область - Белая Церковь - соц.услуги (18 штук)-раскрытие

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#626]
координатор - Лаврусь Павел 
onechifu@gmail.com
380967663974

1. Отримання субсидії на оплату житлово-комунальних послуг. 
2. Призначення допомоги при народженні дитини. 
3. Видача довідок про отримання/неотримання усіх видів державних соціальних допомог. 
4. Видача посвідчень інвалідам з дитинства та дітям-інвалідам, особам, які не мають права на пенсію та інвалідам. 
5. Отримання інформації про призначення субсидії на оплату житлово-комунальних послуг. 
6. Призначення державної соціальної допомоги малозабезпеченим сім’ям.
7. Призначення державної соціальної допомоги інвалідам з дитинства та дітям-інвалідам віком до 18 років.
8. Призначення допомоги на дітей одиноким матерям.
9. Призначення допомоги на дітей, які перебувають під опікою чи піклуванням.
10. Призначення допомоги на дітей-сиріт та дітей, позбавлених батьківського піклування та грошового забезпечення прийомним батькам.
11. Призначення допомоги при усиновленні дитини.
12. Призначення допомоги у зв’язку з вагітністю та пологами.
13. Призначення компенсаційної виплати непрацюючій працездатній особі, яка доглядає за інвалідом І групи, а також за престарілим, який досяг 80-річного віку.
14. Призначення надбавки на догляд за інвалідом з дитинства або дитиною-інвалідом.
15. Призначення одноразової винагороди жінкам, яким присвоєно почесне звання «Мати-героїня».
16. Призначення соціальної допомоги особам, які не мають права на пенсію, та інвалідам.
17. Призначення тимчасової державної допомоги дітям, батьки яких ухиляються від сплати аліментів, не мають можливості утримувати дитину або місце проживання їх невідоме.
18. Призначення щомісячної грошової допомоги особі, яка проживає разом з інвалідом І чи ІІ групи внаслідок психічного розладу, який за висновком лікарської комісії медичного закладу потребує постійного стороннього догляду, на догляд за ним.

**Comment by GrekD** [comment]
на боевом
