### ISSUE TITLE
Житомир - в "Звернення до голови ОДА" добавить возможность обращения к заместителям главы ОДА

### ISSUE THREAD

**Issue by ezhikus** [e-government-ua/iBP#627]
Информация по заместителям главы ОДА - http://oda.zt.gov.ua/zvernennya-gromadyan/

**Comment by ezhikus** [comment]
Плохо тут то, что для данной услуги у нас имеется две принт-формы заявления - ternopil_oda_239zaj.html и mykol_oda_239zaj.html. Возможность выбирать одного из нескольких адресатов реализована только для mykol_oda_239zaj.html, но в Житомире нужно сделать принтформу, как ternopil_oda_239zaj.html, но с той же возможностью указания в шапке главы или одного из замов. 

Т.е. или делать третью форму, или перерабатывать ternopil_oda_239zaj.html, но это затронет и остальные области. Я сниму с себя задачу, поскольку её должен делать тот, кто обладает пониманием картины в целом, а не только по одной области.

**Comment by YmNIK13** [comment]
@ezhikus так а в чем проблема атрибуты для того и придумали.
Я правильно понял что надо сделать возможность выбрать одного из трех:
1. Голова обласної державної адміністрації - Машковський Сергій Олександрович
2. Перший заступник голови обласної державної адміністрації - Дмитренко Геннадій Васильович
3. Заступник голови обласної державної адміністрації - Лагута Ярослав Миколайович

У них один секретарь, который будет принимать заявки, или разные?

**Comment by ezhikus** [comment]
@YmNIK13 
Никаких проблем нет, атрибутами и надо сделать - просто я не знаю значения этих атрибутов для других областей (и надо ли им это вообще). А в Житомире да, надо для этих трёх сделать именно так, как Вы написали. Принимать будет один сотрудник ОДА, тот же, что и сейчас (т.е. изменения состава груп пользователей не нужно).

**Comment by YmNIK13** [comment]
@ezhikus 
В общем я реализовал то что вы просили, можете проверять.

У меня к вам просьба, я там еще добавил три формы с пометкой NEW, не могли бы вы их показать исполнителю. Особенно это касается регистрационных карт, они сделаны по последним изменения законодательства, правда делались они для РДА но на сколько я понял все обращения руководствуются одним законом (http://zakon3.rada.gov.ua/laws/show/348-97-%D0%BF). Пусть не обращают внимание на то, что данные не подтянулись это поправим, важна сама форма.

Просто есть идея все обращения(ОДА РДА меру и т.д.) свести к единому процессу и к единым формам с одинаковыми атрибутами, чтоб как только поменялся закон мы для всех одним махом делали рефакторинг. К тому же мне не очень нравится, как реализован процесс для ОДА - слабая обратная связь, тоесть человек дал запрос, вспомнят о нем или нет не известно

**Comment by ezhikus** [comment]
@YmNIK13 
По изначальной задаче (обращение к замам) - всё ок, можно выкладывать на боевой (буду благодарен, если скажете когда будет выложено)

По обратной связи - мне в ОДА объяснили, что они только принимают заявление, регистрируют и передают дальше. Они не владеют информацией кто же и когда рассмотрит его и даст ответ (это может быть некоторый отдел ОДА или вообще другой гос.орган). Поэтому как сюда прикрутить обратную связь - не ясно.

Новые формы покажу.

**Comment by YmNIK13** [comment]
@ezhikus 

>  Они не владеют информацией кто же и когда рассмотрит его и даст ответ 
Интересно получается, а как же тогда енум в какой форме получить ответ :)
И в карточке надо решение записать, а к карточке еще и журнал есть где должен быть статус решения. Чудеса и только.

**Comment by ezhikus** [comment]
@YmNIK13 
Энум в форме нужен чтобы на принтформе напечатать, как человек желает получить результат. Дальше распечатанное заявление уходит бродить по кабинетам а тот, кто его последним обрабатывает - смотрит, как отправить результат (по почте или на email).

А по поводу карточек - ОДА это не интересно, у них какой-то свой внутренний софт для этих карточек, и статусы они там тоже уже внутри выставляют\меняют.

**Comment by YmNIK13** [comment]
> А по поводу карточек - ОДА это не интересно, у них какой-то свой внутренний софт для этих карточек, и статусы они там тоже уже внутри выставляют\меняют.


Понятно. 

В общем изменения по зверненню до головы ОДА ушло в пятничный релиз

**Comment by ezhikus** [comment]
@YmNIK13 
Спасибо
