### ISSUE TITLE
Нежин - Черниговская область - звернення до міського голови - раскрытие

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#635]
и перевести на стандартные атрибуты весь процесс 
kuznetsovsk_mvk_2

контактное лицо:
Білоусенко Максим Валерійович
vvp_nezhin@ukr.net
Тел. 0683861750

протестировал этот же процесс на Чернигове, все подходит.

**Comment by julyprodan** [comment]
на боевом при ближайшем релизе. Тест прошел удачно
