### ISSUE TITLE
Тернопільська РДА - Експлуатаційний дозвіл операторам потужностей (об’єктів), що здійснюють виробництво харчових продуктів, підконтрольних ветеринарній службі, та для агропродовольчих ринків

### ISSUE THREAD

**Issue by zolotovatatyana** [e-government-ua/iBP#637]
Додати обробку звернення ветеринарною медициною.
Додати для вет.мед. принтформу  https://docs.google.com/document/d/1PrtRu6zJjZO6yfOsecIN8iV0sT4sO3kyu_vjooqSVzQ/edit?ts=5707b246

**Comment by sofiadanylevych** [comment]
https://docs.google.com/document/d/1ylFIOZFKmXH7pfHK7JKPw0r-irvigKY_WJv4W-mKWiQ/edit?usp=sharing

**Comment by zolotovatatyana** [comment]
https://igov.org.ua/service/152/general
