### ISSUE TITLE
Добавить на альфу - Видача листа-довідки на перевезення (перезахоронення) загиблого в зоні АТО

### ISSUE THREAD

**Issue by NizhnikAlex** [e-government-ua/iBP#64]
Имя файла: dnepr_cnap_41.bpmn
Город: Днепропетровск
Группа: dnepr_cnap_prav, dnepr_cnap_lev, dnepr_cnap_post
Услуга: Видача листа-довідки на перевезення (перезахоронення) загиблого в зоні АТО
Орган: АО Головне управління Держсанепідслужби у Дніпропетровській області

**Comment by kurbpa** [comment]
@NizhnikAlex готово
