### ISSUE TITLE
Житомир - звернення до міського голови

### ISSUE THREAD

**Issue by ezhikus** [e-government-ua/iBP#642]
Необходимо сделать так, чтобы принтформа данного заявления для Житомира выглядела "стандартым" образом - шапка заявления (кому, от кого, адрес, телефон, почта), дальше "Заява", в теле - тема и суть обращения, внизу дата и подпись. 

Для городов, где уже используется текущая принтформа (табличка со значениями полей) всё должно остаться, как есть. После обсуждения с @Koffeek было решено сделать это с помощью маркеров для динамических принтформ. Т.е. у нас будет один HTML-документ, в котором те или иные div'ы будут делаться видимыми в зависимости от региона.

**Comment by Koffeek** [comment]
Прошу обратить внимание на недавнюю смену имен переменных в процессе

**Comment by ezhikus** [comment]
Проверено на альфе, всё работает хорошо. Просьба создать пользователей, указанных вот здесь: https://github.com/e-government-ua/iBP/issues/326#issuecomment-212610991 и выложить услугу на боевой при следующем релизе.

**Comment by Koffeek** [comment]
@ezhikus пользователи по задаче добавлены

**Comment by julyprodan** [comment]
Переведена на боевые  флаги.

**Comment by ezhikus** [comment]
Проверено на боевом, работает.
