### ISSUE TITLE
Україна - Подання процесуальних документів для розгляду у відкритому апеляційному/касаційному провадженні

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#644]
[!Алгоритм_подача_проц_документов_ВХСУ.pdf](https://github.com/e-government-ua/iBP/files/214591/_._._._.pdf)
[Выдержка_инструкция_деловодство_хозсуды.pdf](https://github.com/e-government-ua/iBP/files/214594/_._._.pdf)
[СПРАВКА_документы_к_подаче_ВХСУ.pdf](https://github.com/e-government-ua/iBP/files/214593/_._._._.pdf)
[Техзадание_для_iGov_ВХСУ.pdf](https://github.com/e-government-ua/iBP/files/214592/_._iGov_.pdf)

**Comment by annastolbova** [comment]
Координаторы:
Днепр
Роман - poman1507@gmail.com - 0675239090
Екатерина - 	clarice.advocate@gmail.com - 0675391003

Киев
Алексей Куприенко  - kuprienk3@gmail.com - 0503204586

**Comment by GrekD** [comment]
на боевом
https://igov.org.ua/service/344/general
