### ISSUE TITLE
Отримання субсидії на оплату житлово-комунальних послуг - Машівська РДА - Полтавська обл.

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#645]
1. посадова особа суб’єкта надання послуг, що відповідає за подання та оновлення інформації, яка розміщується на порталі державних послуг iGov.org.ua (адміністратора суб’єкта надання послуги)

Бурмус Олексій Володимирович 095-184-93-64
farator4@gmail.com

2. суб’єкт надання послуг для розміщення її на порталі державних послуг iGov.org.ua

Сорока Олена Станіславівна, Elena.soroka.1985@mail.ru
095-460-71-04

[ДЕКЛАРАЦІЯ про доходи.docx](https://github.com/e-government-ua/iBP/files/217072/default.docx)
[ЗАЯВА про призначення житл.субс..docx](https://github.com/e-government-ua/iBP/files/217073/default.docx)
[Управл_ння прац_ та соц_ального захисту населення Маш_вської РДА.docx](https://github.com/e-government-ua/iBP/files/217074/_._._._.docx)

**Comment by zolotovatatyana** [comment]
на боевом
