### ISSUE TITLE
Присвоєння (уточнення) адрес будівлям і спорудам - Коломия - Івано-Франківська обл.

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#648]
координатор по городу 
Михайло Данищук
mishagamst@gmail.com
097 732 23 03

відповідальний за послугу
095 123 05 15 Юрій Васильович 
cnap_kol@ukr.net

![4 1_prusvoennya ytochn _adres_bydivlyam_i_sporydam 1](https://cloud.githubusercontent.com/assets/17762394/14524836/0afb96a4-0243-11e6-8243-a30e75f951fc.jpg)

![4 1_prusvoennya ytochn _adres_bydivlyam_i_sporydam 2](https://cloud.githubusercontent.com/assets/17762394/14524845/159bbbc0-0243-11e6-94a0-f0f6f7b59fef.jpg)

**Comment by GrekD** [comment]
замовнику на тест відправлено вже існуючий процес

**Comment by GrekD** [comment]
пока закрываю
