### ISSUE TITLE
Вернуть потерянные при мердже аттрибуты в SubjectOrganJoinAttribute.csv

### ISSUE THREAD

**Issue by ezhikus** [e-government-ua/iBP#649]
7-го апреля я добавил в SubjectOrganJoinAttribute.csv атрибут sShapkaGolova, необходимый для нескольких городов в ряде процессов. Меня интересовал только Житомир, но я добавил его для всех городов, для которых были включены соответствующие процессы. Вот этот комит:

https://github.com/e-government-ua/i/commit/80a684fe912f5097e32e3a056f8747524711ea1e

Вы можете видеть в нём строку (запомним её)
2872;1490;sShapkaGolova;Міському голові <br>м. Житомир

Далее следуют несколько событий, которые я не могу понять:

1. @YmNIK13 мержит в SubjectOrganJoinAttribute.csv свои правки, из-за которых у нас в файле получаются две строки с id 2872 (https://github.com/e-government-ua/i/blob/efacea5938fc22a28144bb3348b05c99a1515872/wf-central/src/main/resources/data/SubjectOrganJoinAttribute.csv)

2872;1143;sShapkaGolova;Міському голові<br>Філатову Б. А.
...
2872;1490;sShapkaGolova;Міському голові <br>м. Житомир

2. @zolotovatatyana делает несколько правок и мержит свои изменения в файл, при этом удаляя мой атрибут для Житомира вообще. Вот здесь его уже нет: https://github.com/e-government-ua/i/commit/1e79de9879eddf69bfe5174d3ffd163f5d6ef2fd#diff-a39f200232d317fa57d47d125ee0da89

В итоге получаем несколько сломанных услуг для Житомира.

Коллеги, @YmNIK13 , @zolotovatatyana - не могли бы вы перепроверить данные правки и, если это просто ошибка при мерже - вернуть мой атрибутик "2872;1490;sShapkaGolova;Міському голові <br>м. Житомир", а если это какой-то хитрый рефакторинг, которого я не понимаю, то объясните мне его.

Заранее спасибо.

P.S. Правка секундная, я мог бы и сам, но хотел привлечь внимание к той системной проблеме, что в данный момент у нас никак не контролируются случайные удаления используемых атрибутов, что расстраивает. Получается, нужно постоянно проверять, не удалили ли нужный атрибут для твоего города. В идеале нужен бы тест вида "если атрибут Х используется в процессах A, B, C городов X, Y, Z и эти процессы уже включены на боевом и атрибут был удалён - валить тест при билде". А иначе мы будем деплоить процессы со случайно удалёнными атрибутами.

**Comment by zolotovatatyana** [comment]
@ezhikus вашу потерянную строчку я добавила.

**Comment by YmNIK13** [comment]
@ezhikus 
этот хитрый рефакторинг называется "С атрибутами работаем в бете и мержим в альфу"
И очень плохо что вас не поставили в известность.

**Comment by YmNIK13** [comment]
Хотя меня сбило еще и то, что атрибуты были с одинаковым _sName_ и у меня и у вас

**Comment by ezhikus** [comment]
@zolotovatatyana Спасибо, работает.

@YmNIK13 "С атрибутами работаем в бете и мержим в альфу" - это было временно перед релизом, или теперь это постоянное правило? Есть ещё какие-то нюансы, о которых нужно знать?
