### ISSUE TITLE
Добавить на Альфу процессы

### ISSUE THREAD

**Issue by Koffeek** [e-government-ua/iBP#65]
Имя файла: dnepr_cnap_44.bpmn
Город: Днепропетровск
Группы: dnepr_cnap_44_lev и dnepr_cnap_44_prav
Услуга: Надання дозволу релігійним організаціям на проведення релігійних заходів, які проводяться поза межами культових споруд
Орган: Управління внутрішньої політики Дніпропетровської міської ради

Имя файла: ternopol_rcnap-9.bpmn
область: Тернополь
Группа: tern_rai_cnap1
Услуга: Надання витягу з технічної документації про нормативну грошову оцінку земельної ділянки
Орган: Управління Держгеокадастру

Имя файла: dnepr_cnap_50.bpmn
Город: Днепропетровск
Группы: dnepr_cnap_50
Услуга: Надання дозволу на виконання робіт підвищеної небезпеки
Орган: Територіальне управління Держгірпромнагляду

**Comment by kurbpa** [comment]
готово на альфу
