### ISSUE TITLE
Хмельницький - Надання дозволу на перепоховання останкiв померлих - Розкриття

### ISSUE THREAD

**Issue by plyacik** [e-government-ua/iBP#657]
Підключити послугу в боєвий портал, послуга вже відтестована
Координатор Эльза Витишина https://www.facebook.com/elya.vityshyna?fref=ts 380673803243 zlataelya@gmail.com
Посадовець:
1. Малінковська Олена Володимирівна cnap32@rada.khmelnytsky.com 380672831292
2. Онищук Наталя Володимирівна cnap35@rada.khmelnytsky.com

**Comment by msvidran** [comment]
@plyacik підключив на https://test.igov.org.ua/service/1456/general перевірте для Хмельницького, якщо все гаразд - в версію підключемо на боєвий.

**Comment by plyacik** [comment]
@msvidran протестили, підключайте в боєвий

**Comment by msvidran** [comment]
https://igov.org.ua/service/1456/general
