### ISSUE TITLE
Процесс на альфу

### ISSUE THREAD

**Issue by msvidran** [e-government-ua/iBP#66]
Имя файла: dnepr_cnap_42.bpmn
Город: Днепропетровск
Группа: dnepr_cnap_42_velykotonazhni
Услуга:  Відомча реєстрація великотоннажних та інших технологічних транспортних засобів, що не підлягають експлуатації на вулично-дорожній мережі загального користування
Орган: Територіальне управління Держгірпромнагляду у Дніпропетровській області

**Comment by kurbpa** [comment]
прописал для альфы
