### ISSUE TITLE
Аварійний дозвіл на проведення земляних робіт - Острог - Рівненська обл. - розкриття

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#664]
Контактное лицо - координатор - тестувати послуги з ним
 Сергій Галич - 21halich@gmail.com - 380961712728

От горсовета  Орленко Наталія Констянтинівна - 380679131024
Пошта ostrog_amu@ukr.net

**Comment by GrekD** [comment]
https://delta.test.igov.org.ua/service/724/general
на боевом
