### ISSUE TITLE
Надання дозволу на відведення земельної ділянки у власність - Острог - Рівненська область - розкриття

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#665]
Контактное лицо - координатор - тестувати послуги з ним
 Сергій Галич - 21halich@gmail.com - 380961712728

От горсовета  Орленко Наталія Констянтинівна - 380679131024
Пошта ostrog_amu@ukr.net

**Comment by Akylish88** [comment]
https://igov.org.ua/service/126/general на бойовому
