### ISSUE TITLE
Видача копій, витягів з розпоряджень міського голови, рішень, прийнятих міською радою та виконавчим комітетом - ID_Service - 4 - Изюм - Харьковская обл. 

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#668]
Анна Азатовна - сотрудник ЦНАП, хочет все сначала на тестовом посмотреть, услуги первые у них
0506488880
admposl-izyum@ukr.net

**Comment by annastolbova** [comment]
@smoktii-igov , хотят уже на боевой выставлять )

**Comment by smoktii-igov** [comment]
Отлично, выставляем на боевой

**Comment by smoktii-igov** [comment]
В РЕЛИЗе
