### ISSUE TITLE
Погодження режиму роботи об’єктів торгівлі та сфери послуг - ID_Service - 667 - Изюм - Харьковская обл

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#669]
Анна Азатовна - сотрудник ЦНАП, хочет все сначала на тестовом посмотреть, услуги первые у них
0506488880
admposl-izyum@ukr.net

**Comment by smoktii-igov** [comment]
Отправлено письмо с просьбой о тестировании 22-04-2016

**Comment by smoktii-igov** [comment]
Выставлено в РЕЛИЗ 06-05-2016
