### ISSUE TITLE
Добавить на альфу процессы

### ISSUE THREAD

**Issue by NikolayAngel** [e-government-ua/iBP#67]
1. Имя файла: Dnepr_cnap_36.bpmn
Город: Днепропетровск
Группа: dnepr_copyzemroz_rada_post, dnepr_copyzemroz_rada_lev, dnepr_copyzemroz_rada_prav
Услуга: Копії рішень міської ради про продаж земельних ділянок державної та комунальної власності
Орган: Днепропетровск ЦНАП
Процесс уже заведен , но не активен https://test.igov.org.ua/service/142/general 

2. Имя файла: Dnepr_cnap_37.bpmn
Город: Днепропетровск
Группа: dnepr_copyzemroz_rada_post, dnepr_copyzemroz_rada_lev, dnepr_copyzemroz_rada_prav
Услуга: Копії рішення міської ради про надання у постійне користування земельних ділянок державної або комунальної власності
Орган: Днепропетровск ЦНАП
Процесс уже заведен , но не активен https://test.igov.org.ua/service/140/general

**Comment by kurbpa** [comment]
@NikolayAngel  на альфе
