### ISSUE TITLE
Взяття на облік громадян, які потребують поліпшення житлових умов - ID_Service - 17- Изюм - Харьковская обл

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#670]
Анна Азатовна - сотрудник ЦНАП, хочет все сначала на тестовом посмотреть, услуги первые у них
0506488880
admposl-izyum@ukr.net

**Comment by YmNIK13** [comment]
**Процесс:** nikolaev_oda_2

**Відкритий на тестування:**
https://test.igov.org.ua/service/17/general?sID_UA_Region=6300000000&sID_UA_City=6310400000

**Обліковий запис:**
khar_izyumT

**Comment by annastolbova** [comment]
@YmNIK13 , хотят уже на боевой выставлять )

**Comment by YmNIK13** [comment]
@annastolbova , на боевом
https://igov.org.ua/service/17/general?sID_UA_Region=6300000000&sID_UA_City=6310400000

**Comment by YmNIK13** [comment]
и отработали тестовую заявку №**0-292957527**
