### ISSUE TITLE
Хмельницький - Видача довідки про відсутність заборгованості з платежів до бюджету, що контролюються органами державної фіскальної служби - Розкриття

### ISSUE THREAD

**Issue by plyacik** [e-government-ua/iBP#671]
Підключити послугу в боєвий портал, послугу вже відтестили
Координатор по Фіскальній - Ольга Паньковська - +380677140487 - pankovskaya@mail.ru - https://www.facebook.com/profile.php?id=100011112245135&fref=ts

Від держслужбовців - Уманець Олександр Володимирович
elzvit2225@ukr.net - (067) 370-22-27
тел. робочий - (0382) 70-17-03
ДПІ у місті Хмельницькому, головного управління ДФС у Хмельницькій області
Понедельник-Четверг 9-00 - 18-15, Пятница 9-00 - 17-00, Суббота 9-00 - 16-00 (работает только ЦОП - центр обслуговування платників). Обед с 13 до 14.

**Comment by YmNIK13** [comment]
Рефакторинг по Днепропетровской области. Под имеющиеся enum для выбора органа в Днепропетровской обл.:
 - были заведены недостающие регионы 
 - созданы под все 38 вариантов SubjectOrganJoin c 285 SubjectOrgan. Для Днепропетровска и Кривого Рога было создано несколько SubjectOrganJoin под разные отделения налоговой
 - под все SubjectOrganJoin созданы атрибуты sNameOrgan
1. sMailClerk
2. sAddress
3. sPhoneOrgan
4. sWorkTime
5. nCodeTaxOrgan
6. nEGRPOU
по sWorkTime не нашел пока инфы, оставил пустыми
 - переоткрыты в ServiceData все регионы

**Comment by plyacik** [comment]
@YmNIK13 Підскажіть, а підключити послугу для Хмельницького можливо?

**Comment by YmNIK13** [comment]
@plyacik Виставив в бій. С точки зору самої послуги практично нічого не помінялось, добавив ще один мейл для громадянина і самі листи трохи підформатував.

Для цієї послуги "Надання витягу з реєстру платників єдиного податку" (https://github.com/e-government-ua/iBP/issues/672) все зроблено все аналогічно

В мене до вас прохання, думаю сьогодні-завтра буде реліз, тому прохання до Вас, після вихідних проконтролювати ДФС, щоб вони обробили тестові заявки по обом послугам.

P.S. Також писав Вам на пошту протестувати і ось цю заявку
https://github.com/e-government-ua/iBP/issues/634 але гугл повернув листа з помилкою, що не знайшов такої (plyaсik@gmail.com) адреси.
Якщо все влаштовує, там тільки змінити один флаг і послуга відкрита.
"Взяття на облік громадян, які потребують поліпшення житлових умов"
https://test.igov.org.ua/service/17/general?sID_UA_Region=6800000000&sID_UA_City=6810100000

**Comment by YmNIK13** [comment]
Открыта на боевом
https://igov.org.ua/service/376/general?sID_UA_Region=6800000000&sID_UA_City=6810100000
