### ISSUE TITLE
Хмельницький - Надання витягу з реєстру платників єдиного податку - Розкриття

### ISSUE THREAD

**Issue by plyacik** [e-government-ua/iBP#672]
Підключити послугу в боєвий портал, послугу вже відтестили
Координатор по Фіскальній - Ольга Паньковська - +380677140487 - pankovskaya@mail.ru - https://www.facebook.com/profile.php?id=100011112245135&fref=ts

Від держслужбовців - Уманець Олександр Володимирович
elzvit2225@ukr.net - (067) 370-22-27
тел. робочий - (0382) 70-17-03
ДПІ у місті Хмельницькому, головного управління ДФС у Хмельницькій області
Понедельник-Четверг 9-00 - 18-15, Пятница 9-00 - 17-00, Суббота 9-00 - 16-00 (работает только ЦОП - центр обслуговування платників). Обед с 13 до 14.

**Comment by YmNIK13** [comment]
**Процесс:** gni_69
Рефакторинг по Днепропетровской области. Под имеющиеся enum для выбора органа в Днепропетровской обл.:
1. были заведены недостающие регионы
2. созданы под все 38 вариантов SubjectOrganJoin c 285 SubjectOrgan. Для Днепропетровска и Кривого Рога было создано несколько SubjectOrganJoin под разные отделения налоговой
3. под все SubjectOrganJoin созданы атрибуты:
- sNameOrgan
- sMailClerk
- sAddress
- sPhoneOrgan
- sWorkTime
- nCodeTaxOrgan
- nEGRPOU
- по sWorkTime не нашел пока инфы, оставил пустыми

Открыта на боевом
https://igov.org.ua/service/368/general?sID_UA_Region=6800000000&sID_UA_City=6810100000
