### ISSUE TITLE
Хмельницьий - "Призначення допомоги на дітей одиноким матерям" та "Призначення державної соціальної допомоги малозабезпеченим сім’ям" - Рефакторінг

### ISSUE THREAD

**Issue by plyacik** [e-government-ua/iBP#674]
Послуга вже на боєвому порталі
Держслужбовці повідомили що на електрону пошту громадянам які звернулись не приходить ніякого повідомлення

Від волонтерів Пляцик Юрій https://www.facebook.com/yura.plyacik +380977299676
plyacik@gmail.com

Посадовці:
1. Веремчук Олег Борисович - verem225@gmail.com - 8(096)4672016
2. Кримовська Оксана Леонтівна - oksana_krm@ukr.net

**Comment by GrekD** [comment]
@plyacik 
1. Заявки вже оброблені УПСЗНом? згідно БП повідомлення прийдуть тільки якщо посадовець зробе хоч якусь дію.
2. Чи перевіряли спам цих поштових скриньок?
3. Подайете, будь ласка, звернення самі по собі, УПСЗН нехай його опрацює, якщо Вам листи не надійдуть - скиньте мені номери конкретних заявок, будемо розбиратися тоді індивідуально.

**Comment by GrekD** [comment]
@plyacik Юрій, тут є якийсь рух?

**Comment by plyacik** [comment]
@GrekD спробували самостійно створити зверення і пройтись, повідомлення приходять і на пошту держслужбовця і на пошту громадянина, можливо якийсь збій був
