### ISSUE TITLE
Дніпропетровська область - Надання відомостей з Державного земельного кадастру у формі витягу з Державного земельного кадастру про обмеження у використанні земель

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#679]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [ ] Жовті Води
- [ ] Марганець
- [ ] Новомосковськ	
- [ ] Орджонікідзе	
- [ ] Павлоград	
- [ ] Першотравенськ	
- [ ] Синельникове	
- [ ] Тернівка	
- [ ] Верхньодніпровський р-н	
- [ ] Криворізький р-н	
- [ ] Криничанський р-н	
- [ ] Магдалинівський р-н	
- [ ] Межівський р-н	
- [ ] Нікопольський р-н	
- [ ] Новомосковський р-н
- [ ] Петропавлівський р-н	
- [ ] Покровський р-н	
- [ ] Синельниківський р-н	
- [ ] Солонянський р-н
- [ ] Томаківський р-н	
- [ ] Широківський р-н	
- [ ] Юр’ївський р-н

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

інфо-карти знахдяться на офіційному [сайті](http://e-services.dp.gov.ua/_layouts/Information/pgServices.aspx)

треба уточнювати питання платності послуги

**Comment by Akylish88** [comment]
https://igov.org.ua/service/47/general
готово
