### ISSUE TITLE
Дніпропетровська область - Надання довідки з Державної статистичної звітності про наявність земель та розподіл їх за власниками земель, землекористувачами, угіддями (за даними форми 6-ЗЕМ)

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#681]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [ ] Жовті Води
- [x] Марганець
- [ ] Новомосковськ	
- [ ] Орджонікідзе	
- [ ] Павлоград	
- [ ] Першотравенськ	
- [ ] Синельникове	
- [ ] Тернівка	
- [ ] Васильківський р-н	
- [ ] Верхньодніпровський р-н	
- [ ] Криворізький р-н	
- [ ] Криничанський р-н	
- [ ] Магдалинівський р-н	
- [ ] Межівський р-н	
- [ ] Нікопольський р-н	
- [ ] Новомосковський р-н	
- [ ] П’ятихатський р-н
- [ ] Павлоградський р-н
- [ ] Петропавлівський р-н	
- [ ] Покровський р-н	
- [ ] Синельниківський р-н	
- [ ] Солонянський р-н
- [ ] Томаківський р-н	
- [ ] Широківський р-н	
- [ ] Юр’ївський р-н

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

інфо-карти знахдяться на офіційному [сайті](http://e-services.dp.gov.ua/_layouts/Information/pgServices.aspx)

**Comment by Akylish88** [comment]
Раскрыто, этап теста

**Comment by Akylish88** [comment]
https://igov.org.ua/service/102/general
готово
