### ISSUE TITLE
Дніпропетровська область - Надання довідки про наявність у Державному земельному кадастрі відомостей про одержання у власність земельної ділянки у межах норм безоплатної приватизації за певним видом її цільового призначення (використання)

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#682]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [ ] Жовті Води
- [ ] Марганець
- [ ] Новомосковськ	
- [ ] Орджонікідзе	
- [ ] Павлоград	
- [ ] Першотравенськ	
- [ ] Синельникове	
- [ ] Тернівка	
- [ ] Васильківський р-н	
- [ ] Верхньодніпровський р-н	
- [ ] Криворізький р-н	
- [ ] Криничанський р-н	
- [ ] Магдалинівський р-н	
- [ ] Межівський р-н	
- [ ] Нікопольський р-н	
- [ ] Новомосковський р-н	
- [ ] Петропавлівський р-н	
- [ ] Покровський р-н	
- [ ] Синельниківський р-н	
- [ ] Солонянський р-н
- [ ] Широківський р-н	
- [ ] Юр’ївський р-н

закрити послугу на наступні міста/райони:

- [ ] Нікополь

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

інфо-карти знахдяться на офіційному [сайті](http://e-services.dp.gov.ua/_layouts/Information/pgServices.aspx)

**Comment by Akylish88** [comment]
https://igov.org.ua/service/46/general
готово
