### ISSUE TITLE
Дніпропетровська область - Надання довідки про наявність та розмір земельної частки (паю)

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#683]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [ ] Жовті Води
- [x] Марганець
- [ ] Новомосковськ	
- [ ] Орджонікідзе	
- [ ] Павлоград	
- [ ] Першотравенськ	
- [ ] Синельникове	
- [ ] Тернівка	
- [ ] Васильківський р-н	
- [ ] Верхньодніпровський р-н	
- [ ] Криворізький р-н	
- [ ] Криничанський р-н	
- [ ] Магдалинівський р-н	
- [ ] Межівський р-н	
- [ ] Нікопольський р-н	
- [ ] Новомосковський р-н	
- [ ] Петропавлівський р-н	
- [ ] Покровський р-н	
- [ ] Синельниківський р-н	
- [ ] Солонянський р-н
- [ ]  Томаківський р-н
- [ ] Широківський р-н	
- [ ] Юр’ївський р-н

закрити послугу на наступні міста/райони:

- [ ] Нікополь

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

інфо-карти знахдяться на офіційному [сайті](http://e-services.dp.gov.ua/_layouts/Information/pgServices.aspx)

**Comment by Akylish88** [comment]
Марганец уже есть.

**Comment by Akylish88** [comment]
Расскрыто и закрыт Никополь
