### ISSUE TITLE
Дніпропетровська область - Прийняття повідомлення про зміни у громадському об'єднанні

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#684]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [x] Першотравенськ
- [x]  Синельникове
- [x] Криворізький р-н
- [x] Томаківський р-н
- [x] Юр’ївський р-н

закрити послугу на наступні міста/райони:

- [x] Вільногірськ	
- [x] Дніпродзержинськ

**Comment by GrekD** [comment]
выполнено
