### ISSUE TITLE
Черкаська область - Катеринопільський район - Видача довідок про отримання/неотримання усіх видів державних соціальних допомог - розкриття

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#688]
Координатор:
Колодич Олена - Координатор IGov в Черкаській області. тел.+380674704730, 

**дуже велике прохання координатора** -
коли будь-які листи будуть надсилатися на контактних осіб (тестування, питання тощо)
ставити ії в копію elena.kolodich@privatbank.ua
та називати листи **IGov - район/місто -(назва послуги)**

по Катеринополю  - основное контактирующее лицо  - Шарига Ольга Александровна  - +380672245259

Контактна особа:
Пожар Сергій Володимирович (0976847610); ekonomikakater@ukr.net

**Comment by GrekD** [comment]
готово к релизу

**Comment by GrekD** [comment]
https://igov.org.ua/service/786/general
на боевом
логины-пароли отправила
