### ISSUE TITLE
Черкаська область - Катеринопільський район - запит на отримання публічної інформації - розкриття

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#689]
Координатор:
Колодич Олена - Координатор IGov в Черкаській області. тел.+380674704730,

**дуже велике прохання координатора** -
коли будь-які листи будуть надсилатися на контактних осіб (тестування, питання тощо)
ставити ії в копію elena.kolodich@privatbank.ua
та називати листи **IGov - район/місто -(назва послуги)**

по Катеринополю  - основное контактирующее лицо  - Шарига Ольга Александровна  - +380672245259

Контактна особа:
Задвернюк Валентина Дмитрівна (0969783942); ekonomikakater@ukr.net

**Comment by julyprodan** [comment]
відправлено на тестування 18.05

**Comment by julyprodan** [comment]
подготовила к боевой выливке

**Comment by julyprodan** [comment]
на боевом
