### ISSUE TITLE
Черкаська область - Катеринопільський район - надання довідки про наявністьта розмір земельної частки (паю) - розкриття

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#692]
Координатор:
Колодич Олена - Координатор IGov в Черкаській області. тел.+380674704730,

**дуже велике прохання координатора** -
коли будь-які листи будуть надсилатися на контактних осіб (тестування, питання тощо)
ставити ії в копію elena.kolodich@privatbank.ua
та називати листи **IGov - район/місто -(назва послуги)**

по Катеринополю  - основное контактирующее лицо  - Шарига Ольга Александровна  - +380672245259
Контактна особа:
Олійник Ірина Миколаївна (04742-2-21-81);ekonomikakater@ukr.net

**Comment by Akylish88** [comment]
Отправил на тест

**Comment by Akylish88** [comment]
0472 379315 Вікторія Юріївна

**Comment by Akylish88** [comment]
https://igov.org.ua/service/956/general
На бойовому
