### ISSUE TITLE
Полтавська ОДА - Полтавська обл. - Дозвіл на викиди забруднюючих речовин в атмосферне повітря стаціонарними джерелами

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#693]
ПІБ уповноваженої особи суб’єкта надання послуги, e-mail та контактний тел.
Югненко О. Г.
0954350110
Петренко О. В.
0959008002

Відділ користується у Департаменті
тел 56-95-08 
e-mail:eko@adm-pl.gov.ua, 
Web: http://www.eco-poltava.gov.ua

[ДепЕкоресурсиОДА_викидиЗабруднюючихРечовин.docx](https://github.com/e-government-ua/iBP/files/240235/_.docx)

**Comment by GrekD** [comment]
інфо від координатора:
З екологією доведеться почекати, так як вносимо зараз з Департаментом зміни в інформаційні картки, щоб ЦНАП міг надавати послуги в електронному вигляді.

**Comment by GrekD** [comment]
пока закрою
