### ISSUE TITLE
 Видача висновку державної екологічної експертизи - Полтавська ОДА - Полтавська обл.

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#694]
ПІБ уповноваженої особи суб’єкта надання послуги, e-mail та контактний тел.
Корнюшкіна Ірина Михайлівна 0667191011
eko@adm-pl.gov.ua,
iryska.ko@yandex.ua 
Послушна Марина Василівна 0663232937
eko@adm-pl.gov.ua,
poslyshnamarina@gmail.com

Перлова Надія Миколаївна 0663305998

[ДепЕкоресурсиОДА_Експертиза.docx](https://github.com/e-government-ua/iBP/files/240279/_.docx)

**Comment by GrekD** [comment]
інфо від координатора:
З екологією доведеться почекати, так як вносимо зараз з Департаментом зміни в інформаційні картки, щоб ЦНАП міг надавати послуги в електронному вигляді.

**Comment by GrekD** [comment]
пока закрою
