### ISSUE TITLE
Дозвіл на спеціальне водокористування в разі використання води водних об’єктів загальнодержавного значення - Полтавська ОДА - Полтавська обл.

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#695]
ПІБ уповноваженої особи суб’єкта надання послуги, e-mail та контактний тел.

Відділ водних ресурсів та атмосферного повітря Управління природокористування Департаменту:
Савченко Михайло Петрович – начальник відділу  0501947615.
Будаєвська Лариса Олександрівна – головний спеціаліст  0502901835.
Геріньш Людмила Михайлівна – головний спеціаліст  0664951112.
Відділ користується електронною поштою Департаменту – E-mail: eko@adm-pl.gov.ua, телефон приймальні: 56-95-08.

[ДепЕкоресурсиОДА_спецводокористування.docx](https://github.com/e-government-ua/iBP/files/240284/_.docx)

**Comment by GrekD** [comment]
інфо від координатора:
З екологією доведеться почекати, так як вносимо зараз з Департаментом зміни в інформаційні картки, щоб ЦНАП міг надавати послуги в електронному вигляді.

**Comment by GrekD** [comment]
пока закрою
