### ISSUE TITLE
Отримання субсидії на оплату житлово-комунальних послуг - УПСЗН Шишацької РДА - Полтавська обл.

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#696]
Прізвище, ім’я, по батькові уповноваженої особи суб’єкта надання послуги, її електронна пошта та контактний номер телефону

Мозговий Денис Геннадійович 

upszn-sh@adm-pl.gov.ua

(0535) 29-13-47

[Шишацький р-н, субсидія.docx](https://github.com/e-government-ua/iBP/files/240298/-.docx)

**Comment by zolotovatatyana** [comment]
на боевом
