### ISSUE TITLE
Поновлення договору оренди земельної ділянки  - село Давидів і село Черепин Пустомитівського району Львівська область - розкриття

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#697]
Електрона скринька: Davudiv.sr@ukr.net
Графік роботи: понеділок–п’ятниця з 9:00 до 18:00, обідня перерва: 13:00–14:00
Прийом документів: Сільський голова
Вівторок, середа з 9.00 до 13.00
Секретар ради1 (Пошту «фільтрує» секретар , скеровує сільському голові, а вже він дає завдання по відповідальних працівниках. )
Понеділок, середа, п’ятниця з 9.00 до 12.00
Електрона черга: Не потрібна 

для питань
мер давидова 096 588 8897 Віталій Дяків

**Comment by annastolbova** [comment]
село Черепин і село Давидів підпорядковуються одній сільраді

**Comment by Akylish88** [comment]
https://test-delta.igov.org.ua/service/790/general
Давно отправил на тест.
Нужно прозвонить уточнить.

**Comment by Akylish88** [comment]
https://igov.org.ua/service/790/general
на бойовому
