### ISSUE TITLE
ЦНАП - Дніпропетровськ Видача листа про прийняття рішення щодо можливості/неможливості видачі дозволу на викиди забруднюючих речовин в атмосферне повітря стаціонарними джерелами суб`єкта господарювання, об`єкт якого належить до другої або третьої групи

### ISSUE THREAD

**Issue by dmitrijzabrudskij** [e-government-ua/iBP#70]
заява: https://dl.dropboxusercontent.com/u/91233927/%D0%A6%D0%9D%D0%90%D0%9F/%D0%A7%D0%90%D0%A1%D0%A2%D0%AC%204/437/%D0%97%D0%B0%D1%8F%D0%B2%D0%B0%20%28%D0%9D%D0%B0%D0%BA%D0%B0%D0%B7%20%D0%93%D0%A3%20%D0%94%D0%B5%D1%80%D0%B6%D1%81%D0%B0%D0%BD%D0%B5%D0%BF%D1%96%D0%B4%D1%81%D0%BB%D1%83%D0%B6%D0%B1%D0%B8%20%D0%B2%D1%96%D0%B4%2021.03.2014%20%E2%84%96%2023-%D0%9E%D0%B4%29%20%281%29.doc

карточка процесса: https://dl.dropboxusercontent.com/u/91233927/%D0%A6%D0%9D%D0%90%D0%9F/%D0%A7%D0%90%D0%A1%D0%A2%D0%AC%204/437/%D0%9E%D0%91%D0%9B%20%D0%A1%D0%95%D0%A1%20%D0%9B%D0%B8%D1%81%D1%82%20%D0%BF%D1%80%D0%BE%20%D0%BF%D1%80%D0%B8%D0%B9%D0%BD%D1%8F%D1%82%D1%82%D1%8F%20%D1%80%D1%8B%D1%88%D0%B5%D0%BD%D0%BD%D1%8F.pdf

**Comment by GrekD** [comment]
процесс на боевом

**Comment by NizhnikAlex** [comment]
Переделать под ЭЦП
