### ISSUE TITLE
Повідомлення про проведення зборів, мітингів, маніфестацій і демонстрацій, спортивних, видовищних та інших масових заходів  - село Давидів і село ЧерепинПустомитівського району Львівська область - розкриття

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#700]
Електрона скринька: Davudiv.sr@ukr.net
Графік роботи: понеділок–п’ятниця з 9:00 до 18:00, обідня перерва: 13:00–14:00
Прийом документів: Сільський голова
Вівторок, середа з 9.00 до 13.00
Секретар ради1 (Пошту «фільтрує» секретар , скеровує сільському голові, а вже він дає завдання по відповідальних працівниках. )
Понеділок, середа, п’ятниця з 9.00 до 12.00
Електрона черга: Не потрібна 

для питань
мер давидова 096 588 8897 Віталій Дяків

**Comment by annastolbova** [comment]
село Черепин і село Давидів підпорядковуються одній сільраді

**Comment by Akylish88** [comment]
Завел в атрибуты и сервис

**Comment by smoktii-igov** [comment]
Раскрыто, отослано для тестирования

**Comment by GrekD** [comment]
@smoktii-igov Оля Стець сказала виставляти на бойовий і написати їй коли буде готово

**Comment by smoktii-igov** [comment]
Выставлено в РЕЛИЗ 11-05-2016

**Comment by smoktii-igov** [comment]
Сообщу https://www.facebook.com/olga.kuk.7, когда будет версия

**Comment by smoktii-igov** [comment]
Сообщено https://www.facebook.com/olga.kuk.7. Услуга в релизе с сегодняшнего дня
