### ISSUE TITLE
Державна реєстрація смерті  - село Давидів і село Черепин Пустомитівського району Львівська область

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#701]
1. ПІБ
2. *ПІБ померлої особи
3. *Дата смерті особи
4. *Місце смерті особи
5. *Причина смерті особи
6. *Дата народження померлої особи
7. *Місце народження померлої особи (якщо місце народження невідоме, зазначається країна народження)
8. *Останнє місце проживання (перебування) померлої особи (індекс, область, район, місто (селище, село), вулиця, будинок, корпус, квартира)

Потрібні скріплені документи:
1. *Копія паспорта2
2. *Копія паспорта померлої людини
3. *Документ що підтверджує факт смерті
Як працює?

Що отримує людина?
1. Свідоцтво про смерть особи.

**Обов’язково забирати свідоцтво про смерть особисто заявнику. При собі мати оригінали, або завірені дублікати доданих документів до форми-заяви. **

Електрона скринька: Davudiv.sr@ukr.net
Графік роботи: понеділок–п’ятниця з 9:00 до 18:00, обідня перерва: 13:00–14:00
Прийом документів: Сільський голова
Вівторок, середа з 9.00 до 13.00
Секретар ради1 (Пошту «фільтрує» секретар , скеровує сільському голові, а вже він дає завдання по відповідальних працівниках. )
Понеділок, середа, п’ятниця з 9.00 до 12.00
Електрона черга: Не потрібна

мер давидова 096 588 8897 Віталій Дяків

**Comment by GrekD** [comment]
https://igov.org.ua/service/1052/general
на бойовому
