### ISSUE TITLE
Черкаська область - м. Ватутіно - Надання довідки з Державної статистичної звітності про наявність земель та розподіл їх за власниками земель, землекористувачами, угіддями (за даними форми 6-ЗЕМ) - розкриття

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#702]
Координатор:
Колодич Олена - Координатор IGov в Черкаській області. тел.+380674704730,

**дуже велике прохання координатора** -
коли будь-які листи будуть надсилатися на контактних осіб (тестування, питання тощо)
ставити ії в копію elena.kolodich@privatbank.ua
та називати листи **IGov - район/місто -(назва послуги)**

по Ватутіно  - основное контактирующее лицо - Пилипенко Наталія Вікторівна  - +380975975750
Контактна особа:
Жайворонок Леся Іванівна ((04740)61203);vat_admincnap@ukr.net

**Comment by Akylish88** [comment]
Отправил на тест

**Comment by Akylish88** [comment]
На боевом.
