### ISSUE TITLE
Черкаська область - Ватутінський район - Присвоєння та зміни поштових адрес об’єктам нерухомого майна - розкриття

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#703]
Координатор:
Колодич Олена - Координатор IGov в Черкаській області. тел.+380674704730,

**дуже велике прохання координатора** -
коли будь-які листи будуть надсилатися на контактних осіб (тестування, питання тощо)
ставити ії в копію elena.kolodich@privatbank.ua
та називати листи **IGov - район/місто -(назва послуги)**

по Ватутіно  - основное контактирующее лицо - Пилипенко Наталія Вікторівна  - +380975975750
Контактна особа:
Пилипенко Олег Михайлович ((04740)62116);vat_admincnap@ukr.net

**Comment by GrekD** [comment]
обратная связь не получена
