### ISSUE TITLE
Черкаська область - Уманський район - Надання відомостей з Державного земельного кадастру у формі викопіювань з кадастрової карти (плану) та іншої картографічної документації Державного земельного кадастру - розкриття

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#706]
Координатор:
Колодич Олена - Координатор IGov в Черкаській області. тел.+380674704730,

**дуже велике прохання координатора** -
коли будь-які листи будуть надсилатися на контактних осіб (тестування, питання тощо)
ставити ії в копію elena.kolodich@privatbank.ua
та називати листи **IGov - район/місто -(назва послуги)**

Контактна особа:
Сурженко Андрій Миколайович (047 44 3-16-27 моб.0675893662);econom@it-tim.net

**Comment by Akylish88** [comment]
Отправил на тест

**Comment by Akylish88** [comment]
+380-4744  4-01-99

**Comment by Akylish88** [comment]
Адміністрація 0-4744 38025 Тетяна Олександрівна робочий день до 17.15

**Comment by Akylish88** [comment]
admin.rda@ukr.net пошта ЦНАП

Людмила Михайлівна

**Comment by Akylish88** [comment]
Написал письмо для ознакомления.

**Comment by Akylish88** [comment]
https://igov.org.ua/service/45/general
Готово к выливке
