### ISSUE TITLE
Черкаська область - Канівський район - Видача витягу з технічної документації про нормативно-грошову оцінку земельної ділянки - розкриття

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#707]
Координатор:
Колодич Олена - Координатор IGov в Черкаській області. тел.+380674704730,

**дуже велике прохання координатора** -
коли будь-які листи будуть надсилатися на контактних осіб (тестування, питання тощо)
ставити ії в копію elena.kolodich@privatbank.ua
та називати листи **IGov - район/місто -(назва послуги)**

Контактна особа:
Проняєва Олена Леонідівна(098 949 56 29, (04736) 3-17-78), Іванченко Тетяна Василівна(096 116 11 16, (04736) 3-17-78);kaniv_cnap@ukr.net

**Comment by Akylish88** [comment]
https://igov.org.ua/service/10/general
Послуга надається через публічну кадастрову карту.
http://map.land.gov.ua/kadastrova-karta
