### ISSUE TITLE
Черкаська область - м. Канів - 1.Видача довідки з державної статистичної звітності про наявність земель та розподіл їх за власниками земель, землекористувачами, угіддями (за даними форми 6 - зем), 2.Видача довідки про наявність та розмір земельної частки (паю), 3. Довідки про наявність у ДЗК відомостей про одержання у власність земельної ділянки у межах норм безоплатної приватизації за певним видом її цільового призначення (використання) - розкриття

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#708]
Координатор:
Колодич Олена - Координатор IGov в Черкаській області. тел.+380674704730,

**дуже велике прохання координатора** -
коли будь-які листи будуть надсилатися на контактних осіб (тестування, питання тощо)
ставити ії в копію elena.kolodich@privatbank.ua
та називати листи **IGov - район/місто -(назва послуги)**

Контактна особа:
Проняєва Олена Леонідівна(098 949 56 29, (04736) 3-17-78), 
Іванченко Тетяна Василівна(096 116 11 16, (04736) 3-17-78);
kaniv_cnap@ukr.net

**Comment by Akylish88** [comment]
Отправил на тест

**Comment by Akylish88** [comment]
На бойовому. +

**Comment by Akylish88** [comment]
Скинув логын та пароль запропонував выдкрити ще послуг.
