### ISSUE TITLE
Черкаська область - Канівський район - Видача довідки про наявність та розмір земельної частки (паю), довідки про наявність у ДЗК відомостей про одержання у власність земельної ділянки у межах норм безоплатної приватизації за певним видом її цільового призначення (використання) - розкриття

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#709]
Координатор:
Колодич Олена - Координатор IGov в Черкаській області. тел.+380674704730,

**дуже велике прохання координатора** -
коли будь-які листи будуть надсилатися на контактних осіб (тестування, питання тощо)
ставити ії в копію elena.kolodich@privatbank.ua
та називати листи **IGov - район/місто -(назва послуги)**

Контактна особа:
Проняєва Олена Леонідівна(098 949 56 29, (04736) 3-17-78),
Іванченко Тетяна Василівна(096 116 11 16, (04736) 3-17-78);
kaniv_cnap@ukr.net

**Comment by Akylish88** [comment]
Отправил на тест

**Comment by Akylish88** [comment]
04763 35300 Валентина Іванівна

**Comment by Akylish88** [comment]
Канівський рн  (04736) 3-53-00

**Comment by Akylish88** [comment]
Канівський рн. Черкаська область (04736) 32263
Телефон від адміністрації

**Comment by Akylish88** [comment]
Лісогор Валентина Іванівна начальник ЦНАПу

Спілкувався з Віталіною
ecomica.kaniv.rda@ukr.net
Віталіна надасть перік послуг і пошту чиновника завтра.

**Comment by Akylish88** [comment]
Перелік послуг для відкриття трохи змінено 41, 99, 102 за номерами на порталі.
Відкрив, відправив на тест.

**Comment by Akylish88** [comment]
Уже на боевом
