### ISSUE TITLE
ЦНАП - Дніпропетровськ Видача листа про прийняття рішення щодо можливості/неможливості видачі дозволу на викиди забруднюючих речовин в атмосферне повітря стаціонарними джерелами суб`єкта господарювання, об`єкт якого належить до другої або третьої групи

### ISSUE THREAD

**Issue by dmitrijzabrudskij** [e-government-ua/iBP#71]
заява: https://dl.dropboxusercontent.com/u/91233927/%D0%A6%D0%9D%D0%90%D0%9F/%D0%A7%D0%90%D0%A1%D0%A2%D0%AC%204/438/%D0%97%D0%B0%D1%8F%D0%B2%D0%B0_%D0%9F%D1%80%D0%B8%D0%B4%D0%BD%D1%96%D0%BF%D1%80%D0%BE%D0%B2%D1%81%D1%8C%D0%BA%D0%B0%20%D0%A1%D0%95%D0%A1.pdf

карта процесса: https://dl.dropboxusercontent.com/u/91233927/%D0%A6%D0%9D%D0%90%D0%9F/%D0%A7%D0%90%D0%A1%D0%A2%D0%AC%204/438/%D0%A1%D0%95%D0%A1%20%D0%9F%D1%80%D0%B8%D0%B4%D0%BD%D1%96%D0%BF%D1%80%D0%BE%D0%B2%D1%81%D1%8C%D0%BA%D0%B0%20%D0%B7%D0%B0%D0%BB%D1%96%D0%B7%D0%BD%D0%B8%D1%86%D1%8F.pdf

**Comment by GrekD** [comment]
процесс на боевом
