### ISSUE TITLE
Черкаська область - м.Золотоноша - Надання довідки з Державної статистичної звітності про наявність земель та розподіл їх за власниками земель, землекористувачами, угіддями (за даними форми 6-ЗЕМ) - розкриття

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#710]
Координатор:
Колодич Олена - Координатор IGov в Черкаській області. тел.+380674704730,

**дуже велике прохання координатора** -
коли будь-які листи будуть надсилатися на контактних осіб (тестування, питання тощо)
ставити ії в копію elena.kolodich@privatbank.ua
та називати листи **IGov - район/місто -(назва послуги)**

Контактна особа:
Остроглазова Вікторія (0678924701), 
Мірошник Іна(0969455819);
economic@zolo.ck.ua

**Comment by Akylish88** [comment]
Отправил на тест

**Comment by Akylish88** [comment]
Величко Оксана Миколаївна 0679364198

cnap_zolotonosha@ukr.net

**Comment by Akylish88** [comment]
На боевом
