### ISSUE TITLE
Черкаська область - м.Золотоноша - встановлення за погодженням з власником режиму роботи підприємств торгівлі, ресторанного господарства та сфери послуг незалежно від форм власності

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#712]
Координатор:
Колодич Олена - Координатор IGov в Черкаській області. тел.+380674704730,

**дуже велике прохання координатора** -
коли будь-які листи будуть надсилатися на контактних осіб (тестування, питання тощо)
ставити ії в копію elena.kolodich@privatbank.ua
та називати листи **IGov - район/місто -(назва послуги)**

Контактна особа:
Остроглазова Вікторія (0678924701), 
Мірошник Іна(0969455819);
economic@zolo.ck.ua

**Comment by smoktii-igov** [comment]
Раскрыто, отослано письмо с приглашением к тестированию

**Comment by smoktii-igov** [comment]
Выставлено в РЕЛИЗ 06-05-2016
