### ISSUE TITLE
Надання довідки про підтвердження поштової адреси - м.Гола Пристань - Херсонська область

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#723]
Відповідальна особа (ПІБ, посада) - Щипак Анатолій Іванович, начальник відділу містобудування, архітектури та капітального будівництва
вул.1 Травня, 22
м.Гола Пристань
Херсонська область
75600
0553921161
gopri_arhitek@meta.ua

Координатор Проекту iGov в м. Херсоні та Херсонській області.
Email: kylikpavel@ukr.net
Тел: +380661622002
Блог:https://www.facebook.com/kylikpavel

**Comment by GrekD** [comment]
на боевом
https://igov.org.ua/service/456/general
