### ISSUE TITLE
Копія рішення виконавчого комітету міської ради - м.Гола Пристань - Херсонська область

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#724]
Відповідальна особа (ПІБ, посада) - Галич Галина Василівна, секретар виконавчого комітету міської ради
вул.1 Травня, 14
м.Гола Пристань
Херсонська область
75600

0553926368
vykonkom@golapristan-mrada.gov.ua

Координатор Проекту iGov в м. Херсоні та Херсонській області.
Email: kylikpavel@ukr.net
Тел: +380661622002
Блог:https://www.facebook.com/kylikpavel

**Comment by Akylish88** [comment]
https://test.igov.org.ua/service/4/general
Расскрыто на тесте

**Comment by Kylikpavel** [comment]
А логин и пароль ?

**Comment by Kylikpavel** [comment]
Запускаем

**Comment by Akylish88** [comment]
https://igov.org.ua/service/4/general
на боевом
