### ISSUE TITLE
Копія рішення міської ради - м.Гола Пристань - Херсонська область

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#725]
Відповідальна особа (ПІБ, посада) - Лукיянченко Людмила Олександрівна, секретар міської ради

вул.1 Травня, 14
м.Гола Пристань
Херсонська область
75600

0553926070
vykonkom@golapristan-mrada.gov.ua

Координатор Проекту iGov в м. Херсоні та Херсонській області.
Email: kylikpavel@ukr.net
Тел: +380661622002
Блог:https://www.facebook.com/kylikpavel

**Comment by smoktii-igov** [comment]
Открываю 

1) Копії рішень міської ради про надання дозволу на розроблення проекту відведення земельної ділянки
2) Копії рішень міської ради про продаж земельних ділянок державної та комунальної власності
3) Копії рішень міської ради про передачу в оренду земельних ділянок, що перебувають у державній або комунальній власності
4)Копії рішень міської ради про надання земельних ділянок державної комунальної власності у користування

**Comment by smoktii-igov** [comment]
Отправлено Email на тестирование 06-05-2016  (альфа)

**Comment by smoktii-igov** [comment]
Видача копій, витягів з розпоряджень міського голови, рішень, прийнятих міською радою та виконавчим комітетом
cnap_293.bpmn

**Comment by smoktii-igov** [comment]
Получено подтверждение, отправлено в РЕЛИЗ
