### ISSUE TITLE
Реєстрація місця проживання дитини до 14 років - м.Гола Пристань - Херсонська область

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#730]
Відповідальна особа (ПІБ, посада) - Рець Тетяна Яківна, провідний спеціаліст реєстраційного відділу
вул.Каштанова (Кірова), 4
м.Гола Пристань
Херсонська область
75600
05539 77179
vykonkom@golapristan-mrada.gov.ua

Координатор Проекту iGov в м. Херсоні та Херсонській області.
Email: kylikpavel@ukr.net
Тел: +380661622002
Блог:https://www.facebook.com/kylikpavel

**Comment by Koffeek** [comment]
Протестировано и выставлено на боевой 15,06,2016
