### ISSUE TITLE
 Відправити звернення до голови Голопристанської  районної державної адміністрації

### ISSUE THREAD

**Issue by Kylikpavel** [e-government-ua/iBP#733]
Сухомлин 
Юлія Миколаївна	
Відправити звернення до голови районної державної адміністрації	
вул.1 Травня, 41, м.Гола Пристань, Голопристанський район, Херсонська область, 75600	(05539) 2-11-91	

zvern2014@ukr.net

**Comment by julyprodan** [comment]
https://test-delta.igov.org.ua/service/11/general

**Comment by julyprodan** [comment]
https://test-delta.region.igov.org.ua/
Голопристанська РДА	golopristanskaRda

**Comment by Kylikpavel** [comment]
Запускаємо )))

**Comment by julyprodan** [comment]
на боевом
