### ISSUE TITLE
Записатись на прийом до голови районної державної адміністрації

### ISSUE THREAD

**Issue by Kylikpavel** [e-government-ua/iBP#734]
Записатись на прийом до голови Голопристанської районної державної адміністрації

Сухомлин 
Юлія Миколаївна	

Записатись на прийом до голови районної державної адміністрації	
вул.1 Травня, 41, м.Гола Пристань, Голопристанський район, Херсонська область, 75600	(05539) 2-11-91

zvern2014@ukr.net

**Comment by julyprodan** [comment]
Добрый день, @Kylikpavel мне по процессу нужно знать расписание, например, каждый третий вторник месяца с 09 до 12

**Comment by Kylikpavel** [comment]
Голова районної державної адміністрації
 Вакансія 
Телефон: +38 (05539) 2-62-36,2-61-31
 

Перший заступник голови районної державної адміністрації
Кравченко-Скалозуб Олена Валентинівна
 
У першого заступника голови районної державної адміністрації прийомні дні 1.3 среда місяця.
0954314307 контактний телефон 
обід з 12.00-13.00
початок роботи з 8.00-17.00

**Comment by Kylikpavel** [comment]
Запускаемо ))

**Comment by Kylikpavel** [comment]
Приветствую вас, так и не получил логинов и паролей по Херсонской области ...

**Comment by julyprodan** [comment]
на боевом
