### ISSUE TITLE
Заява про ознайомлення з матеріалами виконавчого провадження

### ISSUE THREAD

**Issue by dmitrijzabrudskij** [e-government-ua/iBP#737]
**описание процесса**:
Відповідно до ст.12 ЗУ «Про виконавче провадження» сторони виконавчого провадження мають право ознайомлюватися з матеріалами  виконавчого провадження, робити з них виписки, знімати копії, подавати додаткові матеріали, заявляти клопотання, брати участь у провадженні виконавчих дій, давати усні та письмові пояснення, висловлювати свої доводи та міркування з усіх питань, що виникають у ході виконавчого провадження.
Ознайомлення із матеріалами виконавчого провадження здійснюється на підставі письмової заяви, в якій зазначаються бажана дата та час ознайомлення.
 Ознайомлення з матеріалами виконавчого провадження здійснюється в приміщенні органу державної виконавчої служби та у присутності державного виконавця, про що у виконавчому провадженні робиться відмітка.

форму заявления взять отсюда: https://docs.google.com/document/d/17JtDF8GtCylqBHO1lGYI90WHW2U7nkP2a7xRZZEFl5Y/edit

процесс одноходовый - в результате человека либо приглашают к себе, либо отказывают с указанием причины

**Comment by zolotovatatyana** [comment]
https://igov.org.ua/service/117/general на боевом
