### ISSUE TITLE
Заява про відкриття виконавчого провадження

### ISSUE THREAD

**Issue by dmitrijzabrudskij** [e-government-ua/iBP#738]
**описание процесса**:

Відповідно до статті 19 Закону України «Про виконавче провадження» державний виконавець відкриває виконавче провадження на підставі виконавчого документа за заявою стягувача або його представника про примусове виконання.
У заяві про відкриття виконавчого провадження стягувач вправі зазначити відомості, що ідентифікують боржника чи можуть сприяти примусовому виконанню рішення (рахунок боржника, місце роботи чи отримання ним інших доходів, місцезнаходження його майна тощо), а також шляхи отримання ним коштів, стягнутих з боржника.
Протягом трьох робочих днів державний виконавець повинен вирішити питання щодо відкриття виконавчого провадження або, за наявності підстав передбачених ст.26 Закону, відмови у  відкритті виконавчого провадження, про що в зазначений строк має винести відповідну постанову.

форму заявления можно взять отсюда (тут есть все необходимые поля): https://docs.google.com/document/d/17JtDF8GtCylqBHO1lGYI90WHW2U7nkP2a7xRZZEFl5Y/edit

процесс одноходовый - либо примут его заявления и запустят исполнительное производство, либо откажут с указанием причины

**Comment by zolotovatatyana** [comment]
Принимаются только оригиналы
