### ISSUE TITLE
Форма для подання запиту на отримання публічної інформації від фізичної особи

### ISSUE THREAD

**Issue by dmitrijzabrudskij** [e-government-ua/iBP#739]
**описание процесса**:

Відповідно до ЗУ «Про доступ до публічної інформації» запит на інформацію – це прохання особи до розпорядника інформації надати публічну інформацію, що знаходиться у його володінні. Після отримання запиту на публічну інформацію державний виконавець, в разі, якщо така інформація знаходиться у його володінні надає її заявникові або відмовляє в задоволені запиту.

форму заявления взять отсюда: https://docs.google.com/document/d/17JtDF8GtCylqBHO1lGYI90WHW2U7nkP2a7xRZZEFl5Y/edit

процесс одноходовый - либо дали, либо нет

**Comment by zolotovatatyana** [comment]
Стаття 20. Строк розгляду запитів на інформацію

1. Розпорядник інформації має надати відповідь на запит на інформацію не пізніше п'яти робочих днів з дня отримання запиту.

2. У разі якщо запит на інформацію стосується інформації, необхідної для захисту життя чи свободи особи, щодо стану довкілля, якості харчових продуктів і предметів побуту, аварій, катастроф, небезпечних природних явищ та інших надзвичайних подій, що сталися або можуть статись і загрожують безпеці громадян, відповідь має бути надана не пізніше 48 годин з дня отримання запиту.

3. Клопотання про термінове опрацювання запиту має бути обґрунтованим.

4. У разі якщо запит стосується надання великого обсягу інформації або потребує пошуку інформації серед значної кількості даних, розпорядник інформації може продовжити строк розгляду запиту до 20 робочих днів з обґрунтуванням такого продовження. Про продовження строку розпорядник інформації повідомляє запитувача в письмовій формі не пізніше п'яти робочих днів з дня отримання запиту.

**Comment by zolotovatatyana** [comment]
https://igov.org.ua/service/113/general на боевом
