### ISSUE TITLE
добавить процесс на альфу - ліцензія на надання освітніх послуг

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#74]
услуга есть на тестовом, но неактивна
https://test.igov.org.ua/service/73/general

Имя файла: Dnepr_cnap_45.bpmn
Город: Днепропетровск
Группа: Dnepr_cnap_45
На локали: Dnepr_cnap_45:1:259
Услуга: Переоформлення, видача копії або дубліката ліцензії на надання освітніх послуг у сфері загальної середньої, дошкільної, позашкільної освіти
Орган: Департамент освіти і науки Дніпропетровської ОДА

**Comment by kurbpa** [comment]
@GrekD на альфе
