### ISSUE TITLE
Заява про виконання рішення, яке гарантується державою

### ISSUE THREAD

**Issue by dmitrijzabrudskij** [e-government-ua/iBP#740]
**описание процесса**:
Відповідно до Порядку  погашення заборгованості за рішенням суду, виконання яких гарантується державою, затвердженого постановою КМУ від 03.09.2014 №440, з метою обліку виконавчих документів та судових рішень передбачених ЗУ «Про гарантії держави щодо виконання судових рішень» відповідальна особа на підставі відповідної заяви про виконання рішення, яке гарантоване державою, не пізніше 7 робочих днів з дня надходження до неї такої заяви з відповідним рішенням перевіряє за даними ЄДРВП виконання такого рішення та у разі відсутності відомостей про виконання рішення у повному обсязі вносить дані про це рішення до Реєстру рішень, виконання яких гарантується державою. У разі якщо рішення виконано у повному обсязі останнє повертається заявнику із супровідним листом та відповідною довідкою з ЄДРВП.
У разі внесення рішення до Реєстру  заянику та боржнику надсилається повідомлення про прийняття такого рішення для обліку із зазначенням черги, до якої воно включено.
Якщо рішення виконано у повному обсязі, таке рішення підлягає поверненню заявнику (разом з копіями документів, що підтверджують виконання рішення у повному обсязі), про що вноситься запис до Реєстр. 

заявление брать отсюда: https://docs.google.com/document/d/17JtDF8GtCylqBHO1lGYI90WHW2U7nkP2a7xRZZEFl5Y/edit

процесс тоже одноходовый - что-то дают в ответ

**Comment by zolotovatatyana** [comment]
Принимаются только оригиналы
