### ISSUE TITLE
Видача витягів з господарської книги - село Давидів і село Черепин Пустомитівського району Львівська область

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#742]
Видача витягів з господарської книги

Колонки до заповнення:
1.	ПІБ
2.	*Місце реєстрації (індекс, область, район, місто (селище, село), вулиця, будинок, корпус, квартира)
3.	*Місце проживання (перебування) (індекс, область, район, місто (селище, село), вулиця, будинок, корпус, квартира)
4.	*Контактний телефон
5.	 Контактний e-mail
6.	*Вкажіть потрібний рік (роки) витягу з господарської книги 
7.	*Для чого необхідний витяг? 

Потрібні скріплені документи:
1.	Копія паспорта
2.	Копія ідентифікаційного номеру
Як працює?
Що отримує людина?
1.	Витяг з господарської книги
При собі мати оригінали, або завірені дублікати доданих документів до форми-заяви.

Електрона скринька: Davudiv.sr@ukr.net
Графік роботи: понеділок–п’ятниця з 9:00 до 18:00, обідня перерва: 13:00–14:00
Прийом документів: Сільський голова
Вівторок, середа з 9.00 до 13.00
Секретар ради1 (Пошту «фільтрує» секретар , скеровує сільському голові, а вже він дає завдання по відповідальних працівниках. )
Понеділок, середа, п’ятниця з 9.00 до 12.00
Електрона черга: Не потрібна

мер Давидіва 096 588 8897 Віталій Дяків

**Comment by GrekD** [comment]
https://delta.test.igov.org.ua/service/480/general
на боевом
