### ISSUE TITLE
Посвідчення заповіту - село Давидів і село Черепин Пустомитівського району Львівська область

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#743]
Посвідчення заповіту
1.	ПІБ
2.	ПІБ англійською мовою
3.	*Дата народження
4.	*Місце народження (якщо місце народження невідоме, зазначається країна народження)
5.	*Місце проживання (перебування) (індекс, область, район, місто (селище, село), вулиця, будинок, корпус, квартира)

Потрібні скріплені документи:
1.	Копія паспорта
2.	Копія ідентифікаційного
3.	Документ який змінював, або скасовував заповіт; визнання заповіту спадкового договору недійсним, документ який змінює на підставі якого розірвано спадковий договір.
Як працює?
Що отримує людина?
1.	Довідку про державну реєстрацію заповіту. 
При собі мати оригінали, або завірені дублікати доданих документів до форми-заяви.

Електрона скринька: Davudiv.sr@ukr.net
Графік роботи: понеділок–п’ятниця з 9:00 до 18:00, обідня перерва: 13:00–14:00
Прийом документів: Сільський голова
Вівторок, середа з 9.00 до 13.00
Секретар ради1 (Пошту «фільтрує» секретар , скеровує сільському голові, а вже він дає завдання по відповідальних працівниках. )
Понеділок, середа, п’ятниця з 9.00 до 12.00
Електрона черга: Не потрібна

мер Давидіва 096 588 8897 Віталій Дяків

**Comment by GrekD** [comment]
https://igov.org.ua/service/473/general
на бойовому
