### ISSUE TITLE
Видача довідки про адресу нерухомого майна - село Давидів і село Черепин Пустомитівського району Львівська область

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#744]
Детальна інфа по процесу у файлі:
[Видача-довідки-про-адресу-нерухомого-майна_Давидів.docx](https://github.com/e-government-ua/iBP/files/260785/-.-.-.-.-._.docx)

Електрона скринька: Davudiv.sr@ukr.net
Графік роботи: понеділок–п’ятниця з 9:00 до 18:00, обідня перерва: 13:00–14:00
Прийом документів: Сільський голова
Вівторок, середа з 9.00 до 13.00
Секретар ради1 (Пошту «фільтрує» секретар , скеровує сільському голові, а вже він дає завдання по відповідальних працівниках. )
Понеділок, середа, п’ятниця з 9.00 до 12.00
Електрона черга: Не потрібна

мер Давидіва 096 588 8897 Віталій Дяків

**Comment by GrekD** [comment]
https://igov.org.ua/service/456/general
на боевом
