### ISSUE TITLE
Видача дозволу на розміщення зовнішньої реклами - м.Первомайськ - Миколаївська область

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#746]
[Видача дозволу на розміщення зовнішньої реклами.pdf](https://github.com/e-government-ua/iBP/files/262917/default.pdf)

**Координатор города:**
Корой Виталий - 0991962269 - somati.orlik@gmail.com
И еще просьба, в получатели добавить еще два контакта, для более быстрого реагирования )
kukharenko.vsevolod@gmail.com - Всеволод Кухаренко
sergey.donchenko@gmail.com - Сергей Донченко

**Контактное лицо ЦНАП:**
Наталія Миколаївна Петрущак, natashadc@mail.ru, (099) 277-41-42
на тест отправляем в ЦНАП, но обязательно ставим в копию 3 координаторов выше.

**Comment by smoktii-igov** [comment]
Отправлено письмо на тестирование 16-05-2016 (бета)

**Comment by smoktii-igov** [comment]
В релизе
