### ISSUE TITLE
Днепропетровск. Регистрация авто в МРЭО. Добавление  оплаты гос.пошлины через ликпей.

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/iBP#75]
Описание  процесса до доработки аналогично Киевскому - https://github.com/e-government-ua/iBP/issues/62

Что изменилось:
1. Когда заявка взята в работу (этап "Перевірка наявності обтяжень"),  если ограничений нет, госслужащий в выпадающем списке выбирает размер гос.пошлины для оплаты. 
Это значение в последующем передается в АПИ ликпея для генерации кнопки оплаты.
Кнопка оплаты отправляется гражданину в письме в дополнение к файлу  с реквизитами платежа. Комиссия за оплату услуги онлайн - 1.8%

2. Гражданин в письме получает кнопку "Оплатить" через систему ликпей + файл с реквизитами платежа для оплаты другим образом. Комиссия за оплату услуги онлайн - 1.8% (начисляется поверх суммы к оплате). Средства перечисляются на транзитный счет. 

3. На последующем этапе ("Надання послуги: Огляд авто ")  у служащего появилось поле для отображение id  платежа. Значение туда подтягивается автоматически.

4. Если На этапах "Надання послуги: Огляд авто ", "Перевірка наданих документів" выясняется что услугу нельзя оказать по какойто причине и сотрудник выбирает соответствующее отказу решение в дашборде + гражданин совершил оплату через ликпей, то на адрес сотрудника банка отправляется письмо с указанием id платежа и ФИО гражданина+ фалй с реквизитами  для возврата средств с транзитного счета.

5. если техсосмотр и проверка документов завершены положительно, сотруднику банка отправляется письмо с id платежа и реквизитами получателя для оплаты с транзитного счета на счет казначейства гос.пошлины.

https://test.igov.org.ua/service/159/general - реализовано для Днепропетровска на альфе

**Comment by smit-pb** [comment]
Есть поблема - Дата визита в МРЭО - пустая !
![image](https://cloud.githubusercontent.com/assets/12965717/9676819/d5600804-52d9-11e5-8189-72956df470eb.png)

**Comment by kurbpa** [comment]
@smit-pb слоты для электронной очереди нагенерили

**Comment by smit-pb** [comment]
После входа через BankID
Отображается следующее на странице - 

Крок 2. Ви увійшли як {{data.formData.params.bankIdfirstName.value}} {{data.formData.params.bankIdmiddleName.value}} {{data.formData.params.bankIdlastName.value}}
Змінити
Крок 3. {{data.formData.params["processName"].name==null?"":data.formData.params["processName"].name}}

Дальше тестировать нет возможности.

**Comment by smit-pb** [comment]
Теперь есть очереди - но после нажатия на кнопку - подать заявку получаю :
{"code":"SYSTEM_ERR","message":"invalid date value Aug 30, 2015"}

**Comment by kurbpa** [comment]
Протестировано
