### ISSUE TITLE
Каховський район Херсонськой області-  Надання відомостей з Державного земельного кадастру у формі викопіювання з кадастрової карти

### ISSUE THREAD

**Issue by PavelKyllik** [e-government-ua/iBP#752]
Мартинюк Андрій Володимирович
 Надання відомостей з Державного земельного кадастру у формі викопіювання з кадастрової карти

вул. Червоноармійська, 18, м.Каховка Херсонська область, 74800
05536 4-13-15
 kakhovka_khe@land.gov.ua

-----------------------------------------
Кулик Павло

Координатор Проекту iGov в м. Херсоні та Херсонській області. 
Email: kylikpavel@ukr.net
Тел: +380661622002

**Comment by Akylish88** [comment]
https://test-delta.igov.org.ua/service/45/general
На тестовом

**Comment by Akylish88** [comment]
https://igov.org.ua/service/45/general
на бойовому
