### ISSUE TITLE
Надання відомостей з Державного земельного кадастру у формі довідки, що містить узагальнену інформацію про землю - Каховський район Херсонськой області

### ISSUE THREAD

**Issue by PavelKyllik** [e-government-ua/iBP#753]
Надання відомостей з Державного земельного кадастру у формі довідки, що містить узагальнену інформацію про землю

 Мартинюк Андрій Володимирович	

вул. Червоноармійська, 18, м.Каховка Херсонська область, 74800	05536 4-13-15	 kakhovka_khe@land.gov.ua

-----------------------------------------
Кулик Павло

Координатор Проекту iGov в м. Херсоні та Херсонській області. 
Email: kylikpavel@ukr.net
Тел: +380661622002

**Comment by Akylish88** [comment]
https://test-delta.igov.org.ua/service/48/general
На тестовом

**Comment by Akylish88** [comment]
https://igov.org.ua/service/48/general
на бойовому
