### ISSUE TITLE
Надання відомостей з Державного земельного кадастру у формі витягу з державного земельного кадастру - Каховський район Херсонськой області

### ISSUE THREAD

**Issue by PavelKyllik** [e-government-ua/iBP#754]
Надання відомостей з Державного земельного кадастру у формі витягу з державного земельного кадастру	

Мартинюк Андрій Володимирович	

вул. Червоноармійська, 18, м.Каховка Херсонська область, 74800	05536 4-13-15	 kakhovka_khe@land.gov.ua

-----------------------------------------
Кулик Павло

Координатор Проекту iGov в м. Херсоні та Херсонській області. 
Email: kylikpavel@ukr.net
Тел: +380661622002

**Comment by Akylish88** [comment]
https://test-delta.igov.org.ua/service/46/general
https://test-delta.igov.org.ua/service/47/general
На тестовом

**Comment by Akylish88** [comment]
https://igov.org.ua/service/46/general

https://igov.org.ua/service/47/general
на бойовому
