### ISSUE TITLE
Звернення до голови РДА - Каховський район Херсонськой області

### ISSUE THREAD

**Issue by PavelKyllik** [e-government-ua/iBP#755]
Звернення до голови РДА	

Добвнюк Ганна Григорівна	

Вул.Карла Маркса,103 м.Каховка,
Херсонська обл.	05536 4-08-90	

zvernennya.gromadyan@gmail.com
-----------------------------------------
Кулик Павло

Координатор Проекту iGov в м. Херсоні та Херсонській області. 
Email: kylikpavel@ukr.net
Тел: +380661622002

**Comment by Kylikpavel** [comment]
???

**Comment by julyprodan** [comment]
https://test-delta.igov.org.ua/service/11/general

**Comment by PavelKyllik** [comment]
Юлия, а пароли и долины ?))) Подать могу а обработать нет?(((

Или я чего то не понимаю ещё)))
Жду Вашего ответа:-)

**Comment by julyprodan** [comment]
Каховская РДА 	kahRda (пароль/логин)
https://test-delta.region.igov.org.ua/

**Comment by PavelKyllik** [comment]
Запускаем)))

**Comment by julyprodan** [comment]
на боевом
