### ISSUE TITLE
Запит на отримання публічної інформації РДА  - Каховський район Херсонськой області

### ISSUE THREAD

**Issue by PavelKyllik** [e-government-ua/iBP#756]
Запит на отримання публічної інформації від РДА

Знак Ірина Федорівна

Вул.Карла Маркса,103 м.Каховка,
Херсонська обл.	05536 4-08-90

zvernennya.gromadyan@gmail.com

-----------------------------------------
Кулик Павло

Координатор Проекту iGov в м. Херсоні та Херсонській області. 
Email: kylikpavel@ukr.net
Тел: +380661622002

**Comment by Kylikpavel** [comment]
???

**Comment by julyprodan** [comment]
https://test-delta.igov.org.ua/service/161/general

**Comment by julyprodan** [comment]
Каховская РДА 	kahRda (пароль/логин)
https://test-delta.region.igov.org.ua/

**Comment by PavelKyllik** [comment]
Запускаем

**Comment by julyprodan** [comment]
на боевом
