### ISSUE TITLE
Передача земельних ділянок комунальної власності у власність громадян та юридичних осіб - смт Жовтневе Нововолинської міської ради Волинської області - розкриття

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#772]
новий населений пункт

контактна особа:
Олександр Топорівський - селищний голова
смт Жовтневе Нововолинської міської ради Волинської області.
ел. пошта - z.rada2016@gmail.com, 
тел 067 361 63 37

Жовтнева селищна рада, 
Волинська обл., м. Нововолинськ, смт Жовтневе, вул. В. Стуса, 16
тел. 03344 9 55 88, 093 357 28 38
режим роботи: понеділок-четвер з 08:00 до 17:15, 
п"ятниця - з 08:00 до 16:00, 
субота, неділя - вихідні

**Comment by Akylish88** [comment]
https://test-delta.igov.org.ua/service/126/general
На тестовом портале Дельта

**Comment by Akylish88** [comment]
Готово к релизу

**Comment by Akylish88** [comment]
https://igov.org.ua/service/126/general
на бойовому
