### ISSUE TITLE
Відправити звернення до голови Скадовської районної державної адміністрації

### ISSUE THREAD

**Issue by Kylikpavel** [e-government-ua/iBP#775]
Відправити звернення до голови районної державної адміністрації

Начальник сектору контролю
Соболь Олена Сергіївна
Телефон: (05537) 5-22-70
0509848610
rda-skad@khoda.gov.ua
и ще одна яка працює краще за попередню kontrolskad@ukr.net

**Comment by Kylikpavel** [comment]
Тест пройден. Запускаем

**Comment by julyprodan** [comment]
на боевом
