### ISSUE TITLE
 Записатись на прийом до голови Скадовської районної державної адміністрації

### ISSUE THREAD

**Issue by Kylikpavel** [e-government-ua/iBP#776]
Записатись на прийом до голови районної державної адміністрації

Начальник сектору контролю
Соболь Олена Сергіївна
Телефон: (05537) 5-22-70
0509848610
rda-skad@khoda.gov.ua
и ще одна яка працює краще за попередню kontrolskad@ukr.net

**Comment by Kylikpavel** [comment]
Тест пройден. Запускаем

**Comment by Kylikpavel** [comment]
Графік 
прийому громадян за місцем їх проживання 
головою районної державної 
адміністрації, його першим заступником та заступником 
голови районної державної адміністрації 
у першому півріччі 2016 року


http://www.skadovsk.com/mov_rda_priyom+gromadyan.php

**Comment by julyprodan** [comment]
на боевом
