### ISSUE TITLE
Запит на отримання публічної інформації від Скадовської РДА

### ISSUE THREAD

**Issue by Kylikpavel** [e-government-ua/iBP#777]
Запит на отримання публічної інформації (РДА)

Начальник сектору контролю
Соболь Олена Сергіївна
Телефон: (05537) 5-22-70
0509848610
rda-skad@khoda.gov.ua
и ще одна яка працює краще за попередню kontrolskad@ukr.net

-----------------------------------------
Кулик Павло

Координатор Проекту iGov в м. Херсоні та Херсонській області. 
Email: kylikpavel@ukr.net
Тел: +380661622002
Блог:https://www.facebook.com/kylikpavel,

**Comment by Kylikpavel** [comment]
??? Коли почнеться запуск ?(((

**Comment by Kylikpavel** [comment]
Тест пройден. Запускаем

**Comment by Kylikpavel** [comment]
Приветствую вас, так и не получил логинов и паролей по Херсонской области ...

**Comment by julyprodan** [comment]
на боевом. информация на почте
