### ISSUE TITLE
Черкаська область - Корсунь-Шевченківський район -  Видача довідок про отримання/неотримання усіх видів державних соціальних допомог - розкриття

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#781]
Координатор:
Колодич Олена - Координатор IGov в Черкаській області. тел.+380674704730,

**дуже велике прохання координатора** -
коли будь-які листи будуть надсилатися на контактних осіб (тестування, питання тощо)
ставити ії в копію elena.kolodich@privatbank.ua
та називати листи **IGov - район/місто -(назва послуги)**

контактна особа:
Управління Соціального Захисту Населення Корсунь-Шевченківської РДА Черкаської обл.
Білошапка Ніна Олександрівна (0962028624)
igovusznkorsun@ukr.net 

[інформаційна і технічна_корсунь.pdf](https://github.com/e-government-ua/iBP/files/279157/_.pdf)

**Comment by GrekD** [comment]
паролі відправлено.
на бойовому
