### ISSUE TITLE
Черкаська область - Корсунь-Шевченківський район - Видача довідки про неотримання посвідчень батьків та дитини з багатодіної сім’ї - розкриття

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#782]
Координатор:
Колодич Олена - Координатор IGov в Черкаській області. тел.+380674704730,

**дуже велике прохання координатора** -
коли будь-які листи будуть надсилатися на контактних осіб (тестування, питання тощо)
ставити ії в копію elena.kolodich@privatbank.ua
та називати листи **IGov - район/місто -(назва послуги)**

контактна особа:
Управління Соціального Захисту Населення Корсунь-Шевченківської РДА Черкаської обл.
Білошапка Ніна Олександрівна (0962028624)
igovusznkorsun@ukr.net

[інформаційна і технічна_корсунь.pdf](https://github.com/e-government-ua/iBP/files/279158/_.pdf)

**Comment by GrekD** [comment]
отправлено на тест на Дельте

**Comment by GrekD** [comment]
на тестовом открыла, ждем релиз
