### ISSUE TITLE
добавить на альфу в список процессов - 54, 55

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#79]
Имя файла: Dnepr_cnap_55.bpmn
Город: Днепропетровск
Группа: Dnepr_cnap_55
На локали:dnepr_cnap_55:1:201
Услуга: отримання експлутаційного дозволу для провадження діяльності: на потужностях (об'єктах) з виробництва, змішування та приготування кормових добавок, преміксів і кормів
Орган: управління ветеринарної медицини в м.Дніпропетровську

Имя файла: Dnepr_cnap_54.bpmn
Город: Днепропетровск
Группа: Dnepr_cnap_55
На локали:dnepr_cnap_54:1:299
Услуга: отримання експлутаційного дозволу для провадження діяльності: на потужностях (об'єктах) з переробки їстівних продуктів тваринного походження
Орган: управління ветеринарної медицини в м.Дніпропетровську

**Comment by kurbpa** [comment]
@GrekD на альфе
