### ISSUE TITLE
Дніпропетровська область - Організація ярмарок на території міста

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#790]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [ ] Дніпродзержинськ

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

інфо-карти знахдяться на офіційному [сайті](http://e-services.dp.gov.ua/_layouts/Information/pgServices.aspx)

**Comment by GrekD** [comment]
Для Дніпродзержинська ця послуга вже була реалізована раніше
