### ISSUE TITLE
Дніпропетровська область - Видача довідки про встановлення режиму роботи об’єкта

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#792]
створити послугу на наступні міста Дніпропетровської області:

- [x] Дніпродзержинськ
- [x] Тернівка
- [x] Першотравенськ

https://igov.org.ua/service/1380/general - серая на портале

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

інфо-карти знахдяться на офіційному [сайті](http://e-services.dp.gov.ua/_layouts/Information/pgServices.aspx)

приклад
http://e-services.dp.gov.ua/_layouts/Information/pgCardServices.aspx?ID=4997&TypeAg=0&Filter=%u0440%u0435%u0436%u0438%u043C&IsO=1&IsV=1

**Comment by smoktii-igov** [comment]
После анализа документов получается
Услуга "Видача довідки про встановлення режиму роботи об’єкта" тождественна "Погодження режиму роботи об’єктів торгівлі та сфери послуг".
Услуга "Видача довідки про встановлення режиму роботи об’єкта" скрыта (помечена как свободная для занятия)

**Comment by smoktii-igov** [comment]
Днепродзержинск - давно уже в РЕЛИЗе. подтвердили корректность 31-03-2016
Першотравенськ - выставлено в РЕЛИЗе 06-05-2016

**Comment by smoktii-igov** [comment]
Тернівка раскрыта в БЕТЕ 27-05-2016, отослано на тестирование

**Comment by smoktii-igov** [comment]
Все в РЕЛИЗЕ
