### ISSUE TITLE
Дніпропетровська область - Видача довідки про проведення поховання

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#793]
Розкрити/створити послугу на наступні міста Дніпропетровської області:
- [x] П’ятихатський р-н
- [x] Юр’ївський р-н

 на портале
https://igov.org.ua/service/1433/general
контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)
інфо-карти знахдяться на офіційному [сайті](http://e-services.dp.gov.ua/_layouts/Information/pgServices.aspx)

**Comment by GrekD** [comment]
в бою
