### ISSUE TITLE
Дніпропетровська область - Видача довідки про реєстрацію громадянина за даною адресою на день смерті

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#794]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [x] Жовті Води

https://igov.org.ua/service/1434/general на портале

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

**Comment by GrekD** [comment]
в бою
