### ISSUE TITLE
Дніпропетровська область - Видача дозволу на виконання перепланування, переобладнання та улаштування підвісного балкону

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#795]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [x] Марганець

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

комент от марганца - Послуга називається "Дозвіл на перепланування в житлових квартирахз прибудовою або реконструкцією балконів"

https://igov.org.ua/service/1427/general - на портале

**Comment by GrekD** [comment]
в бою
