### ISSUE TITLE
Калуш (Івано-Франківська обл)  РДА -  Надання витягу з технічної документації про нормативну грошову оцінку земельної ділянки

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/iBP#8]
Описание
http://ymmaz7.axshare.com

**Comment by Koffeek** [comment]
Описание работы: 1.Гражданин заполняет необходимые поля и прикрепляет документ. 2.Происходит загрузка документа и передача данных. 3.Гражданину приходит письмо с уведомлением об успешной регистрации заявления. 4.Чиновник просматривает данные и документы переданные гражданином. 5.Если чего-то не хватает, то отправляется письмо о невозможности оказать услугу с указанием причины. 6. Если всё в порядке, то данные переходят дальше. 7. Поступление решения к чиновнику в зависимости от которого он 8а. Отпраляет письмо, о невозможности оказать услугу. 8б. Отправляет письмо о готовности вытяга и необходимости его забрать в ЦНАП 8в. Отправляет письмо о готовности вытяга и отправке его гражданином по почте на указанный адрес.

**Comment by Koffeek** [comment]
Предварительная приемка региональным РМ проведена. Ждем новостей от регионального РМ по показу чиновникам.

**Comment by Koffeek** [comment]
Услуга заведена через Кадастровую карту на всю Украину
