### ISSUE TITLE
Дніпропетровська область - Висновок державної санітарно-епідеміологічної експертизи щодо ввезення, реалізації та використання сировини, продукції (вироби, обладнання, технологічні лінії тощо) іноземного виробн. за умови відсутності даних щодо їх безпечності для здоров’я населення (крім харчових продуктів)

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#805]
Розкрити/створити послугу на наступні міста Дніпропетровської області:

- [x] Вільногірськ

https://igov.org.ua/service/1406/general на портале

контакти відповідальних осіб у [файлі](https://docs.google.com/spreadsheets/d/10epKJ_lkok-hCNzbTkU-7G8GbWGs5mzjgGFWBl-ONPQ/edit#gid=0)

приклад:
http://e-services.dp.gov.ua/_layouts/Information/pgCardServices.aspx?ID=9879&TypeAg=0&Filter=%u0456%u043D%u043E%u0437%u0435%u043C%u043D&IsO=1&IsV=1

**Comment by zolotovatatyana** [comment]
от:	ЦНАП м.Вільногірськ <cnap.vilnogirsk@gmail.com>
дата:	24 июня 2016 г., 9:20
Доброго дня! У нашому місті не надається така послуга
