### ISSUE TITLE
Видача довідок про отримання/не отримання усіх видів державних соціальних допомог - упсзн Хорольський район - Полтавська обл.

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#808]
Вичерпний перелік документів, необхідних для отримання послуги: заява (приклад заяви додаю). Строк надання послуги - 10 днів.
Відповідальний: 
Гринько Павло Григорович, 
05385909@mail.gov.ua 
Тел. 0536233395

координатор:
Юлія Городчаніна yuliya.bobur@gmail.com
(095) 122 96 44;
(068) 15 98 443

[Приклад заяви УПСЗН_Хорольській.docx](https://github.com/e-government-ua/iBP/files/289825/_.docx)

**Comment by GrekD** [comment]
раскрыто на тестовых, отправлено на тест (дельта)

**Comment by GrekD** [comment]
https://igov.org.ua/service/786/general
на боевом
