### ISSUE TITLE
Днепр МинЮст Внесення змін до відомостей про юридичну особу, які містяться в Єдиному державному реєстрі юридичних осіб та фізичних осіб – підприємців (не пов'язані із змінами, що вносяться до установчих документів юридичної особи, або не підлягають державній реєстрації)

### ISSUE THREAD

**Issue by NizhnikAlex** [e-government-ua/iBP#81]
Технологічна картка
https://drive.google.com/file/d/0BydenhvN5xzeNURYWVA2ajl2YUk/view

Форма 4 http://ddr.minjust.gov.ua/files/main/13.06/ATT00022.doc
Форма 6 http://ddr.minjust.gov.ua/files/main/%D0%A0%D0%B5%D0%BA%D0%B2%D1%96%D0%B7%D0%B8%D1%82%D0%B8%20%D1%80%D0%B0%D1%85%D1%83%D0%BD%D0%BA%D1%96%D0%B2%20%D0%B4%D0%BB%D1%8F%20%D0%B7%D0%B0%D1%80%D0%B0%D1%85%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F%20%D0%BA%D0%BE%D1%88%D1%82%D1%96%D0%B2%20%D0%B7%D0%B0%20%D0%BE%D0%B4%D0%B5%D1%80%D0%B6%D0%B0%D0%BD%D0%BD%D1%8F%20%D0%B2%D0%B8%D1%82%D1%8F%D0%B3%D1%83/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0%206.doc

**Comment by NizhnikAlex** [comment]
БП:
1. Заявитель подает сканкопии заполненных документов. Форма 4, форма 6 - обязательно, остальные по необходимости. Ф4, Ф6 можно скачать по ссылкам. Получает подтверждение по почте
2. Сотрудник минюста проверяет присланные документы. В случае неправильного заполнения отправляется письмо с указанием причины отказа (из списка) и возможностью дать свой комментарий. В случае правильного заполнения - назначается время прихода в ЦНАП, о чем также отправляется уведомление.
3. Заявитель приходит в ЦНАП, после этого чиновник завершает процесс.

**Comment by NizhnikAlex** [comment]
БП изменен для полной автоматизации.
В МинЮст отправлена инструкция https://docs.google.com/document/d/1Z3DUYxzlPK_lP9H9g7gs0CB-HEjy9YOsd6qZj5lZb00/edit?usp=sharing

**Comment by Koffeek** [comment]
Процесс отрабатывает.
Из минусов на портале гражданина и дашборде чиновника поля enum очень длинные и вылазят за границы экрана. Когда гражданину приходит письмо с номером из реестра абзац с номером стоит выделить именно абзацем, а не простым переносом строки (так удобнее читается)
Из вопросов насколько чиновнику нужны прикрепленные файлы на втором этапе обработки

**Comment by NizhnikAlex** [comment]
Версія 1.0
Процес:
1. Заявник реєструється за допомогою BankID

**Comment by kelnerira** [comment]
![image](https://cloud.githubusercontent.com/assets/13996952/9935423/2c2d3f32-5d5f-11e5-8f33-b5b7c6f370c2.png)
При вході через ЕЦП так і має бути, що ПІП у одному полі?

**Comment by NizhnikAlex** [comment]
Услуга разбита на 4 разных:
https://github.com/e-government-ua/iBP/issues/128
https://github.com/e-government-ua/iBP/issues/129
https://github.com/e-government-ua/iBP/issues/130
https://github.com/e-government-ua/iBP/issues/131
и закрыта как цельная на боевом 29.09.2015
