### ISSUE TITLE
Каховський район. Видача довідок про отримання/неотримання усіх видів державних соціальних допомог Каховський район

### ISSUE THREAD

**Issue by Kylikpavel** [e-government-ua/iBP#810]
Гусева Л.В.	
Видача довідок про отримання/неотримання усіх видів державних соціальних допомог	
Вул. К.Маркса, 103, м.Каховка, Херсонська область, 74800	
(05536) 20062	
kruszn_kah@ukr.net

**Comment by YmNIK13** [comment]
**процесс:** dnepr_soc_help_177

**сервіс:**  786

@Kylikpavel 
Відкрито для тестування.

**для замовлення:**
https://test-delta.igov.org.ua/service/687/general?sID_UA_Region=6500000000&sID_UA_City=6523500000

логин: +380102030405
пароль: value
SMS: 123456

**для опрацювання:**
https://test-delta.region.igov.org.ua/
логін: upszn576
пароль: 12345


P.S. Послуга відкрита на новому сервері, де поки-що не має сертифіката SSL і тому браузер буде писати що дане підключення не захищене. Прошу заспоїти чиновників і допомогти в тестуванні послуги.
P.S.2 До послуги підключене СМС-інформування, прошу при замовленні послуги, указувати свій номер.

**Comment by Kylikpavel** [comment]
Запускаем Каховський район.  

6 червня 2016, 22:57:16, від "Valery Stavitsky" < notifications@github.com >: 

процесс: dnepr_soc_help_177 сервіс: 786 @Kylikpavel 
Відкрито для тестування. для замовлення: 
https://test-delta.igov.org.ua/service/687/general?sID_UA_Region=6500000000&sID_UA_City=6523500000 логин: +380102030405 
пароль: value 
SMS: 123456 для опрацювання: 
https://test-delta.region.igov.org.ua/ 
логін: upszn576 
пароль: 12345 P.S. Послуга відкрита на новому сервері, де поки-що не має сертифіката SSL і тому браузер буде писати що дане підключення не захищене. Прошу заспоїти чиновників і допомогти в тестуванні послуги. 
P.S.2 До послуги підключене СМС-інформування, прошу при замовленні послуги, указувати свій номер. — 
You are receiving this because you were mentioned. 
Reply to this email directly, view it on GitHub , or mute the thread . 

-- 
----- 
Кулик Павло 

Координатор Проекту iGov в м. Херсоні та Херсонській області. 
Email: kylikpavel@ukr.net 
Тел: +380661622002 

ПОРТАЛ ДЕРЖАВНИХ ПОСЛУГ ХЕРСОН 
Блог:https://www.facebook.com/kylikpavel, 
https://ok.ru/profile/568464993102

**Comment by YmNIK13** [comment]
@Kylikpavel добрый день
Услуга открыта на боевом под логином **upszn576**
Если будут проблемы с паролем, сообщите пожалуйста, я вышлю на почту (kruszn_kah@ukr.net) новый пароль.

**Comment by Kylikpavel** [comment]
upszn576 - ??? не подходит !!! Что мне людям передавать не рабочий пароль ? Зачем он им ?  


26 липня 2016, 11:08:04, від "Valery Stavitsky" < notifications@github.com >: 

@Kylikpavel добрый день 
Услуга открыта на боевом под логином upszn576 
Если будут проблемы с паролем, сообщите пожалуйста, я вышлю на почту ( kruszn_kah@ukr.net ) новый пароль. — 
You are receiving this because you were mentioned. 
Reply to this email directly, view it on GitHub , or mute the thread . 

----- 
Кулик Павло 

Координатор Проекту iGov в м. Херсоні та Херсонській області. 
Email: kylikpavel@ukr.net 
Тел: +380661622002 

ПОРТАЛ ДЕРЖАВНИХ ПОСЛУГ ХЕРСОН 
Блог:https://www.facebook.com/kylikpavel, 
https://ok.ru/profile/568464993102

**Comment by YmNIK13** [comment]
@Kylikpavel попробуйте еще раз, теперь подходит.

Но все-же, в целях безопасности, я рекомендую придумать им свой пароль и отписаться мне на мыло valery.stavitsky@gmail.com

**Comment by Kylikpavel** [comment]
спасибо.))) 

26 липня 2016, 11:38:12, від "Valery Stavitsky" < notifications@github.com >: 

@Kylikpavel попробуйте еще раз, теперь подходит. Но все-же, в целях безопасности, я рекомендую придумать им свой пароль и отписаться мне на мыло valery.stavitsky@gmail.com — 
You are receiving this because you were mentioned. 
Reply to this email directly, view it on GitHub , or mute the thread . 

----- 
Кулик Павло 

Координатор Проекту iGov в м. Херсоні та Херсонській області. 
Email: kylikpavel@ukr.net 
Тел: +380661622002 

ПОРТАЛ ДЕРЖАВНИХ ПОСЛУГ ХЕРСОН 
Блог:https://www.facebook.com/kylikpavel, 
https://ok.ru/profile/568464993102

**Comment by YmNIK13** [comment]
@Kylikpavel тестовые заявки обработаны, я так понимаю вопросов больше никаких нет?
