### ISSUE TITLE
Каховський район. Видача довідки про те, що за місцем реєстрації батька або матері посвідчення батьків та дитини з багатодітної сім’ї не видавались

### ISSUE THREAD

**Issue by Kylikpavel** [e-government-ua/iBP#811]
Ковальова О.І.	
Видача довідки про те, що за місцем реєстрації батька або матері посвідчення батьків та дитини з багатодітної сім’ї не видавались	
Вул. К.Маркса, 103, м.Каховка, Херсонська область, 74800	
(05536) 20062
kruszn_kah@ukr.net

**Comment by YmNIK13** [comment]
**процесс:** _kusnetsovsk_vssm_117_ 
**сервіс:**  687

@Kylikpavel 
Відкрито для тестування.

**для замовлення:**
https://test-delta.igov.org.ua/service/687/general?sID_UA_Region=6500000000&sID_UA_City=6523500000

логин: +380102030405
пароль: value
SMS: 123456

**для опрацювання:**
https://test-delta.region.igov.org.ua/
логін: dep_family
пароль: 12345


P.S. Послуга відкрита на новому сервері, де поки-що не має сертифіката SSL і тому браузер буде писати що дане підключення не захищене. Прошу заспоїти чиновників і допомогти в тестуванні послуги.
P.S.2 До послуги підключене СМС-інформування, прошу при замовленні послуги, указувати свій номер.

**Comment by Kylikpavel** [comment]
Запускаем.

**Comment by Kylikpavel** [comment]
Запускаем Каховський район.  

7 червня 2016, 00:53:22, від "Valery Stavitsky" < notifications@github.com >: 

процесс: kusnetsovsk_vssm_117 
сервіс: 687 @Kylikpavel 
Відкрито для тестування. для замовлення: 
https://test-delta.igov.org.ua/service/687/general?sID_UA_Region=6500000000&sID_UA_City=6523500000 логин: +380102030405 
пароль: value 
SMS: 123456 для опрацювання: 
https://test-delta.region.igov.org.ua/ 
логін: dep_family 
пароль: 12345 P.S. Послуга відкрита на новому сервері, де поки-що не має сертифіката SSL і тому браузер буде писати що дане підключення не захищене. Прошу заспоїти чиновників і допомогти в тестуванні послуги. 
P.S.2 До послуги підключене СМС-інформування, прошу при замовленні послуги, указувати свій номер. — 
You are receiving this because you were mentioned. 
Reply to this email directly, view it on GitHub , or mute the thread . 

-- 
----- 
Кулик Павло 

Координатор Проекту iGov в м. Херсоні та Херсонській області. 
Email: kylikpavel@ukr.net 
Тел: +380661622002 

ПОРТАЛ ДЕРЖАВНИХ ПОСЛУГ ХЕРСОН 
Блог:https://www.facebook.com/kylikpavel, 
https://ok.ru/profile/568464993102

**Comment by Kylikpavel** [comment]
Тест пройден. Запускаем. И ждем от вас пароля )))

**Comment by YmNIK13** [comment]
@Kylikpavel добрый день
Услуга открыта на боевом под логином **upszn576**
Если будут проблемы с паролем, сообщите пожалуйста, я вышлю на почту (kruszn_kah@ukr.net) новый пароль.
