### ISSUE TITLE
Каховський район. Надання довідки про перебування в єдиному банку даних багатодітних сімей

### ISSUE THREAD

**Issue by Kylikpavel** [e-government-ua/iBP#813]
Гусева Л.В.	
Отримання інформації про призначення субсидії на оплату житлово-комунальних послуг
Вул. К.Маркса, 103, м.Каховка, Херсонська область, 74800	
(05536) 20062	
kruszn_kah@ukr.net

**Comment by YmNIK13** [comment]
дублювання і неспівпадіння даних завдання з заголовком
