### ISSUE TITLE
Каховський район.Отримання субсидії на оплату житлово-комунальних послуг

### ISSUE THREAD

**Issue by Kylikpavel** [e-government-ua/iBP#816]
Гусева Л.В.	
Отримання субсидії на оплату житлово-комунальних послуг	
Вул. К.Маркса, 103, м.Каховка, Херсонська область, 74800	
(05536) 20062	
kruszn_kah@ukr.net

**Comment by YmNIK13** [comment]
**процесс:** subsidiesUkraine
**сервіс:** 654

Відкрито для тестування.

**для замовлення:**
https://test-delta.igov.org.ua/service/654/general?sID_UA_Region=6500000000&sID_UA_City=6523500000

логин: +380102030405
пароль: value
SMS: 123456

**для опрацювання:**
https://test-delta.region.igov.org.ua/
логін: upszn576
пароль: 12345


P.S. Послуга відкрита на новому сервері, де поки-що не має сертифіката SSL і тому браузер буде писати що дане підключення не захищене. Прошу заспоїти чиновників і допомогти в тестуванні послуги.
P.S.2 До послуги підключене СМС-інформування, прошу при замовленні послуги, указувати свій номер.

**Comment by Kylikpavel** [comment]
Приветствую вас, так и не получил логинов и паролей по Херсонской области ...

**Comment by Kylikpavel** [comment]
Тест пройден. Запускаем. И ждем от вас пароля )))

**Comment by YmNIK13** [comment]
@Kylikpavel добрый день
Услуга открыта на боевом под логином **upszn576**
Если будут проблемы с паролем, сообщите пожалуйста, я вышлю на почту (kruszn_kah@ukr.net) новый пароль.
