### ISSUE TITLE
Нетишин - служба по делам детей

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#829]
- [ ] Надання фізичній особі повної цивільної дієздатності - Просимо підключити
- [ ] Обстеження умов проживання громадян Просимо підключити
- [ ] Звільнення опікуна, піклувальника дитини від здійснення їх повноважень Просимо підключити
- [ ] Припинення опіки, піклування над дитиною Просимо підключити
- [ ] Постановка на облік потенційних опікунів, піклувальників, прийомних батьків та батьків-вихователів Просимо підключити

**Comment by zolotovatatyana** [comment]
Координатор Олена Матросова
(067) 601 99 12
Skype: olena_boichuk
<olena.boichuk@gmail.com>

**Comment by GrekD** [comment]
отправила письмо в Нетишин с уточнениями

**Comment by GrekD** [comment]
ответ не получен в течении месяца
