### ISSUE TITLE
Звернення громадян до міської ради - Острог - Рівненська область - розкриття

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#842]
Контактное лицо - координатор - тестувати послуги з ним
Сергій Галич - 21halich@gmail.com - 380961712728

 vladimir3v@gmail.com   Володимир Варишнюк    
Це новий ситемний адміністратор він буде  відповідати за всі послуги місьвиконкому.

**Comment by msvidran** [comment]
На боевом  https://igov.org.ua/service/676/general
