### ISSUE TITLE
Видача копій, витягів з розпоряджень міського (селищного) голови, рішень, прийнятих міською (селищною) радою та виконавчим комітетом - Острог - Рівненська область - розкриття

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#843]
Контактное лицо - координатор - тестувати послуги з ним
Сергій Галич - 21halich@gmail.com - 380961712728

 vladimir3v@gmail.com   Володимир Варишнюк    
Це новий ситемний адміністратор він буде  відповідати за всі послуги місьвиконкому.

**Comment by smoktii-igov** [comment]
выставлено в дельту, отослано приглашение для тестирования

**Comment by smoktii-igov** [comment]
Подтверждено в РЕЛИЗ 24-06-2016

**Comment by smoktii-igov** [comment]
В РЕЛИЗе
