### ISSUE TITLE
Отримання субсидії на оплату житлово-комунальних послуг -  смт Кіровське ( Дніпропетровський район), Дніпропетровська область - розкриття

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#847]
Контактна особа Гарасюк Юрій Павлович 0913031735

координує роботу
Наталія Гарасюк - 380988669455 
nataliya@garasyuk.com 

КІРОВСЬКА СЕЛИЩНА РАДА ДНІПРОПЕТРОВСЬОГО РАЙОНУ ДНІПРОПЕТРОВСЬКОЇ ОБЛАСТІ
вул. Центральна, 35, смт. Кіровське, Дніпропетровський район, Дніпропетровська область, 52030,
e-mail: sekretar@ksr.dp.ua  Web: http://www.kirovskoe-dp.org  Код ЄДРПОУ 04338339
тел. 761-16- 45 (75), факс 721-87- 48,

**Comment by zolotovatatyana** [comment]
отправлено на тест 24/06
11/07 біли сложностис доступом на сервер
25/07 пинг, нет ответа
29/08 пинг

**Comment by zolotovatatyana** [comment]
Юрій Гарасюк
9:40 (45 мин. назад)

Вітаю.
Перепрошую - у нас тимчасова не визначеність. 
1 - Об'єднання Обухівської (Кіровської) селищної ради у громаду затягнулось ( 3 населених пункти - Обухівка, Миколаївка, Горянівка ) - тільки зараз у стадії завершення. 
Поки що, отримані від громадян документи відправляють у відділ субсидій Дніпровського району.
