### ISSUE TITLE
Реєстрація народження дитини та реєстрація місця проживання дитини - смт Кіровське( Дніпропетровський район), Дніпропетровська область

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#849]
Контактна особа Гарасюк Юрій Павлович 0913031735

координує роботу
Наталія Гарасюк - 380988669455 
nataliya@garasyuk.com

КІРОВСЬКА СЕЛИЩНА РАДА ДНІПРОПЕТРОВСЬОГО РАЙОНУ ДНІПРОПЕТРОВСЬКОЇ ОБЛАСТІ
вул. Центральна, 35, смт. Кіровське, Дніпропетровський район, Дніпропетровська область, 52030,
e-mail: sekretar@ksr.dp.ua  Web: http://www.kirovskoe-dp.org  Код ЄДРПОУ 04338339
тел. 761-16- 45 (75), факс 721-87- 48,

**Comment by GrekD** [comment]
отправила письмо Наталье

**Comment by Koffeek** [comment]
@GrekD Даша, там по регистрации ребёнка если будут вопросы. то я могу дать принтформу заявы и список полей для неё

**Comment by GrekD** [comment]
не отвечают на вопросы уже три раза
