### ISSUE TITLE
Добавление процессов на альфу

### ISSUE THREAD

**Issue by NikolayAngel** [e-government-ua/iBP#85]
1. Имя файла: dnepr_cnap_53.bpmn
Город: Днепропетровск
Группа: dnepr_copyzemroz_rada_lev, dnepr_copyzemroz_rada_prav
Услуга: ЦНАП -Дніпропетровськ дозвіл на спеціальне використання водних біоресурсів у рибогосподарських водних об’єктах (їх частинах)
Орган: Управління охорони використання і відновлення водних біоресурсів та регулювання рибальства в Дніпропетровській обл.

2. Имя файла: dnepr_cnap_37.bpmn
Город: Днепропетровск
Группа: dnepr_copyzemroz_rada_lev, dnepr_copyzemroz_rada_prav
Дніпропетровськ ЦНАП - Копії рішення міської ради про передачу в оренду земельних ділянок державної або комунальної власності
https://test.igov.org.ua/service/141/general

3. Имя файла: dpi_reestr_68.bpmn
Город: Днепропетровск
Группа: dpi_reestr_68
ДПІ - Реєстрація платника єдиного податку

4. Имя файла: dnepr_cnap_70.bpmn
Город: Днепропетровск
Группа: dnepr_copyzemroz_rada_lev, dnepr_copyzemroz_rada_prav
ЦНАП - Дніпропетровськ Видача листа про прийняття рішення щодо можливості/неможливості видачі дозволу на викиди забруднюючих речовин в атмосферне повітря стаціонарними джерелами суб`єкта господарювання, об`єкт якого належить до другої або третьої групи 

5. Имя файла: dnepr_cnap_71.bpmn
Город: Днепропетровск
Группа: dnepr_copyzemroz_rada_lev, dnepr_copyzemroz_rada_prav
ЦНАП - Дніпропетровськ Видача листа про прийняття рішення щодо можливості/неможливості видачі дозволу на викиди забруднюючих речовин в атмосферне повітря стаціонарними джерелами суб`єкта господарювання, об`єкт якого належить до другої або третьої групи

**Comment by kurbpa** [comment]
@NikolayAngel 
так добавлять или нет ? (с учетом лейбла HOLD)

**Comment by NikolayAngel** [comment]
Да, лейбл убрал

**Comment by kurbpa** [comment]
на альфе
