### ISSUE TITLE
Добавление процессов на альфу

### ISSUE THREAD

**Issue by msvidran** [e-government-ua/iBP#86]
Имя файла: dnepr_cnap_48.bpmn
Город: Днепропетровск
Группа: dnepr_cnap_48
Услуга: Дніпрпетровськ - ЦНАП - Тимчасова реєстрація великотоннажних та інших технологічних транспортних засобів, що не підлягають експлуатації на вулично-дорожній мережі загального користування
Орган:  АО Територіальне управління Держгірпромнагляду у Дніпропетровській обл.

Имя файла: dnepr_cnap_48_ur.bpmn
Город: Днепропетровск
Группа: dnepr_cnap_48_ur
Услуга: Дніпрпетровськ - ЦНАП - Тимчасова реєстрація великотоннажних та інших технологічних транспортних засобів, що не підлягають експлуатації на вулично-дорожній мережі загального користування (для юридичних осіб)
Орган:  АО Територіальне управління Держгірпромнагляду у Дніпропетровській обл.

**Comment by kurbpa** [comment]
на альфе
