### ISSUE TITLE
Копії рішень сільської ради про продаж земельних ділянок державної та комунальної власності - НЕДОБОЇВСЬКА СІЛЬСЬКА РАДА, ХОТИНСЬКОГО РАЙОНУ ЧЕРНІВЕЦЬКОЇ ОБЛАСТІ

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#869]
Контактна особа для тестування:
Дранчук Андрій  - 0992607124,  nedoboivtsi14@ukr.net 

60035, Чернівецька область, Хотинський район, 
село Недобоївці, вулиця Головна,28-а
Тел.43-1- 34, E-mail: nedoboivtsi14@ukr.net
Пн-Пт 8-30 - 17-00

**Comment by smoktii-igov** [comment]
Отправлено на тестирование 2016-07-18

**Comment by smoktii-igov** [comment]
Выставлено в РЕЛИЗ 2016-07-21
