### ISSUE TITLE
Затвердження проекту землеустрою щодо відведення земельної ділянки - НЕДОБОЇВСЬКА СІЛЬСЬКА РАДА, ХОТИНСЬКОГО РАЙОНУ ЧЕРНІВЕЦЬКОЇ ОБЛАСТІ

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#870]
Контактна особа для тестування:
Дранчук Андрій  - 0992607124,  nedoboivtsi14@ukr.net 

60035, Чернівецька область, Хотинський район, 
село Недобоївці, вулиця Головна,28-а
Тел.43-1- 34, E-mail: nedoboivtsi14@ukr.net
Пн-Пт 8-30 - 17-00

**Comment by Akylish88** [comment]
https://igov.org.ua/service/1419/general
на бойовому
