### ISSUE TITLE
Надання дозволу на відведення земельної ділянки в оренду - НЕДОБОЇВСЬКА СІЛЬСЬКА РАДА, ХОТИНСЬКОГО РАЙОНУ ЧЕРНІВЕЦЬКОЇ ОБЛАСТІ

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#871]
Контактна особа для тестування:
Дранчук Андрій  - 0992607124,  nedoboivtsi14@ukr.net 

60035, Чернівецька область, Хотинський район, 
село Недобоївці, вулиця Головна,28-а
Тел.43-1- 34, E-mail: nedoboivtsi14@ukr.net
Пн-Пт 8-30 - 17-00

**Comment by Akylish88** [comment]
https://igov.org.ua/service/127/general
на бойовому
