### ISSUE TITLE
Відновлення порушеного права споживача у сфері торговельного обслуговування  -  Острог - Рівненська область

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#895]
Контактное лицо - координатор - тестувати послуги з ним
Сергій Галич - 21halich@gmail.com - 380961712728

**Comment by smoktii-igov** [comment]
Отправлено на тестирование 2016-07-18

**Comment by smoktii-igov** [comment]
Віставлено в РЕЛИЗ 2016-07-19 на Дельте
