### ISSUE TITLE
ЦНАП Тернопільського району - Надання витягу з технічної документації про нормативну грошову оцінку земельної ділянки

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/iBP#9]
Копия аналогичного процесса по г. Калуш

**Comment by Koffeek** [comment]
Описание работы: 1.Гражданин заполняет необходимые поля и прикрепляет документ. 2.Происходит загрузка документа и передача данных. 3.Гражданину приходит письмо с 
уведомлением об успешной регистрации заявления. 4.Чиновник просматривает данные и документы переданные гражданином. 5.Если чего-то не хватает, то отправляется письмо о 
невозможности оказать услугу с указанием причины. 6. Если всё в порядке, то данные переходят дальше. 7. Поступление решения к чиновнику в зависимости от которого он 
8а. Отпраляет письмо, о невозможности оказать услугу. 8б. Отправляет письмо о готовности вытяга и необходимости его забрать в ЦНАП 8в. Отправляет письмо о готовности вытяга и отправке его гражданином по почте на указанный адрес.

**Comment by msvidran** [comment]
Прошел все этапы БП - замечаний нет, кроме вышеуказанного бага: При выборе услуги выбираем Тернопольскую область (она не подсвечена баг известен). Тогда дает выбор доступа к данной услуге.

**Comment by kelnerira** [comment]
Зауваження -Портал чиновника/  Друк заяви. Перелік документів. Іде просто нумерація.  
![image](https://cloud.githubusercontent.com/assets/13996952/9852747/94d35e8a-5b08-11e5-9f36-c04225537d46.png)
Потрібно вписувати автоматично назви полів, у які заявник завантажив документи. Думаю, що також з назвами завантажених файлів.

**Comment by kelnerira** [comment]
Лист з підтвердженням - по цій послузі змінено термін розгляду - з 7ми днів до 3-х, тому потрібно внести відповідне виправлення. І додати № заявки.
Текст має вийти такий:
 "Ваше звернення № ............... щодо надання витягу з технічної документації про нормативну грошову оцінку земельної ділянки успішно зареєстроване .
Ви отримаєте відповідь протягом 3-х робочих днів."

**Comment by Koffeek** [comment]
@kelnerira 
Стосовно передачі завантажених файлів до прінтформи. Я можу прописати обов'язкові файли безпосередньо у заяву, а якщо громадянин буде приєднувати необов'язкові - лишити поля для чиновника, щоб він мав змогу їх внести.
Номер звернення задає чиновник (тоді потрібно додавати поле) чи його беремо із нашої системи (тоді він автоматично передається громадянину і так)?

**Comment by kelnerira** [comment]
А динамічно заява працювати не зможе? Щоб заповнювалися ті поля, у яких додано файл. Якщо ні - то гаразд, пропишіть обов`язкові.
Номер звернення для надсилання листа беремо із нашої системи . А для внутрішнього обліку у ЦНАПі потрібно, напевно, ще додаткове поле, де вони будуть вносити свій.

**Comment by Koffeek** [comment]
@kelnerira
Динамічна робота з прінтформами наразі неможлива проектуватиметься в майбутньому.
Номер зверення з системи iGov приходить автоматично в окремому листі. Скоро будемо вносити в основний (наразі програмісти працюють над цим). 
Поля для введеня номеру ЦНАП та додаткових документів я додам. Як буде зроблено відпишусь вам у slack

**Comment by Koffeek** [comment]
Изменения и пожелания по процессу после презентации в госоргане https://docs.google.com/spreadsheets/d/19vPeb6V3qt0UFUOjREb3fdFT09TAqtomup-r31q2Q4Q/edit#gid=0

**Comment by Koffeek** [comment]
1. Зроблено.
2. Передано программистам.
3. Зроблено.
4. Зроблено.
5. Зроблено, автозаповнювання дати подання поки немає технічної можливості.
6. Поки немає технічної можливості, якщо потрібно можемо додати поля на формі адміністратора.
7. Зроблено.
8. Зроблено.
9. Поки немає технічної можливості.
10. Потрібен e-mail земельників.

**Comment by kelnerira** [comment]
10. e-mail земельників  ternopil_ru_ter@dazru.gov.ua

**Comment by kelnerira** [comment]
ternopil_ru_ter@dazru.gov.ua   e-mail земельників.

**Comment by kelnerira** [comment]
11. Чи можна налаштувати смс повідомлення про готовність результату послуги?

**Comment by sofiadanylevych** [comment]
Щодо Файла 4 та 5, якщо залишити їхій номер чи можна виділені файл кинути на низ, оскільки по логіці вони перший та другий в списку, ну або перейменувати на Файл 1 та Файл 2.
![money](https://cloud.githubusercontent.com/assets/14632240/10136239/0f7c4c7a-65fc-11e5-9c30-bd098da2dbf0.JPG)
І ще одне, чому тепер після того як послугу взято на опрацювання ми вже не можемо подивитись на додані документи, до того моменту коли заявка не перейде в повністю оброблені? Можна дізнатись звідки такі зміни?

**Comment by Koffeek** [comment]
@sofiadanylevych
1. Нумерація фалів виправлена на 1 і 2 відповідно
2. Зараз файли мають показуватись на кожному кроці обробки.

**Comment by sofiadanylevych** [comment]
@Koffeek 
Дякую, зміни присутні, тільки хотілося б уточнити, коли я беру заявку, яка уже в роботі і хочу її опрацювати в перший раз, мені не проходить процес, не загружає але це тільки ті заявки в яких є ці додані файли (визначення розміру земельного податку при спадкування земельних ділянок), у решта випадках заявка проходить опрацювання
![jxsredfyyz](https://cloud.githubusercontent.com/assets/14632240/10138867/11646f6a-6609-11e5-8bec-40c7ba339cdb.JPG)
Ось це "зачекайте" вічне, сьогодні жодного разу не пройшла заявка, проходить час і мене викидає. Ви не знаєте з чим це може бути звязано?

**Comment by Koffeek** [comment]
@sofiadanylevych
це тестовий сервер на якому одночасно працює дуже багато людей над своїми завданнями. Іноді його підвішують аналітики, іноді програмісти. В мене з цими двома файлами заявка пройшла. Ми будемо виставляти файл на бойовий? Спитайте у Ірини, бо я повинен знати, що ми робимо. Користувачі на бойовому вже заведені

**Comment by kelnerira** [comment]
@sofiadanylevych, мені все працює, завтра запускаємо.

**Comment by Koffeek** [comment]
Ушел в бой. Тесты проведены
