### ISSUE TITLE
Kiev_ДМС (Регистрация места проживания)_замечания

### ISSUE THREAD

**Issue by OlgaKhomenko** [e-government-ua/iBP#90]
1. На форме гражданина убрать возможность редактируемости фамилии
2. На форме гражданина сделать Дату рождения календарем
3.На форме гражданина использовать атрибуты: Звідки прибув і адреса рестрації, сейчас не понятно куда и что вводить
4. На форме гражданина отделить визуально блок с детьми
5. На форме гражданина Дата народження дитини (Якщо є) - убрать якщо є
6. На форме гражданина убрать “Які саме документи Ви принесете”
7. На форме гражданина убрать “*Чи є у вас дитина (молодша 14 років) яку Ви бажаєте зареєструвати за цією адресою:
Якщо дитині більше 14 років або її реєструвати не треба - виберіть поле НІ. Діти старші 14 років подають заяву самостійно.”
8. На форме чиновника сделать редактируеміми поля Прізвище, Ім’я, По батькові
9. Сделать поле с паспортными данными шире
10. На форме чиновника “Формування пакету документів для ДМС” все поля должны быть доступны для редактирования
11.Сделать названия документов понятными для пользователя, смотреть в спецификации

12. На шагах “Підтвердження отримання ЦНАПом документів від ДМС” и “Підтвердження видачі документів ЦНАПом заявнику” сделать нередактируемыми поля, которые вытягиваются из BankID
13. На шагах “Підтвердження отримання ЦНАПом документів від ДМС” и  “Підтвердження видачі документів ЦНАПом заявнику” сделать нередактируемым поле ПІБ дитини
14. Убрать кнопку Роздрукувати и список документов для печати на шаге “Підтвердження отримання ЦНАПом документів від ДМС”
15. Убрать кнопку Роздрукувати на шаге “Підтвердження видачі документів ЦНАПом заявнику”
16. На последнем шаге “Підтвердження видачі документів ЦНАПом заявнику” идет зацикливание при выборе рішення “Документи видані заявнику”
17.  На форме чиновника добавить поле “Номер справи”. Логика видимости и редактируемости описана в спецификации.

**Comment by kurbpa** [comment]
1. готово
2. 
4. убрать "якщо є"
5. Блок по ребенку сместить в конец фоме
6.  оставляем.
7.  делаем
8.  не делаем
9. делаем
  11. пока оставляем . Актуализировать названия  принт-форм на латинице.
10. делаем
11. делаем
12. делаем
13. делаем
14. проверить.
15. делаем. на первом шаге активно. необязательно. Далее - нередактируемо.

**Comment by Koffeek** [comment]
Правки внесены. Приемка проведена.

**Comment by OlgaKhomenko** [comment]
1. Календарь сделать на украинском языке
2. В поле "Національність" на форме гражданина сделать заполненным по умолчанию - Україна
3. Переименовать поле "Чи є у Вас дитина (молодша 14 років), яку Ви бажаєте зареєструвати за цією адресою" на "Ви бажаєте зареєструвати дитину молодшу 14 років" и вывести подсказку "Діти старші 14 років подають заяву самостійно"
4. Поле "Дата народження дитини" сделать календарем
5. В поле "Громадянство дитини" на форме гражданина сделать заполненным по умолчанию значением "Україна" 
6. Блок "Ваша нова адреса реэстрації": все поля "Населений пункт", "Вулиця", "Будинок", "Корпус" и "№ Квартири" сделать одним полем "Нова адреса реєстрації"
7. Под полем "Звідки Ви прибули"  вставить поле "Коли прибули" типом календарь
8. Сделать поля с типом календарь, чтоб біла возможность вібрать календарем и возможность ручного ввода.
9. Изменить формат ввода даты через календарь на ДД.ММ.ГГГГ
10. поле "Національність" заменить на "Громадянство"
11. изменить подсказку к полю "Свідоцтво про народження дитини" на Серія та номер документу, дата і орган, що його видав
12. Поле "Орган, що оформлює" сделать необязательным на форме гражданина
13. Изменить название поля "Найменування військомату, до якого Ви належали" на "Найменування військомату, в якому Ви перебували на військовому обліку"
14. после поля "Заповніть якщо Ви вибрали опцію "Інші документи"" добавить поле "Власники житла"
15. подсказку к полю "Місце народження" заменить на - Країна, область, район і населений пункт
16. подсказку к полю "Місце народження дитини" заменить на - Країна, область, район і населений пункт
17. в выпадающем списке атрибута "Орган, що оформлює реєстрацію" изменить названия на:
Шевченківський РВГУ ДМС України в м.Києві, Деснянський РВГУ ДМС України в м.Києві, Солом'янський РВГУ ДМС України в м.Києві
18. после поля "Паспортні дані (серія і номер):" добавить поле "Тип паспортного документу" с вариантами значений: паспорт, посвідка на постійне проживання, посвідка на тимчасове проживання.

**Comment by Koffeek** [comment]
1. Пока нет
2. Сделано
3. Сделано
4. Под вопросом, т.к. на принтформах будет печататься "null" при отсутствии ребенка.
5. Нет, т.к. при печати форм значение уйдет даже если нет ребенка
6. Если сделать блок таким образом, то при заполнении форм невозможно бедт вычленить составляющие адреса.
7. Сделано. Эта информация обязательна? Будет ли она передаваться на принтформы?
8. Или календарь или руками.
9. Это принципиально? Скрипт
10. Сделано. Надо ли ставить вариант "Підданство"?
11. Сделано.
12. Сделано. (а есть ли необходимость в этом поле у гражданина или может его оставить только чиновнику?)
13. Сделано.
14. Сделано. Эта информация обязательна? Будет ли она передаваться на принтформы? Что делать, если власников несколько?
15. Сделано.
16. Сделано.
17. Сделано.
18. Паспортные данные подтягиваются с BankID для чего будет служить это поле? Необходимы ли какие-либо данные получать из "посвідка на постійне проживання, посвідка на тимчасове проживання" или достаточно названия документов? Будут ли эти данные передаваться на принтформы?

**Comment by Koffeek** [comment]
Вопросы от нас.
1. Реквизиты для оплаты госпошлины будет вводить чиновник (предусмотреть поле) или они стандартизированы?
2. Возможность предварительной записи на прием реализуется посредством телефона ЦНАП или у гражданина есть другая возможность?

**Comment by OlgaKhomenko** [comment]
4. Ок
5. согласна
6. просмотрю еще раз все формы, но вариант одной записью прописывать подходит.
7. да, обязательная. информация для печатных форм
9. подумаем, может в таком случае уберем календарь и они будут вручную вводить. Принципиально, т.к. ДМС не принимает через слеш
10. про підданство не говорили в ЦНАП. Оставляем только "Громадянство"
12. пусть будет у гражданина, многие его могут заполнить, ЦНАПу будет легче хоть иногда.
14. Если несколько тогда будут, через запятую вводить. Поле необязательное
18. Этой информацией заполняется картка реєстрації. может идентификация будет не только через банкид, и будет в том случае посвидка. Попросили, нужно сделать, тем более, что нам нужно прописывать слово "паспорт" в одной из печатных форм.

**Comment by OlgaKhomenko** [comment]
1.Реквизиты дляоплаты будем выводить в уведомление гражданину. Сейчас работаем над организационными вопросами, т.к. решили просто прикреплять ссылку на страницу портала РДА с этими данными, но пока не у всех РДА есть такая страница.
2. У нас предварительная запись есть через сайт, мы просто в уведомлении сделаем ссылку на него, чтоб гражданин знал о такой возможности и воспользовался.

**Comment by kurbpa** [comment]
п.18 тогда вопрос - может вообще не пытаться предзаполнять паспортные данные ? ТОгда будет 2 доступных для заполнения поля:
* Тип паспортного документу
* Серия / номер документу

И пусть гражданин самостоятельно их заполняет.  Как вариант.

**Comment by OlgaKhomenko** [comment]
@kurbpa 
п18 не делаем, будем в печатной форме заполнять сразу значением "Паспорт"

**Comment by OlgaKhomenko** [comment]
убрать в перечне значений атрибута "Підставою для реєстрації місця проживання заявника є" после інші документи дополнение в скобках, а то когда віводится в печатную форму, получается некрасиво. Оставить без "(Вказати полем нижче)"

**Comment by Koffeek** [comment]
@OlgaKhomenko 
Сделано.

**Comment by OlgaKhomenko** [comment]
необходимо добавить на форму гражданина и потом отображать на форме чиновника атрибуты:
1. ПІБ довіреної особи
2. Паспортні дані довіреної особи
3. Довіреність 
Подсказка к полю  "Довіреність" - серія, номер, дійсна від і до

Поля редактируемые и необязательные на форме гражданина и первом щаге чиновника. Потом эти поля нередактируемые

**Comment by kurbpa** [comment]
@OlgaKhomenko 
по деовренным лицам -  добавление полей не в эту итерацию.
