### ISSUE TITLE
Рішення про продаж земельної ділянки комунальної або державної власності - м.Первомайськ - Харківська обл

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#902]
Косінова Людмила Миколаївна 050 975 17 37
Виконавчий комітет Первомайської міської ради Харківської області
E-mail: tsnap.pervom@ukr.net

інфо-карта:
[Продаж земельної ділянки несільськогосподарського призначення у власність громадян.docx](https://github.com/e-government-ua/iBP/files/366078/default.docx)

Інформація про центр надання адміністративної послуги
Найменування центру надання адміністративної послуги, в якому здійснюється обслуговування суб’єкта звернення

Центр надання адміністративних послуг в м. Первомайський 
1 Місцезнаходження центру надання адміністративної послуги 64102, Харківська обл., м.Первомайський, пр.40 років Перемоги, 1, каб. № 8

Інформація щодо режиму роботи центру надання адміністративної послуги ПРИЙОМ ГРОМАДЯН
Понеділок – 9:00 – 18:00
Вівторок – 9:00 – 18:00
Середа – 9:00 – 18:00
Четвер – 9:00 – 20:00 
П’ятниця – 9:00 – 20:00
Субота – 8:00 – 15:00

Телефон/факс (довідки), адреса електронної пошти та веб-сайт центру надання адміністративної послуги тел/ факс.3-41-03, 050 975 17 37
Адреса веб-сайту: http://www.pervom-rada.gov.ua
E-mail: tsnap.pervom@ukr.net 
skype: tsnap.pervomayskiy

**Comment by Akylish88** [comment]
https://delta.test.igov.org.ua/service/1472/general
На тесте

**Comment by Akylish88** [comment]
https://igov.org.ua/service/1472/general
На бойовому
