### ISSUE TITLE
Дозвіл на розробку проекту землеустрою щодо відведення (3 услуги) - м.Первомайськ - Харківська обл

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#905]
Косінова Людмила Миколаївна 050 975 17 37
Виконавчий комітет Первомайської міської ради Харківської області
E-mail: tsnap.pervom@ukr.net

замовлення на 3 послуги (в їх переліку)

1. Дозвіл на розробку проекту землеустрою щодо відведення  
2. Дозвіл на розробку проекту землеустрою  щодо відведення земельної ділянки або зміни цільового призначення земельної ділянки
3. Надання дозволу розробку проекту землеустрою щодо відведення земельної ділянки громадянам для обслуговування житлового будинку, гаражу, ведення особистого селянського господарства і садівництва та передачу їх у власність (в оренду)

але інфокарти 2 :
[Дозвіл на розробку проекту землеустрою щодо відведення земельної ділянки у власність громадян.docx](https://github.com/e-government-ua/iBP/files/366285/default.docx)
[Дозвіл на розробку проекту землеустрою щодо відведення земельної ділянки у користування.docx](https://github.com/e-government-ua/iBP/files/366284/default.docx)

Інформація про центр надання адміністративної послуги
Найменування центру надання адміністративної послуги, в якому здійснюється обслуговування суб’єкта звернення

Центр надання адміністративних послуг в м. Первомайський 
1 Місцезнаходження центру надання адміністративної послуги 64102, Харківська обл., м.Первомайський, пр.40 років Перемоги, 1, каб. № 8

Інформація щодо режиму роботи центру надання адміністративної послуги ПРИЙОМ ГРОМАДЯН
Понеділок – 9:00 – 18:00
Вівторок – 9:00 – 18:00
Середа – 9:00 – 18:00
Четвер – 9:00 – 20:00 
П’ятниця – 9:00 – 20:00
Субота – 8:00 – 15:00

Телефон/факс (довідки), адреса електронної пошти та веб-сайт центру надання адміністративної послуги тел/ факс.3-41-03, 050 975 17 37
Адреса веб-сайту: http://www.pervom-rada.gov.ua
E-mail: tsnap.pervom@ukr.net 
skype: tsnap.pervomayskiy

**Comment by Akylish88** [comment]
Раскрыта только эта услуга "Дозвіл на розроблення проекту землеустрою щодо відведення земельної ділянки"
https://delta.test.igov.org.ua/service/27/general

**Comment by Akylish88** [comment]
https://igov.org.ua/service/27/general
На бойовому
