### ISSUE TITLE
Обмін паспорта громадянина у разі непридатності для користування - смт.Гусятин - Тернопільська обл.

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#907]
Чачковська Наталія Михайлівна, 
03557 - 2-19-86,  098-223-55-25.  cnap_gus@ukr.net

На рахунок паспортів - послуги надаються Гусятинським районним сектором Державної міграційної служби України адреса: смт. Гусятин, провулок Героїв Майдану, 9
телефон: 2-22-21 
режим роботи: вівторок 9.00-18.00
середа 10.00-19.00
четвер 9.00-18.00
пятниця 10.00-19.00
субота 9.00-16.45

**Comment by sofiadanylevych** [comment]
на бойовому
