### ISSUE TITLE
добавить на альфу в список процессов

### ISSUE THREAD

**Issue by GrekD** [e-government-ua/iBP#91]
Имя файла: Dnepr_cnap_51.bpmn
Город: Днепропетровск
Группа: Dnepr_cnap_55
На локали: dnepr_cnap_51:1:331
Услуга: Дозвіл на експлуатацію машин, механізмів, устатковання підвищеної небезпеки
Орган: Територіальне управління Держгірпромнагляду у Дніпропетровській області

Имя файла: Dnepr_cnap_52.bpmn
Город: Днепропетровск
Группа: Dnepr_cnap_55
На локали:dnepr_cnap_52:1:321
Услуга: Дозвіл на застосування механізмів, устатковання підвищеної небезпеки
Орган: Територіальне управління Держгірпромнагляду у Дніпропетровській області

**Comment by kurbpa** [comment]
на альфе
