### ISSUE TITLE
Добавить готовое видео на портал (Открытый реестр недвижимого имущества) Мин Юст

### ISSUE THREAD

**Issue by VadymVolos** [e-government-ua/iBP#92]
Открытый реестр недвижимого имущества - Мин Юст
Вот видео https://youtu.be/kloGcqQXSRI

Задачу создал тут, так как знаю что Павел добавляет, если нужно в другую ветку перенести, говорите в какую ветку, перенесу.

===
Пост о видео тут:
https://www.facebook.com/groups/458833010941504/permalink/486928944798577/?comment_id=507309269427211&offset=0&total_comments=7&comment_tracking=%7B%22tn%22%3A%22R%22%7D
И тут:
https://www.facebook.com/jaanika.merilo/posts/10207553964665949?comment_id=10207553977546271&reply_comment_id=10207554283193912&total_comments=4&comment_tracking=%7B%22tn%22%3A%22R%22%7D

**Comment by VadymVolos** [comment]
PS возможно нам видео нужно заливать к себе на канал, так как мы будем зависеть от других каналов, и если кто то видео на своем канале уберет, удалит и тп, то у нас будет страница с битой ссылкой. И со временем эти ссылки смогут накапливаться.
Но в добавлении на свой канал есть одно но, авторские права автора видео, нужно получать разрешение.

**Comment by kurbpa** [comment]
@VadymVolos 
Зачем?

**Comment by VadymVolos** [comment]
@kurbpa мы же инструкции для каждой услуги делаем, в видео инструкция как заказать услугу.
Ирина Кельнер занимается этим вопросом.
