### ISSUE TITLE
Хмельницький - Коментарі від заявника - рефакторінг

### ISSUE THREAD

**Issue by plyacik** [e-government-ua/iBP#927]
Доброго дня, від держслужбовця надійшло прохання:
"Чи можливо зробити, що при залишені коментаря заявником, це якось можна було побачити, без переходу на кожну заявку окремо, і перемотування в кінець заявки."

УПСЗН міста Хмельницького

Від волонтерів Пляцик Юрій https://www.facebook.com/yura.plyacik +380977299676
plyacik@gmail.com
Від держслужбовців:
Веремчук Олег Борисович - verem225@gmail.com - 8(096)4672016

Дякую!

**Comment by GrekD** [comment]
@plyacik 
ми обговоримо цю пропозицію на найближчій нараді, напишу Вам результат

**Comment by GrekD** [comment]
@plyacik 
додали у список задач на реалізацію
