### ISSUE TITLE
Некорректная работа фильтра "Сортувати за датою" в режиме админки/дашборда

### ISSUE THREAD

**Issue by RoOmel** [e-government-ua/iBP#93]
Окружение Firefox 40.0
При переключении фильтра в состояние "Від найновіших" или "Від найдавніших" порядок заявок не изменяется вообще.
![bug_igov_17_01](https://cloud.githubusercontent.com/assets/12996514/9753942/20fa9ae0-56cc-11e5-8908-4ada3302f70f.jpg)
![bug_igov_17_02](https://cloud.githubusercontent.com/assets/12996514/9753943/25a2114a-56cc-11e5-9a3b-b5f2605b344f.jpg)

**Comment by kurbpa** [comment]
Исправлено.

Просьба дефекты, которые не касаются непосредственно Б-процессов, фиксировать в  основном репозитории " i "
