### ISSUE TITLE
Отсутствует валидация даты в поле "Зазначте дату отримання довідки або причину неможливості отримання послуги"

### ISSUE THREAD

**Issue by RoOmel** [e-government-ua/iBP#94]
Окружение Firefox 40.0
При вводе даты в поле валидация отсутствует или работает некорректно.
![bug_igov_16_01](https://cloud.githubusercontent.com/assets/12996514/9754070/ccc51cf0-56cd-11e5-911d-1b4a8739dfa1.jpg)
![bug_igov_16_02](https://cloud.githubusercontent.com/assets/12996514/9754076/d15fbb76-56cd-11e5-9f8e-813b3e9a85cd.jpg)

**Comment by kurbpa** [comment]
На текущий момент иного пути реализации нет.
Валидировать дату в поле для свободного ввода - невозможно.
