### ISSUE TITLE
Kiev_ДМС(Замечания к печатным формам)

### ISSUE THREAD

**Issue by OlgaKhomenko** [e-government-ua/iBP#95]
1. замечание к форме dodat12 - https://drive.google.com/file/d/0B7h--_kB6N_NVGV6MXNNOGFkZms/view?usp=sharing
2. замечания к форме kartka - https://drive.google.com/file/d/0B7h--_kB6N_NSklfbkdEbnBrRGs/view?usp=sharing
3. замечания к форме talon_4 - https://drive.google.com/file/d/0B7h--_kB6N_NUExWdmxDQnNQRVE/view?usp=sharing
4. замечания к форме vidomist_4 - https://drive.google.com/file/d/0B7h--_kB6N_NVWRXRmdhQjhNN1U/view?usp=sharing
5. замечания к форме zajava_r - https://drive.google.com/file/d/0B7h--_kB6N_Nc082SHNSNTlfMkk/view?usp=sharing
6.замечания к форме zajava_zn - https://drive.google.com/file/d/0B7h--_kB6N_NLXotQzJ3SlNXa28/view?usp=sharing

**Comment by Koffeek** [comment]
Основная масса замечаний проработана и исправлена. Не исправлено следующееЖ
1. Форма kartka замечание 3 (смещение полей). Надо проверить будет ли смещение при печати
2. Формы talon_4 и vidomist_4 замечание 3 (унификация заполнения старого и нового адресов регистрации) на 100% совпадение возможно только если старый адрес гражданин будет вносить как и новый (отдельно заполнять каждое поле).
3. Формы talon_4 и vidomist_4 замечание 4 (внесение пола гражданина и ребенка) на данные момент возможна только такая передача. Замену пола на цифру может осуществить сотрудник ЦНАПА, т.к. поля для редактирования ему доступны.
4. Формы zajava_r и zajava_zn замечание 1 (склонение названия РВ ДМСУ) на данный момент можем передать только так.

**Comment by OlgaKhomenko** [comment]
1. проверим
2. тогда проще убрать подсказку по форме заполнения текущего адреса. Обычно все пишут через запятую, поэтому внешне будет похоже.
3.Сотрудник ЦНАП не сможет заменить, т.к. там справочник со значениями - жіноча, чоловіча
4. На сегодня пусть будет так, но нужно решать этот вопрос.

**Comment by Koffeek** [comment]
Подсказка по форме заполнения переделана под заполнение с запятыми.
В Дашборд чиновника в поля пол добавлены значения 1 и 2, чтобы он мог поставить их при печати форм.

**Comment by OlgaKhomenko** [comment]
по п.3 - предлагаю вообще убрать пока проставление в форму статі, даже если будут цифры, все равно ничего не решит, т.к. должна быть логика, если выбран 1, по проставить в первойячейке, если 2 - во второй. Сейчас лепит и в первую и во вторую.
Просьба убрать со всех форм автоматическое проставление пола на гражданина и его ребенка.

**Comment by OlgaKhomenko** [comment]
в talon_4 в таблицу с детьми в поле "Місце народження" проставляет "Громадянство"

**Comment by OlgaKhomenko** [comment]
добавила по vidomist_4 замечание п.7 - https://docs.google.com/document/d/1OHq-oEvVO1yp0AtElY33M1Ds9pznvcopllYg1C48dNA/edit

**Comment by OlgaKhomenko** [comment]
добавила по kartka п.6 - https://docs.google.com/document/d/1N9ox5oIBK8l6nTVyV4mB713lj_xIKT4qFwOU8Rh3u58/edit

**Comment by OlgaKhomenko** [comment]
добавила в talon_4 п. 7 и 8 -https://docs.google.com/document/d/1gKRw4vzhMzJupsHLp3R398q8lMMFG9ugGNZOKmT_iF8/edit

**Comment by OlgaKhomenko** [comment]
добавила по zajava_zn п. 10 - https://docs.google.com/document/d/1393uF7fLEgG_f0ls-8lELXWYmWeG8XWpdc4W32iphso/edit?usp=sharing

**Comment by Koffeek** [comment]
vidomost_4
7. Сделано
8. В примитке сказано, что один экземпляр без заполненых полей 1-4 передается в статистику, поэтому поля не заполняли.
Kartka
6. Если сделать записи через запятую, а ребёнка прописывать не будут, то в форме будут отображаться запятые на пустом поле.
talon_4
7. В примитке сказано, что один экземпляр без заполненых полей 1-4 передается в статистику, поэтому поля не заполняли
8. Сделано по образу vidomost_4.
zajava_zn
10. Сделано.

**Comment by OlgaKhomenko** [comment]
8. нужно в статистику тоже заполненное передавать. 
6. пусть будут запятые

**Comment by OlgaKhomenko** [comment]
Сегодня пробовали печатать формы, они не влазят на А4, просьба привести их к размеру А4, а картку к А5.

**Comment by Koffeek** [comment]
1. Пока нет
2. Сделано
3. Сделано
4. Под вопросом, т.к. на принтформах будет печататься "null" при отсутствии ребенка.
5. Нет, т.к. при печати форм значение уйдет даже если нет ребенка
6. Если сделать блок таким образом, то при заполнении форм невозможно бедт вычленить составляющие адреса.
7. Сделано. Эта информация обязательна? Будет ли она передаваться на принтформы?
8. Или календарь или руками.
9. Это принципиально? Скрипт
10. Сделано. Надо ли ставить вариант "Підданство"?
11. Сделано.
12. Сделано. (а есть ли необходимость в этом поле у гражданина или может его оставить только чиновнику?)
13. Сделано.
14. Сделано. Эта информация обязательна? Будет ли она передаваться на принтформы? Что делать, если власников несколько?
15. Сделано.
16. Сделано.
17. Сделано.
18. Паспортные данные подтягиваются с BankID для чего будет служить это поле? Необходимы ли какие-либо данные получать из "посвідка на постійне проживання, посвідка на тимчасове проживання" или достаточно названия документов? Будут ли эти данные передаваться на принтформы?

**Comment by OlgaKhomenko** [comment]
добавила по vidomist_4 замечание п.9- https://docs.google.com/document/d/1OHq-oEvVO1yp0AtElY33M1Ds9pznvcopllYg1C48dNA/edit

**Comment by OlgaKhomenko** [comment]
добавила в talon_4 п. 9 - https://docs.google.com/document/d/1gKRw4vzhMzJupsHLp3R398q8lMMFG9ugGNZOKmT_iF8/edit

**Comment by OlgaKhomenko** [comment]
добавила по zajava_r п. 7-16 - https://docs.google.com/document/d/1fw-GNOFWN6eknI73bbR-rCK2KJ6nMpBv0gG0rozAUes/edit

**Comment by OlgaKhomenko** [comment]
добавила по kartka п.7-11 - https://docs.google.com/document/d/1N9ox5oIBK8l6nTVyV4mB713lj_xIKT4qFwOU8Rh3u58/edit

**Comment by Koffeek** [comment]
kartka
7. Сделано
8. Технически нет возможности
9. Сделано
10,11. Нет возможности
zajava_r
7. Сделано
8. Сделано
9. Сделано
10. Сделано
11. Сделано
12. Сделано
13. Сделано.
14. Нет возможности
15. Сделано
16. Сделано.

**Comment by OlgaKhomenko** [comment]
п.10 в vidomist_4: https://docs.google.com/document/d/1OHq-oEvVO1yp0AtElY33M1Ds9pznvcopllYg1C48dNA/edit

**Comment by OlgaKhomenko** [comment]
п.12, 13 kartka - https://docs.google.com/document/d/1N9ox5oIBK8l6nTVyV4mB713lj_xIKT4qFwOU8Rh3u58/edit

**Comment by Koffeek** [comment]
п.10 в vidomist_4, п.12, 13 kartka сделано
