### ISSUE TITLE
Надання будівельного паспорту забудови земельної ділянки -  м. Ватутіно - Черкаська область

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#980]
vat_admincnap@ukr.net
Пилипенко Наталя голова ЦНАп
+380975975750

Координатор:
Колодич Олена - Координатор IGov в Черкаській області. тел.+380674704730,

**Comment by Akylish88** [comment]
https://delta.test.igov.org.ua/service/455/general
Готово к віливке

**Comment by Akylish88** [comment]
https://igov.org.ua/service/455/general
На бойовому
