### ISSUE TITLE
Надання витягу з технічної документації про нормативну грошову оцінку земельної ділянки - м. Ватутіно - Черкаська область

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#984]
vat_admincnap@ukr.net
Пилипенко Наталя голова ЦНАп
+380975975750

Координатор:
Колодич Олена - Координатор IGov в Черкаській області. тел.+380674704730,

**Comment by Akylish88** [comment]
https://delta.test.igov.org.ua/service/10/general
редирект на всю страну
