### ISSUE TITLE
Добавить ссылку "Заміна посвідчення водія у зв'язку зі зміною особистих даних"

### ISSUE THREAD

**Issue by smoktii-igov** [e-government-ua/iBP#990]
При работе над статьей "Как зарегистрировать брак" возникла потребность добавить услугу "Заміна посвідчення водія у зв'язку зі зміною особистих даних", как смена водительских прав при изменении фамилии, в ЖС "Зміна прізвища, імені та по батькові"

**Comment by GrekD** [comment]
готово
